build.gradle

This way `./gradlew idea` works properly.

shift sourceSets somewhat

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jDelegatedAuthenticationProperties.java
docs/cas-server-documentation/installation/Configuration-Properties.md
gradle.properties
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java

Also updates to pac4j 3.0.0 RC2 because it includes Twitter include_email support.

Add Twitter include_email support

---

support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/AbstractOAuth20Tests.java

A long search for a tiny fix...

Fix OAuth tests

---

gradle.properties
gradle/dependencies.gradle
style/dependency-check-suppressions.xml

a few false positives, a couple embedded dependencies, and jradius dependencies that can't be removed.

suppress some dependency check hits

---

docs/cas-server-documentation/installation/Monitoring-Statistics.md

Inform user to use `/status/health` instead of `/status`
- Reference any other pull requests that might be related.
#3359

Inform user to use `/status/health` instead of `/status`

---

renovate.json

reduce renovate frequency to daily and preserve semver

modify renovate config

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/aup/AcceptableUsagePolicyProperties.java
docs/cas-server-documentation/installation/Configuration-Properties.md
support/cas-server-support-aup-ldap/src/main/java/org/apereo/cas/config/CasAcceptableUsagePolicyLdapConfiguration.java
support/cas-server-support-aup-mongo/src/main/java/org/apereo/cas/config/CasAcceptableUsagePolicyMongoDbConfiguration.java
support/cas-server-support-aup-rest/src/main/java/org/apereo/cas/config/CasAcceptableUsagePolicyRestConfiguration.java
support/cas-server-support-aup-webflow/src/main/java/org/apereo/cas/config/CasAcceptableUsagePolicyWebflowConfiguration.java

This lets you turn off AUP modules via a property rather than removing the dependency.

allow aup to be disabled via property

---

core/cas-server-core-web/src/main/resources/cas_common_messages.properties
webapp/resources/static/js/loggingDashboard.js

Also cleans up the styling of the dropdown menu

Fixes missing popper.js error

---

api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/ExpirationPolicy.java
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/support/BaseDelegatingExpirationPolicy.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/support/RememberMeDelegatingExpirationPolicyTests.java
support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java

Fix the Mongo expireAt field for RememberMe TGTs

---

core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/configurer/DefaultLoginWebflowConfigurer.java

Reinstate the initialAuthnRequestValidationCheckAction as the first webflow action

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/PolicyBasedAuthenticationManager.java

Changed stream to a set implementation that retains order.

Ensure order of authentication handlers

---

style/checkstyle-suppressions-idea.xml

checkstyle-IDEA doesn't like xpath suppressions.
see also https://github.com/jshiell/checkstyle-idea/issues/398

re-add old suppressions file for IDEA

---

ci/tests/cassandra/run-tests-cassandra.sh
ci/tests/cosmosdb/run-tests-cosmosdb.sh
ci/tests/couchbase/run-tests-couchbase.sh
ci/tests/couchdb/run-tests-couchdb.sh
ci/tests/dynamodb/run-tests-dynamodb.sh
ci/tests/filesystem/run-tests-filesystem.sh
ci/tests/ignite/run-tests-ignite.sh
ci/tests/influxdb/run-tests-influxdb.sh
ci/tests/ldap/run-tests-ldap.sh
ci/tests/mail/run-tests-mail.sh
ci/tests/memcached/run-tests-memcached.sh
ci/tests/mongodb/run-tests-mongodb.sh
ci/tests/mssqlserver/run-tests-mssqlserver.sh
ci/tests/mysql/run-tests-mysql.sh
ci/tests/postgres/run-tests-postgres.sh
ci/tests/redis/run-tests-redis.sh
gradle/tests.gradle

disables the main test task during the service oriented tasks
uses regex match against project name for most service tests

Testing tweaks

---

support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/response/OAuth20DefaultAccessTokenResponseGenerator.java

fix oauth compile

---

gradle/tasks.gradle
style/checkstyle-new-rules.xml

defined as warning for all files, error for changed files

[WIP] add import order check

---

_includes/searchfield.html
_layouts/default.html

Waiting on algolia/docsearch-configs/pull/517 to merge the changes to the config file for 5.3.x documentation.  Once that is done, we should be able to merge this.

WIP - Replace Tipue Search with Algolia search for documentation site

---

core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/adaptive/intel/RestfulIPAddressIntelligenceServiceTests.java
support/cas-server-support-audit-rest/src/test/java/org/apereo/cas/audit/RestAuditTrailManagerTests.java
support/cas-server-support-captcha/src/test/java/org/apereo/cas/web/flow/ValidateCaptchaActionTests.java
support/cas-server-support-passwordless/src/test/java/org/apereo/cas/impl/token/RestfulPasswordlessTokenRepositoryTests.java
support/cas-server-support-pm-rest/src/test/java/org/apereo/cas/pm/rest/RestPasswordManagementServiceTests.java
support/cas-server-support-surrogate-authentication-rest/src/test/java/org/apereo/cas/authentication/surrogate/SurrogateRestAuthenticationServiceTests.java
support/cas-server-support-trusted-mfa-rest/src/test/java/org/apereo/cas/trusted/authentication/storage/RestMultifactorAuthenticationTrustStorageTests.java

separate ports for all tests

---

build.gradle

fix jacoco task dependencies

---

gradle/tests.gradle

adjust test suites to run tests once only

---

.travis.yml
api/cas-server-core-api-test-category/src/test/groovy/org/apereo/cas/category/MariaDbCategory.groovy
api/cas-server-core-api-test-category/src/test/groovy/org/apereo/cas/category/RestfulApiCategory.groovy
build.gradle
ci/analyze-bugs.sh
ci/tests/mariadb/run-mariadb-server.sh
ci/tests/mariadb/run-tests-mariadb.sh
ci/tests/restful/run-tests-restful.sh
core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/adaptive/intel/RestfulIPAddressIntelligenceServiceTests.java
core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/policy/RestfulAuthenticationPolicyTests.java
core/cas-server-core-rest/src/test/java/org/apereo/cas/rest/audit/RestResponseEntityAuditResourceResolverTests.java
core/cas-server-core-web-api/src/test/java/org/apereo/cas/web/view/RestfulUrlTemplateResolverTests.java
core/cas-server-core-webflow-api/src/test/java/org/apereo/cas/web/flow/decorator/RestfulLoginWebflowDecoratorTests.java
gradle/tests.gradle
support/cas-server-support-audit-rest/src/test/java/org/apereo/cas/audit/RestAuditTrailManagerTests.java
support/cas-server-support-aup-rest/src/test/java/org/apereo/cas/aup/RestAcceptableUsagePolicyRepositoryTests.java
support/cas-server-support-consent-rest/src/test/java/org/apereo/cas/consent/RestConsentRepositoryTests.java
support/cas-server-support-gauth-core/src/test/java/org/apereo/cas/adaptors/gauth/repository/credentials/RestGoogleAuthenticatorTokenCredentialRepositoryTests.java
support/cas-server-support-interrupt-core/src/test/java/org/apereo/cas/interrupt/RestEndpointInterruptInquirerTests.java
support/cas-server-support-passwordless/src/test/java/org/apereo/cas/impl/account/RestfulPasswordlessUserAccountStoreTests.java
support/cas-server-support-passwordless/src/test/java/org/apereo/cas/impl/token/RestfulPasswordlessTokenRepositoryTests.java
support/cas-server-support-person-directory/src/test/java/org/apereo/cas/RestfulPersonAttributeDaoTests.java
support/cas-server-support-pm-rest/src/test/java/org/apereo/cas/pm/rest/RestPasswordManagementServiceTests.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/PasswordChangeAction.java
support/cas-server-support-rest-authentication/src/test/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandlerTests.java
support/cas-server-support-rest-service-registry/src/test/java/org/apereo/cas/services/RestfulServiceRegistryTests.java
support/cas-server-support-saml-idp-metadata-rest/src/test/java/org/apereo/cas/support/saml/metadata/resolver/RestSamlRegisteredServiceMetadataResolverTests.java
support/cas-server-support-trusted-mfa-rest/src/test/java/org/apereo/cas/trusted/authentication/storage/RestMultifactorAuthenticationTrustStorageTests.java

New categories are introduced for:
- REST-based tests
- MariaDb tests

Move more tests into a separate CI job for parallelism

---

support/cas-server-support-gauth-jpa/build.gradle

fix maria tests compile

---

support/cas-server-support-oauth-core/src/main/java/org/apereo/cas/support/oauth/util/OAuth20Utils.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/validator/token/BaseOAuth20TokenRequestValidator.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/validator/token/OAuth20AuthorizationCodeGrantTypeTokenRequestValidator.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/validator/token/OAuth20PasswordGrantTypeTokenRequestValidator.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/validator/token/OAuth20RefreshTokenGrantTypeTokenRequestValidator.java

Some typo fixes and removed code duplication in GrantType `/token` endpoint request validators

minor fixes + removed duplication

---

support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/validator/token/BaseOAuth20TokenRequestValidator.java

In #3471 I accidentally forgot to actually remove the duplicated code from `3471_follow_up`. This PR fixes it.

Actually removing code duplication in isGrantTypeSupportedBy

---

docs/cas-server-documentation/installation/User-Interface-Customization-Themes.md

doc: fix typo in theme_name variable

---

support/cas-server-support-mongo/build.gradle

fix mongo authn test deps

---

.travis.yml
core/cas-server-core-logout/src/test/java/org/apereo/cas/logout/DefaultLogoutManagerTests.java
core/cas-server-core-logout/src/test/java/org/apereo/cas/logout/DefaultSingleLogoutServiceLogoutUrlBuilderTests.java
gradle/tests.gradle
support/cas-server-support-audit-jdbc/src/test/java/org/apereo/cas/audit/CasSupportJdbcAuditConfigurationTests.java
support/cas-server-support-jpa-service-registry/src/test/java/org/apereo/cas/services/JpaServiceRegistryTests.java
support/cas-server-support-jpa-ticket-registry/src/main/java/org/apereo/cas/config/JpaTicketRegistryConfiguration.java
support/cas-server-support-jpa-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/support/JpaLockingStrategyTests.java
support/cas-server-support-rest-tokens/src/test/java/org/apereo/cas/tokens/BaseTicketResourceEntityResponseFactoryTests.java
support/cas-server-support-throttle-jdbc/src/main/java/org/apereo/cas/config/CasJdbcThrottlingConfiguration.java
support/cas-server-support-throttle-jdbc/src/test/java/org/apereo/cas/web/support/JdbcThrottledSubmissionHandlerInterceptorAdapterTests.java
support/cas-server-support-u2f/src/test/java/org/apereo/cas/adaptors/u2f/storage/AbstractU2FDeviceRepositoryTests.java
support/cas-server-support-u2f/src/test/java/org/apereo/cas/adaptors/u2f/storage/U2FRestResourceDeviceRepositoryTests.java

fix URL builder expectations

---

build.gradle
ci/analyze-dependencies.sh
style/dependency-check-suppressions.xml

Add relevant suppressions.
WIP due to unproven change to dependency check configuration.

Update depedencyCheck stuff

---

support/cas-server-support-couchbase-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/CouchbaseTicketRegistry.java
support/cas-server-support-jpa-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/JpaTicketRegistryCleanerTests.java

style fixes

---

support/cas-server-support-interrupt-webflow/src/main/java/org/apereo/cas/interrupt/webflow/actions/InquireInterruptAction.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/nameid/SamlProfileSamlNameIdBuilder.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/subject/SamlProfileSamlSubjectBuilder.java
support/cas-server-support-shibboleth/src/main/java/org/apereo/cas/support/saml/ShibbolethIdPEntityIdAuthenticationServiceSelectionStrategy.java

fix spotbugs

---

support/cas-server-support-surrogate-authentication-ldap/src/test/resources/ldif/ldap-surrogate.ldif

fix ldap surrogate test

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/audit/AuditRestProperties.java
core/cas-server-core-audit/build.gradle
core/cas-server-core-audit/src/test/java/org/apereo/cas/audit/spi/BaseAuditConfigurationTests.java
support/cas-server-support-audit-couchbase/build.gradle
support/cas-server-support-audit-couchbase/src/test/java/org/apereo/cas/audit/CouchbaseAuditTrailManagerTests.java
support/cas-server-support-audit-jdbc/build.gradle
support/cas-server-support-audit-jdbc/src/test/java/org/apereo/cas/audit/CasSupportJdbcAuditConfigurationTests.java
support/cas-server-support-audit-jdbc/src/test/java/org/apereo/cas/audit/CasSupportMicrosoftSqlServerJdbcAuditConfigurationTests.java
support/cas-server-support-audit-jdbc/src/test/java/org/apereo/cas/audit/CasSupportMySQLJdbcAuditConfigurationTests.java
support/cas-server-support-audit-jdbc/src/test/java/org/apereo/cas/audit/CasSupportPostgresJdbcAuditConfigurationTests.java
support/cas-server-support-audit-jdbc/src/test/resources/auditmssql.properties
support/cas-server-support-audit-jdbc/src/test/resources/auditmysql.properties
support/cas-server-support-audit-jdbc/src/test/resources/auditpostgres.properties
support/cas-server-support-audit-mongo/build.gradle
support/cas-server-support-audit-mongo/src/test/java/org/apereo/cas/audit/MongoDbAuditTrailManagerTests.java
support/cas-server-support-audit-rest/build.gradle
support/cas-server-support-audit-rest/src/main/java/org/apereo/cas/audit/RestAuditTrailManager.java
support/cas-server-support-audit-rest/src/main/java/org/apereo/cas/config/CasSupportRestAuditConfiguration.java
support/cas-server-support-audit-rest/src/test/java/org/apereo/cas/audit/RestAuditTrailManagerTests.java

Clean audit

---

core/cas-server-core-events/src/test/java/org/apereo/cas/support/events/AbstractCasEventRepositoryTests.java
support/cas-server-support-events-influxdb/build.gradle
support/cas-server-support-events-influxdb/src/test/java/org/apereo/cas/support/events/dao/InfluxDbCasEventRepositoryTests.java
support/cas-server-support-events-jpa/src/test/java/org/apereo/cas/support/events/jpa/JpaCasEventRepositoryTests.java
support/cas-server-support-events-memory/build.gradle
support/cas-server-support-events-memory/src/test/java/org/apereo/cas/support/events/dao/InMemoryCasEventRepositoryTests.java
support/cas-server-support-events-mongo/src/test/java/org/apereo/cas/support/events/mongo/MongoDbCasEventRepositoryTests.java

clean up event tests

---

.travis.yml

Trying an invocation that'll get output so we don't get phantom fails...

use different method of calling install-jdk.sh

---

ci/tests/radius/run-radius-server.sh

fix radius

---

docs/cas-server-documentation/index.md

Fixed link to Configuring-Authentication-Components

Broken link fix

---

.travis.yml

fix build cache

---

.travis.yml

remove cache info that always changes in CI

---

support/cas-server-support-trusted-mfa/src/main/java/org/apereo/cas/trusted/authentication/storage/MultifactorAuthenticationTrustStorageCleaner.java
support/cas-server-support-trusted-mfa/src/main/java/org/apereo/cas/trusted/config/MultifactorAuthnTrustConfiguration.java

Mfa trust cleaner fix for 5.3.x

---

core/cas-server-core-events/src/test/java/org/apereo/cas/support/events/AbstractCasEventRepositoryTests.java

fix events test

---

docs/cas-server-documentation/installation/Configuration-Properties-Common.md
docs/cas-server-documentation/installation/Configuration-Properties.md
docs/cas-server-documentation/installation/Configuring-Proxy-Authentication.md
docs/cas-server-documentation/installation/Configuring-SAML2-Authentication.md
docs/cas-server-documentation/integration/Attribute-Release-Consent.md
docs/cas-server-documentation/planning/Security-Guide.md
docs/cas-server-documentation/protocol/REST-Protocol.md
docs/cas-server-documentation/protocol/WS-Federation-Protocol.md

Fixing links in the 5.3.x documentation

Fixing broken links in the 5.3.x documentation

---

support/cas-server-support-consent-core/build.gradle
support/cas-server-support-ehcache-monitor/build.gradle
support/cas-server-support-saml-idp/build.gradle
support/cas-server-support-saml-mdui/build.gradle
support/cas-server-support-token-authentication/build.gradle
webapp/package-lock.json

Fixes dependency errors in test path

fix build dependency

---

docs/cas-server-documentation/installation/Configuration-Properties-Common.md
docs/cas-server-documentation/installation/Configuring-Multifactor-Authentication-Bypass.md
docs/cas-server-documentation/installation/Configuring-Multifactor-Authentication.md

Updated documentation for new features and changes for the next CAS release

Updated MFA Documentation

---

gradle.properties

Upgrading a number of *tricky* components that are known to break the functionality of others, such as #JDK11, commons-lang, couchbase, and duo, etc.

WIP - Dependency Updates

---

gradle/tests.gradle

Changes test tasks from project name based to detecting the presence of the correct annotation.

streamline test tasks

---

docs/cas-server-documentation/installation/Configuration-Properties.md

Update of documentation for #3501 on 5.3.x branch.

Update of 5.3.x documentation for HiOrg-Server delegated PAC4J authn

---

docs/cas-server-documentation/configuration/Configuration-Properties.md

Update of documentation for #3501 on head/master branch.

Update of documentation for HiOrg-Server delegated PAC4J authn (forward port)

---

core/cas-server-core-authentication-mfa/src/main/java/org/apereo/cas/authentication/DefaultMultifactorAuthenticationContextValidator.java

Sorry first pull wasn't quite right.

Fix multivalue auth attributes

---

docs/cas-server-documentation/integration/SCIM-Integration.md

The `scim2` repository has moved to the [PingIdentity](https://github.com/PingIdentity) GitHub organization.

Update UnboundID GitHub URL

---

support/cas-server-support-radius/build.gradle

Fixes `cas-server-support-radius` test build dependencies.

fix radius test build

---

.travis.yml
ci/tests/couchdb/run-couchdb-server-admin.sh
ci/tests/couchdb/run-couchdb-server-user.sh
ci/tests/couchdb/run-couchdb-server.sh
ci/tests/couchdb/run-tests-couchdb-admin.sh
ci/tests/couchdb/run-tests-couchdb-user.sh
support/cas-server-support-couchdb-service-registry/src/test/java/org/apereo/cas/services/CouchDbServiceRegistryTests.java
support/cas-server-support-radius/build.gradle

Creates accounts in docker startup to ensure an normal account may be used.

Fix CouchDb testing WIP

---

build.gradle
gradle/tests.gradle
support/cas-server-support-audit-couchdb/src/main/java/org/apereo/cas/config/CasSupportCouchDbAuditConfiguration.java

replaces shelling out to grep with a caching implementation for tag detection

use caching native groovy grep implementation

---

core/cas-server-core-configuration-api/build.gradle
core/cas-server-core-configuration-api/src/main/java/org/apereo/cas/configuration/DefaultCasConfigurationPropertiesSourceLocator.java

document DefaultCasConfigurationPropertiesSourceLocator

---

build.gradle
gradle/springboot.gradle

I added this so I could set some breakpoints during startup when running "bc"

add build option -DremoteDebuggingSuspend=true, default is false

---

support/cas-server-support-x509-webflow/src/main/java/org/apereo/cas/web/flow/X509WebflowConfigurer.java

My previous pull request included a change I hadn't tested yet and sure enough it doesn't work. This reverts the change for the time being until I can fix it.

undo previous x509 change that didn't work

---

core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasCoreTicketsSchedulingConfiguration.java
webapp/resources/bootstrap.properties

Corrects the property used to enable cleaner scheduler.  
corrects duration syntax in bootstrap.properties

Ticket Cleaner Scheduler Fix

---

support/cas-server-support-aup-couchdb/build.gradle
support/cas-server-support-gauth-couchdb/build.gradle
support/cas-server-support-gauth-couchdb/src/test/java/org/apereo/cas/gauth/credential/CouchDbGoogleAuthenticatorTokenCredentialRepositoryTests.java
support/cas-server-support-gauth-couchdb/src/test/java/org/apereo/cas/gauth/token/GoogleAuthenticatorCouchDbTokenRepositoryTests.java

change gauth test db names

---

developer/Build-Process-6X.md

Add guideline for certificate import to cacert by using Windows.

Update Build Process - Windows guide for keys import to cacert

---

api/cas-server-core-api-test-category/build.gradle
build.gradle

Gradle: only apply groovy if needed

---

core/cas-server-core-services/src/test/java/org/apereo/cas/services/AbstractServiceRegistryTests.java
support/cas-server-support-couchdb-service-registry/src/main/java/org/apereo/cas/config/CouchDbServiceRegistryConfiguration.java
support/cas-server-support-couchdb-service-registry/src/main/java/org/apereo/cas/couchdb/services/RegisteredServiceCouchDbRepository.java
support/cas-server-support-couchdb-service-registry/src/main/java/org/apereo/cas/services/CouchDbServiceRegistry.java
support/cas-server-support-couchdb-service-registry/src/test/resources/log4j2.xml
support/cas-server-support-ldap-service-registry/build.gradle
support/cas-server-support-ldap-service-registry/src/main/java/org/apereo/cas/adaptors/ldap/services/LdapServiceRegistry.java
support/cas-server-support-ldap-service-registry/src/main/resources/log4j2.xml

Fixes error in CouchDb service registry and adds test covering it.

CouchDb: modify service registry test, fix failure

---

api/cas-server-core-api-configuration-model/build.gradle
api/cas-server-core-api-configuration-model/src/test/java/org/apereo/cas/configuration/AdditionalMetadataVerificationTests.java
style/checkstyle-suppressions.xml

Add test for additional configuration metadata to make sure its valid.

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/EncodingUtils.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/cipher/BaseBinaryCipherExecutor.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/crypto/DecryptionException.java

Logs decryption errors with stack traces only in debug mode.
backport of #3689

better crypto exception handling

---

support/cas-server-support-interrupt-core/src/test/java/org/apereo/cas/interrupt/RestEndpointInterruptInquirerTests.java
support/cas-server-support-saml/src/test/java/org/apereo/cas/AllTestsSuite.java

Fix RestEndpointInterruptInquirer and add SAML test to suite

---

core/cas-server-core-services/src/test/java/org/apereo/cas/services/AbstractServiceRegistryTests.java
support/cas-server-support-couchdb-service-registry/src/main/java/org/apereo/cas/services/CouchDbServiceRegistry.java

add missing test, fix failure in couchdb

---

webapp/gulpfile.js
webapp/package-lock.json
webapp/package.json

updated Gulp to v4 and updated the gulpfile to fix issue with using v4

update Gulp to v4

---

support/cas-server-support-pac4j-authentication/src/main/java/org/apereo/cas/integration/pac4j/authentication/handler/support/AbstractPac4jAuthenticationHandler.java

This is a port forward of #3709 to the master branch.

pac4j: Consider typedIdUsed when a custom principalAttributeId is specified (port forward)

---

webapp/resources/messages_de.properties

German translations for welcome screen, password management and AUP (port forward)

---

webapp/resources/messages_de.properties

Added German translations for welcome screen, password management and AUP.

German translations for welcome screen, password management and AUP

---

api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/registry/TicketRegistry.java
core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/policy/UniquePrincipalAuthenticationPolicy.java
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/registry/AbstractTicketRegistry.java
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/registry/DefaultTicketRegistryCleaner.java
core/cas-server-core/src/main/java/org/apereo/cas/AbstractCentralAuthenticationService.java
core/cas-server-core/src/test/java/org/apereo/cas/DefaultCentralAuthenticationServiceMockitoTests.java
support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/RedisTicketRegistry.java

Just a port of #3712 to master branch

Reducing Redis heap memory overhead when running ticket registry cleaner

---

webapp/resources/messages.properties
webapp/resources/messages_de.properties
webapp/resources/static/js/passwordMeter.js
webapp/resources/templates/fragments/pwdupdateform.html

I18n support for Password Reset view (port forward to 6.0.x)

---

webapp/resources/messages.properties
webapp/resources/messages_de.properties
webapp/resources/static/js/passwordMeter.js
webapp/resources/templates/fragments/pwdupdateform.html

Port forward of #3724. Backward port to 6.0 by #3730 .

I18n support for Password Reset view (port forward to master)

---

docs/cas-server-documentation/configuration/Configuration-Properties.md
docs/cas-server-documentation/installation/JAAS-Authentication.md
docs/cas-server-documentation/installation/JDBC-Drivers.md
docs/cas-server-documentation/installation/LDAP-Authentication.md
docs/cas-server-documentation/installation/OAuth-OpenId-Authentication.md
docs/cas-server-documentation/installation/Password-Policy-Enforcement.md
docs/cas-server-documentation/installation/Rest-Authentication.md
docs/cas-server-documentation/monitoring/Configuring-Metrics.md
docs/cas-server-documentation/monitoring/Configuring-Monitoring.md
docs/cas-server-documentation/ticketing/Configuring-Ticket-Expiration-Policy.md

More broken links, mostly anchor tags...

fix broken links in documentation - html-proofer

---

support/cas-server-support-aup-core/src/main/java/org/apereo/cas/aup/AbstractPrincipalAttributeAcceptableUsagePolicyRepository.java

AUP: Do not require TGT before AUP execution (port forward to 6.0)

---

support/cas-server-support-aup-core/src/main/java/org/apereo/cas/aup/AbstractPrincipalAttributeAcceptableUsagePolicyRepository.java

Forward port of #3726 and #3734

AUP: Do not require TGT before AUP execution (port forward to master)

---

.travis.yml
ci/html-proofer-docs.rb
ci/html-proofer-docs.sh
docs/cas-server-documentation/configuration/Configuration-Properties.md
docs/cas-server-documentation/planning/Security-Guide.md

Back-port of validate documentation from master.

6.0.x html proof documentation

---

.travis.yml
ci/html-proofer-docs.rb
ci/html-proofer-docs.sh
docs/cas-server-documentation/installation/Configuration-Properties-Common.md
docs/cas-server-documentation/installation/Configuration-Properties.md
docs/cas-server-documentation/installation/Configuring-Ticket-Expiration-Policy.md
docs/cas-server-documentation/installation/JDBC-Drivers.md
docs/cas-server-documentation/installation/OAuth-OpenId-Authentication.md
docs/cas-server-documentation/planning/Security-Guide.md

Back-port html proofer doc validation and fix some broken links. Also label the build jobs in travis.yml.

Backport documentation validation via html proofer to 5.3.x

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jOidcClientProperties.java
docs/cas-server-documentation/installation/Configuration-Properties.md
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java

Add responseMode and responseType parameters for pac4j OIDC delegation.

Allow to set responseType and responseMode for OIDC clients

---

webapp/resources/messages_de.properties

Would be great to have this included in 5.3.8

Revised German messages

---

webapp/resources/messages_de.properties

Forward port of #3747 to 6.0.x

Revised German messages (6.0.x port)

---

webapp/resources/messages_de.properties

Forward port of #3747 and #3748 to master

Revised German messages (master port)

---

core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/DefaultRegisteredServiceAccessStrategy.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/DefaultRegisteredServiceAccessStrategyTests.java

Forward port if #3755 to 6.0.x branch.
@mmoayyed, please port to master as discussed.

Bug in DefaultRegisteredServiceAccessStrategy checking required attributes (6.0 port)

---

webapp/resources/templates/fragments/loginform.html
webapp/resources/templates/fragments/scripts.html

Requested login page responses with http 500 when google recaptcha is implemented. Comparisions of variable recaptchaSiteKey in two html fragment files has been fixed

Http500 response with google recaptcha

---

gradle.properties
gradle/dependencies.gradle

upgrade dom4j version to version used by hibernate, avoid having two dom4j jars in webapp

dependency update - fix dom4j group and update version

---

build.gradle
core/cas-server-core-audit/src/test/java/org/apereo/cas/audit/spi/BaseAuditConfigurationTests.java
core/cas-server-core-cookie-api/build.gradle
core/cas-server-core-cookie-api/src/test/java/org/apereo/cas/web/support/CookieRetrievingCookieGeneratorTests.java
core/cas-server-core-cookie-api/src/test/java/org/apereo/cas/web/support/CoreCookieTestsSuite.java
core/cas-server-core-cookie-api/src/test/java/org/apereo/cas/web/support/DefaultCasCookieValueManagerTests.java
core/cas-server-core-cookie/build.gradle
style/checkstyle-rules-junit5.xml
style/checkstyle-rules.xml
style/import-control-junit5.xml

migrate core/cas-server-core-cookie to junit5

---

build.gradle
core/cas-server-core-audit/src/test/java/org/apereo/cas/audit/spi/BaseAuditConfigurationTests.java
core/cas-server-core-logging-api/build.gradle
core/cas-server-core-logging/build.gradle
core/cas-server-core-logging/src/test/java/org/apereo/cas/logging/web/ThreadContextMDCServletFilterTests.java
core/cas-server-core-logout-api/build.gradle
core/cas-server-core-logout/build.gradle
core/cas-server-core-logout/src/test/java/org/apereo/cas/logout/CasLogoutTestsSuite.java
core/cas-server-core-logout/src/test/java/org/apereo/cas/logout/DefaultLogoutManagerTests.java
core/cas-server-core-logout/src/test/java/org/apereo/cas/logout/DefaultSingleLogoutServiceLogoutUrlBuilderTests.java
core/cas-server-core-logout/src/test/java/org/apereo/cas/logout/LogoutHttpMessageTests.java
core/cas-server-core-logout/src/test/java/org/apereo/cas/logout/SamlCompliantLogoutMessageCreatorTests.java
style/checkstyle-rules-junit5.xml
style/checkstyle-rules.xml
style/import-control-junit5.xml

migrates `core/cas-server-core-log*` to junit5

Migrate core/cas-server-core-log* to junit5

---

core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/configurer/DefaultLoginWebflowConfigurer.java

Open the `DefaultLoginWebflowConfigurer` class by turning `private` methods into `protected` ones.

Open the DefaultLoginWebflowConfigurer

---

support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java

See: https://github.com/apereo/cas/pull/3797 for more explanations.

Fix password management

---

support/cas-server-support-actions/build.gradle
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/AllTestsSuite.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/AuthenticationViaFormActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/CreateTicketGrantingTicketActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/FlowExecutionExceptionResolverTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/FrontChannelLogoutActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/GenerateServiceTicketActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/GenericSuccessViewActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/InitialFlowSetupActionCookieTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/InitialFlowSetupActionSsoTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/InitialFlowSetupActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/LogoutActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/SendTicketGrantingTicketActionSsoTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/SendTicketGrantingTicketActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/ServiceAuthorizationCheckTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/ServiceWarningActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/SetServiceUnauthorizedRedirectUrlActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/TerminateSessionActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/TerminateSessionConfirmingActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/TicketGrantingTicketCheckActionTests.java

junit5 migrations: support/cas-server-support-actions WIP

---

support/cas-server-support-configuration-cloud-aws-s3/build.gradle
support/cas-server-support-configuration-cloud-aws-s3/src/test/java/org/apereo/cas/AmazonS3BucketsCloudConfigBootstrapConfigurationTests.java
support/cas-server-support-configuration-cloud-jdbc/build.gradle
support/cas-server-support-configuration-cloud-jdbc/src/test/java/org/apereo/cas/JdbcCloudConfigBootstrapConfigurationTests.java
support/cas-server-support-configuration-cloud-mongo/build.gradle
support/cas-server-support-configuration-cloud-mongo/src/test/java/org/apereo/cas/MongoDbCloudConfigBootstrapConfigurationTests.java

junit5 migrations: support/cas-server-support-configuration WIP

---

.travis.yml

remove gradle 5 from cache

---

support/cas-server-support-saml-idp-metadata/src/main/java/org/apereo/cas/support/saml/services/idp/metadata/SamlRegisteredServiceMetadataHealthIndicator.java

Revise the logic in the SamlRegisteredServiceMetadataHealthIndicator so that service metadata is reported as "available" if *any* metadata provider supports the service, instead of requiring *all* providers to support it. 
Without this, the health indicator spuriously reports everything as "DOWN" if you have a mixture of FileSystemResourceMetadataResolver and URLResourceMetadataResolver services -- the FileSystem resolver will reject "http://" metadataLocation values, and the URL resolver will reject "file://"

SAML2 - Fix problem of MetadataHealthIndicator always reporting "DOWN"

---

gradle/webapp.gradle
webapp/cas-server-webapp-bootadmin-server/build.gradle
webapp/cas-server-webapp-config-server/build.gradle
webapp/cas-server-webapp-config/build.gradle
webapp/cas-server-webapp-config/src/test/java/org/apereo/cas/AllWebflowTestsSuite.java
webapp/cas-server-webapp-config/src/test/java/org/apereo/cas/BaseCasWebflowSessionContextConfigurationTests.java
webapp/cas-server-webapp-config/src/test/java/org/apereo/cas/WiringConfigurationTests.java
webapp/cas-server-webapp-config/src/test/java/org/apereo/cas/web/security/authentication/BaseMonitorEndpointLdapAuthenticationProviderTests.java
webapp/cas-server-webapp-config/src/test/java/org/apereo/cas/web/security/authentication/MonitorEndpointLdapAuthenticationProviderGroupsBasedTests.java
webapp/cas-server-webapp-config/src/test/java/org/apereo/cas/web/security/authentication/MonitorEndpointLdapAuthenticationProviderRolesBasedTests.java
webapp/cas-server-webapp-eureka-server/build.gradle
webapp/cas-server-webapp-init-bootadmin-server/build.gradle
webapp/cas-server-webapp-init-config-server/build.gradle
webapp/cas-server-webapp-init-eureka-server/build.gradle
webapp/cas-server-webapp-init-tomcat/build.gradle
webapp/cas-server-webapp-init-tomcat/src/test/java/org/apereo/cas/tomcat/CasTomcatServletWebServerFactoryTests.java
webapp/cas-server-webapp-init/build.gradle
webapp/cas-server-webapp-init/src/test/java/org/apereo/cas/CasEmbeddedContainerUtilsTests.java
webapp/cas-server-webapp-jetty/build.gradle
webapp/cas-server-webapp-tomcat/build.gradle
webapp/cas-server-webapp-tomcat/src/test/java/org/apereo/cas/CasTomcatBannerTests.java
webapp/cas-server-webapp-undertow/build.gradle
webapp/cas-server-webapp/build.gradle

junt5 migrations: webapp

---

core/cas-server-core-authentication-mfa-api/src/main/java/org/apereo/cas/authentication/trigger/PrincipalAttributeMultifactorAuthenticationTrigger.java

Need to add .get() to get the id of the element. Without that it gives error and it is not called the MFA.

Fix method isActivated in PrincipalAttributeMultifactorAuthenticationTrigger

---

gradle.properties

To fix the issue with the Google OAuth client.

Upgrade to pac4j v3.6.0

---

style/dependency-check-suppressions.xml
support/cas-server-support-couchbase-core/src/main/java/org/apereo/cas/couchbase/core/CouchbaseException.java
support/cas-server-support-couchbase-service-registry/src/main/java/org/apereo/cas/services/CouchbaseServiceRegistry.java

This backports a fix for the couchbase service registry's query that was fixed during the junit5 upgrade.

Fix couchbase

---

support/cas-server-support-memcached-core/src/main/java/org/apereo/cas/memcached/kryo/CloseableKryoFactory.java
support/cas-server-support-memcached-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/MemcachedTicketRegistryTests.java

This PR intends to fix kryo problems with memcached.
The first commit try to show problems
The second commit will fix problems

fix: kryo serialization problems with memcached

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/authentication/PasswordEncoderProperties.java
core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/support/password/PasswordEncoderUtils.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/crypto/GlibcCryptPasswordEncoder.java
core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/crypto/GlibcCryptPasswordEncoderTests.java
docs/cas-server-documentation/configuration/Configuration-Properties-Common.md

Port forward to master of #3849

Add glibc crypt password encoder (master branch port)

---

docs/cas-server-documentation/monitoring/Monitoring-Statistics.md

url update - outdated info

---

docs/cas-server-documentation/configuration/Configuration-Properties.md

Update documentation : fix spnego properties names

---

webapp/resources/templates/fragments/loginsidebar.html

ui/node Fix typo

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java

Pac4j: Fix SAML IdP initiated logout 

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java

Adds simple check that delegation handling may continue correctly for logout requests initiated by identity provider.
Identified the problem when using SAML integration.

Pac4j: Fix SAML IdP initiated logout

---

webapp/resources/templates/fragments/loginsidebar.html

Update commit 4fec66cf890549d11ba9b209f571e60c954b5fe5
Minnor UI change
Replace not open `p` tag by `br` tag

UI Thymeleaf: Use linebreak instead of empty paragraph

---

core/cas-server-core-web/src/main/resources/cas_common_messages.properties

This fix a problem introduced by https://github.com/apereo/cas/commit/da0c072e990e7823621c5a5bf86e333ed8c8a4cf
Jquery-dist make change on the packaging distribution [see here](https://github.com/jquery/jquery-dist/commit/180c5c33e477463ed93a9d5f7ac7cad7c9809f1c)

fix: jquery dist path changed

---

api/cas-server-core-api-webflow/src/main/java/org/apereo/cas/web/flow/CasWebflowConstants.java
support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedAuthenticationWebflowConfigurer.java
support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java

Same story as #3898 for the 6.0.x branch.

Skip delegation when SSO session present (6.0.x branch)

---

support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/token/OidcIdTokenGeneratorService.java

This PR backports a fix from master for setting the JwtId when OIDC is called for PASSWORD or CLIENT_CREDENTIALS flows.

Backport of fix for OIDC JwtId

---

docs/cas-server-documentation/configuration/Configuration-Properties.md

Fix probable typo in Yubikey JPA doc

---

webapp/resources/messages_fr.properties

Add French translation of `screen.service.initial.message` key

add French message for requiredServicePattern

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/saml/Pac4jSamlClientProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
gradle.properties
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java

Update pac4j version to be able to fix certificates generation per clientName when having several clientName. [For more details of the change see here](https://github.com/pac4j/pac4j/commit/c9aa8c14e4fb911257183db4910683792e07d437).

chore: upgrade pac4j and apply unicity fix on pac4j SAML certificates

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/principal/resolvers/PersonDirectoryPrincipalResolver.java
core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/AllAuthenticationTestsSuite.java
core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/principal/resolvers/PersonDirectoryPrincipalResolverTests.java
core/cas-server-core-authentication/src/test/java/org/apereo/cas/AllTestsSuite.java

Fix NPE from null attribute values backport for 6.0.x

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/principal/resolvers/PersonDirectoryPrincipalResolver.java
core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/principal/PersonDirectoryPrincipalResolverTests.java

Fix NPE from null attribute values backport for 5.3.x

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java
support/cas-server-support-saml-mdui/src/main/java/org/apereo/cas/support/saml/mdui/config/SamlMetadataUIWebflowConfiguration.java
support/cas-server-support-saml-mdui/src/test/java/org/apereo/cas/support/saml/mdui/web/flow/SamlMetadataUIParserActionTests.java
support/cas-server-support-saml-mdui/src/test/java/org/apereo/cas/support/saml/mdui/web/flow/SamlMetadataUIParserDynamicActionTests.java

Porting commit 6d4b11ff615e20e2661a7dfd374433520956651a to 5.3.x branch, so I can use the saml mdui.

Port MDUI bean def fixes to 5.3 branch

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java

This is a back port to branch 5.3.x of the pull request #3874 "Pac4j: Fix SAML IdP initiated logout", which fixed the Single Logout logout initiated from a SAML IdP.

Pac4j: Fix SAML IdP initiated logout - backport to 5.3.x

---

support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileEndpointController.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java

As a customization, I may want to change the user info endpoint in the OIDC support.

Open up a little the OAuth/OIDC support

---

support/cas-server-support-saml-mdui/src/main/java/org/apereo/cas/support/saml/mdui/config/SamlMetadataUIWebflowConfiguration.java
support/cas-server-support-saml-mdui/src/test/java/org/apereo/cas/support/saml/mdui/web/flow/SamlMetadataUIParserActionTests.java
support/cas-server-support-saml-mdui/src/test/java/org/apereo/cas/support/saml/mdui/web/flow/SamlMetadataUIParserDynamicActionTests.java

Same as #4029, but for 6.0 branch.

Port mdui bean def fixes to 6.0 branch

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/saml/Pac4jSamlClientProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java

Provide a way to be able to add `<ds:Signature>` part into `AuthnRequest`.

feat: adding pac4j AuthnRequest Embedded signature

---

api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/TicketCatalog.java
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/DefaultTicketCatalog.java
support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java

Improvements to the mongo ticket registry (6.0.x)

---

api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/TicketCatalog.java
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/DefaultTicketCatalog.java
support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java

Improvments for mongo ticket registry (5.3.x)

---

core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/ServiceRegistryInitializer.java

Doing a regex match on service id leads to false positives (6.0.x)

---

core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/ServiceRegistryInitializer.java

Doing a regex match on service id leads to false positives (5.3.x)

---

support/cas-server-support-mongo-service-registry/src/main/java/org/apereo/cas/services/MongoDbServiceRegistry.java

Implement MongoDbServiceRegistry queries as mongo queries 6.0.x

---

support/cas-server-support-mongo-service-registry/src/main/java/org/apereo/cas/services/MongoDbServiceRegistry.java

Implement MongoDbServiceRegistry queries as mongo queries 5.3.x

---

api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/TicketCatalog.java
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/DefaultTicketCatalog.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/BaseTicketRegistryTests.java

Fix TicketCatalog.find(Class) (6.0.x)

---

api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/TicketCatalog.java
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/DefaultTicketCatalog.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/BaseTicketRegistryTests.java

Fix TicketCatalog.find(Class)

---

support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/PasswordChangeAction.java

This is the 6.0.x version of #4093

Fix password change error message stickiness

---

core/cas-server-core-authentication-mfa-api/src/main/java/org/apereo/cas/authentication/MultifactorAuthenticationUtils.java

When using the MFA simple support and no service, I have encountered a NPE. This PR fixes it.

Fix NPE on MFA

---

gradle/overrides.gradle

Pull in fix for thread safety bug in mimetype caching (until next tagged release)

Update spring version to use snapshot

---

core/cas-server-core-cookie-api/src/test/java/org/apereo/cas/web/support/CookieRetrievingCookieGeneratorTests.java

Port forward the unit test fixes from #4113

Port forward CookieRetrievingCookieGeneratorTests fixes

---

core/cas-server-core-cookie-api/build.gradle
core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/CookieRetrievingCookieGenerator.java
core/cas-server-core-cookie-api/src/test/java/org/apereo/cas/web/support/CookieRetrievingCookieGeneratorTests.java

Not required for master as master already deals with multivalue attributes.

Allow multivalue attributes in CookieRetrievingCookieGenerator

---

docs/cas-server-documentation/configuration/Configuration-Properties.md

fix link in docs

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/http/SimpleHttpClientFactoryBean.java

https://github.com/apereo/cas/pull/4126 to 6.0.x branch.

Add method to override http client keep alive strategy

---

core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/BaseTicketSerializers.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/TicketSerializersTests.java

Already solved in master so no port forward required.

Add TST support to BaseTicketSerializers 6.0.x

---

support/cas-server-support-jpa-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/JpaTicketRegistry.java

Backport https://github.com/apereo/cas/commit/58bb84ca43c882377c90b73b2a759b134540248b into 6.0.x branch.

Fix JpaTicketRegistry logging

---

docs/cas-server-documentation/configuration/Configuration-Discovery.md
docs/cas-server-documentation/configuration/Configuration-Management-Reload.md
docs/cas-server-documentation/configuration/Configuration-Metadata-Repository.md
docs/cas-server-documentation/configuration/Configuration-Properties-Security.md
docs/cas-server-documentation/configuration/Configuration-Server-Management.md

This PR fixes minor typos and grammars in Configuration docs.

Update Configuration Docs

---

gradle.properties

Update dependency version to 1.8.14

update person-directory dependency to 1.8.14

---

core/cas-server-core-authentication-mfa/src/test/java/org/apereo/cas/authentication/DefaultMultifactorAuthenticationProviderResolverTests.java

checkstyle fix

---

.travis.yml

This will allow spotbugs checks and dependency checks to run in parallel.

travis ci - group spotbugs and dependencies into same stage

---

.travis.yml

Avoid escaping parenthesis and just match any character.
Test:
travis-conditions eval "NOT (commit_message =~ env(DEPENDENCY_BOT_RE) and type = pull_request)" --data '{"type": "pull_request", "commit_message": "renovatebot(deps): update amazonsdk to v1.11.613", "env": ["DEPENDENCY_BOT_RE=^renovatebot.deps"]}'
false

travis-ci - attempt fo fix condition

---

.travis.yml

The commit_message changes and branch is updated

travis - use head_branch instead of commit_message

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pm/PasswordManagementProperties.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/SendPasswordResetInstructionsAction.java

Changes add service url to the password reset url.

adding service url to password reset url

---

gradle/dependencies.gradle
style/dependency-check-suppressions.xml

This may or may not get rid of logback that was getting into overlay with lots of dependencies.

Update dependency exclusions

---

core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/ChainingAttributeReleasePolicy.java

If you use jpa service registry for oidc services and define scopes in your service than you the getConsentPolicy method creates an endless chain consentPolicies in the database. The new class of OidcServiceRegistryListener introduce this error because it runs during transaction of load services method of the JpaRepository. So the OidcRegisteredService changes and JPA writes the object back to the database. With every call of the load method the consent policies get one more ChainingRegisteredServiceConsentPolicy.
Database Object:
```
o   r   g   .   a   p   e   r   e   o   .   c   a   s   .   s   e   r   v   i   c   e   s   .   c   o   n   s   e   n   t   .   C   h   a   i   n   i   n   g   R   e   g   i   s   t   e   r   e   d   S   e   r   v   i   c   e   C   o   n   s   e   n   t   P …
```

OIDC JpaServiceRegistry Leak Detection Error

---

support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/OAuth20DefaultTokenGenerator.java

Backport of: https://github.com/apereo/cas/pull/4059/files

Fix the OAuth+JPA support with @Transactional

---

core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasCoreTicketIdGeneratorsConfiguration.java

Fixing this one issue to see what tests are still failing.

Fixing Tests

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/ResourceUtils.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/scripting/ScriptingUtils.java
core/cas-server-core-util/src/test/java/org/apereo/cas/util/ScriptingUtilsTests.java
core/cas-server-core-util/src/test/resources/ScriptingUtilsTestGroovyScript.groovy

6.0.x backport: Fix issue where Groovy scripts on the classpath cannot be loaded

---

core/cas-server-core-configuration-metadata-repository/src/main/java/org/springframework/boot/configurationmetadata/CasConfigurationMetadataRepositoryJsonBuilder.java

Configuration metadata: prevent NPE if source.getType() is null

---

docs/cas-server-documentation/index.md

Added link to Acceptto MFA documentation at the docs index page.

Link to Acceptto MFA documentations

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/oidc/Pac4jAzureOidcClientProperties.java

Provide some description for Pac4jAzure `tenant` properties:
- Add in what can be pass in to tenant
- Add in the behavior of setting `tenant` overriding `discoveryUri`

[Doc] Provide description for Pac4jAzure `tenant` properties

---

webapp/cas-server-webapp-resources/src/main/resources/templates/fragments/loginform.html

Enable 'login button' when the user returns with the browser back button (enable the submit button and replace text 'Wait a moment...' by 'Login').

User Interface: Re-enable login button

---

webapp/cas-server-webapp-resources/src/main/resources/static/js/passwordMeter.js
webapp/cas-server-webapp-resources/src/main/resources/templates/fragments/pwdupdateform.html

- Display of strength warning and suggestions as warning alerts
- Remove "," between each suggestions
- add fontawesome lock behind password inputs

Password Management : display feedback warning and suggestions as warning alerts when user change his password

---

support/cas-server-support-pm-ldap/src/main/java/org/apereo/cas/pm/LdapPasswordManagementService.java

Factor out duplicated code from findUsername(), findEmail(), and findPhone()

refactor duplicate LDAP attribute fetch code

---

core/cas-server-core-web/build.gradle
core/cas-server-core-web/src/main/resources/cas_common_messages.properties
core/cas-server-core-web/src/test/java/org/apereo/cas/AllTestsSuite.java
core/cas-server-core-web/src/test/java/org/apereo/cas/web/WebjarValidationTests.java
core/cas-server-core-web/src/test/resources/log4j2.xml

This adds a test which validates that all the webjars links in cas_common_messages.properties are in the classpath. This also fixes two links that were bad.

add test to check for bad webjar links, fix two links

---

gradle.properties

update quartz dependency for CVE-2019-13990

---

developer/Maintenance-Policy.md

Change SPM Starting Date for 6.1.x

---

gradle.properties

(cherry picked from commit a99d765c0da7b004f433183d45b17b1fdf56a8ea)

update quartz dependency for CVE-2019-13990 (#4382)

---

gradle.properties
gradle/dependencies.gradle

(cherry picked from commit a7e3f33f1641965a78b9f947943c95fcdc76e145)

update signalfx dependency (#4385)

---

support/cas-server-support-saml-idp-metadata/src/main/java/org/apereo/cas/support/saml/services/idp/metadata/cache/resolver/MetadataQueryProtocolMetadataResolver.java

Backport error prone fix so snapshots will build.

backport errorprone fix

---

etc/loadtests/jmeter/CAS_SAML2.jmx

Updated JMeter script for SAML2 protocol support.  Needed to move parameters from Body tab to JMeter Parameters tab for it to work.
Thanks!

updated SAML JMeter test script to reflect needed changes to work

---

support/cas-server-support-ehcache-ticket-registry/src/main/java/org/apereo/cas/config/EhcacheTicketRegistryConfiguration.java
support/cas-server-support-ehcache-ticket-registry/src/test/java/org/apereo/cas/AllTestsSuite.java
support/cas-server-support-ehcache-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/CachesEndpointTests.java
support/cas-server-support-ehcache-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/EhCacheTicketRegistryTests.java

This fixes the spring boot CachesEndpoint within the EhCache module.

Backport CachesEndpoint actuator fix

---

support/cas-server-support-logging-config-cloudwatch/build.gradle
support/cas-server-support-logging-config-splunk/build.gradle

This PR adds annotation processing for log4j. This creates the appropriate log4j file so that that appenders can be used.

Add annotation processing for logging so that log4j file is created

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/saml/Pac4jSamlClientProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java

From pac4j to CAS. SAML protocol.

Add the allSignatureValidationDisabled property

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java

To allow some customizations...

Open up a little the DelegatedClientAuthenticationAction

---

docs/cas-server-documentation/configuration/Configuration-Properties.md

added a pipe symbol to fix table formatting for SAML SPs

Fix table formatting for SAML SPs

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/DelegatedClientWebflowManager.java

The authentication delegation to a CAS server has a big issue. It seems to work, but it doesn't. You generally see that under a certain workload, but it can be reproduced fairly easily.
The TST is saved into the `customParams` of the `configuration` of the `CasClient` which is a problem because it's a singleton so the TST used at the time of the ticket validation (`CasAuthenticator`) can be the one of another authentication delegation.
This PR fixes the issue by using the session instead.
It can be tested easily with this project: https://github.com/casinthecloud/cas-pac4j-oauth-demo (master branch). It's the version 6.2.0-RC1, but all CAS versions have the same code and issue.
- Call the login page (http://localhost:8080/cas/login) and start the authentication delegation to a CAS server …

Fix the authentication delegation to a CAS server

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/replication/SessionReplicationProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-acceptto-mfa/src/main/java/org/apereo/cas/config/AccepttoMultifactorAuthenticationConfiguration.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20Configuration.java
support/cas-server-support-pac4j-api/src/main/java/org/apereo/cas/integration/pac4j/DistributedJ2ESessionStore.java
support/cas-server-support-pac4j-api/src/test/java/org/apereo/cas/integration/pac4j/DistributedJ2ESessionStoreTests.java
support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/support/authentication/Pac4jAuthenticationEventExecutionPlanConfiguration.java

This is a new implementation of the `DistributedJ2ESessionStore` based on a cookie to solve previous issues.

Delegated authentication: fix again the DistributedJ2ESessionStore

---

docs/cas-server-documentation/mfa/Configuring-Multifactor-Authentication-Triggers.md

Doc : fix MFA Groovy Trigger Example script

---

support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/flow/SamlIdPMetadataUIAction.java

This needs to check for null in case the service it is looking for is not of type saml.

Avoid trying to process null (not found) saml service

---

support/cas-server-support-saml-core-api/src/main/java/org/apereo/cas/support/saml/util/AbstractSaml20ObjectBuilder.java
support/cas-server-support-saml-core-api/src/main/java/org/apereo/cas/support/saml/util/AbstractSamlObjectBuilder.java

More debug trace instrumentation

---

support/cas-server-support-spnego-webflow/src/main/java/org/apereo/cas/web/flow/SpengoWebflowConfigurer.java

…param
cherry-pick into master #4662

Fix missing "warn" transition for spnego weblflow with "renew" query param

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/saml/Pac4jSamlClientProperties.java
api/cas-server-core-api-configuration-model/src/main/resources/META-INF/additional-spring-configuration-metadata.json
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java

signLogoutRequests seems to duplicate signServiceProviderLogoutRequest

Remove cas.authn.pac4j.saml[0].signLogoutRequests

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/saml/Pac4jSamlClientProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java
support/cas-server-support-pac4j-core-clients/src/test/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactoryTests.java

Added and handled configuration parameter to specify saml session store factory WRT pac4j property org.pac4j.saml.config.SAML2Configuration#samlSessionStoreFactory

Provides feature to configure saml session store factory

---

gradle.properties
support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/util/LdapUtils.java

PoolConfig class removed, properties are now on the connection factory.

Update ldaptive to v2.0.0-RC2.

---

support/cas-server-support-thymeleaf/src/main/resources/messages_it.properties

Italian messages: fix accents + some missing keys

---

gradle/dependencies.gradle
support/cas-server-support-aup-ldap/build.gradle
support/cas-server-support-consent-ldap/build.gradle
support/cas-server-support-ldap/build.gradle
support/cas-server-support-passwordless-ldap/build.gradle
support/cas-server-support-pm-ldap/build.gradle
support/cas-server-support-spnego-webflow/build.gradle
support/cas-server-support-surrogate-authentication-ldap/build.gradle
support/cas-server-support-x509-core/build.gradle
webapp/cas-server-webapp-config/build.gradle

com.unboundid:unboundid-ldapsdk shall be only a test dependency

---

support/cas-server-support-radius/src/main/java/org/apereo/cas/config/RadiusConfiguration.java

This patch fixes missing attribute resolution from separate attribute repository in RADIUS as primary authentication

Fix attribute resolution in Radius

---

support/cas-server-support-token-authentication/build.gradle
support/cas-server-support-token-webflow/build.gradle

Backport of https://github.com/apereo/cas/pull/4768

Remove JWT generation in JWT authentication

---

support/cas-server-support-token-authentication/src/main/java/org/apereo/cas/token/authentication/TokenAuthenticationHandler.java

Backport of: https://github.com/apereo/cas/pull/4770

Fix the JWT TokenAuthenticationHandler

---

support/cas-server-support-throttle-redis/src/main/java/org/apereo/cas/web/support/RedisThrottledSubmissionHandlerInterceptorAdapter.java

Ref: (https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/79qaQ_P-0Kg)
As mentioned in the link, there is a casting error that prevents this piece of code from actually functioning.

Redis authentication throttling: Fix class casting error

---

webapp/cas-server-webapp-resources/src/main/resources/application.properties

See https://github.com/apereo/cas/pull/4784/

[bugfix] Prevent infinite 302 when embedded jetty and behind LB (backport)

---

support/cas-server-support-throttle-redis/src/main/java/org/apereo/cas/web/support/RedisThrottledSubmissionHandlerInterceptorAdapter.java

RedisThrottledSubmissionHandlerInterceptorAdapter.java coding style fix

---

support/cas-server-support-trusted-mfa-core/src/main/java/org/apereo/cas/trusted/authentication/DefaultMultifactorAuthenticationTrustedDeviceBypassEvaluator.java

fix direct login /cas unauthorized service error with MFA trusted device enabled

---

gradle.properties

Connection factory close() is now a synchronous operation.

Upgrade ldaptive to v2.0.0-RC4

---

gradle.properties
support/cas-server-support-gua/src/test/java/org/apereo/cas/gua/impl/LdapUserGraphicalAuthenticationRepositoryTests.java
support/cas-server-support-ldap/src/test/java/org/apereo/cas/util/LdapTestUtils.java

Includes new Authenticator#close method.

Upgrade ldaptive to v2.0.0-RC5.

---

support/cas-server-support-captcha/src/main/java/org/apereo/cas/web/flow/config/CasCaptchaConfiguration.java

Allow more Captcha customisations

---

gradle.properties

Update pac4j to 4.0.2.
This version fix this ClassCastException which occur in CAS : https://github.com/pac4j/pac4j/commit/ca250474deea8d23585b3574eaf8331c04f953b3

Update pac4j to 4.0.2

---

support/cas-server-support-syncope-authentication/src/main/java/org/apereo/cas/syncope/authentication/SyncopeAuthenticationHandler.java

Fix few typos from previous PR #4893

Fixing property errors for Syncope Authentication

---

support/cas-server-support-thymeleaf/src/main/resources/messages.properties
support/cas-server-support-thymeleaf/src/main/resources/templates/protocol/oidc/confirm.html

Added Claims and Scopes in confirm template in OIDC protocol to lang resources.

Change template for OIDC - Scopes and claims as string resource

---

ci/tests/perf/perftests-jmeter.sh

I was trying to run jmeter test locally and was having some issues with spring webflow token and wanted to see how they were running in CI, but looked like there were errors copying users to /etc/ folder and I didn't see any output from cas server after startup so not sure they are running. 
Create jmeter folders with sudo so they get created in ci
Quiet the jmeter unzip b/c it makes looking at log painful
cat results.log to make sure tests are running

update jmeter ci test

---

gradle.properties

Update to ldaptive v2.0.0 release.

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/saml/Pac4jSamlClientProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DefaultDelegatedClientFactory.java

Provides support for pac4j configuration parameter wantsResponsesSigned

Support Delegated AuthN SAML configuration parameter: wantsResponsesSigned

---

developer/Maintenance-Policy.md

Fix typo: "Dcember" to "December"

Fix typo: "Dcember" to "December" (Maintenance Policy)

---

core/cas-server-core-logging-api/src/main/java/org/apereo/cas/logging/LoggingUtils.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/LoggingUtils.java
core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/LoggingUtilsTests.java

Minor polishing for code consistency

@UtilityClass already transforms all methods to `static`

---

core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/AbstractRegisteredService.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/AbstractRegisteredServiceTests.java

The title describes the details.

AbstractRegisteredService -> add null check in `setRequiredHandlers`

---

core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/AbstractRegisteredService.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/AbstractRegisteredServiceTests.java

PR (#4955)
(cherry picked from commit 82746e3e3d90374c1e37065ee6b7e03e6dd59043)

AbstractRegisteredService -> add null check in `setRequiredHandlers` backport

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/oidc/BasePac4jOidcClientProperties.java
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DefaultDelegatedClientFactory.java

Support disable Pkce

---

docs/cas-server-documentation/protocol/CAS-Protocol-Specification.md

Issues to be solved in this PR:
- Some appendix and a reference are not linked yet
- Appendix A in the first sentence of section [2.5.2](https://apereo.github.io/cas/6.2.x/protocol/CAS-Protocol-Specification.html#252-response)
- Appendix A in the first sentence of section [2.6.2](https://apereo.github.io/cas/6.2.x/protocol/CAS-Protocol-Specification.html#262-response)
- [6] in the third point after code snippet in [Appendix B](https://apereo.github.io/cas/6.2.x/protocol/CAS-Protocol-Specification.html#appendix-b-safe-redirection)
- Broken link format in section [2.5.5](https://apereo.github.io/cas/6.2.x/protocol/CAS-Protocol-Specification.html#255-attributes-cas-30), rendered as:
> .... See \[Appendix A\]\(<#head_appdx_a>\) for details.
Actually, I'm not really sure why this link is not …

Docs: Fix Links and Naming in Protocol Specification

---

support/cas-server-support-saml-idp-core/src/main/java/org/apereo/cas/support/saml/SamlIdPUtils.java
support/cas-server-support-saml-idp-core/src/main/java/org/apereo/cas/support/saml/services/idp/metadata/SamlRegisteredServiceServiceProviderMetadataFacade.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/idp/metadata/SamlRegisteredServiceServiceProviderMetadataFacadeTests.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/util/SamlIdPUtilsTests.java

(cherry picked from commit 88e8977e11b4cb489bf161bad350cf5a9ed8ba69)

Fix problem with SP metadata that defines multiple ACS endpoints (#4923)

---

docs/cas-server-documentation/configuration/Configuration-Properties.md

See https://codecentric.github.io/spring-boot-admin/current/#spring-boot-admin-client

Doc : fix spring boot admin configurations example

---

support/cas-server-support-hazelcast-ticket-registry/src/main/java/org/apereo/cas/config/HazelcastTicketRegistryConfiguration.java

[6.2.x] Fix Hazelcast Cluster shutdown when configuration is reloaded

---

support/cas-server-support-actions/src/main/java/org/apereo/cas/web/flow/logout/TerminateSessionAction.java

Open a little the TerminateSessionAction

---

docs/cas-server-documentation/logging/Logging-MDC.md
docs/cas-server-documentation/logging/Logging-SysLog.md

Add warning in documentation about clear password sent in MDC to syslog.

documentation: add warning about password in MDC

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/authentication/HttpClientProperties.java
core/cas-server-core-web/src/main/java/org/apereo/cas/config/CasCoreHttpConfiguration.java
docs/cas-server-documentation/configuration/Configuration-Properties.md

Backport of https://github.com/apereo/cas/pull/5045

Configure default headers for HTTP client

---

support/cas-server-support-simple-mfa-core/src/main/java/org/apereo/cas/mfa/simple/CasSimpleMultifactorAuthenticationHandler.java
support/cas-server-support-simple-mfa/src/test/java/org/apereo/cas/mfa/simple/CasSimpleMultifactorAuthenticationHandlerTests.java

This is the patch from ﻿#5039 applied to master.

Accept simple MFA tokens without prefix

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20IntrospectionEndpointController.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/AbstractOAuth20Tests.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20IntrospectionEndpointControllerTests.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/web/controllers/introspection/OidcIntrospectionEndpointController.java

Backport of: https://github.com/apereo/cas/pull/5047

Fix OAuth/OIDC support

---

.github/workflows/initializr-build.yml
app/src/main/resources/overlay/helmcharts/helm/cas-server/Chart.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/_helpers.tpl
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/bootadmin/configmap.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/bootadmin/deployment.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/bootadmin/ingress.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/bootadmin/service.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/mgmt/configmap.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/mgmt/deployment.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/mgmt/ingress.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/mgmt/service.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/script-configmap.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/statefulset.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/values.yaml
app/src/main/resources/overlay/helmcharts/helm/create-truststore.sh
ci/validate-helm.sh

add persistent volume using volumeClaimTemplate
good for storing git cloned stuff persistently so you don't have to re-clone every startup
update k3s versions and add 1.20
add some config options to ingress controller that might be useful in some deployments

helm chart updates

---

app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/bootadmin/deployment.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/mgmt/deployment.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/statefulset.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/values.yaml

Add environment variable needed for clustering and configure for clustering by default.

casinit helm chart - configure cas with tomcat kubernetes clustering

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/HttpUtils.java

Backport of: https://github.com/apereo/cas/pull/5076

Set timeouts for HttpUtils

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java

Backport of: https://github.com/apereo/cas/pull/5088

Allow the overriding of the client name retrieval in authn delegation

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/memcached/BaseMemcachedProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties-Common.md
support/cas-server-support-memcached-core/src/main/java/org/apereo/cas/memcached/MemcachedPooledClientConnectionFactory.java

Backport of: https://github.com/apereo/cas/pull/5092

Add the protocol property for Memcached

---

core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/AbstractServicesManager.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/DefaultServicesManagerRegisteredServiceLocator.java

By using equals to compare classes won't be possible to extend Regex and Saml Registered Service in order to provide custom ones. This PR replace equals with isAssignableFrom to fix the issue. 
Furthermore the PR fixes lines too long.

Permit RegexRegisteredService and SamlRegisteredService extension

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20AuthorizeEndpointController.java

Fix the logger argument mismatch of position for `OAuth20AuthorizeEndpointController.java`

Fix trace logger arguments mismatch

---

docs/cas-server-documentation/developer/Build-Process.md

as discussed in the cas-dev Google group

add some hints for current IntelliJ IDE setup

---

support/cas-server-support-actions/src/main/java/org/apereo/cas/web/flow/login/InitialFlowSetupAction.java

Everything is in the title ;-)

Open the InitialFlowSetupAction for customization

---

ci/tests/puppeteer/scenarios/pm-must-change-password-ldap-ad/script.js
ci/tests/puppeteer/scenarios/pm-must-change-password-ldap-ad/script.json

This configures pm for ldap so the ldap change password service is property configured.

update puppeteer test - pm-ldap

---

docs/cas-server-documentation/authentication/Configuring-SSO.md

Add documentation about type and username request
parameters in DELETE endpoint.

ssoSessions: add doc for DELETE endpoint

---

docs/cas-server-documentation/configuration/Configuration-Properties-Common.md

Update strategyType from camel case to snake case (i.e. strategy-type ) in 6.3.x document

[Documentation] Update camel case property to snake case property: strategyType 

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/token/OidcIdTokenGeneratorService.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/token/OidcIdTokenGeneratorServiceTests.java

Backport of: https://github.com/apereo/cas/pull/5185

OIDC: Fix the auth_time claim in ID tokens

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/profile/OidcUserProfileDataCreator.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/profile/OidcUserProfileDataCreatorTests.java

Backport of https://github.com/apereo/cas/pull/5191

Fix the auth_time claim in the OIDC support

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/jpa/AbstractJpaProperties.java
ci/tests/puppeteer/package.json
ci/tests/puppeteer/scenarios/db-postgres-load/init.sh
ci/tests/puppeteer/scenarios/db-postgres-load/script.js
ci/tests/puppeteer/scenarios/db-postgres-load/script.json
ci/tests/puppeteer/scenarios/db-postgres-load/test.js
support/cas-server-support-jpa-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/JpaTicketEntityFactory.java
support/cas-server-support-jpa-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/generic/JpaTicketEntity.java
support/cas-server-support-jpa-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/postgres/PostgresJpaTicketEntity.java
webapp/cas-server-webapp-resources/src/main/resources/application.properties

Backport postgres jpa updates. If this isn't appropriate for backport, not a big deal, just cherry-picked from master. 
(cherry picked from commit b65125e0996858c6cbd85b96669c170a22c6908b)

update for jpa (postgres) ticket registry (#5221) - backport

---

support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/RefreshableDelegatedClients.java

Backport of https://github.com/apereo/cas/pull/5223

Open up a little the RefreshableDelegatedClients

---

support/cas-server-support-oauth-uma/src/main/java/org/apereo/cas/config/CasOAuthUmaConfiguration.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20ThrottleConfiguration.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcEndpointsConfiguration.java

Backport of: https://github.com/apereo/cas/pull/5233

Do not generate pac4j CSRF token

---

gradle.properties

Reverts apereo/cas#5261
Causes:
```
java.lang.ClassCastException: class org.slf4j.helpers.NOPLoggerFactory cannot be cast to class org.apache.logging.slf4j.Log4jLoggerFactory (org.slf4j.helpers.NOPLoggerFactory and org.apache.logging.slf4j.Log4jLoggerFactory are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5c7fa833)
at org.apereo.cas.logging.web.LoggingConfigurationEndpoint.getActiveLoggersInFactory(LoggingConfigurationEndpoint.java:211)
at org.apereo.cas.logging.web.LoggingConfigurationEndpoint.configuration(LoggingConfigurationEndpoint.java:171)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```

Revert "use released versions of loggers"

---

core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/config/CasWebflowContextConfiguration.java
core/cas-server-core-webflow/src/test/java/org/apereo/cas/web/flow/DefaultLoginWebflowConfigurerTests.java
core/cas-server-core-webflow/src/test/java/org/apereo/cas/web/flow/DefaultLogoutWebflowConfigurerTests.java

Backport of: https://github.com/apereo/cas/pull/5265

Fix cache busting on login/logout webflows

---

support/cas-server-support-thymeleaf/src/main/resources/messages_it.properties

Correct little typos in italian messages

Little typos in messages (italian)

---

core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/config/CasWebflowContextConfiguration.java

Many tests are broken in branch 6.4.x because of the injection of the `mvcResourceUrlProvider`. 
To fix them, the `WebMvcConfigurationSupport` component should be added in the tests.
An easy solution is to make that component "optional".

Fix tests in 6.4.x

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/oauth/OAuthAccessTokenProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/oauth/OAuthCodeProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/oauth/OAuthDeviceTokenProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/oauth/OAuthDeviceUserCodeProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/oauth/OAuthRefreshTokenProperties.java
support/cas-server-support-dynamodb-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/DynamoDbTicketRegistryTests.java
support/cas-server-support-oauth-core/src/main/java/org/apereo/cas/config/OAuth20ProtocolTicketCatalogConfiguration.java

Make storage names for OAuth ticket catalog objects configurable

---

support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20Configuration.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/OAuth20TestsSuite.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/logout/OAuth20LogoutDontReplicateSessionTests.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/logout/OAuth20LogoutReplicateSessionTests.java

Backport of: https://github.com/apereo/cas/pull/5277

Fix the OIDC logout when the session is replicated

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/callback/OAuth20AuthorizationCodeAuthorizationResponseBuilder.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/issuer/OidcDefaultIssuerService.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/web/OidcAccessTokenResponseGenerator.java

Backport of: https://github.com/apereo/cas/pull/5290

Allow more customisations on OAuth/OIDC

---

support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/audit/SamlResponseAuditResourceResolver.java
support/cas-server-support-saml-idp-web/src/test/java/org/apereo/cas/support/saml/web/idp/audit/SamlResponseAuditResourceResolverTests.java

Backport [PR 5289](https://github.com/apereo/cas/pull/5289)

add SAML2 Response ID to audit message

---

support/cas-server-support-thymeleaf/src/main/resources/messages_it.properties

Add GAuth section in italian messages

Add GAuth section

---

core/cas-server-core-web/src/main/resources/cas_common_messages.properties

especially useful for material-components-web.js which is quite big

use minified versions of js/css

---

support/cas-server-support-thymeleaf/src/main/resources/static/js/webauthn/webauthn.js
support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/webAuthnLogin.html
support/cas-server-support-webauthn-core-webflow/src/main/java/org/apereo/cas/webauthn/web/flow/WebAuthnMultifactorWebflowConfigurer.java
support/cas-server-support-webauthn-core-webflow/src/main/java/org/apereo/cas/webauthn/web/flow/WebAuthnStartRegistrationAction.java
support/cas-server-support-webauthn/src/main/java/org/apereo/cas/config/WebAuthnWebflowConfiguration.java
support/cas-server-support-webauthn/src/test/java/org/apereo/cas/webauthn/web/flow/WebAuthnStartRegistrationActionTests.java

Backport of: https://github.com/apereo/cas/pull/5271

Fix CSRF in WebAuthn support

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/ticket/accesstoken/OAuth20DefaultAccessTokenFactory.java
support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java
support/cas-server-support-simple-mfa-core/src/main/java/org/apereo/cas/mfa/simple/web/flow/CasSimpleMultifactorSendTokenAction.java

Backport of: https://github.com/apereo/cas/pull/5313

Open some CAS classes

---

support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DefaultDelegatedClientFactory.java
support/cas-server-support-pac4j-core-clients/src/test/java/org/apereo/cas/support/pac4j/authentication/DefaultDelegatedClientFactoryTests.java

Backport of: https://github.com/apereo/cas/pull/5319
Removed unused imports in test class BTW.

Fix initialization issues of the pac4j clients

---

ci/tests/puppeteer/scenarios/pac4j-delegated-concurrency/script.js
ci/tests/puppeteer/scenarios/pac4j-delegated-concurrency/script.json
ci/tests/puppeteer/scenarios/pac4j-delegated-concurrency/test.js

The idea is to have an issue because of the way pac4j clients are built. Though, no issue happens this way.

Test the pac4j concurrency

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20CallbackAuthorizeEndpointController.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20CallbackAuthorizeEndpointControllerTests.java

Backport of: https://github.com/apereo/cas/pull/5321

Fix the default URL in OAuth callback

---

support/cas-server-support-thymeleaf/src/main/resources/templates/delegated-authn/casDelegatedAuthnStopWebflow.html

Backport of: https://github.com/apereo/cas/pull/5311

fix: Exception evaluating SpringEL expression: 'screen.pac4j.authn.' + rootCauseException.class.simpleName

---

core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/gen/CookieRetrievingCookieGenerator.java

port from `master` back to `6.4.x` for https://github.com/apereo/cas/pull/5339

[6.4] Update addCookieHeaderToResponse method from private to protected

---

ci/tests/puppeteer/scenarios/oidc-authzcode-relogin-tgt-expired/script.js
ci/tests/puppeteer/scenarios/oidc-authzcode-relogin-tgt-expired/script.json
ci/tests/puppeteer/scenarios/oidc-authzcode-relogin-tgt-expired/services/Sample-1.json
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/OAuth20TicketGrantingTicketAwareSecurityLogic.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20AuthorizeEndpointController.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20ThrottleConfiguration.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/web/OidcAuthenticationAuthorizeSecurityLogic.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/web/OidcAuthenticationAuthorizeSecurityLogicTests.java

Backport of: https://github.com/apereo/cas/pull/5341

Synchronize the CAS and pac4j sessions

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedAuthenticationClientFinishLogoutAction.java
support/cas-server-support-pac4j-webflow/src/test/java/org/apereo/cas/web/flow/DelegatedAuthenticationClientFinishLogoutActionTests.java

Backport of: https://github.com/apereo/cas/pull/5349

Authn delegation: fix post logout URL computation

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/DefaultDelegatedClientAuthenticationWebflowManager.java
support/cas-server-support-pac4j-webflow/src/test/java/org/apereo/cas/web/flow/DefaultDelegatedClientAuthenticationWebflowManagerTests.java

Backport of: https://github.com/apereo/cas/pull/5350

Authn delegation: fix multi-threading issues

---

support/cas-server-support-thymeleaf/src/main/resources/messages_cs.properties

Fixed czech language - One letter was missing.

---

support/cas-server-support-thymeleaf/src/main/resources/messages_cs.properties

Added translation for additional words and phrases in Czech.
Note: Order is changed, where original `messages.properties`

Added translation for additional words and phrases in Czech.

---

support/cas-server-support-git-service-registry/src/main/java/org/apereo/cas/services/GitServiceRegistry.java
support/cas-server-support-git-service-registry/src/test/java/org/apereo/cas/services/GitServiceRegistryTests.java

Backport [PR 5378](https://github.com/apereo/cas/pull/5378)

Catch JSON parsing exception when loading Git service repository

---

support/cas-server-support-saml-idp-discovery/src/main/java/org/apereo/cas/config/SamlIdentityProviderDiscoveryConfiguration.java

Revert "Allow alternative identityProviderDiscoveryFeedControllers"

---

support/cas-server-support-spnego/src/main/java/org/apereo/cas/support/spnego/authentication/principal/SpnegoCredential.java
support/cas-server-support-spnego/src/test/java/org/apereo/cas/support/spnego/authentication/principal/SpnegoCredentialsTests.java

Backport [PR 5427](https://github.com/apereo/cas/pull/5427)

Exclude initToken and nextToken from SpnegoCredential JSON Serialization

---

ci/tests/puppeteer/scenarios/oidc-authzcode-profile-jwt-format/script.js
ci/tests/puppeteer/scenarios/oidc-authzcode-profile-jwt-format/script.json
ci/tests/puppeteer/scenarios/oidc-authzcode-profile-jwt-format/services/Sample-1.json
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/web/controllers/profile/OidcUserProfileEndpointController.java

Backport of: https://github.com/apereo/cas/pull/5437

Fix OIDC UserInfo in JWT format

---

core/cas-server-core/src/main/java/org/apereo/cas/DefaultCentralAuthenticationService.java
support/cas-server-support-memcached-ticket-registry/build.gradle
support/cas-server-support-memcached-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/MemcachedTicketRegistryTests.java

Backport of: https://github.com/apereo/cas/pull/5439

Fix createPGT for remote ticket registries

---

support/cas-server-support-thymeleaf/src/main/resources/messages.properties
support/cas-server-support-thymeleaf/src/main/resources/templates/gauth/casGoogleAuthenticatorRegistrationView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/mfa-trusted-devices/casMfaRegisterDeviceView.html

Make more strings translateable in gauth registration and mfa register device views.

More i18n to gauth and mfa register device views

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/OneTimeTokenAccount.java

To be able to store encrypted scratch codes.

MFA Gauth: fix scratch_codes column type

---

support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/SamlProfileHandlerConfigurationContext.java
support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/config/SamlIdPEndpointsConfiguration.java

This is a partial backport of: https://github.com/apereo/cas/pull/5449
I couldn't easily backport the integration test as there is no SimpleSAML server in version 6.5.

Fix SAML IdP initiated support when authn request is signed

---

support/cas-server-support-throttle-bucket4j/src/main/java/org/apereo/cas/web/Bucket4jThrottledRequestExecutor.java
support/cas-server-support-throttle-bucket4j/src/test/java/org/apereo/cas/web/BaseBucket4jThrottledRequestTests.java

Backport of: https://github.com/apereo/cas/pull/5452

Fix bucket4j throttling support

---

core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasCoreTicketComponentSerializationConfiguration.java

Backport of: https://github.com/apereo/cas/pull/5460

Fix serialization configuration for Memcached

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/profile/OidcUserProfileViewRenderer.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/profile/OidcUserProfileViewRendererDefaultTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/profile/OidcUserProfileViewRendererFlatTests.java

Backport of: https://github.com/apereo/cas/pull/5462

Fix the consistency of the JWT attributes for the OIDC user info

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/policy/AtLeastOneCredentialValidatedAuthenticationPolicy.java

Fixing log statement to reflect the enclosing if clause

---

support/cas-server-support-generic/src/main/java/org/apereo/cas/adaptors/generic/JsonResourceAuthenticationHandler.java
support/cas-server-support-generic/src/test/java/org/apereo/cas/adaptors/generic/JsonResourceAuthenticationHandlerTests.java
support/cas-server-support-generic/src/test/resources/sample-users.json

Backport of #5478 to 6.5.x branch

Fix JsonResourceAuthenticationHandler to work with encoded passwords (6.5.x)

---

docs/cas-server-documentation/protocol/CAS-Protocol-Specification.md

fix typo in spec

---

support/cas-server-support-person-directory/src/main/java/org/apereo/cas/config/CasPersonDirectoryJdbcConfiguration.java
support/cas-server-support-person-directory/src/main/java/org/apereo/cas/config/CasPersonDirectoryLdapConfiguration.java
support/cas-server-support-syncope-authentication/src/main/java/org/apereo/cas/config/SyncopePersonDirectoryConfiguration.java

This PR removes conditions that would prevent some `PersonDirectoryConfiguration` to reload on application refresh.

Ability to refresh PersonDirectoryConfiguration classes

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/serialization/MessageSanitizationUtils.java
core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/serialization/MessageSanitizationUtilsTests.java

Backport [PR 5457](https://github.com/apereo/cas/pull/5457)

sanitize oauth refresh tokens in log

---

docs/cas-server-documentation/ux/User-Interface-Customization-Themes.md

Fix invalid artifact name in docs

Fix invalid artifact name in docs

---

ci/tests/redis/docker-compose.yml
ci/tests/redis/run-redis-server.sh
gradle.properties

Switch to bitnami docker images b/c they maintain current sentinel image.

update redis to 7 and lettuce to 6.2

---

ci/tests/puppeteer/cas.js
ci/tests/puppeteer/scenarios/x509-login-ldap-attributes/notusedattributes.groovy
ci/tests/puppeteer/scenarios/x509-login-ldap-attributes/script.js
ci/tests/puppeteer/scenarios/x509-login-ldap-attributes/script.json
core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/principal/resolvers/InternalGroovyScriptDao.java
core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/principal/resolvers/InternalGroovyScriptDaoTests.java
support/cas-server-support-person-directory/src/main/java/org/apereo/cas/config/CasPersonDirectoryGroovyConfiguration.java

Porting forward change so groovy scripts only run if they are active and run in the correct order.

fix groovy scripts so they are only run when they are the person dao under consideration

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pm/ResetPasswordManagementProperties.java
ci/tests/puppeteer/scenarios/forgot-password-multi-use/accounts.json
ci/tests/puppeteer/scenarios/forgot-password-multi-use/script.js
ci/tests/puppeteer/scenarios/forgot-password-multi-use/script.json
ci/tests/puppeteer/scenarios/forgot-password/script.js
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/SendPasswordResetInstructionsAction.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/VerifyPasswordResetRequestAction.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/pm/web/flow/actions/SendPasswordResetInstructionsActionTests.java

Backport of: https://github.com/apereo/cas/pull/5499
It is fully backward compatible.

Handle multi use token for reset password

---

core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/expiration/MultiTimeUseOrTimeoutExpirationPolicy.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/expiration/MultiTimeUseOrTimeoutExpirationPolicyTests.java

Backport of: https://github.com/apereo/cas/pull/5507

Use a hard timeout for the multi use policy

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/slo/OidcSingleLogoutServiceMessageHandler.java

Backport of: https://github.com/apereo/cas/pull/5509

Fix the OIDC back channel logout

---

support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/googleanalytics.html
support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/scripts.html

Backport of: https://github.com/apereo/cas/pull/5515

Improve Google Analytics support

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/git/services/BaseGitProperties.java
support/cas-server-support-git-core/src/main/java/org/apereo/cas/git/DefaultGitRepository.java
support/cas-server-support-git-core/src/main/java/org/apereo/cas/git/GitRepositoryBuilder.java
support/cas-server-support-git-core/src/test/java/org/apereo/cas/git/GitRepositoryTests.java

Port forward of https://github.com/apereo/cas/pull/5517

Add rebase option to git

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/authenticator/OAuth20UsernamePasswordAuthenticator.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/authenticator/OAuth20UsernamePasswordAuthenticatorTests.java

Backport of: https://github.com/apereo/cas/pull/5524

Add authentication attributes on resource password grant type

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/authentication/AuthenticationAttributeReleaseProperties.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/authenticator/OAuth20UsernamePasswordAuthenticator.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20Configuration.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/authenticator/BaseOAuth20AuthenticatorTests.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/authenticator/OAuth20UsernamePasswordAuthenticatorTests.java

To follow our Slack discussion and the previous PR: https://github.com/apereo/cas/pull/5524

Use authn attribute release policy for resource password grant type

---

core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/resolver/impl/DefaultCasDelegatingWebflowEventResolver.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/ticket/accesstoken/OAuth20DefaultAccessTokenFactory.java

Backport of: https://github.com/apereo/cas/pull/5545

Open up a little the CAS server for customisations

---

ci/tests/puppeteer/scenarios/delegated-login-saml2-postbinding-for-authnrequest/init.sh
ci/tests/puppeteer/scenarios/delegated-login-saml2-postbinding-for-authnrequest/script.js
ci/tests/puppeteer/scenarios/delegated-login-saml2-postbinding-for-authnrequest/script.json
ci/tests/saml2/saml20-idp-hosted.php
core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/resolver/impl/DefaultCasDelegatingWebflowEventResolver.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/ticket/accesstoken/OAuth20DefaultAccessTokenFactory.java
support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/actions/DelegatedClientAuthenticationRedirectAction.java
support/cas-server-support-pac4j-webflow/src/test/java/org/apereo/cas/web/flow/actions/DelegatedClientAuthenticationRedirectActionTests.java
support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/config/RedisTicketRegistryConfiguration.java
support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/RedisTicketRegistry.java
support/cas-server-support-redis-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/RedisServerTicketRegistryTests.java

Backport of: https://github.com/apereo/cas/pull/5543

Fix SAML POST redirection in authn delegation

---

support/cas-server-support-thymeleaf/src/main/resources/messages_de.properties

A complete revision of the german translation, brought in line with the current english messages.

complete revision of the german translation

---

support/cas-server-support-jdbc-authentication/src/main/java/org/apereo/cas/adaptors/jdbc/JdbcAuthenticationUtils.java
support/cas-server-support-jdbc-authentication/src/main/java/org/apereo/cas/adaptors/jdbc/QueryAndEncodeDatabaseAuthenticationHandler.java
support/cas-server-support-jdbc/src/main/java/org/apereo/cas/adaptors/jdbc/config/CasJdbcAuthenticationConfiguration.java

Backport of: https://github.com/apereo/cas/pull/5553

Open up JDBC support

---

api/cas-server-core-api-util/src/main/java/org/apereo/cas/util/LogMessageSummarizer.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/DefaultLogMessageSummarizer.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/LoggingUtils.java
core/cas-server-core-util-api/src/main/resources/META-INF/services/org.apereo.cas.util.LogMessageSummarizer
core/cas-server-core-util-api/src/test/java/org/apereo/cas/AllUtilTestsSuite.java
core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/LoggingUtilsSummarizeTests.java
core/cas-server-core-util-api/src/test/resources/log4j2-test.xml

Make LoggingUtils configurable (#5551)

---

gradle.properties

The version should be updated after the release of v6.6.3.

Update to 6.6.4-SNAPSHOT

---

support/cas-server-support-actions-core/src/main/java/org/apereo/cas/web/flow/account/PrepareAccountProfileViewAction.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/account/PrepareAccountProfileViewActionTests.java

Just sorted authorizedServices.

Put sorted services in profile flow scope

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/spnego/SpnegoProperties.java
support/cas-server-support-spnego/src/main/java/org/apereo/cas/config/SpnegoConfiguration.java
support/cas-server-support-spnego/src/main/java/org/apereo/cas/support/spnego/authentication/handler/support/JcifsSpnegoAuthenticationHandler.java
support/cas-server-support-spnego/src/test/java/org/apereo/cas/support/spnego/authentication/handler/support/JcifsSpnegoAuthenticationHandlerTests.java

Backport of: https://github.com/apereo/cas/pull/5564

Fix SPNEGO performance issues

---

support/cas-server-support-thymeleaf/src/main/resources/messages_zh_CN.properties

Check out the latest `message.properties` file, then review and translate into Chinese:
- Add and translate resource items that do not exist
- Remove useless resource items
- review all existing resource items and modify it
Problem: There are still dozens of resource items left untranslated, which are not commonly used in the Chinese environment.

Review the latest internationalization items and translate into Chinese

---

gradle/dependencies.gradle

The `springmodules` project has been abandoned a long time ago.

WIP: remove Spring modules

---

support/cas-server-support-sms-smsmode/src/main/java/org/apereo/cas/support/sms/SmsModeSmsSender.java
support/cas-server-support-sms-smsmode/src/test/java/org/apereo/cas/support/sms/SmsModeSmsSenderTests.java

Backport of: https://github.com/apereo/cas/pull/5583

Fix the SmsMode support

---

support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/SendPasswordResetInstructionsAction.java

Backport of: https://github.com/apereo/cas/pull/5589

Open up the SendPasswordResetInstructionsAction

---

webapp/cas-server-webapp-config/src/main/java/org/apereo/cas/config/CasFiltersConfiguration.java

Backport of: https://github.com/apereo/cas/pull/5596

Make CasCorsFilter overridable

---

core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/RegexRegisteredService.java

Fix typo in RegexRegisteredService

---

ci/tests/syncope/docker-compose.yml
ci/tests/syncope/run-syncope-server.sh
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/util/InternalTicketValidator.java
support/cas-server-support-syncope-authentication/src/main/java/org/apereo/cas/syncope/SyncopeUserTOConverterUtils.java
support/cas-server-support-syncope-authentication/src/test/java/org/apereo/cas/syncope/authentication/SyncopePersonAttributeDaoTests.java

Current implementation does not permit to provide mapping for username, plai/der/vir attr.
This PR enables this feature.

 provides the possibility to map plan, vir, der attrs

---

support/cas-server-support-rest-core/src/main/java/org/apereo/cas/support/rest/resources/ServiceTicketResource.java
support/cas-server-support-rest-core/src/main/java/org/apereo/cas/support/rest/resources/TicketGrantingTicketResource.java
support/cas-server-support-rest-core/src/main/java/org/apereo/cas/support/rest/resources/TicketStatusResource.java
support/cas-server-support-rest-core/src/main/java/org/apereo/cas/support/rest/resources/UserAuthenticationResource.java

Also make the javadocs more concise and fix the metadata of UserAuthenticationResource.

docs: make javadocs of REST controllers reflect their actual content

---

ci/tests/k3d/setup.sh
ci/tests/puppeteer/scenarios/oidc-login-sonarqube/init.sh
ci/tests/puppeteer/scenarios/oidc-login-sonarqube/script.js
ci/tests/puppeteer/scenarios/oidc-login-sonarqube/services/Sonarqube-20221009.json
ci/tests/puppeteer/scenarios/oidc-login-sonarqube/sonarqube-test-values.yaml

backport - fix sonarqube test

---

core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/CasFlowHandlerMapping.java
core/cas-server-core-webflow/src/test/java/org/apereo/cas/AllTestsSuite.java
core/cas-server-core-webflow/src/test/java/org/apereo/cas/web/flow/DefaultCasFlowHandlerMappingTests.java

It seems that every request is being processed twice in the HandlerExecutionChain methods applyPreHandle and applyPostHandle. The reason for this behavior is that the initApplicationContext method in AbstractHandlerMapping is called twice during the creation of the CasFlowHandlerMapping bean. This method copies the interceptors list to the adaptedInterceptors list. When the request is processed in HandlerExecutionChain, it is processed twice.
CasFlowHandlerMapping is a descendant of the Spring ApplicationObjectSupport class, where the initApplicationContext method is called automatically. Therefore, calling it in afterPropertiesSet is probably unnecessary.
I have created a test to check this behavior. The test passes successfully after the change is approved, but fails in the original …

Fix duplicate request processing caused by duplicate interceptor initialization in CasFlowHandlerMapping

---

ci/tests/puppeteer/scenarios/login-success-double-renew/script.js
ci/tests/puppeteer/scenarios/login-success-double-renew/script.json
support/cas-server-support-actions-core/src/main/java/org/apereo/cas/web/flow/login/InitialFlowSetupAction.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/InitialFlowSetupActionTests.java

Backport of: https://github.com/apereo/cas/pull/5640
master: https://github.com/apereo/cas/pull/5640

Fix the double renew call

---

support/cas-server-support-saml-core-api/src/main/java/org/apereo/cas/support/saml/util/AbstractSaml20ObjectBuilder.java
support/cas-server-support-saml-core/src/test/java/org/apereo/cas/support/saml/util/NonInflatingSaml20ObjectBuilderTests.java

(cherry picked from commit dbee7eed9b3eef7b630754c207bdb07d6258a07c)
master: https://github.com/apereo/cas/pull/5638

update saml to avoid unnecessary stack trace (#5638)

---

core/cas-server-core-web-api/src/main/java/org/apereo/cas/web/support/CasLocaleChangeInterceptor.java
core/cas-server-core-web/src/test/java/org/apereo/cas/web/support/CasLocaleChangeInterceptorTests.java

master: https://github.com/apereo/cas/pull/5645

Add backward compatibility for the locale parameter

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/redis/BaseRedisProperties.java
support/cas-server-support-redis-core/src/main/java/org/apereo/cas/redis/core/RedisObjectFactory.java
support/cas-server-support-redis-core/src/test/java/org/apereo/cas/redis/core/RedisObjectFactoryTests.java

master: https://github.com/apereo/cas/pull/5659
This is a backward compatible change.

Support URI for Redis

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/throttle/ThrottleFailureProperties.java
docs/cas-server-documentation/authentication/Configuring-Authentication-Throttling.md

People often ask me questions about the throttling and they don't correctly understand the documentation (as well as the Javadoc).
This PR tries to improve the throttling documentation.

Improve throttling documentation

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/oauth/Pac4jOAuth20ClientProperties.java
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/clients/BaseDelegatedClientFactory.java

```
master: https://github.com/apereo/cas/pull/5745
```

Improve Authn delegation

---

gradle.properties

To be on the latest stable version.

 Update to pac4j v6-RC8

---

core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/GroovyScriptAttributeReleasePolicy.java
core/cas-server-core-authentication-attributes/src/test/java/org/apereo/cas/services/GroovyScriptAttributeReleasePolicyTests.java

Backport of https://github.com/apereo/cas/pull/5758
```
master: https://github.com/apereo/cas/pull/5758
```

Don't reparse script in GroovyScriptAttributeReleasePolicy

---

docs/cas-server-documentation/mfa/GoogleAuthenticator-Authentication.md

```
master: https://github.com/apereo/cas/pull/5776
```

Update MFA Gauth doc

---

support/cas-server-support-redis-service-registry/src/test/java/org/apereo/cas/adaptors/redis/services/RedisSentinelServerServiceRegistryTests.java

Fixes property name for redis sentinel test

Fix property name

---

core/cas-server-core-audit/src/main/java/org/apereo/cas/audit/spi/config/CasCoreAuditConfiguration.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java

```
master: https://github.com/apereo/cas/pull/5781
```

Open up for multihost

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/actions/logout/DelegatedAuthenticationClientLogoutAction.java

Open up a little the DelegatedAuthenticationClientLogoutAction

---

README.md

fix contributor link in README.md

---

support/cas-server-support-themes-core/src/main/java/org/apereo/cas/services/web/RegisteredServiceThemeResolver.java

```
master: https://github.com/apereo/cas/pull/5822
```

Open up a little the RegisteredServiceThemeResolver

---

gradle.properties

For better peformance on recursive JSONs.

Update JSON deps

---

gradle/dependencies.gradle

It should not be necessary for Jetty.

Remove tomcat-embed-el from spring-boot-starter-jetty

---

support/cas-server-support-thymeleaf/src/main/resources/messages_es.properties

add simple and register device translations

---

support/cas-server-support-reports-core/src/main/java/org/apereo/cas/web/report/RegisteredAuthenticationHandlersEndpoint.java

Low hanging fruit: adding a couple details more to authentication handlers as reported by their actuator endpoint.

Reporting more details in RegisteredAuthenticationHandlersEndpoint

---

support/cas-server-support-pac4j-core/src/main/java/org/apereo/cas/web/flow/DelegatedAuthenticationSingleSignOnParticipationStrategy.java
support/cas-server-support-pac4j-core/src/test/java/org/apereo/cas/web/flow/DelegatedAuthenticationSingleSignOnParticipationStrategyTests.java

master: https://github.com/apereo/cas/pull/5872

fix NoSuchElementException is throwed when tgt is expired 

---

gradle/dependencies.gradle

```
master: https://github.com/apereo/cas/pull/5883
```

Remove duplicate checker-qual

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/config/DelegatedAuthenticationWebflowConfiguration.java

```
master: https://github.com/apereo/cas/pull/5888
```

Make DefaultDelegatedAuthenticationNavigationController overridable

---

support/cas-server-support-thymeleaf/src/main/resources/messages.properties
support/cas-server-support-thymeleaf/src/main/resources/messages_fr.properties
support/cas-server-support-thymeleaf/src/main/resources/templates/gauth/casGoogleAuthenticatorRegistrationView.html

Revert "Replace table by responsive design on casGoogleAuthenticaticatorRegis…"

---

ci/tests/puppeteer/scenarios/oauth2-login-jwt-at/script.js
ci/tests/puppeteer/scenarios/oauth2-login-jwt-at/script.json
ci/tests/puppeteer/scenarios/oauth2-login-jwt-at/services/Sample-1.json
ci/tests/puppeteer/scenarios/oauth2-login-jwt-at/services/Sample-2.json
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileEndpointController.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileEndpointControllerTests.java

```
master: https://github.com/apereo/cas/pull/5908
```

Avoid strack traces on OAuth /profile

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/discovery/OidcServerDiscoverySettingsFactory.java

```
master: https://github.com/apereo/cas/pull/5913
```

Allow customisations of the OIDC discovery settings

---

gradle/dependencies.gradle

```
master: https://github.com/apereo/cas/pull/5926
```

Fix the jackson-dataformat-cbor dependency for WebAuthn

---

support/cas-server-support-thymeleaf/src/main/resources/messages_es.properties

add authenticationFailure translations

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/validator/DefaultOAuth20ClientSecretValidator.java

```
master: https://github.com/apereo/cas/pull/5940
```

Improve error log for PKCE

---

support/cas-server-support-thymeleaf/src/main/resources/messages_fr.properties

```
master: https://github.com/apereo/cas/pull/5945
```

add French translation for passwordless

---

support/cas-server-support-thymeleaf/src/main/resources/messages_fr.properties

```
master: https://github.com/apereo/cas/pull/5949
```

Add missing French pm properties

---

gradle/dependencies.gradle

Partial backport:
```
master: https://github.com/apereo/cas/pull/5954
```

Fix a Jakarta dependency

---

core/cas-server-core-web-api/src/main/java/org/apereo/cas/web/support/WebUtils.java
core/cas-server-core-web/src/test/java/org/apereo/cas/web/support/WebUtilsTests.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/AccountProfilePreparePasswordManagementAction.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurerTests.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/pm/web/flow/actions/AccountProfilePreparePasswordManagementActionTests.java
support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/pmlinks.html

```
master: https://github.com/apereo/cas/pull/5964
```

Fix the 'forgot username' feature

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/passwordless/account/PasswordlessAuthenticationLdapAccountsProperties.java
support/cas-server-support-passwordless-ldap/src/main/java/org/apereo/cas/impl/account/LdapPasswordlessUserAccountStore.java
support/cas-server-support-passwordless-ldap/src/test/java/org/apereo/cas/impl/account/LdapPasswordlessUserAccountStoreTests.java

```
master: https://github.com/apereo/cas/pull/5973
```

For passwordless LDAP, allow to choose the final username

---

support/cas-server-support-pac4j-core/src/main/java/org/apereo/cas/web/flow/error/DefaultDelegatedClientAuthenticationFailureEvaluator.java
support/cas-server-support-pac4j-core/src/test/java/org/apereo/cas/web/flow/error/DefaultDelegatedClientAuthenticationFailureEvaluatorTests.java

```
master: https://github.com/apereo/cas/pull/5976
```

Fix authn delegation + throttling

---

support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/RedisTicketRegistry.java
support/cas-server-support-redis-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/RedisServerTicketRegistryTests.java

```
master: https://github.com/apereo/cas/pull/5984
```

Fix the Redis ticket registry

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20CallbackAuthorizeEndpointController.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20CallbackAuthorizeEndpointControllerTests.java

```
master: https://github.com/apereo/cas/pull/5981
```

Handle OAuth clients with same redirect URIs

---

support/cas-server-support-pac4j-core/src/main/java/org/apereo/cas/pac4j/discovery/DefaultDelegatedAuthenticationDynamicDiscoveryProviderLocator.java
support/cas-server-support-pac4j-core/src/test/java/org/apereo/cas/pac4j/discovery/DefaultDelegatedAuthenticationDynamicDiscoveryProviderLocatorTests.java

```
master: https://github.com/apereo/cas/pull/5988
```

dynamic discovery provider principal fix

---

core/cas-server-core-logging/src/main/java/org/apereo/cas/logging/web/ThreadContextMDCServletFilter.java
core/cas-server-core-logging/src/test/java/org/apereo/cas/logging/web/ThreadContextMDCServletFilterTests.java

```
master: https://github.com/apereo/cas/pull/5994
```

ThreadContextMDC password and cookie fix

---

support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/RedisTicketRegistry.java
support/cas-server-support-redis-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/RedisServerTicketRegistryTests.java

By using a sorted set.
The build passes on my fork: https://github.com/leleuj/cas/pull/3

Fix the expiration in the SSO sessions stored in the Redis ticket registry

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/util/TicketProperties.java
core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasCoreTicketsConfiguration.java

To follow up our discussion on https://github.com/apereo/cas/pull/5997.

Deprecate the `cas.ticket.crypto` setting

---

support/cas-server-support-actions-core/src/main/java/org/apereo/cas/web/flow/login/InitialFlowSetupAction.java

```
master: https://github.com/apereo/cas/pull/6004
```

Add logs to InitialFlowSetupAction

---

core/cas-server-core-webflow/src/main/java/org/apereo/cas/config/CasCoreWebflowConfiguration.java

Added ConditionalOnMissingBean annotation for webflowCipherExecutor in order to allow the bean to be overridden

Added ConditionalOnMissingBean annotation for webflowCipherExecutor

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/callback/OAuth20TokenAuthorizationResponseBuilder.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/response/callback/OAuth20TokenAuthorizationResponseBuilderTests.java

```
master: https://github.com/apereo/cas/pull/6009
```

URL encode parameters in fragment

---

support/cas-server-support-thymeleaf/src/main/resources/messages_de.properties

Thank you for your contributions to Apereo CAS.
When you publish the pull request, please check off relevant items below in the description of your pull request.
Please make sure you include the following:
- [] Test cases for all modified changes, where applicable
- [] The same pull request targeted at the master branch, if applicable
- [] Reference any other pull requests that might be related
Fixed several typos and grammar errors in german message properties-file.

chore: Fix typos and grammar errors (german language)

---

support/cas-server-support-webauthn-core/src/main/java/com/yubico/core/DefaultSessionManager.java
support/cas-server-support-webauthn/src/main/java/org/apereo/cas/config/WebAuthnConfiguration.java

```
master: https://github.com/apereo/cas/pull/6053
```

Small refactoring for the WebAuthn support

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/actions/logout/DelegatedAuthenticationIdentityProviderLogoutAction.java
support/cas-server-support-pac4j-webflow/src/test/java/org/apereo/cas/web/flow/actions/DelegatedAuthenticationIdentityProviderLogoutActionTests.java

```
master: https://github.com/apereo/cas/pull/6064
```

Add logout support for OIDC in authn delegation

---

support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/RedisTicketRegistry.java

After deploying a new CAS server v7 into production for one of my customers, we have encountered Java memory issues leading to crashes of the CAS server. Redis is used as the ticket registry.
After analyzing the memory dump, I have noticed numerous `org.apereo.cas.ticket.Registry.RedisTicketDocument_Instantiator_xxx` classes loaded.
This is the same problem as the one reported here: https://groups.google.com/a/apereo.org/g/cas-user/c/W_o60jguUAI/m/0_VxHpqLDgAJ?pli=1
I have applied the fix provided in this PR for my customer and deployed into production.
The memory consumption has gone to normal. The numerous `RedisTicketDocument*` classes have shrunk to only one class.
I have locally confirmed the fix by performing a memory dump before and after the fix. I'm not sure what test is expected …

Fix Redis ticket registry over-memory consumption

---

core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/BaseTicketRegistryTests.java
support/cas-server-support-hazelcast-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/HazelcastTicketRegistry.java

```
master: https://github.com/apereo/cas/pull/6099
```

Improve sessions/tickets counting by using Jet for the Hazelcast ticket registry

---

ci/tests/puppeteer/scenarios/login-success/script.js
ci/tests/puppeteer/scenarios/login-success/script.json
support/cas-server-support-webconfig/src/main/java/org/apereo/cas/config/CasFiltersConfiguration.java
support/cas-server-support-webconfig/src/main/java/org/apereo/cas/config/CasWebSecurityConfiguration.java
webapp/cas-server-webapp-init-tomcat/src/main/java/org/apereo/cas/config/CasEmbeddedContainerTomcatFiltersConfiguration.java

Backport of: https://github.com/apereo/cas/commit/4604988baa1980bf005367f33e491665d8eba9b0

Fix encoding problem

---

support/cas-server-support-thymeleaf/src/main/resources/templates/login-error/casAccountDisabledView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/login-error/casAccountLockedView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/login/casGenericSuccessView.html

by adding identifiers to some HTML elements.

Make UI more easily testable

---

gradle/dependencies.gradle

```
master: https://github.com/apereo/cas/pull/6153
```
This is an extended backport of the master as the 7.1 branch has one more duplicate dependencies.

Clean duplicate dependencies

---

ci/tests/puppeteer/scenarios/oidc-clientcredentials-scopefree/script.js

```
master: https://github.com/apereo/cas/pull/6158
```

Complement the oidc-clientcredentials-scopefree CI test

---

support/cas-server-support-saml-idp-metadata-aws-s3/src/main/java/org/apereo/cas/support/saml/idp/metadata/AmazonS3SamlIdPMetadataLocator.java

Currently, SAML IdP metadata keeps getting created in S3 over and over again. This PR fixes the problem.

Fix AmazonS3SamlIdPMetadataLocator

---

support/cas-server-support-pac4j-saml/src/main/java/org/apereo/cas/web/flow/actions/logout/DelegatedSaml2ClientLogoutAction.java
support/cas-server-support-pac4j-saml/src/test/java/org/apereo/cas/web/saml2/DelegatedSaml2ClientLogoutActionTests.java
support/cas-server-support-thymeleaf-core/src/main/java/org/apereo/cas/services/web/CasThymeleafTemplatesDirector.java
support/cas-server-support-thymeleaf/src/main/resources/templates/logout/casPropagateLogoutView.html
support/cas-server-support-thymeleaf/src/test/java/org/apereo/cas/services/web/CasThymeleafTemplatesDirectorTests.java

```
master: https://github.com/apereo/cas/pull/6205
```

Fix the SAML logout support in authentication delegation

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/slo/OidcSingleLogoutMessageCreator.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/slo/OidcSingleLogoutMessageCreatorTests.java

```
master: https://github.com/apereo/cas/pull/6218
```

Fix the OIDC logout support (back channel) in authentication delegation

---

support/cas-server-support-syncope-authentication/src/main/java/org/apereo/cas/syncope/SyncopeAuthenticationHandler.java
support/cas-server-support-syncope-authentication/src/main/java/org/apereo/cas/syncope/SyncopeUtils.java
support/cas-server-support-syncope-authentication/src/test/java/org/apereo/cas/syncope/BaseSyncopeTests.java
support/cas-server-support-syncope-authentication/src/test/java/org/apereo/cas/syncope/authentication/SyncopeAuthenticationHandlerTests.java

master: https://github.com/apereo/cas/pull/6271
These changes can be available for cas 7.1.x

Update information content for membership in syncope authentication response

---

support/cas-server-support-throttle-core/src/main/java/org/apereo/cas/throttle/InMemoryThrottledSubmissionCleaner.java

```
master: https://github.com/apereo/cas/pull/6341
```

Fix throttling CRON keys

---

support/cas-server-support-throttle-core/src/main/java/org/apereo/cas/throttle/ThrottledSubmissionHandlerEndpoint.java
support/cas-server-support-throttle/src/test/java/org/apereo/cas/web/support/ThrottledSubmissionHandlerEndpointTests.java
support/cas-server-support-thymeleaf/src/main/resources/static/js/palantir.js

```
master: https://github.com/apereo/cas/pull/6367
```

Fix throttling endpoint deleteByKey

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/discovery/webfinger/OidcDefaultWebFingerDiscoveryService.java

Make pattern matching faster in some edge cases.

Faster pattern matching

---

support/cas-server-support-webauthn-core-webflow/src/main/java/org/apereo/cas/webauthn/web/flow/WebAuthnMultifactorWebflowConfigurer.java
support/cas-server-support-webauthn-core/src/main/java/org/apereo/cas/webauthn/web/WebAuthnController.java

```
master: https://github.com/apereo/cas/pull/6941
```

Improve logs and fix bug in WebAuthn support

---

api/cas-server-core-api-webflow/src/main/java/org/apereo/cas/web/flow/CasWebflowConstants.java
ci/tests/puppeteer/scenarios/mfa-webauthn-account-profile-register/script.js
ci/tests/puppeteer/scenarios/mfa-webauthn-account-profile-register/script.json
support/cas-server-support-gauth-core/src/main/java/org/apereo/cas/gauth/web/flow/GoogleAuthenticatorMultifactorWebflowConfigurer.java
support/cas-server-support-gauth-core/src/main/java/org/apereo/cas/gauth/web/flow/account/GoogleMultifactorAuthenticationAccountProfileWebflowConfigurer.java
support/cas-server-support-gauth/src/test/java/org/apereo/cas/gauth/web/flow/account/GoogleMultifactorAuthenticationAccountProfileWebflowConfigurerTests.java
support/cas-server-support-webauthn-core-webflow/src/main/java/org/apereo/cas/webauthn/web/flow/WebAuthnMultifactorWebflowConfigurer.java
support/cas-server-support-webauthn-core-webflow/src/main/java/org/apereo/cas/webauthn/web/flow/account/WebAuthnMultifactorAccountProfileWebflowConfigurer.java
support/cas-server-support-webauthn/src/test/java/org/apereo/cas/webauthn/web/flow/WebAuthnMultifactorAccountProfileWebflowConfigurerTests.java
support/cas-server-support-yubikey-core/src/main/java/org/apereo/cas/adaptors/yubikey/web/flow/YubiKeyMultifactorWebflowConfigurer.java

```
master: https://github.com/apereo/cas/pull/7059 + https://github.com/apereo/cas/pull/7065
```

Fix WebAuthn registration bug

---

ci/tests/puppeteer/cas.js
ci/tests/puppeteer/scenarios/mfa-webauthn-register-discoverablecredentials-logout-login/script.js
ci/tests/puppeteer/scenarios/mfa-webauthn-register-discoverablecredentials-logout-login/script.json

This PR adds a Puppeteer test related to the registration and authentication of the WebAuthn "Discoverable credentials".

Improve test coverage

---

ci/tests/puppeteer/scenarios/mfa-webauthn-register-logout-login/script.json
webapp/cas-server-webapp-resources/src/main/resources/application.properties

This PR fixes the Spring Session feature when using the WebAuthn support.

Fix Spring Session when using the WebAuthn support

---

docs/cas-server-documentation/mfa/FIDO2-WebAuthn-Authentication.md
support/cas-server-support-webauthn-core-webflow/src/main/java/org/apereo/cas/webauthn/WebAuthnAuthenticationHandler.java
support/cas-server-support-webauthn-core-webflow/src/main/java/org/apereo/cas/webauthn/web/flow/WebAuthnAccountSaveRegistrationAction.java
support/cas-server-support-webauthn-core-webflow/src/main/java/org/apereo/cas/webauthn/web/flow/WebAuthnValidateSessionCredentialTokenAction.java
support/cas-server-support-webauthn-core/src/main/java/com/yubico/core/DefaultSessionManager.java
support/cas-server-support-webauthn-core/src/main/java/com/yubico/core/SessionManager.java
support/cas-server-support-webauthn-core/src/main/java/com/yubico/core/WebAuthnCache.java
support/cas-server-support-webauthn-core/src/main/java/com/yubico/core/WebAuthnServer.java
support/cas-server-support-webauthn-core/src/main/java/com/yubico/core/WebSessionWebAuthnCache.java
support/cas-server-support-webauthn-core/src/main/java/com/yubico/data/AssertionRequestWrapper.java
support/cas-server-support-webauthn-core/src/main/java/org/apereo/cas/webauthn/web/WebAuthnController.java
support/cas-server-support-webauthn-core/src/main/java/org/apereo/cas/webauthn/web/WebAuthnQRCodeController.java
support/cas-server-support-webauthn-core/src/test/java/com/yubico/core/WebSessionWebAuthnCacheTests.java
support/cas-server-support-webauthn-core/src/test/java/org/apereo/cas/webauthn/WebAuthnControllerTests.java
support/cas-server-support-webauthn/src/main/java/org/apereo/cas/config/WebAuthnConfiguration.java
support/cas-server-support-webauthn/src/test/java/org/apereo/cas/webauthn/web/WebAuthnQRCodeControllerMvcTests.java
support/cas-server-support-webauthn/src/test/java/org/apereo/cas/webauthn/web/flow/WebAuthnAccountSaveRegistrationActionTests.java
support/cas-server-support-webauthn/src/test/java/org/apereo/cas/webauthn/web/flow/WebAuthnAuthenticationWebflowActionTests.java
support/cas-server-support-webauthn/src/test/java/org/apereo/cas/webauthn/web/flow/WebAuthnValidateSessionCredentialTokenActionTests.java

Backport of:
```
master: https://github.com/apereo/cas/pull/7122
```

Handle clustering for the WebAuthn support

---

gradle/maven.gradle

Backport of:
```
master: https://github.com/apereo/cas/pull/7156
```

Remove the apache-snapshots repository

---

support/cas-server-support-git-core/src/main/java/org/apereo/cas/git/GitRepositoryBuilder.java
support/cas-server-support-git-core/src/test/java/org/apereo/cas/git/GitRepositoryBuilderTests.java

Backport of:
```
master: https://github.com/apereo/cas/pull/7642
```

Fix Git support
