api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/support/CasConfigurationJasyptCipherExecutor.java
core/cas-server-core-configuration/src/test/java/org/apereo/cas/configuration/support/CasConfigurationJasyptCipherExecutorTests.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/AbstractServicesManager.java
support/cas-server-support-shell/src/main/java/org/apereo/cas/shell/commands/jasypt/JasyptEncryptPropertyCommand.java

Due to https://sourceforge.net/p/jasypt/bugs/32/ bug, test whether encrypted value can be decrypted by jasypt. 
@mmoayyed You suggested writing some tests related to this issue. Which module would those go in? Note that there is already a JasyptTestAlgorithmsCommand command in the shell that tests all the algorithms (in the shell, not during CI).

add back decryption check to cas shell encrypt function

---

core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/ChainingAttributeReleasePolicy.java
core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/DenyAllAttributeReleasePolicy.java
core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/GroovyScriptAttributeReleasePolicy.java
core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/ScriptedRegisteredServiceAttributeReleasePolicy.java
support/cas-server-support-ws-idp-api/src/main/java/org/apereo/cas/ws/idp/services/WSFederationClaimsReleasePolicy.java

without this method, oidc services get saved (without actual changes)
every minute by OidcProfileScopeToAttributesFilter.reconcile method
(at least in some configurations)

add equals method to chaining attribute release policy

---

gradle/dependencies.gradle

There are currently two jquery-3.4.1.jar files in war and they have different directory structure (org.webjars.bower version includes dist folder). The one you get in your overlay will be random but the current layout.xhtml template references the non-bower non-dist version.

exclude duplicate version of jquery webjar with different directory structure

---

support/cas-server-support-couchbase-authentication/src/main/java/org/apereo/cas/authentication/CouchbaseAuthenticationHandler.java
support/cas-server-support-couchbase-authentication/src/test/java/org/apereo/cas/AllTestsSuite.java
support/cas-server-support-couchbase-authentication/src/test/java/org/apereo/cas/authentication/CouchbaseAuthenticationHandlerIntegrationTests.java
support/cas-server-support-couchbase-authentication/src/test/java/org/apereo/cas/authentication/CouchbaseAuthenticationHandlerTests.java

The way to check the password is currently not correct when using the BCrypt password encoder. `equals` does not work, it should be `matches`.
This PR fixes this issue for Couchbase, but other handlers may have the same issue.

Fix password check for Couchbase when using BCrypt

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/rest/RestAuthenticationProperties.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/HttpUtils.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-rest-authentication/src/main/java/org/apereo/cas/adaptors/rest/RestAuthenticationApi.java
support/cas-server-support-rest-authentication/src/main/java/org/apereo/cas/config/CasRestAuthenticationConfiguration.java

I'm working on the integration of CAS in a project, using the [REST Authentication API](https://apereo.github.io/cas/6.0.x/installation/Rest-Authentication.html)
It works quite well, but we had some issues with usernames or password which contains non-ascii characters (for example: "cépafô"), as the Auth header encoding was hard-coded into ASCII.
This PR adds a configuration property `cas.authn.rest.charset` (still "US-ASCII" by default) to enable to use credentials in another charset.
How to test:
* Create an external REST API endpoint that meets CAS REST Authentication API, and add there a user which credentials contain some non-ascii characters, encoded in UTF-8.
* Configure CAS to call the endpoint above, and add following property: `cas.authn.rest.charset=UTF-8`
* Try to authenticate

REST Authentication: enable to configure the charset used to encode the credentials

---

support/cas-server-support-duo/src/main/java/org/apereo/cas/adaptors/duo/config/DuoSecurityMultifactorProviderBypassConfiguration.java

ChainingMultifactorAuthenticationProviderBypass setup for Duo was neglecting to include         duoSecurityPrincipalMultifactorAuthenticationProviderBypass() in the chain. Without this, attribute-based bypass doesn't work.

enable duoSecurityPrincipalMultifactorAuthenticationProviderBypass

---

support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java

Add the missing `setAcceptedMethod` method call when configuring the SAML client

Pac4j delegation: Add missing setAcceptedSkew

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/principal/resolvers/PersonDirectoryPrincipalResolver.java
core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/AllAuthenticationTestsSuite.java
core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/principal/resolvers/PersonDirectoryPrincipalResolverTests.java
core/cas-server-core-authentication/src/test/java/org/apereo/cas/AllTestsSuite.java

Fix a crash when a person directory returns a null attribute value introduced in 5.3.something.
Rationale for needing this is I have a JDBC attribute source that can return null values in attribute result sets.

Fix NPE from null attribute values

---

docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-cassandra-ticket-registry/src/main/java/org/apereo/cas/config/CassandraTicketRegistryConfiguration.java

The `ticketSerializationManager` in `CassandraTicketRegistry` is null I suspect because of the `;` in the spring qualifier.

Fix the null ticketSerializationManager for cassandra integration

---

support/cas-server-support-shell/src/main/java/org/apereo/cas/shell/commands/jasypt/JasyptDecryptPropertyCommand.java
support/cas-server-support-shell/src/main/java/org/apereo/cas/shell/commands/jasypt/JasyptEncryptPropertyCommand.java

This fixes the decrypt command saying "encrypt" in the help and it makes it easier to leave iterations as the default Jasypt value of 1000. Previously you would have to pass "iterations=" in order to set it to blank which then makes the value the default. If you set the iterations to something other than what you have set in CAS for the `cas.standalone.configurationSecurity.iterations` property (which also defaults to NULL) then CAS won't be able to decrypt.

CAS Shell encrypt/descrypt verbiage cleanup and provide iterations default

---

support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java

As a customization, I may want to override the ID token generator and the access token response generator in the OIDC support.

Make OIDC support more extensible

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java

As a customisation, I may want to force the delegated authentication to always override the current SSO session by not detecting an existing one. For that, I extend this class and override the `singleSignOnSessionExists` method to always return `false`.

Open up a little the DelegatedClientAuthenticationAction

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/DelegatedClientWebflowManager.java

In the package cas-server-support-pac4j-webflow, the Java class DelegatedClientWebflowManager uses the attribute PARAMETER_CLIENT_ID, a string whose value is delegatedclientid.
This attribute plays role of an HTTP parameter for different authentication protocols.
FranceConnect implements the OpenID Connect protocol and refuses this HTTP parameter delegatedclientid in its workflow.
Precisely, in the 39812c171e6f5f1f2e3800d335b3cfaa96f19203 "clean up findbugs" commit, concerning the OidcClient condition, the following code line should not be written:
config.setCustomParams(CollectionUtils.wrap(PARAMETER_CLIENT_ID, ticketId));
To make the same thing as the #3981 PR but in the CAS version i need.

To make CAS be FranceConnect-based correctly as well 5.3.

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/oidc/Pac4jOidcClientProperties.java

Fix the generic property type `generic`. Change from type `Pac4jKeyCloakOidcClientProperties` to `Pac4jGenericOidcClientProperties`.

Fix Pac4jOidcClientProperties generic prop type

---

support/cas-server-support-consent-api/src/main/java/org/apereo/cas/consent/ConsentReminderOptions.java

The previous description for ConsentReminderOption enum is 3 duplicate `Always ask for consent.`, which is not correct. This PR will attempt to add back some meaning to the different enum.

Add description to ConsentReminderOptions enum (code documentation)

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/OAuth20DefaultTokenGenerator.java
support/cas-server-support-pac4j-api/src/main/java/org/apereo/cas/integration/pac4j/DistributedJ2ESessionStore.java

JPA ticket registry with OIDC does not work at the moment because `DistributedJ2ESessionStore` and `OAuth20DefaultTokenGenerator` both make use of the `ticketRegistry` without using transactions. This PR should resolve this by making these classes `Transactional`.

Transactional DistributedJ2ESessionStore and OAuth20DefaultTokenGenerator to get jpa working

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/ticket/accesstoken/AccessTokenImpl.java

Oauth ID tokens can contain more than 255 characters of text. JPA ticket registry thus fails to insert the id token data into the column. This PR adds the `@Lob` annotation to `idToken` which ensures the column type will be `text` or similar in the db.

Make idToken @Lob so jpa makes it more than varchar(255)

---

core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/support/RememberMeDelegatingExpirationPolicy.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/support/RememberMeDelegatingExpirationPolicyTests.java

The ticket registry cleaner crashes after upgrading to 5.3.11 from an earlier version with scalar attributes.  This patch allows our CAS to migrate cleanly from scalar attributes to collections the other.
IMHO this patch is only necessary for 5.3 so that I can upgrade but happy to port forward to 6.0 and master if necessary.

Check for old scalar boolean attributes to prevent old style ticket attributes crashing the ticket cleaner

---

api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/TicketCatalog.java
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/DefaultTicketCatalog.java
support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java

- Override getTicketsStream to provide a cursor backed stream instead of loading all tickets to memory via the Collection method
- Implement sessionCount and serviceTicketCount by querying the count directly from Mongo

Improvements for the mongo ticket registry

---

core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/TransientSessionTicketImpl.java

When the TransientSessionTicket table is created in H2 we get: 
```
create table TRANSIENTSESSIONTICKET (
TYPE varchar(31) not null,
ID varchar(255) not null,
NUMBER_OF_TIMES_USED integer,
CREATION_TIME timestamp,
EXPIRATION_POLICY blob(2147483647) not null,
EXPIRED boolean not null,
LAST_TIME_USED timestamp,
PREVIOUS_LAST_TIME_USED timestamp,
PROPERTIES blob(255) not null,
SERVICE blob(255),
primary key (ID)
)
```
In my case, when the properties is updated with `pac4jRequestedUrl`, for an OIDC service, the sql update fails since the parameter is too large. I have not ran into any issue with SERVICE but notice it is the same size so also increased that value in the PR.
This issue does not appear when using Postgres (which I was using in https://github.com/apereo/cas/pull/4061) since the …

Set length to max value for the properties and service fields of TST

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java

For a customization of the `DelegatedClientAuthenticationAction`, I have needed to use the `isLogoutRequest` method in a subclass.

Open up a little the authentication delegation

---

core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/ServiceRegistryInitializer.java

eg the automatic oauth callback can cause a false positive match to a catch all on the same domain with the Mongo Service registry.
A combination of exact service id and numeric id checks should be sufficient to prevent duplicates being inserted and implementations of `findServiceById(String)` all work differently.

ServiceRegistryInitializer: Doing a regex match on service id leads to false positives

---

support/cas-server-support-mongo-service-registry/src/main/java/org/apereo/cas/services/MongoDbServiceRegistry.java

Use mongo queries to implement `findServiceBy` methods.

Implement MongoDbServiceRegistry queries as mongo queries

---

gradle.properties
gradle/overrides.gradle

so the correct version ends up in the .war file.  Not necessary to port forward as spring boot dependency management appears to have changed (?)

Override the Spring Boot mongo driver version

---

api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/TicketCatalog.java
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/DefaultTicketCatalog.java
core/cas-server-core-tickets/src/test/groovy/org/apereo/cas/config/AbstractTicketRegistryTicketCatalogConfigTests.groovy
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/BaseTicketRegistryTests.java

The class comparison was inverted in the `DefaultTicketCatalog.find(Class)` method.
I've added tests for this method in `AbstractTicketRegistryTicketCatalogConfigTests` but it seems these tests have been removed in 6.0+?  As a proxy for this I've added `verifyTicketCountsEqualToTicketsAdded`, which will exercise the `.find(Class)` method via the `MongoDbTicketRegistryTests` (as well as verify the `sessionCount` and `serviceTicketCount` methods) since that's the only use of `DefaultTicketCatalog.find(Class)`.

Fix TicketCatalog.find(Class) (5.3.x)

---

api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/ServiceRegistry.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/ChainingServiceRegistry.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/InMemoryServiceRegistry.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/resource/AbstractResourceBasedServiceRegistry.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/AbstractServiceRegistryTests.java
support/cas-server-support-cassandra-service-registry/src/main/java/org/apereo/cas/adaptors/cassandra/services/CassandraServiceRegistry.java
support/cas-server-support-cosmosdb-service-registry/src/main/java/org/apereo/cas/services/CosmosDbServiceRegistry.java
support/cas-server-support-couchbase-service-registry/src/main/java/org/apereo/cas/services/CouchbaseServiceRegistry.java
support/cas-server-support-couchdb-service-registry/src/main/java/org/apereo/cas/services/CouchDbServiceRegistry.java
support/cas-server-support-dynamodb-service-registry/src/main/java/org/apereo/cas/services/DynamoDbServiceRegistry.java
support/cas-server-support-git-service-registry/src/main/java/org/apereo/cas/services/GitServiceRegistry.java
support/cas-server-support-jpa-service-registry/src/main/java/org/apereo/cas/services/JpaServiceRegistry.java
support/cas-server-support-ldap-service-registry/src/main/java/org/apereo/cas/adaptors/ldap/services/LdapServiceRegistry.java
support/cas-server-support-mongo-service-registry/src/main/java/org/apereo/cas/services/MongoDbServiceRegistry.java
support/cas-server-support-redis-service-registry/src/main/java/org/apereo/cas/adaptors/redis/services/RedisServiceRegistry.java
support/cas-server-support-rest-service-registry/src/main/java/org/apereo/cas/services/RestfulServiceRegistry.java

Builds on #4071 to remove the findServiceById method as it's now unused.
Also note that the various implementations of `ServiceRegistry.findServiceById(String id)` across all the repository types were completely different:
The following all load every service into a collection and returns find the first `serviceId` that regex matches the parameter:
- `AbstractResourceBasedServiceRegistry`
- `CouchbaseServiceRegistry`
- `InMemoryServiceRegistry`
- `JpaServiceRegistry`
- `LdapServiceRegistry`
- `RedisServiceRegistry`
`CosmosDbServiceRegistry`: find a service with the parameter in the document body
`CouchDbServiceRegistry`: find a service with the `id` equal to the parameter
`DynamoDbServiceRegistry`: find a service with the `id` equal to the parameter
`MongoDbServiceRegistry`: find a …

Remove unused ServiceRegistry.findServiceById(String) method

---

support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/PasswordChangeAction.java

This PR fixes an issue we've found with password change validation errors. When using custom errors for specific validation failures only the first message encountered is ever displayed to all users (the first message becomes the message always displayed).
I've tested this change and it resolves the issue, there should be zero side effects.
I'll also follow up with a PR for the 6.0.x branch. Let me know if I can provide any further information.

Fix password change error message stickiness

---

build.gradle
gradle.properties

This is to pick up new version of spring framework (also snapshot) that fixes concurrency bug. Spring version was already updated but without pointing to new spring boot that references it, cas overlay dependencies will still pick up the older milestone release of spring in addition and there will be duplicate versions of the spring jars in the resulting war.

Update spring-boot to 2.2.0-BUILD-SNAPSHOT

---

core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/CookieRetrievingCookieGenerator.java
core/cas-server-core-cookie-api/src/test/java/org/apereo/cas/web/support/CookieRetrievingCookieGeneratorTests.java

The old `CookieRetrievingCookieGeneratorTests` didn't verify that remember me age was applied correctly.
Also fixes handling for multivalue attributes.

Fix remember me cookie unit test

---

support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/jwks/OidcJsonWebKeystoreGeneratorService.java

When setting a custom location for the keystore via `cas.authn.oidc.jwksFile=file:/my/custom/folder/keystore.jwks`, the resulting `Resource` implementation `org.apereo.cas.configuration.model.support.oidc.OidcProperties#getJwksFile` is of type `FileUrlResource` instead of `FileSystemResource`

Support FileUrlResource for OIDC JWK

---

support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/conditions/SamlProfileSamlConditionsBuilder.java

Make the 'skewAllowance' setting in the SAML assertion conditions apply to the "not before" condition as well as "not after". This accounts for clock skew in either direction.
For example, at assertion generated at 16:22:30 with a skewAllowance of 10 seconds should be valid from 16:22:20 - 16:22:40

SAML condition clock skew allowance applies 'before' as well as 'after'

---

docs/cas-server-documentation/installation/Configuring-Servlet-Container.md

Example of setting up logging.properties file needs to use java.util.logging levels ("FINE", "FINEST", etc.) "DEBUG" is not a valid choice

Doc fix: syntax error in setting java.util.logging.ConsoleHandler.level

---

support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/util/OidcAuthorizationRequestSupport.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/web/OidcCallbackAuthorizeViewResolver.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/util/OidcAuthorizationRequestSupportTests.java

Context: Authentication with OpenID Connect (OIDC) identity layer
I need renew parameter in the login url, so I use prompt query parameter with 'login' as value.
prompt parameter is used to rewrite login url but is never removed from original url. It throws infinite loop on login.
In this PR I remove prompt parameter before redirect url rewrite (containing renew parameter). The parameter is already used by the pre-handler to know if the parameter renew is added or not to redirect url.
This PR fixes infinite login loop.

[OpenID Connect (OIDC)] fix prompt=login login api query parameter

---

support/cas-server-support-jpa-ticket-registry/src/test/java/org/apereo/cas/AllTestsSuite.java
support/cas-server-support-jpa-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/OauthJpaTicketRegistryTests.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/ticket/code/OAuthCodeImpl.java

When using OAuth/OIDC together with JPA, we can run into a situation where we want to delete a TGT (i.e. after logout), while an Auth Code related to that SSO session has been created and still exists in the database. In this case, logging out results in an exception
```
2019-07-15 12:36:37,322 DEBUG [org.apereo.cas.web.FlowExecutionExceptionResolver] - <Ignoring the received exception due to a type mismatch>org.postgresql.util.PSQLException: ERROR: update or delete on table "ticketgrantingticket" violates foreign key constraint "fk2yj68mj21qq1k3h6jaq1n3gl9" on table "oauth_tokens"  Detail: Key (id)=(TGT-1-4BzyjhqHd0-drYrTyuXZeheoEDD-den8Nk2WSM7q5afLvrUuhwsF-9N9jomNjfgtrM0-cip-84d6cb956d-85wr8) is still referenced from table "oauth_tokens".
at …
```

Fix missing clean-up of Auth Codes when using JPA+OAuth2.0/OIDC

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/EncodingUtils.java

I was facing a problem with the jwt access token generated by cas. Its payload was encoded using base64 instead of base64url. I created this PR because the jwt standard (https://tools.ietf.org/html/rfc7519#section-3) says:
- "A JWT is represented as a sequence of URL-safe parts separated by period ('.') characters.  Each part contains a base64url-encoded value."

Fix the JWS encoding payload

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/monitor/MonitorProperties.java
api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/ExpirationPolicyBuilder.java
core/cas-server-core-monitor/src/main/java/org/apereo/cas/monitor/SystemMonitorHealthIndicator.java
core/cas-server-core-monitor/src/main/java/org/apereo/cas/monitor/config/CasCoreMonitorConfiguration.java
docs/cas-server-documentation/configuration/Configuration-Properties.md

PR adds  new SystemHealthIndicator to the current list of health monitors that can be configured.  It can be used to monitor and alert when system load of a CAS server exceeds a threshold.   It also provides system information that is used on the /dashboard endpoint for CAS Management web application.

Adds a SystemHealthIndicator to Monitors

---

webapp/cas-server-webapp-resources/src/main/resources/messages.properties
webapp/cas-server-webapp-resources/src/main/resources/messages_de.properties
webapp/cas-server-webapp-resources/src/main/resources/messages_fr.properties
webapp/cas-server-webapp-resources/src/main/resources/messages_pl.properties
webapp/cas-server-webapp-resources/src/main/resources/messages_sk.properties
webapp/cas-server-webapp-resources/src/main/resources/messages_vi.properties
webapp/cas-server-webapp-resources/src/main/resources/templates/fragments/loginform.html
webapp/cas-server-webapp-resources/src/main/resources/templates/fragments/pwdupdateform.html

there is incosistent usage of pwd.example.org or changepsw.exampple.org in messages. Some translations expects URL as parameter, some not, but parameter was not set. 
The better place for customization of URL is template file. The best would be to provide configurable parameter. In that case we could solve also reference in expiring password warning.
- as  user open login page and check URL provided in _Forgot password_
- as user with expired password try to login and check URL provided in error message

refactor usage of pwd.example.org

---

core/cas-server-core-web-api/src/main/java/org/apereo/cas/services/web/support/RegisteredServiceResponseHeadersEnforcementFilter.java
core/cas-server-core-web/src/test/java/org/apereo/cas/web/RegisteredServiceResponseHeadersEnforcementFilterTests.java

Update RegisteredServiceResponseHeadersEnforcementFilter to support disabling  HTTP security headers on a per-service basis.
For each security header property (e.g. "httpHeaderEnableXContentOptions"), there are 3 cases:
- service definition sets it "true"  ==> include the header
- service definition sets it "false" ==> do not include the header
- service definition does not specify any value ==> use the global (cas-security-filter) setting
Previous code did not distinguish between "false" and "not present", leaving no way to disable a header for a single specific service.

Allow disabling HTTP headers on a per-service basis

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/authentication/PrincipalAttributesProperties.java
core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/CoreAuthenticationUtils.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
gradle/overrides.gradle
style/dependency-check-suppressions.xml
support/cas-server-support-configuration-cloud-aws-s3/src/test/java/org/apereo/cas/AmazonS3BucketsCloudConfigBootstrapConfigurationTests.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20CallbackAuthorizeEndpointController.java
support/cas-server-support-saml-core/src/main/java/org/apereo/cas/config/CoreSamlConfiguration.java
support/cas-server-support-saml-idp-metadata-aws-s3/src/test/java/org/apereo/cas/support/saml/idp/metadata/AmazonS3SamlIdPMetadataGeneratorTests.java

WARN [org.apache.velocity.deprecation]
- <configuration key 'resource.loader' has been
deprecated in favor of 'resource.loaders'>
WARN [org.apache.velocity.deprecation]
- <configuration key 'file.resource.loader.class' has been
deprecated in favor of 'resource.loader.file.class'>
WARN [org.apache.velocity.deprecation]
- <configuration key 'string.resource.loader.class' has been
deprecated in favor of 'resource.loader.string.class'>
WARN [org.apache.velocity.deprecation]
- <configuration key 'classpath.resource.loader.class' has been
deprecated in favor of 'resource.loader.classpath.class'>

fix velocity property keys to avoid deprecation warnings

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/CasVersion.java

Follow up to commit c5138a1e510a476ce6c4dbdc177d7ed2ae8ab9b2
`URLConnection.getLastModified()` returns the the last modified date.  Referencing JBoss VFS classes is not required.
There was a bug fixed in JBoss VFS https://issues.jboss.org/browse/JBVFS-206 where
JBoss VFS was incorrectly returning JBoss VFS VirtualFile when it should have returned the Content.
In the `CasVersion` use case, it is using `ClassLoader.getResource(CasVersion.class)` and trying to get the last modified time
The content is cannot be assumed to be a file since classes are almost always in a jar file or in 2 layers or zipped archives
The URLConnection (and the classes that extend it that handle Jars, Files, etc) has a `getLastModified()`, so this can be used without having to reference JBoss VFS …

Refactor: Determine last-modified-date for CASVersion correctly

---

.travis.yml

I added some needed parenthesis so the skipping only applies to PRs by dependency bot. (As-is it is not running some stages on non-PR builds. )

fix logic in travis ci so skipping stages only applies to PRs

---

.travis.yml

also avoid doc validation on dependency update
tested with travis-conditions:
travis-conditions eval "NOT (commit_message =~ env(DEPENDENCY_BOT_RE) and type = pull_request)" --data '{"type": "pull_request", "commit_message": "renovatebot(deps): update amazonsdk to v1.11.613", "env": ["DEPENDENCY_BOT_RE=^renovatebot\\(deps\\)"]}'
false
travis-conditions eval "NOT (commit_message =~ env(DEPENDENCY_BOT_RE) and type = pull_request)" --data '{"type": "pull_request", "commit_message": "regular update", "env": ["DEPENDENCY_BOT_RE=^renovatebot\\(deps\\)"]}'
true

travis ci - need to double escape backslash in env variable

---

support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java

In class OidcProperties default supported response types are "code", "token", "id_token token". If you use id_token token reposne type you get an exception because the validator oauthIdTokenAndTokenResponseTypeRequestValidator is not added.

OIDC missing response type validator

---

support/cas-server-support-token-core/src/main/java/org/apereo/cas/token/cipher/RegisteredServiceTokenTicketCipherExecutor.java
support/cas-server-support-token-core/src/test/java/org/apereo/cas/token/BaseJWTTokenTicketBuilderTests.java
support/cas-server-support-token-core/src/test/java/org/apereo/cas/token/JWTTokenTicketBuilderWithoutEncryptionTests.java

Description
Fix for jwt service ticket bug. It should be possible from sources  to disable encryption or fall back to default encryption key  if custom encryption keys are not set for service.
Secondary effects
If custom encryption or signing keys are not set for service it should allow to fall back into default configuration for signing and encrypting. From documentation it should be possible.
Test cases
JWTTokenTicketBuilderWithoutEncryptionTests -> verifyJwtForServiceTicketWithoutEncryptionKey

Fix jwt service token without encryption key

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/util/OidcAuthorizationRequestSupport.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/web/OidcCallbackAuthorizeViewResolver.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/util/OidcAuthorizationRequestSupportTests.java

Summary: When using CAS as OpenId Connect Provider and using silent authentication (prompt=none), if the user logged in session is not active, then redirect to original redirect url with error code as `login_required`
https://openid.net/specs/openid-connect-core-1_0.html#AuthError
When we set `prompt=none`, then if the user authenticated session is valid, CAS is redirecting to original redirect url with new Auth Code.
If the user authenticated session is not valid, then currently CAS is showing `..\oauth2.0/callbackAuthorize?..` with error code `{
"error": "login_required"
}`
But expected behaviour is to redirect back to the service redirect url with error code in url param.
Such as `https://www.example.org?error=login_required`. This will enable the service to act upon this response …

OIDC: Redirect to Original url with error code as login required.

---

core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/resource/RegisteredServiceResourceNamingStrategy.java

When using YAML service registry, CAS warns in the logs that the service file name does not match the recommended pattern `(\w+)-(\d+)\.yml|yaml`. That's because the regex should be: `(\w+)-(\d+)\.(yml|yaml)`.
The error message is logged here: https://github.com/apereo/cas/blob/f7666b51df/core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/resource/AbstractResourceBasedServiceRegistry.java#L267  but the regex is built in `RegisteredServiceResourceNamingStrategy`.
This PR fixes the regex building.

Service Registry: Fix regex for service YAML file names

---

support/cas-server-support-shell/src/main/java/org/apereo/cas/shell/commands/services/ValidateRegisteredServiceCommand.java

There's actually 3 fixes:
- Argument "file" is made optional (by providing a default empty value), in order to enable validating a directory (currently, "file" was required, which means it was never blank, and directory validation was implemented but not possible)
- Files with extension .yaml will be validated (in addition to .yml files)
- YAML files will be validated with the right deserializer (currently, validation of YAML services fails)

Fixes the shell command "validate-service" for YAML

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20CallbackAuthorizeEndpointController.java

Small fix for race condition in `OAuth20CallbackAuthorizeEndpointController`.
Addresses the issue introduced in commit b1cbcb2a1b305fb915be3dac65e130da315772c0, when `callback` variable instance is shared between all threads accessing `OAuth20CallbackAuthorizeEndpointController`.

fix for race condition in OAuth20CallbackAuthorizeEndpointController

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/web/OidcCallbackAuthorizeViewResolver.java

Summary: Ref https://github.com/apereo/cas/pull/4227, the URL need to be changed from requestURL, which is url of `callBackAuthorize`, to use `redirect_uri` parameter set in Authorization request.

Redirecting to original redirect_uri in the original request when prompt is none.

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/profile/OidcProfileScopeToAttributesFilter.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java

Per the first part of this cas dev post:
https://groups.google.com/a/apereo.org/forum/#!topic/cas-dev/Fn08B3lhhAI
The custom scopes to release need to be stored in map by name rather than the type "custom". Standard scopes are stored by their standard types as the key, they don't have names.

store custom scopes by name instead of "custom"

---

support/cas-server-support-oidc-core/src/main/java/org/apereo/cas/oidc/claims/BaseOidcScopeAttributeReleasePolicy.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/claims/mapping/DefaultOidcAttributeToScopeClaimMapperTests.java

Since #4217, the `OidcScopeAttributeReleasePolicy` is applied twice:
- once during the creation of the service ticket,
- once during the generation of the JWT ticket.
This causes a bug where custom claims cannot be resolved.
Mapping:
cas.authn.oidc.claimsMap.email=mail
If resolved attributes are:
- name: foo
- mail: my@email.com
- unknownAttribute: bar
- ...
The `OidcScopeAttributeReleasePolicy` is applied during the generation of the service ticket.
Then, the `Principal` passed to `OidcProfileScopeToAttributesFilter` during the JWT generation (which is `authentication.getPrincipal()` in [OidcIdTokenGeneratorService](https://github.com/apereo/cas/blob/775162461b776db4cad1545c3bcc39fa14dbe973/support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/token/OidcIdTokenGenerat …

OidcScopeAttributeReleasePolicy: fix release of custom claims

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/policy/AtLeastOneCredentialValidatedAuthenticationPolicy.java
core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/PolicyBasedAuthenticationManagerTests.java

According to the documentation at https://apereo.github.io/cas/development/configuration/Configuration-Properties.html#any , this policy should make sure, that every handler is checked if the tryAll flag is set.
Instead the function checked, if the amount of provided credentials equals the amount of checked handlers, which is not the same.

Bug with tryAll in AtLeastOneCredentialValidatedAuthenticationPolicy

---

core/cas-server-core-authentication-mfa/build.gradle
core/cas-server-core-authentication-mfa/src/test/java/org/apereo/cas/authentication/DefaultMultifactorAuthenticationProviderResolverTests.java
core/cas-server-core-tickets/build.gradle
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/DefaultTicketCatalogTests.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/TicketSerializersTests.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/factory/BaseTicketFactoryTests.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/BaseTicketRegistryTests.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/serialization/DefaultTicketStringSerializationManagerTests.java
core/cas-server-core/src/test/java/org/apereo/cas/BaseCasCoreTests.java
support/cas-server-support-discovery-profile/src/test/java/org/apereo/cas/discovery/CasServerProfileRegistrarTests.java
support/cas-server-support-ldap-monitor/src/main/java/org/apereo/cas/monitor/config/LdapMonitorConfiguration.java

There was a dependency cycle ("Requested bean is currently in creation") when this module was used due to some changes after 6.1.RC5. I couldn't get the cycle to happen in a unit test but this fixes it when I tested it with "bc".

avoid bean cycle in ldap monitor config class

---

README.md

Adding [Acceptto](https://www.acceptto.com/)'s logo to the README file as [Accpetto's MFA module](https://github.com/apereo/cas/blob/master/docs/cas-server-documentation/mfa/Acceptto-Authentication.md) has already been implemented and added to CAS.

Add Acceptto's Logo to the README.md

---

support/cas-server-support-memcached-core/src/main/java/org/apereo/cas/memcached/kryo/CloseableKryoFactory.java
support/cas-server-support-saml-googleapps/src/main/java/org/apereo/cas/support/saml/config/SamlGoogleAppsComponentSerializationConfiguration.java
support/cas-server-support-saml-googleapps/src/main/resources/META-INF/spring.factories

Class registrations were missing for `GoogleAccountsService` and ValidationResponseType classes preventing error free use of the KRYO transcoder for memcached serialization.

Added missing class registrations for kryo + memcached

---

gradle/dependencies.gradle

If ehcache is needed by jradius or fortress (and it may not be) then it needs to be ehcache artifact rather than the older ehcache-core.

exclude old ehcache-core dependency

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/authenticator/OAuth20ClientIdClientSecretAuthenticator.java

Added changes to check for `code_challenge` not null and empty instead of just checking for not null.
Related to PR https://github.com/apereo/cas/pull/4262

Check for empty oauth code challenge

---

support/cas-server-support-git-service-registry/src/main/java/org/apereo/cas/config/GitServiceRegistryConfiguration.java
support/cas-server-support-ldap-service-registry/src/main/java/org/apereo/cas/adaptors/ldap/services/config/LdapServiceRegistryConfiguration.java

I want to be able to be able choose between json and git service registries for the same CAS image (war). This PR makes the git service registry conditional on one of its required properties. I also made ldap service registry conditional on properties although I don't personally plan on using it. Json and Yaml service registries are already conditional on properties and rest is conditional although it is conditional on the service registry bean rather than the whole configuration class. 
I backed out change to make JpaServiceRegistry conditional on url property b/c there are some unit tests that don't set a appear to set a url and it wasn't clear to me how they worked.

make some service registries conditional on required properties

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/PolicyBasedAuthenticationManager.java
core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/handler/support/jaas/AccountsPreDefinedLoginModule.java
style/dependency-check-suppressions.xml

This moves some variable declarations and assignments inside block where they are used to make spotbugs BAS_BLOATED_ASSIGNMENT_SCOPE go away. 
Also suppress Tomcat 7 CVE.

minor spotbug changes and suppress false positive tomcat CVE

---

core/cas-server-core-configuration-metadata-repository/src/main/java/org/springframework/boot/configurationmetadata/CasConfigurationMetadataRepositoryJsonBuilder.java

The old code threw an NullPointerException if `org.springframework.boot.configurationmetadata.ConfigurationMetadataSource#getType` retuned `null`

Configuration metadata: prevent NPE if source.getType() is null

---

ci/tests/ldap/reset-ad-server.sh
ci/tests/ldap/run-ad-server.sh
support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/util/LdapUtils.java
support/cas-server-support-pm-ldap/src/main/java/org/apereo/cas/pm/LdapPasswordManagementService.java
support/cas-server-support-pm-ldap/src/test/java/org/apereo/cas/pm/ADPasswordManagementServiceTests.java

The previous change password code, when LDAP type was AD, wasn't using the old password. This may have been OK if the changing of an expiring password was done after login where the old password was validated on login, but using a "reset password" (without old password) vs. a "change password" that requires old password isn't really the same. The reset password requires the bind user to have more privileges and it doesn't respect some domain password policies such as history and minimum age. 
I think this should make the AD handling comparable to the non-AD LDAP handling which used the old password if it was not blank. 
This also sets a default JKS store password of "changeit" if the password field is empty. Since JKS keystores require passwords, might as well use one that is more likely …

password management: add support for Active Directory "change password" vs "reset password"

---

ci/init-travis-build.sh

I have seen several travis jobs fail because the java install failed. This retries it a few times if it fails.

CI: retry java install if it fails

---

ci/tests/ldap/run-ad-server.sh
core/cas-server-core-web/src/main/resources/cas_common_messages.properties
docs/cas-server-documentation/ux/User-Interface-Customization-CSSJS.md
support/cas-server-support-ldap/src/test/java/org/apereo/cas/AllLdapTestsSuite.java
support/cas-server-support-ldap/src/test/java/org/apereo/cas/authentication/ActiveDirectoryJndiSamAccountNameLdapAuthenticationHandlerTests.java
support/cas-server-support-ldap/src/test/java/org/apereo/cas/authentication/ActiveDirectoryJndiUPNLdapAuthenticationHandlerTests.java
support/cas-server-support-ldap/src/test/java/org/apereo/cas/authentication/ActiveDirectoryLdapAuthenticationHandlerPasswordPolicyTests.java

This is adds a test for AD to validate that warnings for upcoming password expiration are returned with Active Directory.

add Active Directory test for password policy warnings due to password expiration

---

gradle.properties
gradle/dependencies.gradle

Manage signalfx-java dependency to get latest version so old shaded jackson-databind doesn't get included in CAS.

update signalfx dependency

---

docs/cas-server-documentation/installation/Whitelist-Authentication.md

When I tried to use the example above, it failed by default due to expiration date on `2018`.
I proposed to set the date to a time in the far future (e.g. `2050`) , so this example can work out of the box.

Docs: Change example expiration date so it don't fail by default

---

core/cas-server-core-authentication-mfa-api/src/main/java/org/apereo/cas/authentication/trigger/GroovyScriptMultifactorAuthenticationTrigger.java

as described here: https://apereo.github.io/cas/6.1.x/mfa/Configuring-Multifactor-Authentication-Triggers.html#groovy
def service = args[0]
def registeredService = args[1]
def authentication = args[2]
def httpRequest = args[3]
def logger = args[4]

Groovy MFA Trigger: The first args parameter will be service instead of registeredService

---

support/cas-server-support-saml-idp-metadata/src/main/java/org/apereo/cas/support/saml/services/idp/metadata/cache/SamlRegisteredServiceCacheKey.java
support/cas-server-support-saml-idp-metadata/src/main/java/org/apereo/cas/support/saml/services/idp/metadata/cache/resolver/UrlResourceMetadataResolver.java
support/cas-server-support-saml-idp-metadata/src/test/java/org/apereo/cas/support/saml/services/idp/metadata/cache/resolver/UrlResourceMetadataResolverTests.java

PR stops UrlMetadataResolver from being included in supported resolvers when metadata location is an MDQ server.
Change SamlRegisteredCacheKey to be based on Entity Id of SPs instead of metadata location.  When using MDQ, all entities use the same location and is no longer a unique key.

Fix for MDQ Metadata Resolve

---

ci/tests/webapp/validate-embedded-webapp.sh
webapp/cas-server-webapp-resources/src/main/resources/application.properties

Turn off spring.cloud.discovery.client.composite-indicator by default
test more urls in embedded webapp test
Not critical to back port these b/c the properties can be set by the user, but finding the property to turn off spring.cloud.discovery.client.composite-indicator is a little tough, unless you are using spring cloud discovery and they you probably know where it is. There is an issue open regarding the health actuator erroring out with 404 if no health monitors are enabled but might as well enable do ping check in the meantime so it does something it if  the health endpoint is enabled.

backport health actuator fixes

---

core/cas-server-core-authentication-mfa-api/src/main/java/org/apereo/cas/authentication/trigger/GroovyScriptMultifactorAuthenticationTrigger.java

Groovy MFA Trigger: The first args parameter will be service instead of registeredService as described here: https://apereo.github.io/cas/6.1.x/mfa/Configuring-Multifactor-Authentication-Triggers.html#groovy
def service = args[0]
def registeredService = args[1]
def authentication = args[2]
def httpRequest = args[3]
def logger = args[4]

backport Groovy MFA Trigger (#4380)

---

docs/cas-server-documentation/installation/Whitelist-Authentication.md

The previous json example don't work, but this modified one would work
I have tried the original example 
```
...
"firstName" : ["Apereo"],
...
```
and exception like this one `ERROR [org.apereo.cas.authentication.PolicyBasedAuthenticationManager] - <[JsonResourceAuthenticationHandler]: [com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'CAS' as a subtype of [collection type; class java.util.List, contains [simple type, class java.lang.Object]]: no such class found` is thrown .
After some tinkering with the json file, I found that the following syntax would work
```
"firstName" : [ "java.util.List", ["Apereo"]],
```
Adding this would make this example work as expected.
I can demonstrate the example of this behavior using overlay if it is deem necessary, …

Updating Json Authentication Documentation Example to make it work

---

docs/cas-server-documentation/configuration/Configuration-Properties.md

Just tested Rest Authentication Attribute, the request parameter should be:
**`username`.** 
Instead of:
**`username.`**
Changed the position of the full-stop. Thanks.

Fix typo of Rest Attribute `username.`  back to `username`.

---

core/cas-server-core-events-api/src/main/java/org/apereo/cas/support/events/listener/DefaultCasEventListener.java

If TGT creation event is async, geoLocation and agent information is lost when handling/storing event.
A side effect of this, is a NPE in UserAgentAuthenticationRequestRiskCalculator when calculating score.

Remave Async from TGT creation event

---

support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/slo/SLOSamlPostProfileHandlerController.java

As stated, fixes UnmodifiableComponentException during *any* subsequent SAML2 SLO attempt. Without this fix, the first logout/SLO attempt succeeds, but the second and any other SLO attempts will fail since BaseHttpServletRequestXMLMessageDecoder is already initialized and trips the `ComponentSupport.ifInitializedThrowUnmodifiabledComponentException` check.

Fix UnmodifiableComponentException during SAML2 SLO

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/services/OidcServiceRegistryListener.java

This PR ensures that when Scopes for OIDC requests are resolved they will use the PrincipalAttributeRepository that has been defined in the AttributeReleasePolicy from the registered service for the request.

Use PrincipalAttributeRepository defined in OidcRegisteredService 

---

docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/AbstractX509PrincipalResolver.java
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SubjectAlternativeNameUPNPrincipalResolver.java
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/X509UPNExtractorUtils.java
support/cas-server-support-x509-core/src/test/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SubjectAlternativeNameRFC822EmailPrincipalResolverTests.java
support/cas-server-support-x509-core/src/test/resources/log4j2.xml

I would like to use this feature on 6.1.x. It isn't a bug fix but it addresses an oversight that left out a fairly important attribute.

backport x509 additional x509subjectUPN attribute to 6.1.x branch

---

core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/DefaultRegisteredServiceAccessStrategy.java

Check if requiredAttributes and rejectedAttributes are null before using them.
Fixes NPE which arises for services that are added through service management webapp.
When using json service registry to add services, there is no NPE.
1. Use service management webapp to add a service with all the default values (Add only serviceId and serviceName and click save).
2. Access this service
3. Authenticate to CAS
4. The following NPE is thrown:
>[info] 2019-11-16 10:19:01,187 INFO [org.apereo.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN
[info] =============================================================             
[info] WHO: 0000000000000000000003                                               
[info] WHAT: Supplied credentials: …

Fix possible NPE

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/HttpUtils.java

The `HttpUtils` component is a really useful one.
Nonetheless, there are some use cases when I'd like to change the internal HTTP client.
This is what this PR proposes: allow to change the internal HTTP client.

Open up the HttpUtils component

---

core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/resolver/impl/DefaultCasDelegatingWebflowEventResolver.java

The `DefaultCasDelegatingWebflowEventResolver` generates full stack traces at the WARN level which pollutes the logs with no real value.
For an authentication failed, there is already a log from the `PolicyBasedAuthenticationManager` for example:
```
2019-12-03 08:54:45,004 ERROR [org.apereo.cas.authentication.PolicyBasedAuthenticationManager] - <Authentication has failed. Credentials may be incorrect or CAS cannot find authentication handler that supports [UsernamePasswordCredential(username=non, source=null, customFields={})] of type [UsernamePasswordCredential]. Examine the configuration to ensure a method of authentication is defined and analyze CAS logs at DEBUG level to trace the authentication event.>
2019-12-03 08:54:45,011 WARN …
```

Limit stack traces

---

support/cas-server-support-simple-mfa/src/main/java/org/apereo/cas/config/CasSimpleMultifactorAuthenticationTicketCatalogConfiguration.java

I'm getting an exception when using the JpaTicketRegistry related to the DefaultTicketRegistryCleaner.  Shouldn't the ticket definition use the Entity class, not the interface?  The rest of the ticket definitions in my ticketCatalog do this.
From debug, ticketCatalog.ticketMetadataMap:
```
"TGT" -> {DefaultTicketDefinition@20866} "DefaultTicketDefinition(implementationClass=class org.apereo.cas.ticket.TicketGrantingTicketImpl, prefix=TGT, properties=DefaultTicketDefinitionProperties(cascade=true, storageName=null, storageTimeout=0, storagePassword=null), order=2147483647)"
"ST" -> {DefaultTicketDefinition@20306} "DefaultTicketDefinition(implementationClass=class org.apereo.cas.ticket.ServiceTicketImpl, prefix=ST, properties=DefaultTicketDefinitionProperties(cascade=false, …
```

Jpa: Simple MFA configuration should change TransientSessionTicket to TransientSessionTicketImpl

---

.github/renovate.json
gradle.properties
gradle/dependencies.gradle

* use jradius dependencies from maven central
The jar referenced in mvnrepository.com for com.github.coova:jradius is 22 bytes.
* exclude jradius from renovate under new group name
(cherry picked from commit 4463954c96c3e32d503d8c448fabd00861c9e253)

update jradius dependency to use version from maven central (#4507)

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileEndpointController.java

when `/oauth2.0/profile` endpoint is used with `POST` verb, the mime type response is correct : `application/json`
when `/oauth2.0/profile` endpoint is used with `GET` verb, the mime type response is wrong :` text/plain`

Fix oauth2 profile endpoint mediatype when HTTP verb is GET

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileEndpointController.java

when `/oauth2.0/profile` endpoint is used with `POST ` verb, the mime type response is correct : `application/json`
when `/oauth2.0/profile` endpoint is used with `GET` verb, the mime type response is wrong :` text/plain`

Fix oauth2 profile endpoint mediatype when HTTP verb is GET 

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/authenticator/OAuth20ProofKeyCodeExchangeAuthenticator.java

In `rfc7636` **Proof Key for Code Exchange by OAuth Public Clients**, the `code_challenge_method` is OPTIONAL (https://tools.ietf.org/html/rfc7636#section-4.3)
When I test PKCE in CAS wihtout `code_challenge_method` parameter (`/oauth2.0/authorize` endpoint), it ends with an error during `code_verifier` verification (`/oauth2.0/accessToken` endpoint) :
```
org.pac4j.core.exception.CredentialsException: Code verification method is unrecognized: 
at org.apereo.cas.support.oauth.authenticator.OAuth20ProofKeyCodeExchangeAuthenticator.calculateCodeVerifierHash(OAuth20ProofKeyCodeExchangeAuthenticator.java:85) ~[cas-server-support-oauth-core-api-6.1.2.jar!/:6.1.2]
at org.apereo.cas.support.oauth.authenticator.OAuth20ProofKeyCodeExchangeAuthenticator.validateCredentials(OAuth20ProofKeyCodeExchang …
```

oauth2 pkce code_challenge_method should be optional

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/DelegatedClientWebflowManager.java

The authentication delegation to a CAS server has a big issue. It seems to work, but it doesn't. You generally see that under a certain workload, but it can be reproduced fairly easily.
The TST is saved into the `customParams` of the `configuration` of the `CasClient` which is a problem because it's a singleton so the TST used at the time of the ticket validation (`CasAuthenticator`) can be the one of another authentication delegation.
This PR fixes the issue by using the session instead.
It can be tested easily with this project: https://github.com/casinthecloud/cas-pac4j-oauth-demo (master branch). It's the version 6.2.0-RC1, but all CAS versions have the same code and issue.
- Call the login page (http://localhost:8080/cas/login) and start the authentication delegation to a CAS server …

Fix the authentication delegation to a CAS server

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/authenticator/OAuth20UsernamePasswordAuthenticator.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/util/OAuth20Utils.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/validator/token/OAuth20PasswordGrantTypeTokenRequestValidator.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenPasswordGrantRequestExtractor.java

As per the OIDC Client implementors guide clients should use Basic Auth to send client credentials. It points to Section 2.1.3 of the OAuth 2.0 specification which states that
The client identifier is encoded using the
"application/x-www-form-urlencoded" encoding algorithm per
Appendix B, and the encoded value is used as the username; the client
password is encoded using the same algorithm and used as the
password.
The Authentication part works as expected as this supports using Authentication Header
https://github.com/apereo/cas/blob/master/support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/authenticator/OAuth20UsernamePasswordAuthenticator.java#L45
But due to additional validation in `OAuth20PasswordGrantTypeTokenRequestValidator` …

OIDC - Allow client basic auth to be used in password grant flow

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/DigestUtils.java

OAuth2 PKCE `code_challenge` must be a SHA2 digest (not a SHA3).
https://tools.ietf.org/html/rfc7636#section-2
https://tools.ietf.org/html/rfc7636#section-4.2

OAuth2 PKCE code_challenge must be a SHA2 digest

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/ehcache/Ehcache3Properties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-ehcache-monitor/src/main/java/org/apereo/cas/monitor/config/EhCacheMonitorConfiguration.java

This bean is already conditional on ehcacheHealthIndicator being enabled so it isn't needed (and doesn't work due to no property at cas.ticket.registry.ehcache.monitor.enabled

remove ehcache monitor enabled property that doesn't exist in config

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20IntrospectionEndpointController.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/web/controllers/OidcIntrospectionEndpointControllerTests.java

A valid introspection response body "exp" value should be "Integer timestamp, measured in the number of seconds since January 1 1970 UTC, indicating when this token will expire". 
Before it was just the expiration policy's time to live value. 
https://tools.ietf.org/html/rfc7662#section-2.2
This problem affects OAuth 2.0 and OIDC protocols. 
Limitation: Trying to use Apereo CAS introspection request with Spring Security 5 resource server throws an "IllegalArgumentException: expiresAt must be after issuedAt" exception in the resource server when introspecting the token.  This might affect other resource servers that also perform these check for fields "iat" and "exp".

Oauth 2 introspection expires at fix

---

support/cas-server-support-pac4j-api/src/main/java/org/apereo/cas/integration/pac4j/DistributedJ2ESessionStore.java

I get the following error from the `DefaultTicketRegistryCleaner` when the TGT expires and when I use the `DistributedJ2ESessionStore`:
```java
2020-01-06 10:04:52,519 DEBUG [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <Cleaning up expired ticket-granting ticket [TGT-1-*****pIWKKdU-castest]>
2020-01-06 10:04:52,519 INFO [org.apereo.cas.logout.DefaultLogoutManager] - <Performing logout operations for [TGT-1-*****pIWKKdU-castest]>
2020-01-06 10:04:52,520 ERROR [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <request cannot be null>
org.pac4j.core.exception.TechnicalException: request cannot be null
at org.pac4j.core.util.CommonHelper.assertTrue(CommonHelper.java:107) ~[pac4j-core-4.0.0-RC2.jar!/:?]
at …
```

Fix the DistributedJ2ESessionStore when a TGT expires

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/handler/RegisteredServiceAuthenticationHandlerResolver.java
core/cas-server-core-authentication/src/main/java/org/apereo/cas/config/CasCoreAuthenticationSupportConfiguration.java
core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/PolicyBasedAuthenticationManagerTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/RegisteredServiceAuthenticationHandlerResolverTests.java

We should retrieve the right service in the `RegisteredServiceAuthenticationHandlerResolver` by using the `authenticationServiceSelectionPlan`.
Currently, if the CAS server acts as a SAML IdP, we try to find the authentication handlers related to the callback URL instead of the SAML service.

Find the right service in the RegisteredServiceAuthenticationHandlerResolver

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/principal/resolvers/PersonDirectoryPrincipalResolver.java
core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/ChainingAttributeReleasePolicy.java
support/cas-server-support-git-service-registry/src/main/java/org/apereo/cas/services/GitServiceRegistry.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/services/OidcServiceRegistryListener.java

The change to ChainingAttributeReleasePolicy and OidcServiceRegistryListener seeks to avoid ConcurrentModificationException observed during service ticket validation in policies.foreach loop (something modifying policies, presumably the sorting). 
Change to GitServiceRegistry seeks to avoid clearing instance variable collection used by findServiceById method. Instead collection is replaced when loaded or reloaded. This problem wasn't observed but seemed like it could happen. While the load method is Synchronized, the findServiceById method wasn't.
Change to PersonDirectoryPrincipalResolver seeks to remove Synchronize on method of singleton object which can cause many threads to block if retrieving attributes for any one user takes a significant amount of time. This attempts to synchronize …

Address various concurrency issues

---

webapp/cas-server-webapp-init-tomcat/src/main/java/org/apereo/cas/tomcat/CasTomcatServletWebServerFactoryCustomizer.java

The access logging valve was being added to the engine and the context so requests were being logged twice. This logs at the engine level to get all requests regardless of context (e.g outside of /cas).

fix double logging of requests in access logs

---

support/cas-server-support-hazelcast-monitor/src/main/java/org/apereo/cas/monitor/HazelcastHealthIndicator.java
support/cas-server-support-hazelcast-monitor/src/test/java/org/apereo/cas/monitor/HazelcastHealthIndicatorTests.java

…cast monitor
Signed-off-by: Marek Chodor <marek.chodor@grupawp.pl>
Casting free heap value (*100) to integer made it overflow and report wrong values.
eg.
```
jshell> (long)((int) 125555248L * 100 / 251658240L)
$1 ==> -1
jshell> (int) 125555248L * 100
$3 ==> -329377088
jshell> (long)( 125555248L * 100 / 251658240L)
$4 ==> 49
```

Hazelcast Monitor: Fixes integer overflow when calculating free heap percentage

---

support/cas-server-support-okta-authentication/build.gradle

Okta impl library brings snakeyaml 1.17 which conflicts with already available 1.25 and application fails to start. This behavior exhibits itself when compiling cas.war and running with `java -jar` It will also sometimes fail when deploying into Tomcat, but it is not deterministic and depends on the random order of Tomcat class loader. This was tested locally and is the only way to eliminate this transitive dependency.

Eliminate snakeyaml conflict

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java

If we force the authn delegation process on an existing SSO session, the current behavior is unappropriate: the credentials should not be put in the webflow for an existing session as they trigger a login process, erasing the previous authenticated user.
I also changed the visibility of two methods from `private` to `protected` for customisation purposes.

Fix authn delegation behavior

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/x509/SubjectDnPrincipalResolverProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/x509/X509Properties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/AbstractX509PrincipalResolver.java
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SubjectDNPrincipalResolver.java
support/cas-server-support-x509-core/src/test/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SubjectDNPrincipalResolverTests.java
support/cas-server-support-x509/src/main/java/org/apereo/cas/adaptors/x509/config/X509AuthenticationConfiguration.java

I have something I am working on where I will need to retrieve additional person attributes using a combination of the x509 subject DN and the issuer DN. I am thinking I will need to use a GroovyScriptAttributeReleasePolicy and that I will need the issuer DN extracted from the certificate as an additional attribute. This PR extracts the issuer DN, both using the "denigrated" getIssuerDN() method and the preferred getIssuerX500Principal().getName() method. 
This also allows specifying the subject DN format since the default format is listed as "denigrated" in javadocs. This doesn't change the default that CAS currently uses but it allows for other non-denigrated formats to be specified.

Extract issuer dn from certificate as x509 attribute

---

support/cas-server-support-spnego-webflow/src/main/java/org/apereo/cas/web/flow/SpengoWebflowConfigurer.java

…param
When requesting sso session renew with spnego enabled, eg. `https://mycasdomain/cas/login?service=https://myotherservice&renew=true`, authentication process fails on missing transition for "warn".
User receives error screen instead of being redirected to requested service, because ST was succesfully created.
From application logs:
```
ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/cas].[dispatcherServlet]] - <Servlet.service() for servlet [dispatcherServlet] in context with path [/cas] threw exception [Request processing failed; nested exception is org.springframework.webflow.engine.NoMatchingTransitionException: No transition was matched on the event(s) signaled by the [1] action(s) that executed in this action state 'spnego' of flow 'login'; transitions must …
```

Fix missing "warn" transition for spnego weblflow with "renew" query param

---

build.gradle
gradle.properties

See [the case for mavenLocal()](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:case-for-maven-local) which is really a case for not using mavenLocal() or using it with a repository filter and that is what this PR does. This PR configures mavenLocal to use person-directory from the local repo since that is a related maven project that someone working on CAS might be also working on. This also allows someone to define a group regular expression that someone might use to include other maven dependencies that they are working on and want to pull from mavenLocal. Someone could define a wildcard that included all groups if they really wanted to use mavenLocal() despite the drawbacks. This doesn't use mavenLocal() at all for ```buildscript``` repositories.

limit use of mavenLocal() per gradle best practices

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/io/CommunicationsManager.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/io/SmsSender.java
core/cas-server-core-util/src/main/java/org/apereo/cas/config/CasCoreUtilConfiguration.java

The detection of the `SmsSender` setup is incorrect.
We instantiate a `SmsSender.noOp()` although we test if `this.smsSender` is `null`. Thus, the `SmsSender` is always considered to be properly defined even if it is not.
This PR fixes this problem.

Fix SmsSender detection

---

support/cas-server-support-pm-ldap/src/main/java/org/apereo/cas/config/LdapPasswordManagementConfiguration.java

While adding the `cas-server-support-pm-ldap` dependency is a required step to add LDAP PM support, it should not be enough and the `cas.authn.pm.ldap.ldpUrl` property (at least) should be defined.

Make LDAP PM conditonal on property

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/authenticator/Authenticators.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/authenticator/OAuth20ProofKeyCodeExchangeAuthenticator.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20Configuration.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/authenticator/OAuth20ProofKeyCodeExchangeAuthenticatorTests.java

Hello,
Today the PKCE authentication with a client_secret only works with the client_secret_post authenticator and not with the client_secret_basic authenticator.
This pull request adds support for PKCE with a client_secret submitted with the client_secret_basic authentication.
Let me know if you need any further information.
Regards,
Julien

PKCE with client_secret_basic

---

docs/cas-server-documentation/integration/Attribute-Release-Caching.md
docs/cas-server-documentation/services/JSON-Service-Management.md

The currently documented syntax results in this warning:
2020-02-06 08:44:14,142 WARN
[org.apereo.cas.services.util.JasigRegisteredServiceDeserializationProblemHandler]
- <CAS has converted legacy JSON property [duration] for type
[org.apereo.cas.authentication.principal.cache.CachingPrincipalAttributesRepository].
It parsed 'expiration' value [120] with time unit of [MINUTES].
It is STRONGLY recommended that you review the configuration and upgrade from the legacy syntax.

Update json in documentation for CachingPrincipalAttributesRepository.

---

gradle.properties

Upgrade cryptacular to v1.2.4

---

support/cas-server-support-saml-sp-integrations/src/main/java/org/apereo/cas/util/SamlSPUtils.java

A generated service should not override non-generated service. Occasionally a SAML service will get generated and it overrides my custom SAML service (which for whatever reason wasn't found when the server started). Eventually the correct service definition arrives but its eval order can't override HIGHEST_PRIORITY. I actually set this to HIGHEST in previous commit but it was MIN_VALUE before that so I was just keeping the behavior the same.

Changing generated SAML service eval order to LOWEST

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/support/password/GroovyPasswordEncoder.java
core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/support/password/GroovyPasswordEncoderTests.java
core/cas-server-core-authentication-api/src/test/resources/GroovyPasswordEncoder.groovy
docs/cas-server-documentation/configuration/Configuration-Properties-Common.md

Hello,
Today, when you try to use the JDBC Groovy Password Encoder [referenced here](https://apereo.github.io/cas/6.1.x/configuration/Configuration-Properties-Common.html#password-encoding), the authentication will fail due to the matches method from spring security which is never overrided.
The Groovy Password Encoder will successfully produce a hash according to the scheme you've defined in the Groovy script, but the matches method will be false because it is the one from spring which cannot work with a custom scheme:
```
@Override
public boolean matches(CharSequence rawPassword, String encodedPassword) {
byte[] digested = Hex.decode(encodedPassword);
byte[] salt = subArray(digested, 0, this.saltGenerator.getKeyLength());
return matches(digested, encodeAndConcatenate(rawPassword, …
```

Fix JDBC Groovy Password Encoder

---

api/cas-server-core-api-configuration-model/src/main/resources/META-INF/additional-spring-configuration-metadata.json

Hello Misagh,
When you're using the authentication throttling feature [referenced here](https://apereo.github.io/cas/6.1.x/installation/Configuring-Authentication-Throttling.html), the configuration properties are the folowing: 
```
``` 
But when you're starting CAS with this configuration, you will have the following warning message: 
```
WARN [org.springframework.boot.context.properties.migrator.PropertiesMigrationListener] - <
The use of configuration keys that have been renamed was found in the environment:
Property source 'bootstrapProperties':
Key: cas.authn.throttle.appcode
Replacement: cas.authn.throttle.app-code
Property source 'migrate-bootstrapProperties':
Key: cas.authn.throttle.appcode
Replacement: cas.authn.throttle.app-code
Each configuration key has been temporarily mapped …
```

Fix cas.authn.throttle.appCode property falsy renamed

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pm/PasswordManagementProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-pm-core/src/main/java/org/apereo/cas/pm/BasePasswordManagementService.java

Hello Misagh
When you're using the reset password feature, a Token is generated and sent inside a hyperlink by email or SMS.
The Token contains the client IPaddress who requested the reset and the server IP adress who received it.
If the link is used by another client IP address or processed by another server IP address than the ones contains in the Token, the reset will fail.
Problem: When you're running cas inside a container orchestrator like Kubernetes :
* It could be difficult to stick a user to a specific container
* A container could have a very short life (less than the token TTL) because of horizontal autoscaling
This pull request adds the capability to disable the check of the server IP address. It also adds the capability to disable to check of the client IP address if needed. …

Password Management Token & Server/Client IP Address check

---

support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/util/LdapUtils.java

For boolean return types success should be determined by the LDAP result code.

Check the LDAP result code to determine success.

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/principal/resolvers/PersonDirectoryPrincipalResolver.java

I am working on tying to load testing this person attribute code and I haven't found the problem I was looking for but I did get lots of exceptions from things being added and removed from the HashMap at the same time. Changing it to a ConcurrentHashMap fixed it.

Avoid concurrent modification exception on map

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/jwks/OidcDefaultJsonWebKeystoreCacheLoader.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/jwks/OidcJsonWebKeySetUtils.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/jwks/OidcServiceJsonWebKeystoreCacheExpirationPolicy.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/jwks/OidcServiceJsonWebKeystoreCacheLoader.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/profile/OidcUserProfileSigningAndEncryptionService.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/token/BaseOidcJsonWebKeyTokenSigningAndEncryptionService.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/token/OidcIdTokenSigningAndEncryptionService.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/token/OidcRegisteredServiceJwtAccessTokenCipherExecutor.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/AbstractOidcTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/authn/OidcPrivateKeyJwtAuthenticatorTests.java

Hello Misagh,
When you're generating a keystore.jwks file with a EC key like this one:
```
{
"keys": [
{
"kty": "EC",
"d": "RmIrX6aZ-5ttAFtFCz-K4INVFGdII2VPg-gOWMLYqr4",
"use": "sig",
"crv": "P-256",
"kid": "pouet",
"x": "5MuRs_uRY86eBblVqHKsHjin_VhBSX_Robg8E1GyfH8",
"y": "v7FD3O-XVzF1R2QbR7d75XlDBtU22pR-u1WkSSAhlo0",
"alg": "ES256"
}
]
}
```
And configure your service to use it:
```
{
"@class" : "org.apereo.cas.services.OidcRegisteredService",
"clientId": "test",
"serviceId" : "http://test",
"name": "TEST",
"id": 1000,
"scopes" : [ "java.util.HashSet", 
[ "profile", "email", "offline_access" ]
],
"idTokenSigningAlg": "ES256",
"userInfoSigningAlg": "ES256"
}
```
You'll have the following error when you'll try to get the id_token (or the signed userinfo):
```
2020-02-16 19:18:52,673 DEBUG …
```

Add Elliptic Curve support for OIDC token signature

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/attribute/DefaultAttributeDefinitionStore.java
core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/principal/resolvers/PersonDirectoryPrincipalResolver.java

This is a minor cleanup you suggested, although if you think we should get rid of the PersonAttributeRetriever altogether, let me know.

removed unnecessary synchronized method

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/principal/resolvers/PersonDirectoryPrincipalResolver.java
core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/AllAuthenticationTestsSuite.java
core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/principal/resolvers/PersonDirectoryPrincipalResolverConcurrencyTests.java
core/cas-server-core-authentication-api/src/test/resources/ConcurrencyPersonAttributeDao.groovy

We don't really know of a reason calls to retrieve person attributes need to be synchronized so this removes the synchronization. This adds a test that tries run lots of retrievals in parallel to see if there are any concurrency errors. I copied the assertConcurrent method from junit 4 wiki but maybe there is version in a library somewhere.

back out synchronization in PersonDirectoryPrincipalResolver

---

core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/DefaultTicketCatalog.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/BaseTicketRegistryTests.java
support/cas-server-support-ehcache-monitor/src/test/java/org/apereo/cas/monitor/EhCacheHealthIndicatorTests.java

When using the simple MFA + the Hazelcast tickets registry, I noticed it didn't work because there was an issue with the `DefaultTicketCatalog`.
Here is the fix.

fix DefaultTicketCatalog

---

api/cas-server-core-api-configuration-model/src/main/resources/META-INF/additional-spring-configuration-metadata.json

Typos in additional-spring-configuration-metadata.json - seplication -> replication
Also remove "deprecated: true" from another entry because Intellij said it was bad and it appears out of place (i.e. deprecation block implies deprecated) so I assume it doesn't need to be there.

fix some typos in configuration metadata JSON

---

docs/cas-server-documentation/webflow/Webflow-Customization-Interrupt.md

Current documentation for custom Authentication Interrupt is not working.
Declare @Bean for "InterruptInquirer" disable "InterruptInquiryExecutionPlan" bean.
If custom "InterruptInquirer" is not registered in "ExecutionPlanConfigurer" nothing happen.

[docs] Update custom Authentication Interrupt documentation

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/oidc/OidcProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/discovery/OidcServerDiscoverySettings.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/discovery/OidcServerDiscoverySettingsFactory.java

Hello Misagh,
The OIDC discovery endpoint from CAS doesn't currently support the [code_challenge_methods_supported](https://tools.ietf.org/html/rfc8414#section-2) parameter.
This pull request adds support for this metadata parameter in the discovery endpoint.
Regards,
Julien

OIDC Discovery : code_challenge_methods_supported support

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/logout/LogoutProperties.java
support/cas-server-support-actions/src/main/java/org/apereo/cas/web/flow/logout/LogoutAction.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/web/controllers/logout/OidcLogoutEndpointController.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/OidcTestsSuite.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/AbstractOidcTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/web/controllers/OidcLogoutEndpointControllerTests.java

Hello Misagh,
The OIDC RP-initiated logout [describe here](https://openid.net/specs/openid-connect-session-1_0.html#RPLogout) seems broken in CAS if you're using any of the specified parameters.
This pull request fixes the oidc logout and adds unit tests to avoid any future problem. the following bugs are fixed:
The state parameter is never returned:
```
> GET /cas/oidc/logout?state=fefefe HTTP/1.1
< Location: http://cas.example.org:8080/cas/logout?state
```
If you're not setting the following property in your cas.properties:
```
cas.logout.redirectParameter=service
```
When you're sending a valid id token, the following error will appears:
```
2020-02-21 11:53:16,056 DEBUG [org.apereo.cas.logout.slo.DefaultSingleLogoutServiceLogoutUrlBuilder] - <Logout request will be sent to …
```

Fix OIDC logout

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/ldap/AbstractLdapProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties-Common.md
gradle.properties
support/cas-server-support-aup-ldap/src/main/java/org/apereo/cas/aup/LdapAcceptableUsagePolicyRepository.java
support/cas-server-support-consent-ldap/src/main/java/org/apereo/cas/config/CasConsentLdapConfiguration.java
support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/util/LdapUtils.java
support/cas-server-support-ldap-service-registry/src/main/java/org/apereo/cas/adaptors/ldap/services/config/LdapServiceRegistryConfiguration.java
support/cas-server-support-ldap/src/main/java/org/apereo/cas/authentication/LdapPasswordSynchronizationAuthenticationPostProcessor.java
support/cas-server-support-ldap/src/test/java/org/apereo/cas/AllLdapTestsSuite.java
support/cas-server-support-ldap/src/test/java/org/apereo/cas/authentication/ActiveDirectorySamAccountNameLdapAuthenticationHandlerTests.java
support/cas-server-support-ldap/src/test/java/org/apereo/cas/authentication/ActiveDirectoryUPNLdapAuthenticationHandlerTests.java
support/cas-server-support-person-directory/src/main/java/org/apereo/cas/config/CasPersonDirectoryConfiguration.java
support/cas-server-support-pm-ldap/src/main/java/org/apereo/cas/pm/LdapPasswordManagementService.java
support/cas-server-support-spnego-webflow/src/main/java/org/apereo/cas/web/flow/config/SpnegoWebflowActionsConfiguration.java
support/cas-server-support-surrogate-authentication-ldap/src/main/java/org/apereo/cas/config/SurrogateLdapAuthenticationConfiguration.java
webapp/cas-server-webapp-config/src/main/java/org/apereo/cas/web/security/authentication/MonitorEndpointLdapAuthenticationProvider.java

Remove the OpenActivator and ClosePassivator in favor of a disablePooling flag.
LdapUtils#newLdaptiveConnectionFactory inspects this flag and produces an appropriate connection factory.
Renamed classes containing 'Jndi' in the name, provider doesn't exist anymore.

Upgrade ldaptive to v2.0.0-RC3

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/validator/token/OAuth20RefreshTokenGrantTypeTokenRequestValidator.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenAuthorizationCodeGrantRequestExtractor.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenRefreshTokenGrantRequestExtractor.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/validator/token/OAuth20RefreshTokenGrantTypeTokenRequestValidatorTests.java

Hello Misagh,
The refresh token request in CAS is not working with client_secret_basic authentication. The following error appears:
```
2020-03-03 13:37:58,486 ERROR [org.apereo.cas.util.HttpRequestUtils] - <Missing request parameter: [client_id]>
```
[According to the OAuth 2.0 specification](https://tools.ietf.org/html/rfc6749#section-2.3): The authorization server MUST support the HTTP Basic authentication scheme for authenticating clients that were issued a client password and alternatively, the authorization server MAY support including the client credentials in the request-body using the following parameters: client_id & client_secret.
This pull request fixes the problem and adds client_secret_basic authentication support for the refresh token requests.
Let me know if you need any …

Backport: Add client_secret_basic authentication support for refresh token request

---

support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/pwdupdateform.html

The ```screen.pm.password.policyViolation``` message was always displaying and calling "hide()" on it wasn't working. I think the ```d-flex``` class might have been making it stay visible at all times but this changes the styles to match the ```screen.pm.password.confirmMismatch``` message right below it.

fix css so password policy requirement hide() will work

---

support/cas-server-support-jpa-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/JpaTicketRegistry.java

I have a special use case where I chain a JWT authentication and a SAML IdP-initiated call.
This leads to a "transaction error":
```java
ERROR [org.apereo.cas.web.flow.login.CreateTicketGrantingTicketAction] - <Executing an update/delete query>
javax.persistence.TransactionRequiredException: Executing an update/delete query
at org.hibernate.internal.AbstractSharedSessionContract.checkTransactionNeededForUpdateOperation(AbstractSharedSessionContract.java:409) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1601) ~[hibernate-core-5.4.9.Final.jar:5.4.9.Final]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMet …
```

Enable transaction on deleteTicket

---

core/cas-server-core-audit-api/src/main/java/org/apereo/cas/audit/spi/entity/AuditTrailEntity.java

When I use the JDBC audit ( `cas-server-support-audit-jdbc`) and the `cas.audit.includeValidationAssertion: true` property, I have SQL errors as the resource column (`AUD_RESOURCE`) is too small (255 characters).
I propose to increase the size of this column to 2048. As the user (`AUD_USER`) and the action (`AUD_ACTION`) columns are also linked by the trimming mechanism ( `cas.audit.jdbc.columnLength` property), I propose to increase them as well.

Extend the length of the JDBC audit columns

---

support/cas-server-support-token-authentication/build.gradle
support/cas-server-support-token-webflow/build.gradle

I may be missing the point but I don't understand why the `cas-server-support-token-core` dependency is used for the JWT authentication (`cas-server-support-token-webflow` and `cas-server-support-authentication` dependencies). We don't need the JWT generation mechanism, do we?
Waiting for approval to back port to the 6.1.x branch.

Remove JWT generation in JWT authentication

---

webapp/cas-server-webapp-resources/src/main/resources/application.properties

We upgraded our embedded jetty CAS installation to 6.1.5 and when we deployed the service behind a load balancer we would see 302 responses for all calls that passed through the load balancer. After debugging we found that the `X-Forwarded-Proto: https` header being passed by our LB was triggering the 302.
To fix the issue we added `server.forward-headers-strategy=NATIVE` to our `application.properties`. This PR is meant to match the prior config that had `server.use-forward-headers=true`.
See https://github.com/apereo/cas/commit/fc9e7653aeb0cbb4b309bfab75712453e57db61e#diff-4b4050db4930afc20ddc6fda1aae1c13L14 for original change that introduced the problem.

[bugfix] Prevent infinite 302 when embedded jetty and behind LB

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jDelegatedAuthenticationProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java

I noticed CAS configuration does not support customizing the provider of the Github SSO delegate but pac4j's client implementation does. I used the Google/Facebook client configuration as a blueprint to add the support.
What's missing:
1) No tests done, yet. I first have to understand how to get it running in my CAS overlay project.
2) I did not find any tests for providers like FB and Google. Or did I just miss them?

Pac4j: Allow configuring the scope for delegated Github SSO

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/mongo/MongoAuthenticationProperties.java

Some times ago, we discuss an issue about the Mongo authentication defaults managed by pac4j. See: https://github.com/apereo/cas/pull/4404#issuecomment-549442367
This is the PR to fix the problem. I thought I could use "id,username,password" as the default `attributes` value but it's rejected by pac4j as these attributes are already retrieved. The empty string does the job.

Fix default Mongo authn config

---

docs/cas-server-documentation/protocol/REST-Protocol.md

Documentation of REST protocol erroneously says that "400 Bad Request" is returned if incorrect credentials are sent.
Instead, "401 Unauthorized" is returned in this case, which is much more logical.
See org.apereo.cas.support.rest.resources.TicketGrantingTicketResource
See org.apereo.cas.support.rest.resources.RestResourceUtils.createResponseEntityForAuthnFailure(...)

doc: TGT REST API returns 401 on incorrect credentials

---

support/cas-server-support-saml-idp-core/src/main/java/org/apereo/cas/support/saml/idp/metadata/generator/FileSystemSamlIdPMetadataGenerator.java

By changing the `writeCertificateAndKey` method visibility (`private` ->  `protected`).

Open up a little the FileSystemSamlIdPMetadataGenerator

---

support/cas-server-support-trusted-mfa-couchdb/src/main/java/org/apereo/cas/config/CouchDbMultifactorAuthenticationTrustConfiguration.java

Trusted MFA storage in CouchDB is broken, evidently since the design document is not created. To fix this, I updated CouchDbMultifactorAuthenticationTrustConfiguration.java to call `initStandardDesignDocument` on the repository object before returning it.
It appears that CouchDbMultifactorAuthenticationTrustStorageTests.java calls `initStandardDesignDocument` on the repository, leading to the impression that this works as intended.

Trusted mfa couchdb fix

---

support/cas-server-support-electrofence/src/main/java/org/apereo/cas/impl/calcs/DateTimeAuthenticationRequestRiskCalculator.java

When I was working in another pull request, I found that this unit test sometimes failed, which was supposed to be caused by the event counting bug in `DateTimeAuthenticationRequestRiskCalculator`
https://github.com/apereo/cas/blob/0701abd2a03c9fc41e44575785e61b54d321029f/support/cas-server-support-electrofence/src/test/java/org/apereo/cas/impl/calcs/DateTimeAuthenticationRequestRiskCalculatorTests.java#L30-L37
It seems like it doesn't take into account the possibility that `hoursFromNow` could be smaller than `hoursBeforeNow`.
https://github.com/apereo/cas/blob/0701abd2a03c9fc41e44575785e61b54d321029f/support/cas-server-support-electrofence/src/main/java/org/apereo/cas/impl/calcs/DateTimeAuthenticationRequestRiskCalculator.java#L44-L53
By the way, I think there is no need to add or …

Fix event counting bug in DateTimeAuthenticationRequestRiskCalculator

---

build.gradle

pull-parser conflicts with tomcat, tomcat refuses to load cas when pull-parser is included in war. I have to exclude pull-parser from the output war to make tomcat start.
This dependency is introduced by org.dom4j:dom4j:2.1.3 via :support:cas-server-support-jpa-hibernate

exclude pull-parser from dependency

---

core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/InvalidCookieException.java
core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/gen/CookieRetrievingCookieGenerator.java
core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/mgmr/DefaultCasCookieValueManager.java
core/cas-server-core-cookie-api/src/test/java/org/apereo/cas/web/support/DefaultCasCookieValueManagerTests.java

I was seeing the CAS TGC cookie get deleted by CAS and it wasn't clear why. I believe it was due to CAS cookies being `pinToSession=true` (which guards against client ip changes) but the "client" ip was changing due to a faulty load balancer setup. 
I suspect my problem has to do with me setting up CAS behind AWS ALB and then a Kubernetes nginx ingress controller and the ingress controller isn't configured to respect the headers set by ALB (the `use-forwarded-headers` setting) and it is either not setting its own headers or the traffic is being round-robin'ed to nginx on more than one node in the kubernetes cluster and so the X-Forwarded-For header is changing. 
I can fix my setup but hopefully this extra logging will help someone catch on to the reason any cookies are being deleted …

log warning when cookie is invalidated

---

core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/expiration/ThrottledUseAndTimeoutExpirationPolicy.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/expiration/ThrottledUseAndTimeoutExpirationPolicyTests.java

After enabling TGT's throttling policy in our test environment, the SERVICE_TICKET_VALIDATE_FAILED event occurs frequently on the server. The configuration we used for this policy is below.
```
cas.ticket.tgt.throttledTimeout.timeToKillInSeconds=28800
cas.ticket.tgt.throttledTimeout.timeInBetweenUsesInSeconds=1
```
After trawling through the logs, the reason is that the ST was removed from the cache (redis) due to the TGT expiration.
```
2020-04-15 13:28:15,897 DEBUG [org.apereo.cas.services.RegisteredServiceAccessStrategyUtils] - Current authentication via ticket [TGT-717-********************************************************ZDJyFo0PCWYxxxxx-xxxxx-02] allows service [http://oa.example.org/login] to participate in the existing SSO session 
2020-04-15 13:28:15,898 TRACE …
```

improve ticket expiration policies - throttled timeout

---

docs/cas-server-documentation/installation/OAuth-OpenId-Authentication.md
docs/cas-server-documentation/installation/OIDC-Authentication.md

Update HTTP basic auth requirement for introspect and revoke endpoint. I have to read the source code directly to figure the authentication required.

Fix openid and oauth doc

---

support/cas-server-support-jdbc-drivers/src/main/java/org/apereo/cas/JdbcServletContextListener.java
support/cas-server-support-jdbc-drivers/src/test/java/org/apereo/cas/AllTestsSuite.java
support/cas-server-support-jdbc-drivers/src/test/java/org/apereo/cas/JdbcServletContextListenerTests.java

PR #4803 rewritten. This should really work now. I realized I can simply use `@WebListener` annoation to add ServletContextListener.
We should unregister JDBC drivers at shutdown instead of relying tomcat to forcefully deregister it. (This feature may not exist in other servlet servers.)
Tomcat throws this message
`SEVERE: A web application registered the JDBC driver [XXXXX] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.`
when a JDBC driver deregisters forcefully.
Also, for unknown reason quartz thread shut down is asynchronous and I have to put 5 sec wait to wait these threads to shut down

properly clean up resources at application shutdown

---

core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/junit/EnabledIfPortOpenCondition.java

CAS only runs some tests if something is listening on the port that the test will connect to. This doesn't seem to work on windows (at least for me, on two different computers hitting services on docker for windows). I tried various things to get the port available check to work but I was unsuccessful. This allows the checks to be bypassed with and environment variable. I think environment variable is easier than java system property b/c it doesn't require changing any existing scripts if running from command line. 
I thought about optionally having the IGNORE_PORT_CHECK allow specifying a list of ports to ignore the check for but the annotation takes a list of ports and it starts to get complicated coding that check when it probably isn't worth it. (e.g. if you only ignore the check for …

Add a way to bypass unit test port available check

---

support/cas-server-support-oauth-uma/src/main/java/org/apereo/cas/config/CasOAuthUmaConfiguration.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20ThrottleConfiguration.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java

fixing pac4j update from 4.0.0-RC2 to 4.0.0 in release 6.1.6 which breaks default behavior of cas	
see warning https://www.pac4j.org/docs/authorizers.html

pac4j update from 4.0.0-RC2 to 4.0.0 in release 6.1.6 breaks default behavior

---

core/cas-server-core-monitor/src/main/java/org/apereo/cas/monitor/AbstractPoolHealthIndicator.java
core/cas-server-core-monitor/src/test/java/org/apereo/cas/monitor/PoolHealthIndicatorTests.java
support/cas-server-support-consent-ldap/src/main/java/org/apereo/cas/consent/LdapConsentRepository.java
support/cas-server-support-ldap-monitor/src/main/java/org/apereo/cas/monitor/PooledLdapConnectionFactoryHealthIndicator.java
support/cas-server-support-ldap-monitor/src/main/java/org/apereo/cas/monitor/config/LdapMonitorConfiguration.java
support/cas-server-support-ldap-service-registry/src/main/java/org/apereo/cas/adaptors/ldap/services/LdapServiceRegistry.java
support/cas-server-support-ldap/src/main/java/org/apereo/cas/authentication/LdapAuthenticationHandler.java
support/cas-server-support-ldap/src/main/java/org/apereo/cas/authentication/LdapPasswordSynchronizationAuthenticationPostProcessor.java
support/cas-server-support-ldap/src/main/java/org/apereo/cas/config/LdapAuthenticationConfiguration.java
support/cas-server-support-ldap/src/main/java/org/apereo/cas/config/LdapPasswordSynchronizationConfiguration.java
support/cas-server-support-spnego-webflow/src/main/java/org/apereo/cas/web/flow/client/LdapSpnegoKnownClientSystemsFilterAction.java
support/cas-server-support-surrogate-authentication-ldap/src/main/java/org/apereo/cas/authentication/surrogate/SurrogateLdapAuthenticationService.java

Ref: #4804
Now I split this PR into smaller pieces. This should be the most straightforward one: declaring various beans as DisposableBean, and tracking prototype DisposableBean in DestroyPrototypeBeansPostProcessor for final disposal.
Unit test added for DestroyPrototypeBeansPostProcessor.

Fix ldap connection pool shut down - phase 1

---

support/cas-server-support-person-directory/src/main/java/org/apereo/cas/config/CasPersonDirectoryConfiguration.java

Adds binary attribute handling to LDAP Attribute Repositories. Currently binary attributes only works with LDAP Authentication repositories.  Note needs a change on the Person Directory side as well: https://github.com/apereo/person-directory/pull/171

Add Binary Attribute Handling to LDAP Repositories

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/authentication/passwordsync/PasswordSynchronizationProperties.java
ci/tests/ldap/reset-ad-server.sh
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-ldap/src/main/java/org/apereo/cas/config/LdapPasswordSynchronizationConfiguration.java

I was getting a bean in process of creation or bean cycle error when running in an overlay. This moves bean creation inside of lambda function which was first attempt to avoid the error. That didn't help so I had to turn set proxyBeanMethods=true. The latter is probably sufficient and I can back out moving the bean creation into the lambda (which is little messier since it can't leverage sneakythrows). I was only able to recreate this error in the overlay.

fix bean creation error for LDAP password sync

---

support/cas-server-support-validation-core/src/main/java/org/apereo/cas/web/AbstractServiceValidateController.java

The javadoc comment says `augmentSuccessViewModelObjects()` method defined in `AbstractServiceValidateController` class is provided as a way for extension of the controllers, but `static` modifier of the method prevents developers from overriding it. I believe this modifier was added by accident.

Remove static modifier from augmentSuccessViewModelObjects()

---

support/cas-server-support-ldap-monitor/src/main/java/org/apereo/cas/monitor/config/LdapMonitorConfiguration.java
support/cas-server-support-saml-idp-metadata/src/main/java/org/apereo/cas/support/saml/services/idp/metadata/cache/resolver/JsonResourceMetadataResolver.java
support/cas-server-support-saml-idp-metadata/src/test/java/org/apereo/cas/support/saml/services/idp/metadata/cache/resolver/JsonResourceMetadataResolverTests.java

There is another bean creation error in LdapMonitorConfiguration. I am turning on proxyBeanMethods similar to the last fix. 
Also, the JsonResourceMetadataResolver is blowing up on `file:/etc/cas/saml` which is the default value for the metadata directory. I added a test that just creates the object and it would fail with the changes to the JsonResourceMetadataResolver.

fix bean creation error and fix saml metadata resolver

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/oauth/OAuthProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/oauth/Pac4jOAuth20ClientProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DefaultDelegatedClientFactory.java

Hi,
I was in need to change the `response_type` parameter when CAS delegates to an OAuth2 IdP, but it defaults to `code`. If I add this custom value to `cas.authn.pac4j.oauth2[0].customParams.response_type`, the request is made with an array instead of overwriting it.
I've checked the pac4j source and [opened an issue](https://github.com/pac4j/pac4j/issues/1583), which resulted in [this commit](https://github.com/pac4j/pac4j/commit/9ef4f5186e971cc14adc59544867e4a18feff560). After that, I've found the configuration for this value, and I tried to change it through the configuration files, which you can see in the diff for this PR.
This is resulting in an unexpected error in the report from `./gradlew check` , saying that the value should comply a certain RegEx:
```
Name 'response_type' must …
```

Delegated OAuth2: reponse_type is static

---

core/cas-server-core-web-api/src/main/java/org/apereo/cas/web/support/filters/ResponseHeadersEnforcementFilter.java

Static resources are never cached because the regex pattern never matches

fix cache control static resources pattern

---

gradle.properties

Update pac4j to 4.0.2.
This version fix this ClassCastException which occur in CAS : https://github.com/pac4j/pac4j/commit/ca250474deea8d23585b3574eaf8331c04f953b3

update pac4j to 4.0.2

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/services/ServiceRegistryProperties.java
api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/ServiceRegistry.java
api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/ServicesManager.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/AbstractServicesManager.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/ChainingServicesManager.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/DefaultServicesManager.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/domain/DefaultDomainAwareServicesManager.java
core/cas-server-core-services/src/main/java/org/apereo/cas/config/CasCoreServicesConfiguration.java
core/cas-server-core-services/src/test/java/org/apereo/cas/authentication/principal/SimpleWebApplicationServiceImplTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/AbstractServiceRegistryTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/AbstractServicesManagerTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/ChainingServicesManagerTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/DefaultDomainAwareServicesManagerTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/DefaultServicesManagerByEnvironmentTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/DefaultServicesManagerTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/RegisteredServiceAuthenticationHandlerResolverTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/RegisteredServiceAuthenticationPolicyResolverTests.java
core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/MockWebServer.java
core/cas-server-core-web/src/test/java/org/apereo/cas/web/RegisteredServiceResponseHeadersEnforcementFilterTests.java
core/cas-server-core-webflow/src/test/java/org/apereo/cas/web/flow/authentication/RequiredAuthenticationHandlersSingleSignOnParticipationStrategyTests.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/LogoutActionTests.java
support/cas-server-support-openid/src/test/java/org/apereo/cas/support/openid/authentication/principal/OpenIdServiceTests.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/SamlRegisteredServiceTests.java
support/cas-server-support-saml/src/test/java/org/apereo/cas/support/saml/authentication/principal/SamlServiceTests.java
support/cas-server-support-saml/src/test/java/org/apereo/cas/support/saml/web/view/Saml10SuccessResponseViewTests.java

This pull request fixes the fact that find operations of the ServiceRegistry is not fully utilized by the ServicesManager instead it does its own filtering logic.

ServicesManager should use ServiceRegistry for find operations

---

support/cas-server-support-otp-mfa-core/src/main/java/org/apereo/cas/otp/repository/token/OneTimeTokenRepositoryCleaner.java
support/cas-server-support-reports-core/src/main/java/org/apereo/cas/web/report/RegisteredAuthnHandlersEndpoint.java
support/cas-server-support-reports/src/main/java/org/apereo/cas/config/CasReportsConfiguration.java
support/cas-server-support-reports/src/test/java/org/apereo/cas/AllCasReportsTestsSuite.java
support/cas-server-support-reports/src/test/java/org/apereo/cas/web/report/AbstractCasEndpointTests.java
support/cas-server-support-reports/src/test/java/org/apereo/cas/web/report/RegisteredAuthnHandlersEndpointTests.java
support/cas-server-support-reports/src/test/java/org/apereo/cas/web/report/RegisteredAuthnHandlersTests.java
support/cas-server-support-syncope-authentication/src/main/java/org/apereo/cas/config/SyncopeAuthenticationConfiguration.java

Similar to the existing `/registeredServices`, a new Endpoint to inspect the configured Authentication Handlers.

Adding new Spring Boot Actuator Endpoint: /registeredAuthnHandlers

---

core/cas-server-core-authentication-mfa-api/src/main/java/org/apereo/cas/authentication/trigger/RestEndpointMultifactorAuthenticationTrigger.java
core/cas-server-core-authentication-mfa-api/src/test/java/org/apereo/cas/authentication/mfa/trigger/RestEndpointMultifactorAuthenticationTriggerTests.java
core/cas-server-core-webflow-mfa/src/main/java/org/apereo/cas/web/flow/config/CasMultifactorAuthenticationWebflowConfiguration.java

- Creating a new RestTemplate on every login is expensive.
- This way the RestTemplate can be customized if necessary
- If Jackson XML is on the classpath, the request body would be sent as XML instead of JSON

Improve RestEndpointMultifactorAuthenticationTrigger

---

core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasCoreTicketCatalogConfiguration.java

The JpaTicketRegistry tries to traverse ticketGrantingTicket attribute using HQL. TransientSessionTicket has always ticketGrantingTicket constant, and is implemented as a getter returning null and therefore does not have HQL equivalent. It could be changed in JpaTicketRegistryTicketCatalogConfiguration as the bug seems to be just in JPA registry but the core package seems more adecuate.

Add exclude from cascade in TransientSessionTicket

---

support/cas-server-support-spnego/src/main/java/org/apereo/cas/support/spnego/authentication/principal/SpnegoCredential.java

Backport [PR 4897](https://github.com/apereo/cas/pull/4897)

Exclude initToken and nextToken from SpnegoCredential.toString

---

core/cas-server-core-audit/src/main/java/org/apereo/cas/audit/spi/config/CasCoreAuditConfiguration.java

The latest implementation of  `ClientInfoThreadLocalFilter` calls internally `getParameter("geolocation")` on `HttpServletRequest` **BEFORE**  Spring Boot's  `CharacterEncodingFilter` assigns the correct character encoding to the request. Therefore the former filter decodes the POSTed data using wrong character encoding and the result is cached into the request for later processing. 
This is a critical bug because the username and the password in the login form will be broken if they contain any Unicode characters beyond simple US-ASCII letters. I believe we should change the order of `ClientInfoThreadLocalFilter` with +1 and keep the highest order only for `CharacterEncodingFilter`.

Move ClientInfoThreadLocalFilter after CharacterEncodingFilter

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/cipher/AbstractCipherExecutor.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/token/OidcRegisteredServiceJwtAccessTokenCipherExecutor.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/AbstractOidcTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/authn/OidcAccessTokenAuthenticatorTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/authn/OidcClientConfigurationAccessTokenAuthenticatorTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/token/OidcIdTokenGeneratorServiceTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/token/OidcJwtAccessTokenEncoderTests.java
support/cas-server-support-token-core-api/src/main/java/org/apereo/cas/token/JwtBuilder.java
support/cas-server-support-token-core-api/src/main/java/org/apereo/cas/token/JwtTokenTicketBuilder.java

This PR allows to:
* set JWT access token's issuer as `cas.authn.oidc.issuer`
* use the same signing algorithm as specified for the configured JsonWeb keystore.

Ensure OIDC uses appropriate settings for issuer and JwtBuilder

---

support/cas-server-support-oidc-core/src/main/java/org/apereo/cas/oidc/claims/OidcAddressScopeAttributeReleasePolicy.java
support/cas-server-support-oidc-core/src/main/java/org/apereo/cas/oidc/claims/OidcEmailScopeAttributeReleasePolicy.java
support/cas-server-support-oidc-core/src/main/java/org/apereo/cas/oidc/claims/OidcPhoneScopeAttributeReleasePolicy.java
support/cas-server-support-oidc-core/src/main/java/org/apereo/cas/oidc/claims/OidcProfileScopeAttributeReleasePolicy.java
support/cas-server-support-syncope-authentication/src/main/java/org/apereo/cas/syncope/authentication/SyncopeAuthenticationHandler.java
support/cas-server-support-syncope-authentication/src/test/java/org/apereo/cas/syncope/authentication/SyncopeAuthenticationHandlerTests.java

* more thorough check for `null` values
* add derived and virtual attributes, not just plain
* generate attribute names as `syncopeUserAttr_userId` rather than `syncopeUserAttruserId`.

Small enhancements to Syncope auth

---

support/cas-server-support-saml-idp-core/src/main/java/org/apereo/cas/support/saml/idp/metadata/locator/AbstractSamlIdPMetadataLocator.java

This PR is:
1. increasing cache's maximum size from 1 to 100 (otherwise, when having > 1 keys to look up, every get is likely resulting into a miss)
2. applying the advice in https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Cache.java#L133-L134

Making effective SAML IdP Metadata caching

---

ci/tests/perf/EvalJMeterTestResults.java
ci/tests/perf/perftests-jmeter.sh

The CAS output from JMeter tests was > 200MB so this dumps log after startup and before tests, then greps for WARN|ERROR|FATAL after running tests.
Also not sure if the results were being processed so added some more output

Put jmeter CAS logs in file

---

core/cas-server-core-services-authentication/src/main/java/org/apereo/cas/authentication/principal/DefaultResponse.java
core/cas-server-core-services/src/test/java/org/apereo/cas/authentication/principal/ResponseTests.java

Fixed an error in building urlRedirect.
When url like "http://localhost:8080/foo#hello?test=boo", we expect "http://localhost:8080/foo?ticket=foobar#hello?test=boo".

Fixed an error in building urlRedirect

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/callback/OAuth20AuthorizationCodeAuthorizationResponseBuilder.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20AuthorizeEndpointControllerTests.java

It looked like the newer code was passing all the parameters in a map to the ModelAndView, so this keeps that code but also avoids adding blank state or nonce parameters like the older code did. The previous code was adding multiple `code` parameters in all cases and multiple `state` parameters if it was not blank. It was also adding a single blank `nonce` parameter and a single blank `state` parameter if it was blank.

redirect from /oidc/authorize contains duplicate parameters (code and sometimes state)

---

core/cas-server-core-logout-api/src/main/java/org/apereo/cas/logout/DefaultLogoutExecutionPlan.java
etc/loadtests/jmeter/CAS_CAS.jmx

I was using the JMeter load test against a cluster and I wanted to have the service ticket validation requests not use the same cookies as the other requests so it better simulated an application making the call with CAS client. If it uses cookies then load balancer sticky session cookies will keep ticket validation on the same server that generated the ticket and that might not be the case in an active/active cluster. I tried various ways to make JMeter not send cookies on the request but I was unsuccessful and ended up doing the service validate call in a groovy script. 
During the load test I saw some failures on logout due to ConcurrentModificationException and this tries to fix by moving the collection sort to the register calls instead of the get methods. The two stack traces I saw …

Update jmeter perf tests to not use cookies on serviceValidate calls

---

support/cas-server-support-thymeleaf/src/main/resources/templates/casLoginMessageView.html

Changed design structure for casLoginMessageView.html
First image is Before, second image is after change.
The new layout more corresponds with layout for pwdupdateform.html

Changed design for casLoginMessageView.html

---

core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/mgmr/DefaultCasCookieValueManager.java
core/cas-server-core-cookie-api/src/test/java/org/apereo/cas/web/support/DefaultCasCookieValueManagerTests.java

This tries to address error observed during deployment when users bounced to new server and session info containing original client ip of session was lost. Indicates session replication probably not working but might as well get exception with message rather than NPE. One could make case that this is not user's fault and we should just let them use the cookie without the IP check if the server no longer knows what it was, but that is not what this change does.

Check for null client info from thread local to avoid NPE

---

support/cas-server-support-saml-idp-core/src/main/java/org/apereo/cas/support/saml/SamlIdPUtils.java
support/cas-server-support-saml-idp-core/src/main/java/org/apereo/cas/support/saml/services/idp/metadata/SamlRegisteredServiceServiceProviderMetadataFacade.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/idp/metadata/SamlRegisteredServiceServiceProviderMetadataFacadeTests.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/util/SamlIdPUtilsTests.java

The code that validates that the AssertionConsumerService location in an unsigned SAML request matches the location specified in the SP metadata is checking only the first ACS location defined in the metadata. This fails to handle the case of SPs that define multiple ACS locations (for example https://www.testshib.org/Shibboleth.sso/SAML2/POST vs. https://sp.testshib.org/Shibboleth.sso/SAML2/POST). Result is that valid requests are rejected.
Added a getAssertionConsumerServiceLocations() method to facilitate checking against all defined ACS locations.

Fix problem with SP metadata that defines multiple ACS endpoints

---

docs/cas-server-documentation/configuration/Configuration-Properties.md
webapp/cas-server-webapp-init-tomcat/src/main/java/org/apereo/cas/tomcat/CasTomcatServletWebServerFactory.java

The Tomcat cluster sending and receiving settings are applicable to CLOUD member discovery, even though many of the settings are defaults so it worked without them. This is mostly moving the code up in the method. 
The `cluster.setChannel(groupChannel);`  call was only being called in the static members for loop and in the CLOUD block. 
It doesn't need to be called in loop and wouldn't be called at all if not using CLOUD or at least one static member (e.g. using multicast). This change moves the call to the bottom of the method so it is always called once. 
Updated documentation on CLOUD discovery.

Update tomcat clustering config

---

.github/renovate.json
gradle.properties

I noticed the following message during a build:
```
> Task :support:cas-server-support-saml-core-api:compileJava UP-TO-DATE
POM relocation to an other version number is not fully supported in Gradle : xml-apis:xml-apis:2.0.2 relocated to xml-apis:xml-apis:1.0.b2.
Please update your dependency to directly use the correct version 'xml-apis:xml-apis:1.0.b2'.
Resolution will only pick dependencies of the relocated element.  Artifacts and other metadata will be ignored.
```
It looks like xml-apis 2.0.2 is from 2005 and maps to 1.0.b2, but 1.4.01 is from 2011 so this updates version to newest version.

update xml-apis to 1.4.01, 2.0.2 is redirected to 1.0.b2

---

docs/cas-server-documentation/configuration/Configuration-Properties.md

Added some more verbiage under X509 LDAP section since most of the X509 LDAP usage is probably retrieving attributes from LDAP using X509 principal rather than fetching CRLs from LDAP.

x509 documentation update

---

docs/cas-server-documentation/configuration/Configuration-Properties.md
docs/cas-server-documentation/mfa/FIDO-U2F-Authentication.md

There's already a note on the cleaner process, but explicitly mention the default interval of 30 days (it's covered in the generic Configuration-Properties doc), but it seems important enough to mention explicitly.

Explicitly mention U2F token expiry in U2F docs

---

core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/MockWebServer.java
gradle.properties
gradle/dependencies.gradle
support/cas-server-support-aup-webflow/src/test/java/org/apereo/cas/aup/DefaultAcceptableUsagePolicyRepositoryTests.java
support/cas-server-support-azuread-authentication/build.gradle
support/cas-server-support-events-influxdb/build.gradle
support/cas-server-support-influxdb-core/build.gradle
support/cas-server-support-metrics/build.gradle
support/cas-server-support-openid/src/test/java/org/apereo/cas/support/openid/authentication/principal/OpenIdServiceTests.java

I am trying to make sure kotlin dependencies are at > 1.4.0 to make CVE-2020-15824 go away. Kotlin is used by person-directory but only one azure related class:
```
org.jetbrains.kotlin:kotlin-stdlib:1.3.72
+--- com.squareup.okhttp3:okhttp:4.8.0
|    +--- com.squareup.retrofit2:retrofit:2.9.0 (requested com.squareup.okhttp3:okhttp:3.14.9)
|    |    +--- org.apereo.service.persondir:person-directory-impl:2.0.0
|    |    |    \--- runtimeClasspath
```
This PR puts the retrofit2 and okhttp3 into their own library and includes it for the azure module that uses that person-directory class that needs them and it includes that group whereever influxdb library is used (they used to be part of that library but I removed so as not to duplicate that block).
Kotlin is needed by jackson but only …

update kotlin version

---

support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/VerifyPasswordResetRequestAction.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/pm/web/flow/actions/VerifyPasswordResetRequestActionTests.java

Hello Misagh,
When you're using the password reset feature in CAS, you will receive a mail or a sms with a reset link associated with a token in the registry.
Unfortunately, in the versions 6.2 and 6.3, if the link has already been used or has expired and doesn't appears in the registry, you'll have the following error in the web page:
```
Error: Exception thrown executing org.apereo.cas.pm.web.flow.actions.VerifyPasswordResetRequestAction@4af8ff3 in state 'verifyPasswordResetRequest' of flow 'pswdreset' -- action execution attributes were 'map[[empty]]'
```
It's because the method "getTicket" from "centralAuthenticationService" raise an exception if the ticket doesn't exists instead of provide a null response.
Here a little fix to solve the problem.
Regards,
Julien

Backport : Fix Password Reset Request Verification

---

api/cas-server-core-api-webflow/src/main/java/org/apereo/cas/web/flow/CasWebflowConstants.java

`The state 'gatewayRequestCheck'.` should be  `The state 'generateServiceTicket'.`, thanks

Fix code comment typo in CasWebflowConstants

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenAuthorizationCodeGrantRequestExtractor.java

check if the client id is the same when getting code and change token, if it's not the same, we should not allow access token to be given to the application, as the later client id owner can intercept other application's code and get the access token which can access to other application's resource.

check if the client id is same - get code and at

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/ehcache/Ehcache3Properties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
docs/cas-server-documentation/ticketing/Ehcache-Ticket-Registry.md
support/cas-server-support-ehcache3-ticket-registry/src/main/java/org/apereo/cas/config/Ehcache3TicketRegistryConfiguration.java

Docs say that if using Ehcache3 without terracotta "the registry should survive restarts due to the disk persistence"
However as the persistent option is not set on the disk resource pool the disk files are deleted on shutdown.
This pull request just sets the persistent option to true

Make ehcache3 disk pool persistent

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/replication/SessionReplicationProperties.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20AuthorizeEndpointController.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20ConfigurationContext.java
support/cas-server-support-oauth-uma/src/main/java/org/apereo/cas/config/CasOAuthUmaConfiguration.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20Configuration.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20AuthorizeEndpointControllerTests.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java

There are currently two issues with session replication autoconfiguration. I tested it with master, but I think it's the same for the 6.2.x branch.
1) The `SessionReplicationProperties` sets its cookies `DISSESSION` on the `/cas/` path. Though, in the `doPreExecute` method of the `DelegatedClientAuthenticationAction`, this path is compared to blank if the `autoConfigureCookiePath` property is set to `true` (by default). Thus, it is never auto-configured.
2) The `SessionReplicationProperties` is shared between authentication and OAuth server support. Though, it is only auto-configured for authentication delegation in the `DelegatedClientAuthenticationAction`. It must also be auto-configured for OAuth server support when replication is enabled `cas.authn.oauth.replicate-sessions: true`. …

Fix session replication autoconfigure

---

support/cas-server-support-token-tickets/src/main/java/org/apereo/cas/token/authentication/principal/TokenWebApplicationServiceResponseBuilder.java
support/cas-server-support-token-tickets/src/test/java/org/apereo/cas/token/authentication/principal/TokenWebApplicationServiceResponseBuilderTests.java

Fix the following issue:
Given the service xxx is configured to allow service ticket as JWT
And the user has no TGT session
When the user tries to go on the url /cas/login?service=xxx&gateway=true
Expected behaviour: 302 Redirect on the requested service
Found behaviour: The following exception
`org.jasig.cas.client.validation.TicketValidationException: service and ticket parameters are both required
at org.jasig.cas.client.validation.Cas20ServiceTicketValidator.parseResponseFromServer(Cas20ServiceTicketValidator.java:84) ~[cas-client-core-3.5.1.jar!/:3.5.1]
at org.jasig.cas.client.validation.AbstractUrlBasedTicketValidator.validate(AbstractUrlBasedTicketValidator.java:198) ~[cas-client-core-3.5.1.jar!/:3.5.1]
at org.apereo.cas.token.JWTTokenTicketBuilder.build(JWTTokenTicketBuilder.java:5 …

Service ticket as JWT without TGT and gateway=true

---

api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/RegisteredService.java

I just added a link to the new method replacing gerRequiredHandlers to help developers

Add link for deprecated getRequiredHandlers()

---

docs/cas-server-documentation/developer/Build-Process.md
gradle/webapp.gradle

This change allows using the same casmodules property between the recent cas-template-overlay and when running cas from this project, e.g. with `bc`.
```
casmodules=core-monitor,\
support-ldap,\
support-aup-webflow,\
support-x509,\
support-x509-core,\
support-x509-webflow,\
support-saml-idp,\
support-saml-sp-integrations,\
support-oidc,\
support-oauth-webflow,\
support-rest-x509,\
support-ehcache-ticket-registry,\
support-ehcache3-ticket-registry,\
support-ldap-monitor,\
support-metrics,\
support-reports,\
support-pm-webflow,\
support-pm-ldap,\
support-pm,\
support-swagger,\
support-events-memory,\
core-configuration-metadata-repository,\
support-bootadmin-client
```

add support for overlay casmodules property

---

support/cas-server-support-actions/src/main/java/org/apereo/cas/web/flow/login/InitialFlowSetupAction.java

Currently, if you call the `/login` endpoint with an unauthorized service (`httpno`), you'll get this log:
```
WARN [...RegisteredServiceAccessStrategyUtils] - <Unauthorized Service Access. Service [] is not found in service registry.>
```
A bit disappointing.
With this fix, you'll get:
```
WARN [...RegisteredServiceAccessStrategyUtils] - <Unauthorized Service Access. Service [httpno] is not found in service registry.>
```

Fix log for service not found

---

webapp/cas-server-webapp-resources/src/main/resources/log4j2.xml

This removes extraneous `b` that was in the file. It also lets `includeLocation` be inherited from root logger. It is off by default but isn't needed b/c the current config doesn't use the %L pattern to print line number. I would argue that the overhead of that isn't worth it and that debug log messages in a particular category (class) should be distinguishable from each other based on the message and shouldn't require a line number. Stack traces already include line numbers in the stack trace. 
This is in response to comments by @pbodnar.

fixes in log4j2.xml

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/ldap/AbstractLdapProperties.java
support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/util/LdapUtils.java

Easy switch to trust (only during development!) self-signed TLS certificates for LDAPS.

Allowing to specify LDAP TrustManager

---

support/cas-server-support-thymeleaf/src/main/java/org/apereo/cas/web/view/ThemeClassLoaderTemplateResolver.java
support/cas-server-support-thymeleaf/src/main/java/org/apereo/cas/web/view/ThemeFileTemplateResolver.java
support/cas-server-support-thymeleaf/src/test/java/org/apereo/cas/web/view/ThemeClassLoaderTemplateResolverTests.java
support/cas-server-support-thymeleaf/src/test/java/org/apereo/cas/web/view/ThemeFileTemplateResolverTests.java

- [n/a] Reference any other pull requests that might be related
We noticed a bug that error pages (404, 500) wouldn't honor the default theme [set in cas.properties](https://apereo.github.io/cas/6.2.x/configuration/Configuration-Properties.html#themes). You can verify this by running a custom theme (even just a different CSS background color) and then trying to visit `login2` instead of `login`. 
This MR fixes that issue along with test cases to prove it. I'll follow up with a master version as well.
We also noticed that error page handling falls through to `SpringTemplateResolver` instead of using `ChainingTemplateViewResolver` which then caches the resulting view. This prevents custom theme views from ever appearing again (specifically the header). I spent a little time trying to …

Fix error pages ignoring the default theme in cas.properties

---

support/cas-server-support-thymeleaf/src/main/java/org/apereo/cas/web/view/ThemeClassLoaderTemplateResolver.java
support/cas-server-support-thymeleaf/src/main/java/org/apereo/cas/web/view/ThemeFileTemplateResolver.java
support/cas-server-support-thymeleaf/src/test/java/org/apereo/cas/web/view/ThemeClassLoaderTemplateResolverTests.java
support/cas-server-support-thymeleaf/src/test/java/org/apereo/cas/web/view/ThemeFileTemplateResolverTests.java

This is the master branch version of #4962:
> We noticed a bug that error pages (404, 500) wouldn't honor the default theme [set in cas.properties](https://apereo.github.io/cas/6.2.x/configuration/Configuration-Properties.html#themes). You can verify this by running a custom theme (even just a different CSS background color) and then trying to visit `login2` instead of `login`. 
> This MR fixes that issue along with test cases to prove it. I'll follow up with a master version as well.
> We also noticed that error page handling falls through to `SpringTemplateResolver` instead of using `ChainingTemplateViewResolver` which then caches the resulting view. This prevents custom theme views from ever appearing again (specifically the header). I spent a little time trying to determine why only …

Allow error pages to use the default theme specified in cas.properties

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/authentication/LdapPrincipalAttributesProperties.java

It will prevent users to have to cast keys and values from Object to String

Specify types for the attributes Map

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/OAuth20HandlerInterceptorAdapter.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20ThrottleConfiguration.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/OAuth20HandlerInterceptorAdapterTests.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/web/OidcHandlerInterceptorAdapter.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java

Hello Misagh,
When you're trying to do an invalid OAuth 2.0/OIDC Authorization request against the CAS server, for instance a request without or with invalid response_type and client_id parameters, you don't have any error.
Instead, you're redirected to the login page for the "OAuth Authentication Callback Request URL" service.
Authorization Requests validators exist in the code but they are not used because of the OAuth20HandlerInterceptorAdapter who is requesting authentication even for invalid requests.
This PR fix the problem and adds tests to avoid any future problem.
Another PR will be made later to adds OIDC Authorization Requests Validators to ensure the scope parameter exists in the OIDC Authorization request because it's a required parameter.
Regards,
Julien

Reject invalid oauth/oidc Authentication Requests.

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/callback/OAuth20AuthorizationCodeAuthorizationResponseBuilder.java

Hello Misagh,
When you're successfully connected to an OAuth/OIDC service against CAS. You are redirected to the service with some parameters (code, state etc...).
The client_id parameter is send back to the service but it's not specified anywhere in the OAuth 2.0 or the OIDC Protocol specifications.
Here a little fix for the problem.
Regards,
Julien

Authorization response don't need to contain the client_id.

---

api/cas-server-core-api-webflow/src/main/java/org/apereo/cas/web/flow/CasWebflowConstants.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/config/PasswordManagementWebflowConfiguration.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementSingleSignOnParticipationStrategy.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowUtils.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/SendPasswordResetInstructionsAction.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/ValidatePasswordResetTokenAction.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/AllTestsSuite.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/pm/web/flow/PasswordManagementSingleSignOnParticipationStrategyTests.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/pm/web/flow/actions/BasePasswordManagementActionTests.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/pm/web/flow/actions/ValidatePasswordResetTokenActionTests.java

Hello,
When you're using the password reset link received by Mail or SMS when you're already connected, you'll have a 500 error and it's impossible to reset the password.
Access logs:
```
192.168.176.1 - - [01/Nov/2020:12:22:09 +0000] "GET /login?pswdrst=TST-1-******************************&service=https%3A%2F%2Fcasserver%3A8443%2Foauth2.0%2FcallbackAuthorize%3Fclient_id%3Dclient%26redirect_uri%3Dhttps%253A%252F%252Fwww.client.com%26response_type%3Dcode%26client_name%3DCasOAuthClient HTTP/1.1" 302 -
192.168.176.1 - - [01/Nov/2020:12:22:09 +0000] "GET /oauth2.0/callbackAuthorize?client_id=client&redirect_uri=https%3A%2F%2Fwww.client.com&response_type=code&client_name=CasOAuthClient&ticket=ST-2-**************** HTTP/1.1" 302 -
192.168.176.1 - - [01/Nov/2020:12:22:09 +0000] "GET …
```

[backport] Password Management : Allow an authenticated user to reset his password.

---

support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/config/PasswordManagementWebflowConfiguration.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementSingleSignOnParticipationStrategy.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowUtils.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/AllTestsSuite.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/pm/web/flow/PasswordManagementSingleSignOnParticipationStrategyTests.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/pm/web/flow/actions/BasePasswordManagementActionTests.java

Hello,
When you're using the password reset link received by Mail or SMS when you're already connected, you'll have a 500 error and it's impossible to reset the password.
Access logs:
```
192.168.176.1 - - [01/Nov/2020:12:22:09 +0000] "GET /login?pswdrst=TST-1-******************************&service=https%3A%2F%2Fcasserver%3A8443%2Foauth2.0%2FcallbackAuthorize%3Fclient_id%3Dclient%26redirect_uri%3Dhttps%253A%252F%252Fwww.client.com%26response_type%3Dcode%26client_name%3DCasOAuthClient HTTP/1.1" 302 -
192.168.176.1 - - [01/Nov/2020:12:22:09 +0000] "GET /oauth2.0/callbackAuthorize?client_id=client&redirect_uri=https%3A%2F%2Fwww.client.com&response_type=code&client_name=CasOAuthClient&ticket=ST-2-**************** HTTP/1.1" 302 -
192.168.176.1 - - [01/Nov/2020:12:22:09 +0000] "GET …
```

Password management: Allow an authenticated user to reset password

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/util/OAuth20Utils.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/util/OAuth20UtilsTests.java

When the `OAuth20AuthorizationCodeResponseTypeAuthorizationRequestValidator.validate()` method rejects a request, all the various ways that can fail validation result in WARN logging that specifies why it was rejected, with the exception of the call to `OAuth20Utils.isAuthorizedResponseTypeForService()`. This adds a WARN logging inside `isAuthorizedResponseTypeForService` where more details are available. Below is the current logging if debug turned on in OAuth20Utils and someone more observant could probably see why the request was going to fail validation, but it would be better if it were logged at WARN level once problem is identified. The isAuthorizedResponseTypeForService method is only called in two places and neither logs a return of "false" at the WARN level. 
Current Logging: …

add logging at warn level when response type not supported by service

---

docs/cas-server-documentation/protocol/CAS-Protocol-Specification.md

A new line will be rendered as a whitespace.
I've checked [the demo](https://casserver.herokuapp.com/cas) and there's no additional whitespace after the first \<LF\>.
```python3
>>> url = 'https://casserver.herokuapp.com/cas/validate?service={}&ticket={}'.format(service, ticket)
>>> validation = requests.get(url)
>>> validation.text
'yes\ncasuser\n'
```

Docs: Fix CAS 1.0 Validation Response Format

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/hazelcast/BaseHazelcastProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties-Common.md
support/cas-server-support-hazelcast-core/src/main/java/org/apereo/cas/hz/HazelcastConfigurationFactory.java
support/cas-server-support-hazelcast-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/DefaultHazelcastInstanceConfigurationTests.java

Enabling Management Center scripting is configured through the property `cas.ticket.registry.hazelcast.enable-management-center-scripting`. Kept the default to true to be consistent with previous version of the code.

Enabling Management Center scripting through property

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/hazelcast/BaseHazelcastProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties-Common.md
support/cas-server-support-hazelcast-core/src/main/java/org/apereo/cas/hz/HazelcastConfigurationFactory.java
support/cas-server-support-hazelcast-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/DefaultHazelcastInstanceConfigurationTests.java

Use `cas.ticket.registry.hazelcast.enable-management-center-scripting` property to enable/disable scripting from Management Center.

Enable Management Center scripting through property

---

support/cas-server-support-saml-idp-core/src/main/java/org/apereo/cas/support/saml/services/SamlIdPServicesManagerRegisteredServiceLocator.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/SamlIdPServicesManagerRegisteredServiceLocatorTests.java

Following the addition of `SamlIdPServicesManagerRegisteredServiceLocator`, unidentified service IDs are evaluated as possible SAML entityIDs against known SAML services, in addition to regular service ID matching as performed by `DefaultServicesManagerRegisteredServiceLocator`. This introduces an interesting failure case.
First, we need a SAML registered service that retrieves its metadata over MDQ, but it has not yet been retrieved, or the cached copy has expired. Now, we fire a request bearing a service ID not related to the SAML service; let's say it's not an entityID at all but a regular CAS service ID. What will happen is that, at some point, a call to `locate()` on `SamlIdPServicesManagerRegisteredServiceLocator` will fire in …

restrict SAML service lookups to matching entityIDs

---

support/cas-server-support-aws/src/main/java/org/apereo/cas/aws/ChainingAWSCredentialsProvider.java

When using EKS it's common to use IAM roles for service accounts. Adding
WebIdentityTokenCredentialsProvider to the credentials chain supports
that.

Add WebIdentityTokenCredentialsProvider support

---

docs/cas-server-documentation/installation/Configuring-SAML2-Authentication.md

In order to override the SAML2 idP's metadata and/or keys, one needs to
provide the folder structure described in this commit, e.g.
`<service_name>-<service_id>`
The official guide on CAS' blog is [already changed](https://github.com/apereo/apereo.github.io/commit/c2d15ab84cd8b3b9f7a6c90e184808502b21dc5f) to reflect this
issue [0].

docs: Correct the per-SP metadata overrides guide

---

docs/cas-server-documentation/configuration/Configuration-Properties-Common.md

As title, camel case `maxAge` spotted, PR change it back to `max-age`, thanks.

Documentation: Cookie maxAge should be max-age

---

core/cas-server-core-audit-api/src/main/java/org/apereo/cas/audit/spi/entity/AuditTrailEntity.java

Reduce column sizes, so that an index on
(AUD_CLIENT_IP,AUD_USER,AUD_ACTION,APPLIC_CD,AUD_DATE) can be created.
After PR #4759 , the above index creation fails as key size exceeds maximum supported key size by DB.

Reduce length of the JDBC audit columns.

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/web/OidcCasClientRedirectActionBuilder.java

Hi Misagh,
In the 6.2 version of CAS, if you're not connected and you're trying to use the `prompt=login` parameter in an authorization request you'll be prompted for login/password two times.
Steps to reproduce:
The origin authorization request here:
```
https://cas.example.org:8443/cas/oidc/authorize?redirect_uri=http://redirecturi&client_id=clientid&response_type=code&scope=openid&prompt=login
```
will redirect you to:
```
https://cas.example.org:8443/cas/login?service=https%3A%2F%2Fcas.example.org%3A8443%2Fcas%2Foauth2.0%2FcallbackAuthorize%3Fclient_id%3Dclientid%26redirect_uri%3Dhttp%3A%2F%2Fredirecturi%26response_type%3Dcode%26client_name%3DCasOAuthClient&renew=true
```
You'll login with your user/password. Since the renew parameter is here you'll not get a TGC cookie. After the …

[OIDC] Fix OIDC Prompt=login when user is unauthenticated

---

core/cas-server-core-configuration-api/src/main/java/org/apereo/cas/configuration/loader/YamlConfigurationPropertiesLoader.java
core/cas-server-core-configuration/src/test/java/org/apereo/cas/configuration/support/DefaultCasConfigurationPropertiesSourceLocatorTests.java
core/cas-server-core-configuration/src/test/resources/badyaml.yml

I had some bad yaml that was preventing the server from starting and the global spring boot application exception handler wasn't logging the exception message or stack trace for some reason. 
This makes sure the error message is logged as a warning.

Configuration: make sure invalid yaml is logged

---

support/cas-server-support-hazelcast-ticket-registry/src/main/java/org/apereo/cas/config/HazelcastTicketRegistryConfiguration.java

See this group post: https://groups.google.com/a/apereo.org/g/cas-user/c/xix3So1Hsrg
I encountered an issue with  **reload configuration dynamically** features shutting down **Hazelcast ticket cluster** hence impacting login during my testing. This PR is intended to fix the issue.
1. Follow this article to setup dynamic configuration reload: https://fawnoos.com/2020/05/02/cas62x-reloadable-configuration/
2. Add Hazelcast Ticekt Registry feature to `build.gradle`
3. Go to `/cas/login` able to login
4. Edit `/etc/cas/config/cas.properties` , hence trigger a reload
5. Seeing `shutting down 127.0.0.1 hazelcast cluster` INFO message
6.  Go to `/cas/login` not able to login, see `Hazelcast cluster is not active` ERROR message
Remove the `@RefreshScope` as suggested in the above will fix this …

Fix Hazelcast Cluster shutdown when configuration is reloaded

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/events/EventsProperties.java

See: https://github.com/apereo/cas/pull/5004
Set `trackConfigurationModifications` to `false` by default.

Set Event `trackConfigurationModifications` to `false` by default

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/git/services/BaseGitProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/git/services/GitServiceRegistryProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/saml/idp/metadata/GitSamlMetadataProperties.java
api/cas-server-core-api-configuration-model/src/main/resources/META-INF/additional-spring-configuration-metadata.json
ci/tests/webapp/validate-external-webapp.sh
docs/cas-server-documentation/configuration/Configuration-Properties-Common.md
gradle.properties
support/cas-server-support-git-core/src/main/java/org/apereo/cas/git/GitRepositoryBuilder.java
support/cas-server-support-git-core/src/test/java/org/apereo/cas/git/GitRepositoryBuilderTests.java
support/cas-server-support-git-service-registry/src/test/java/org/apereo/cas/locator/DefaultGitRepositoryRegisteredServiceLocatorTests.java
support/cas-server-support-git-service-registry/src/test/java/org/apereo/cas/locator/TypeAwareGitRepositoryRegisteredServiceLocatorTests.java
support/cas-server-support-git-service-registry/src/test/java/org/apereo/cas/services/GitServiceRegistryTests.java
support/cas-server-support-saml-idp-metadata-git/src/main/java/org/apereo/cas/support/saml/metadata/resolver/GitSamlRegisteredServiceMetadataResolver.java
support/cas-server-support-saml-idp-metadata-git/src/test/java/org/apereo/cas/support/saml/metadata/resolver/GitSamlRegisteredServiceMetadataResolverTests.java

This adds support for the git clone-directory property to access file path with the file resource prefix, to match documentation. The  privateKeyPath also take a Resource now but the underlying JSch library eventually wants a String path so it would only take a file: type of resource or classpath: type if in file in classpath but not in an archive. File type of resource also only makes sense for clone-directory but that should be obvious.  
I don't understand what is going on with GitServiceRegistryTests.java - There is a ```"cas.service-registry.git.repository-url=file:/tmp/cas-sample-data.git"``` and it deletes "/tmp/cas-sample-data" but I don't think it uses either one? Is that supposed to be a git repo that it clones from and pushes to because it is making the git repo in …

Make git repository support file: URI prefix for clone-directory and private-key-path

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/OAuth20ClientIdAwareProfileManager.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/OAuth20TestsSuite.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/profile/OAuth20ClientIdAwareProfileManagerTests.java

When user signed in by [Delegated Authentication](https://apereo.github.io/cas/development/integration/Delegate-Authentication.html), it will cause `NullPointerException` in OAuth 2.0 callback authorize flow.
```
Exception: Servlet.service() for servlet [dispatcherServlet] in context with path [/cas] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException
at org.apereo.cas.support.oauth.profile.ClientIdAwareProfileManager.lambda$retrieveAll$0(ClientIdAwareProfileManager.java:47) ~[cas-server-support-oauth-5.3.16.jar!/:5.3.16]
```
Use `StringUtils.equals` instead of `Object.equals` to compare `clientId` that may not exists in `AuthenticationAttribute`

Fix profiles missing SESSION_CLIENT_ID throws NullPointerException

---

docs/cas-server-documentation/developer/Build-Process.md
docs/cas-server-documentation/developer/Test-Process.md
gradle/webapp.gradle

This fixes some docs related to casModules, but I also figured it doesn't cost anything to support the casModules being specified with the support- or core- prefix, since it is looking for two things already, might as well look for the fully qualified module suffix and prefer that since it is more specific. At least the docs should be merged before 6.3 release, but I can back out the webapp.gradle if you prefer.

fix casModules docs

---

ci/validate-helm.sh
ci/validate.sh

This allows validate-helm.sh script to run locally on linux (when k3s is installed) and should make it more reliable by using kubectl wait instead of sleep.

CAS Initializr - update CI for helm

---

support/cas-server-support-aws-cognito-authentication/src/main/java/org/apereo/cas/authentication/AmazonCognitoAuthenticationAuthenticationHandler.java

username in AdminGetUserRequest object appears null in adminGetUser method call and gives ''userName' failed to satisfy constraint: Member must not be null' error. This is a minor fix to address that issue. Looks like this bug was introduced in 6.3.0 release.

Amazon Cognito Authentication: fix adminGetUser

---

.github/workflows/cas-build.yml
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/config/standalone/StandaloneConfigurationSecurityProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/web/tomcat/CasEmbeddedApacheTomcatBasicAuthenticationProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/support/CasConfigurationJasyptCipherExecutor.java
ci/tests/shell/cas-shell-script.sh
core/cas-server-core-configuration/src/test/java/org/apereo/cas/configuration/support/CasConfigurationJasyptCipherExecutorTests.java
support/cas-server-support-shell/src/main/java/org/apereo/cas/shell/commands/jasypt/JasyptDecryptPropertyCommand.java
support/cas-server-support-shell/src/main/java/org/apereo/cas/shell/commands/jasypt/JasyptEncryptPropertyCommand.java
support/cas-server-support-shell/src/main/java/org/apereo/cas/shell/commands/jasypt/JasyptTestAlgorithmsCommand.java
support/cas-server-support-shell/src/test/java/org/apereo/cas/shell/commands/jasypt/JasyptDecryptPropertyCommandTests.java
support/cas-server-support-shell/src/test/java/org/apereo/cas/shell/commands/jasypt/JasyptEncryptPropertyCommandTests.java

Having initialization vector used by default breaks passwords encrypted without it (e.g. in existing installations). This turns its use off by default but turns it on automatically for previously blacklisted algorithms that don't work without an initialization vector. Test added to make sure future changes don't break existing encrypted values, although the test only does so for a particular algorithm. 
There was a test already that would have caught this but it doesn't currently do a good job checking for errors:
https://github.com/apereo/cas/runs/1722512587?check_suite_focus=true#step:7:108
That isn't fixed by this PR but I will take a look at it.

Turn off jasypt initialization vector by default

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/LoggingUtils.java
core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/LoggingUtilsTests.java

This seeks to log a better exception message if the top level throwable's message is null, as is the case with an UndeclaredThrowableException used by SneakyThrows. This looks for the first non-null message but still results in the top level exception's stack trace being logged (as it may have useful information). Here is an example where the top level exception provides details on where the exception occurred but the nested exception message is more useful as to the cause of the problem. This shouldn't add any extra overhead in the case where the top level message is not null. 
```
2021-01-20 15:00:59,880 WARN [org.apereo.cas.services.GitServiceRegistry] - <UndeclaredThrowableException>
java.lang.reflect.UndeclaredThrowableException: null
at …
```

avoid logging null messages if nested message available

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/web/security/HttpCorsRequestProperties.java
api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/RegisteredServiceProperty.java
core/cas-server-core-web-api/src/main/java/org/apereo/cas/services/web/support/RegisteredServiceCorsConfigurationSource.java
core/cas-server-core-web/src/test/java/org/apereo/cas/web/RegisteredServiceCorsConfigurationSourceTests.java
docs/cas-server-documentation/services/Configuring-Service-Http-Security-Headers.md

Spring 5.3 has started throwing this exception when you use * as an allowed origin and credentials are allowed:
```
java.lang.IllegalArgumentException: When allowCredentials is true, allowedOrigins cannot contain the special value "*"since that cannot be set on the "Access-Control-Allow-Origin" response header. To allow credentials to a set of origins,
list them explicitly or consider using "allowedOriginPatterns" instead.
```
Previously Spring would echo back the requested origin for the allowed origin if * was configured with allow credentials true.
This adds support for the new Spring `allowedOriginPatterns` setting.

support cors allowed origin patterns

---

support/cas-server-support-thymeleaf/src/main/resources/templates/casConsentView.html

- Fix labels reference for radio inputs in casConsentView template.
- Adds missing messages references to screen.consent.attributes.attribute and screen.consent.attributes.values.

Fix labels in casConsentView

---

webapp/cas-server-webapp-init/src/main/java/org/apereo/cas/web/BeanDefinitionStoreFailureAnalyzer.java
webapp/cas-server-webapp-init/src/main/resources/META-INF/spring.factories
webapp/cas-server-webapp-init/src/test/java/org/apereo/cas/AllCasWebApplicationTestsSuite.java
webapp/cas-server-webapp-init/src/test/java/org/apereo/cas/BeanDefinitionStoreFailureAnalyzerTests.java

I had a startup failure caused by a BeanDefinitionStoreException due to an unresolved placeholder and there wasn't a good message logged when the server stopped. This adds a spring boot FailureAnalyzer that prints more information about the error, and you can turn on debug to try to get the stack trace.
Here is the example of what the error message looks like, although I have updated the Action text since this was generated:
```
2021-01-29 10:37:27,250 WARN [org.apereo.cas.web.CasWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [org.apereo.cas.web.CasWebApplication]; nested exception is …
```

capture better error message on startup for BeanDefinitionStoreException

---

app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/bootadmin/deployment.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/script-configmap.yaml
app/src/main/resources/overlay/helmcharts/helm/cas-server/templates/statefulset.yaml

Kubernetes doesn't like underscores in volume mount names. Also SPRING_PROFILES env variable gets interpreted by spring boot 2.4 as spring.profiles property setting and that breaks things in some cases.

fix illegal underscores in kubernetes names

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/git/services/BaseGitProperties.java
docs/cas-server-documentation/release_notes/RC2.md

This updates the default branches to clone to "all" branches. If it isn't all, and you change the `activeBranch`, you also have to change the `branchesToClone` to include the `activeBranch`. Since most config repositories are probably small, defaulting to cloning all the branches is probably not a big deal. If the default is going to remain as-is, we should probably automatically add the activeBranch to the list of branchesToClone.

change default branchesToClone to all branches, update javadocs

---

core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/DefaultChainingServiceRegistry.java

This PR adds an implemented findServiceBy(String id) to the DefaultChainingServiceRegistry.  Without this implementation the default methods in the interface are called.  The side affect of that is the service registry would be reloaded on every call to this method, resulting in poor performance for registries of any significant size.

Implement findServiceBy for service id

---

support/cas-server-support-simple-mfa-core/src/main/java/org/apereo/cas/mfa/simple/CasSimpleMultifactorAuthenticationHandler.java
support/cas-server-support-simple-mfa/src/test/java/org/apereo/cas/mfa/simple/CasSimpleMultifactorAuthenticationHandlerTests.java

I propose to accept Simple MFA tokens without prefix. This way users won't have to type the additional first 7 characters.

Accept simple MFA tokens without prefix

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/redis/BaseRedisProperties.java
support/cas-server-support-audit-redis/src/main/java/org/apereo/cas/config/CasSupportRedisAuditConfiguration.java
support/cas-server-support-aup-redis/src/main/java/org/apereo/cas/config/CasAcceptableUsagePolicyRedisConfiguration.java
support/cas-server-support-aup-redis/src/test/java/org/apereo/cas/RedisAcceptableUsageTestsSuite.java
support/cas-server-support-aup-redis/src/test/java/org/apereo/cas/aup/ConditionalOnExpressionNegativeTests.java
support/cas-server-support-consent-redis/src/main/java/org/apereo/cas/config/CasConsentRedisConfiguration.java
support/cas-server-support-gauth-redis/src/main/java/org/apereo/cas/config/GoogleAuthenticatorRedisConfiguration.java
support/cas-server-support-redis-authentication/src/main/java/org/apereo/cas/config/RedisAuthenticationConfiguration.java
support/cas-server-support-redis-service-registry/src/main/java/org/apereo/cas/config/RedisServiceRegistryConfiguration.java
support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/config/RedisTicketRegistryConfiguration.java
support/cas-server-support-saml-idp-metadata-redis/src/main/java/org/apereo/cas/config/SamlIdPRedisIdPMetadataConfiguration.java
support/cas-server-support-saml-idp-metadata-redis/src/main/java/org/apereo/cas/config/SamlIdPRedisRegisteredServiceMetadataConfiguration.java
support/cas-server-support-saml-idp-metadata-redis/src/test/java/org/apereo/cas/RedisSamlTestsSuite.java
support/cas-server-support-saml-idp-metadata-redis/src/test/java/org/apereo/cas/support/saml/ConditionalOnExpressionNegativeTests.java
support/cas-server-support-saml-idp-metadata-redis/src/test/java/org/apereo/cas/support/saml/ConditionalOnExpressionPositiveTests.java
support/cas-server-support-throttle-redis/src/main/java/org/apereo/cas/config/CasRedisThrottlingConfiguration.java
support/cas-server-support-trusted-mfa-redis/src/main/java/org/apereo/cas/trusted/config/RedisMultifactorAuthenticationTrustConfiguration.java
support/cas-server-support-u2f-redis/src/main/java/org/apereo/cas/config/U2FRedisConfiguration.java
support/cas-server-support-webauthn-redis/src/main/java/org/apereo/cas/config/RedisWebAuthnConfiguration.java
support/cas-server-support-yubikey-redis/src/main/java/org/apereo/cas/config/RedisYubiKeyConfiguration.java

I like to be able to add a module for something like the redis ticket registry but not necessarily use it right away or in every deployment, but I like to use the same image in multiple deployments. This allows me to add the redis module and then disable it via a property. I went ahead and added it to `BaseRedisProperties` so I made the various Configurations that use properties extending from that conditional on enabled being true, which is the default.

allow redis modules to be disabled via properties

---

gradle.properties

Signal shards an older version of jackson databind which has lots of vulnerabilities on scans, this version of signalfx uses newer version of jackson.

update signalfx version

---

support/cas-server-support-saml-idp-core/src/main/java/org/apereo/cas/support/saml/services/InCommonRSAttributeReleasePolicy.java

According to: https://refeds.org/category/research-and-scholarship and https://spaces.at.internet2.edu/display/federation/Identity+provider+-+support+Research+and+Scholarship the mail and sn attributes are expected instead of email and surname.

Fix attributes released to InCommon and RefedsRS

---

support/cas-server-support-thymeleaf/src/main/resources/templates/casMfaRegisterDeviceView.html
support/cas-server-support-trusted-mfa-core/src/main/java/org/apereo/cas/trusted/web/flow/AbstractMultifactorTrustedDeviceWebflowConfigurer.java

Skip button is not working at all. If you fill form correctly, then skip button behaves exactly like register button.
This path adds separate transition for skip button and  fixes form validation.

Fix skip button in casMfaRegisterDeviceView

---

support/cas-server-support-thymeleaf/src/main/resources/templates/casSimpleMfaLoginView.html

Token should not be required in casSimpleMfaLoginView. Otherwise clicking on resend button would be not possible if the token input is empty.

Cannot resend token in casSimpleMfaLoginView

---

docs/cas-server-documentation/installation/Configuring-SAML2-Attribute-Release.md
docs/cas-server-documentation/integration/Attribute-Definitions.md
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/attr/SamlIdPAttributeDefinition.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/attr/SamlProfileSamlAttributeStatementBuilder.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/AllSamlIdPTestsSuite.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/web/idp/profile/builders/attr/SamlProfileSamlAttributeStatementBuilderTests.java
support/cas-server-support-saml-idp/src/test/resources/basic-definitions.json

This PR adds a new `urn` property to `SamlIdPAttributeDefinition`.  This allows defining `key` and `name` with more friendly names that are likely to match what is pulled form attribute repositories and still assign the attributes published urn to be used as the `Name` attribute for a SAML response. If `urn` is not defined the `name` property will be used as it currently is in the SAML response. 
Documentation has also been updated to reflect the two types of attribute definitions available.

SAML Attribute Definition should support "urn" 

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/web/LocaleCookieProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/analytics/GoogleAnalyticsCookieProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/cookie/CookieProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/cookie/PinnableCookieProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/cookie/TicketGrantingCookieProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/cookie/WarningCookieProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/mfa/trusteddevice/DeviceFingerprintProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/oauth/CsrfCookieProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/oauth/OAuthProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/replication/CookieSessionReplicationProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/wsfed/WsFederationDelegatedCookieProperties.java
core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/mgmr/DefaultCasCookieValueManager.java
docs/cas-server-documentation/authentication/OAuth-Authentication.md
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20Configuration.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/OAuth20TestsSuite.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/CSRFCookieTests.java

This is an attempt at configuring the properties of the pac4jCsrfToken cookie. I am trying to leave the defaults to pac4j. There were some people having trouble hitting an app running on localhost that was trying to do CAS OIDC auth to a backend on a different domain. The pac4j cookie was blocked when browsers started defaulting to lax so this lets the same site policy be set to "none". Not sure what type of test would be appropriate for this.

setting the pac4j csrf cookie properties

---

gradle/dependencies.gradle

I was looking into how cas-management was getting slf4j since it wasn't declaring and it appeared to be getting from reflection-util dependency. This excludes it so it can be managed directly (easier).

exclude transitive dependencies from reflection-util

---

gradle/dependencies.gradle

(cherry picked from commit 9d417ab06bd0e6c1e0a93c1d0783fb94e0f0e5a9)
I would like this on 6.3 branch to help with slf4j dependencies in cas-management 6.3.x.

exclude transitive dependencies from reflection-util (#5057)

---

support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/enc/validate/SamlObjectSignatureValidator.java

The `SAML2HTTPRedirectDeflateSignatureSecurityHandler` used to validate signed SAML authn request in `SamlObjectSignatureValidator` cannot be reused once initialized, evidently even given `destroy` is called. This means that it is impossible to validate the signature on a request that comes from an SP with metadata that includes multiple certificates. As such, this patch ensures that a new instance is used for each potential credential.
Unfortunately, I do not have a functional understanding of how the potential signing credentials are resolved, and thus have no idea how to go about testing for this scenario. I can, however, provide an example of metadata that caused this to become an issue: https://bard.zoom.us/saml/metadata/sp

ensure SecurityHandler on SamlObjectSignatureValidator is not reused when multiple credentials are present

---

api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/RegisteredServiceAttributeReleasePolicy.java
core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/AbstractRegisteredServiceAttributeReleasePolicy.java
core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/ReturnAllowedAttributeReleasePolicy.java
core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/ReturnEncryptedAttributeReleasePolicy.java
core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/ReturnMappedAttributeReleasePolicy.java
core/cas-server-core-authentication-attributes/src/test/java/org/apereo/cas/services/RegisteredServiceAttributeReleasePolicyTests.java
core/cas-server-core-authentication-attributes/src/test/java/org/apereo/cas/services/ReturnAllowedAttributeReleasePolicyTests.java
core/cas-server-core-authentication-attributes/src/test/java/org/apereo/cas/services/ReturnMappedAttributeReleasePolicyTests.java
support/cas-server-support-oidc-core/src/main/java/org/apereo/cas/oidc/claims/BaseOidcScopeAttributeReleasePolicy.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/claims/OidcAddressScopeAttributeReleasePolicyTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/claims/OidcCustomScopeAttributeReleasePolicyTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/claims/OidcEmailScopeAttributeReleasePolicyTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/claims/OidcPhoneScopeAttributeReleasePolicyTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/claims/OidcProfileScopeAttributeReleasePolicyTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/claims/mapping/OidcDefaultAttributeToScopeClaimMapperTests.java
support/cas-server-support-ws-idp-api/src/main/java/org/apereo/cas/ws/idp/services/CustomNamespaceWSFederationClaimsReleasePolicy.java
support/cas-server-support-ws-idp-api/src/main/java/org/apereo/cas/ws/idp/services/WSFederationClaimsReleasePolicy.java

Currently an attribute definition is only resolved and made available for release if it's key matches an attribute that was resolved by an attribute repository.  This limits attribute definition keys to match a corresponding attribute in a repository.  It also limits that separate definitions could not use the same base attribute for it's definition.  
This PR then adds a requestedAttributeDefinitions() method to policies that allow specifying attributes to be released, such as ReturnAllowed and ReturnMapped policies.  The list of definitions is then processed and added to the attribute list before resolving them from the AttrributeDefinitionStore so that they are available to the release policy.
This approach of only resolving requested definitions is preferable to resolving all …

Resolve Attribute Definition requested by release policy

---

support/cas-server-support-gauth-core/src/main/java/org/apereo/cas/gauth/credential/GoogleAuthenticatorOneTimeTokenCredentialValidator.java

Currently, when the application is using Google Authenticator as 2FA, it always return authentication success even though the OTP code is inputted randomly.
By seeing the code, the validator always return the Object of `GoogleAuthenticatorToken` even though the `authzAcoount` is null
The change only includes the checking at the end of `validate` function, so that only when `authzAccount` is not null, it will create the object of `GoogleAuthenticatorToken`

Bug Fix: Wrong authentication checking in Google Authenticator

---

api/cas-server-core-api-services/src/main/java/org/apereo/cas/authentication/attribute/AttributeDefinitionStore.java
core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/attribute/DefaultAttributeDefinitionStore.java
support/cas-server-support-person-directory/src/test/java/org/apereo/cas/DefaultAttributeDefinitionStoreTests.java

PR adds a method to be able to remove an AttributeDefinition from an AttributeDefinitionStore that is loaded in memory.  This method is needed for a new feature in CAS Management to be able to edit and sync an attribute definitions to CAS servers.

Add method to remove definition from AttributeDefinitionStore

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/HttpUtils.java

I encountered the issue for CAS 6.2.
Without timeouts defined on the `HttpClient`, the CAS server can be fully blocked by external not-responding systems.
BTW, I missed the change but I see that since v6.3.x, the `HttpClient` is now built for every HTTP request, I fear a strong performance impact as I changed things the opposite way in 5.x.

Set timeouts for HttpUtils

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/util/EncryptionJwtCryptoProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/oauth/OAuthProperties.java

I encountered this  issue when I wanted to encrypt an OAuth secret.
The `EncryptionJwtCryptoProperties` class with an encryption key of 512 is only used in the `EncryptionJwtSigningJwtCryptographyProperties` class where the algorithm is `"A128CBC-HS256"`.
There is a mismatch here: the encryption key size should be 256 to match the algorithm: `A128CBC-HS256`.
Though, I fixed it like it is done in other CAS places: the encryption key size is forced to 256 in the properties class constructor.

Fix the default size of the encryption key for OAuth

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/x509/CnEdipiPrincipalResolverProperties.java
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/AbstractX509PrincipalResolver.java
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/DefaultX509AttributeExtractor.java
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/EDIPIX509AttributeExtractor.java
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/X509AttributeExtractor.java
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/X509CommonNameEDIPIPrincipalResolver.java
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/X509ExtractorUtils.java
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SubjectAlternativeNameRFC822EmailPrincipalResolver.java
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SubjectAlternativeNameUPNPrincipalResolver.java
support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/X509UPNExtractorUtils.java
support/cas-server-support-x509-core/src/test/java/org/apereo/cas/AllTestsSuite.java
support/cas-server-support-x509-core/src/test/java/org/apereo/cas/adaptors/x509/authentication/principal/DefaultX509AttributeExtractorTests.java
support/cas-server-support-x509-core/src/test/java/org/apereo/cas/adaptors/x509/authentication/principal/EDIPIX509AttributeExtractorTests.java
support/cas-server-support-x509-core/src/test/java/org/apereo/cas/adaptors/x509/authentication/principal/X509CommonNameEDIPIPrincipalResolverTests.java
support/cas-server-support-x509-core/src/test/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SerialNumberAndIssuerDNPrincipalResolverTests.java
support/cas-server-support-x509-core/src/test/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SerialNumberPrincipalResolverTests.java
support/cas-server-support-x509-core/src/test/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SubjectAlternativeNameRFC822EmailPrincipalResolverTests.java
support/cas-server-support-x509-core/src/test/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SubjectAlternativeNameUPNPrincipalResolverTests.java
support/cas-server-support-x509-core/src/test/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SubjectDNPrincipalResolverTests.java
support/cas-server-support-x509-core/src/test/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SubjectPrincipalResolverTests.java
support/cas-server-support-x509/src/main/java/org/apereo/cas/adaptors/x509/config/X509AuthenticationConfiguration.java
support/cas-server-support-x509/src/test/java/org/apereo/cas/AllTestsSuite.java
support/cas-server-support-x509/src/test/java/org/apereo/cas/adaptors/x509/config/EDIPIX509AttributeExtractorConfigTests.java

I wanted to extract EDIPI number as an attribute but I didn't want to inflict that attempt on everyone without an option since it is only applicable to a specific certificate issuer. I decided to move the attribute extraction logic out of `AbstractX509PrincipalResolver` and into its own bean and then that is passed to all the x509 person resolvers. I put a property to enable the EDIPI version of the attribute extractor bean in the `CnEdipiPrincipalResolverProperties` which might not be appropriate because users of other principal resolvers would likely enable EDIPI attribute extraction, but the flag to enable the extraction is EDIPI related and principalresolver related... 
A possible enhancement would be to make the attribute extraction bean configurable so that a deployer could control …

x509 extract edipi as attribute, make attribute extractor a bean

---

docs/cas-server-documentation/integration/Configuring-SAML-SP-Integrations.md

Previously, it pointed to the general GitLab home page. The new link is probably more helpful for most admins.
Please make sure you include the following:

DOC: Link to specific GitLab documentation page

---

docs/cas-server-documentation/developer/Build-Process.md
docs/cas-server-documentation/installation/WAR-Overlay-Initializr.md

Update docs to refer to new project rather than branch. Remove build initializr "build" docs since they are covered in the project docs.

Update initializr docs to point at project

---

docs/cas-server-documentation/_includes/attribute-resolution-configuration.md

I was working on a test project and I wanted to leave the default in-memory user and stub repository I was using, but when I added LDAP attribute repository and had the aggregation set to CASCADE, the stub repo stopped working b/c the dummy user wasn't in LDAP attribute repository. This documentation update might have made it easier to figure out what was going on. 
This is a result of the code `dao.setStopIfFirstDaoReturnsNull(true);` in 
```
case CASCADE:
val dao = new CascadingPersonAttributeDao();
dao.setAddOriginalAttributesToQuery(true);
dao.setStopIfFirstDaoReturnsNull(true);
```

update documentation about CASCADE aggregation

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/memcached/BaseMemcachedProperties.java
support/cas-server-support-memcached-core/src/main/java/org/apereo/cas/memcached/MemcachedPooledClientConnectionFactory.java

I'm migrating a CAS server from version 3.5 to the latest version. It uses Memcached.
I notice that it's no longer possible to set the protocol property, which is really strange as it's an important feature and as it's default value (text) is less efficient (than binary).
I may be missing something, but this PR allows to set again the Memcached protocol.

Add the protocol property for Memcached

---

core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/DenyAllAttributeReleasePolicy.java

This is probably bad (adding a new class to avoid log statement) but looking for better ideas on how to avoid the following log statement on an internal oauth/oidc redirect that doesn't really play into the final attribute release as far as I can tell. I don't want to just lower the level b/c if I am troubleshooting an attribute release issue have logging turned up I still don't want to see it. 
```
LOGGER.info("CAS will not authorize anything for release, given the service is denied access to all attributes. "
+ "If there are any default attributes set to be released to all services, "
+ "those are also skipped for [{}]", service);
```
That is from `DenyAllAttributeReleasePolicy` added here:
```
@Bean
@ConditionalOnMissingBean(name = "oauthServiceRegistryExecutionPlanConfigurer")
public …
```

Update log level for message in DenyAllAttributeReleasePolicy

---

webapp/cas-server-webapp-resources/src/main/resources/log4j2.xml

This specifies baseDir in log4j2.xml to use a system property (-DbaseDir=/tmp) but if it isn't set then it will fall back to the log42.xml baseDir property that it is using now. This allows for overriding the default config without changing it or using the overlay/initializr config (which may also need this change, if this is accepted).

allow log4j2.xml baseDir to be overridden by system property

---

core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/domain/DefaultDomainAwareServicesManager.java
gradle.properties

PR provides a solution to an issue that mostly affects CAS Manager.  If a change is made to one of the fields in a service that is part of the compareTo() method, the changed service is added as a new service in the domain instead of replacing the existing service in the map.  This fix removes a service by Id if found in the domain before adding the edited service to the domain map to avoid the duplicate.

Avoid duplicate service in DomainManager when a service is edited

---

support/cas-server-support-git-service-registry/src/test/java/org/apereo/cas/services/GitServiceRegistryTests.java
support/cas-server-support-saml-idp-metadata-git/src/test/java/org/apereo/cas/support/saml/idp/metadata/GitSamlIdPMetadataGeneratorTests.java
support/cas-server-support-saml-idp-metadata-git/src/test/java/org/apereo/cas/support/saml/idp/metadata/GitSamlIdPMetadataLocatorTests.java
support/cas-server-support-saml-idp-metadata-git/src/test/java/org/apereo/cas/support/saml/metadata/resolver/GitSamlRegisteredServiceMetadataResolverTests.java

These tests worked locally on windows. The `file:` url instead of `file://` might work on other platforms but jgit seems to treat "file" as a hostname if it sees file:C:\Users\xyz\temp. I also did an add before the commit, not sure that is necessary but it seemed like it was writing a file before commit and I think the commit was ending up empty.

fix tests on windows

---

gradle/tasks.gradle

Probably unintentionally, cleanLogs task body was executed in the configuration phase already, i. e. every time. Moving it to the execution phase - this improves builds' performance greatly.
For example, the fix seems to spare about 20 seconds for every Gradle build run on my Windows. It wouldn't be probably that much on a Linux machine (or a faster PC 😉 ).
Another positive side effect is avoiding this error when you've got CAS Tomcat currently running:
```
$ ./gradlew <anything>
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.
FAILURE: Build failed with an exception.
* Where:
Script 'D:\projects\my-forks\cas\gradle\tasks.gradle' line: 61
* What went wrong:
A problem occurred evaluating script.
> java.io.IOException: Unable to …
```

build(gradle): fixing when logs deletion happens for cleanLogs task

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/cognito/AmazonCognitoAuthenticationProperties.java
docs/cas-server-documentation/configuration/Configuration-Properties.md
support/cas-server-support-aws-cognito-authentication/src/main/java/org/apereo/cas/authentication/AmazonCognitoAuthenticationAuthenticationHandler.java
support/cas-server-support-aws-cognito-authentication/src/main/java/org/apereo/cas/config/AmazonCognitoAuthenticationConfiguration.java
support/cas-server-support-aws-cognito-authentication/src/test/java/org/apereo/cas/authentication/AmazonCognitoAuthenticationAuthenticationHandlerTests.java

Allow renaming Cognito user pool attribute names before putting into a principal

Allow renaming Cognito user pool attribute names

---

core/cas-server-core-web-api/src/main/java/org/apereo/cas/web/support/CasLocaleChangeInterceptor.java
core/cas-server-core-web/src/test/java/org/apereo/cas/web/support/CasLocaleChangeInterceptorTests.java

The previous version of `CasLocaleChangeInterceptor` would lead to users being surprised, because their preferred language set in their browser / OS wouldn't be taken into account anymore. I. e. ignore the client's preferences only when `cas.locale.force-default-locale=true` is set.

fix: keep honoring language requested in "Accept-Language" header

---

build.gradle

Explanation: `buildDate` is tested in `tasks.jar.onlyIf` and the committed code was removed in 6c1ac15204a8745a2 probably just by an accident.
So with this fix, we should get a normal "incremental" build behavior again, for example:
1. Have CAS completely built, e. g. in "cas\webapp\cas-server-webapp\build\libs\cas-server-webapp-6.4.0-SNAPSHOT.war".
1. Change a class in one of CAS library projects.
2. Run CAS build again, without running clean and without manually removing the library jar from "build/libs" of the project.
3. The library project gets correctly recompiled.
4. _With the fix_, we also get a new library jar, which also appears within the CAS war. _Without the fix_, we don't get any of this.

build(gradle): build jars after every compilation again

---

core/cas-server-core-web/src/main/resources/cas_common_messages.properties

Hello, i found a bug. There was use wrong js file for whatwg-fetch. Pointing to the Issue here https://github.com/github/fetch/issues/656#issuecomment-420219378 i fix this. And problem with unknown word export disapear.

wrong file use for whatwg-fetch.js (export error problem in browser)

---

support/cas-server-support-reports-core/src/main/java/org/apereo/cas/web/report/SingleSignOnSessionsEndpoint.java
support/cas-server-support-reports/src/test/java/org/apereo/cas/web/report/SingleSignOnSessionsEndpointTests.java

Currently, invoking `GET /ssoSessions` without passing any `?type=` gives an error. This makes this endpoint not callable by SpringBoot Admin Server UI.

Allow to invoke actuator's GET /ssoSessions with no type query parameter

---

gradle/dependencies.gradle

Trying to run RC3 build got this error: 
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.mongodb.MongoClientSettings]: Factory method 'mongoClientSettings' threw exception; nested exception is java.lang.NoClassDefFoundError: org/bson/codecs/JsonObjectCodecProvider
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
... 27 more
Caused by: java.lang.NoClassDefFoundError: org/bson/codecs/JsonObjectCodecProvider
at com.mongodb.MongoClientSettings.<clinit>(MongoClientSettings.java:61)
at org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration$MongoClientSetting …
```

fix mongo dependencies, otherwise will get older version from springboot

---

docs/cas-server-documentation/release_notes/RC4.md
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/util/OAuth20Utils.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/util/OAuth20UtilsTests.java

This change is to use the service matching strategy with oauth, actually it always compares with a regex but if someone creates a new custom service matching strategy it is not being used and the application is rejected saying it is not supported. Applications that are not using a custom strategy should not be affected by this change because FullRegexRegisteredServiceMatchingStrategy is used by default.

Oauth not using service matching strategy to verify redirect_uri

---

support/cas-server-support-saml-idp-metadata/src/main/java/org/apereo/cas/support/saml/services/idp/metadata/cache/SamlRegisteredServiceMetadataResolverCacheLoader.java

This patch fixes logging the eligible metadata resolvers in SamlRegisteredServiceMetadataResolverCacheLoader.java

Fix logging of eligible metadata resolvers

---

core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/util/InternalTicketValidator.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/AllTestsSuite.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/util/InternalTicketValidatorTests.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20Configuration.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/OAuth20TestsSuite.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/SamlProfileHandlerConfigurationContext.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/sso/SSOSamlIdPProfileCallbackHandlerController.java
support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/config/SamlIdPEndpointsConfiguration.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/web/idp/profile/sso/SSOSamlIdPProfileCallbackHandlerControllerTests.java

Partial backport of: https://github.com/apereo/cas/commit/5d968ae4dc8730d0ebfb1efe8c20a9e6acae95cd to use an internal CAS validation for the SAML server support.

Backport internal validation for SAML support

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/git/services/BaseGitProperties.java
gradle/dependencies.gradle
support/cas-server-support-git-core/src/main/java/org/apereo/cas/git/GitRepositoryBuilder.java
support/cas-server-support-git-core/src/test/java/org/apereo/cas/git/GitRepositoryBuilderTests.java

I am running into an issue trying to clone via https (ssh is blocked) through an ssl proxy. I don't know if this will fix the issue but I would like to have the option of trying to the non-default http client for troubleshooting purposes. For some reason JGit makes this choice static/global so I put in the docs how the same value should be used for all cloned repositories, but maybe I should only be setting the factory if it is not the default, that way setting it for one would set it for all.

add support for alternate jgit http client

---

support/cas-server-support-git-core/src/main/java/org/apereo/cas/git/GitRepositoryBuilder.java
support/cas-server-support-git-core/src/test/java/org/apereo/cas/git/GitRepositoryBuilderTests.java

Gitlab.com doesn't require this but at least some versions of gitlab hosted (e.g. v12) seem to require that access tokens are specified on the URL so this will substitute ${username} and ${password} tokens if they are present on the URL with the username/password properties for that particular git repository. This also adds a test that only works if https auth is working b/c it is using a mostly empty private repo with a read-only access token that never expires.

test git clone over https with private repo

---

support/cas-server-support-memcached-core/src/main/java/org/apereo/cas/memcached/kryo/CloseableKryoFactory.java

It's been a few versions since I have used Memcached with CAS.
Maybe I'm missing something obvious, but it does not seem to work. The order in which classes are registered for the Kryo serialization is not the same for every start of the CAS server. You can confirm that by enabling trace logs on `org.apereo.cas.memcached.kryo.CloseableKryoFactory`.
Thus, the serialization/deserialization process does not work between multiple nodes of the same cluster or if you restart the CAS server.
I tested the issue in v6.3 and v6.4.
My naive proposal is to order classes by names.

Fix classes ordering for Kryo serialization

---

support/cas-server-support-git-service-registry/src/main/java/org/apereo/cas/config/GitServiceRegistryConfiguration.java
support/cas-server-support-git-service-registry/src/main/java/org/apereo/cas/services/GitServiceRegistry.java
support/cas-server-support-git-service-registry/src/main/java/org/apereo/cas/services/locator/GitRepositoryRegisteredServiceLocator.java
support/cas-server-support-git-service-registry/src/test/java/org/apereo/cas/services/GitServiceRegistryTests.java

This makes the load method in git service registry only load services in the root-directory. Still need to make a test...

Make git service registry load use root-directory

---

docs/cas-server-documentation/installation/Configuring-SAML2-Authentication.md
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/sso/SSOSamlIdPPostProfileHandlerEndpoint.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/web/idp/profile/sso/SSOSamlIdPPostProfileHandlerEndpointTests.java

PR adds the option to send parameters to the endpoint as a map using the http Post.
Adds 'encrypt' as parameter.  The default is to now return an unencrypted response and attribute statement.  If set to true the response and the attribute statement will be encrypted.
Sets the formatting of the response to be indented.

SamlPostProfileResponse Endpoint enhancements

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenAuthorizationCodeGrantRequestExtractor.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenAuthorizationCodeGrantRequestExtractorTests.java

PR corrects the Access Token generator to first look up RegisteredService by clientId and then fall back to redirectUri if clientId is not found.

Fix AT Generator to lookup by service by client id

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/HttpUtils.java

I have a custom authentication handler in my CAS server. It relies on a JSON web service to validate credentials.
I reuse the `HttpUtils` component to post my JSON request.
Though, I use French accents and it does not work properly: I realize that the default encoding for the `StringEntity` is "ISO-8859-1".
So I propose to use the "UTF-8" encoding for `StringEntity` in `HttpUtils` as we use "UTF-8" everywhere.

 Use UTF-8 for entity in JSON

---

support/cas-server-support-oidc-core/src/main/java/org/apereo/cas/oidc/claims/BaseOidcScopeAttributeReleasePolicy.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/claims/OidcOpenIdScopeAttributeReleasePolicyTests.java

PR prevents a null pointer in BaseOIDCScopeAttributeReleasePolicy if extending class does not set any claims.

Prevent potential NP with OIDC Scopes

---

support/cas-server-support-x509-core/src/main/java/org/apereo/cas/adaptors/x509/authentication/RequestHeaderX509CertificateExtractor.java
support/cas-server-support-x509/src/test/java/org/apereo/cas/adaptors/x509/RequestHeaderX509CertificateExtractorTests.java

The RequestHeaderX509CertificateExtractor.extract method generally tries to return null for any failures to reconstitute a certificate from the value in a http header but certain invalid headers (in my case `-----BEGIN CERTIFICATE-----`) were causing the sanitizeCertificateBody to fail with an exception. This avoids calling sanitizeCertificateBody with values that will cause it to  throw an exception. 
```
^[[1;31m2021-05-20 22:01:15,422 ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/cas].[dispatcherServlet]] - <Servlet.service() for servlet [dispatcherServlet] in context with path [/cas] threw exception [R
^[[m java.lang.StringIndexOutOfBoundsException: begin 27, end 2, length 27
at java.lang.String.checkBoundsBeginEnd(String.java:3319) ~[?:?]
at …
```

Avoid unhandled exception if x509 cert header invalid

---

core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/AbstractServicesManager.java

Moves getCandidateServicesToMatch out of Lambda and so a list of services to match is only generated once before applying locators.

Call getCandidateServicesToMatch once for all locators

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/services/OAuth20ServicesManagerRegisteredServiceLocator.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/services/OAuth20ServicesManagerRegisteredServiceLocatorTests.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/services/OidcServicesManagerRegisteredServiceLocator.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/services/OidcServicesManagerRegisteredServiceLocatorTests.java

Changes the OAuth Service Manager Locators to match only by client_id.  This allows for more exact matches, especially in the cases where a redirect_uri regex can be too encompassing or two OAuth clients can redirect to the same domain such as localhost.

Change OAuth Service Locators to match on client_id

---

core/cas-server-core-logout-api/src/main/java/org/apereo/cas/logout/DefaultLogoutManager.java

I have a SP (pac4j app) integrated via the SAML protocol with a CAS server.
In CAS, I configure my SP to logout via the front channel:
```xml
{
"@class" : "org.apereo.cas.support.saml.services.SamlRegisteredService",
"serviceId" : "http://localhost:8081.*",
"name" : "SAMLService",
"id" : 1,
"evaluationOrder" : 1,
"metadataLocation" : "/Users/jleleu/sources/spring-webmvc-pac4j-boot-demo/sp-metadata.xml",
"logoutType": "FRONT_CHANNEL"
}
```
I also want the SAML logout responses to be sent via the HTTP-Redirect binding:
```yml
cas.authn.saml-idp.logout.logout-response-binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
```
After a successful SAML login, I perform a SAML logout: the SP sends a SAML logout request to CAS which displays its logout page. Two AJAX logout requests are sent …

Remove duplicate logout requests

---

ci/tests/puppeteer/run.sh
support/cas-server-support-pm-core/src/main/java/org/apereo/cas/pm/BasePasswordManagementService.java
support/cas-server-support-pm-core/src/main/java/org/apereo/cas/pm/impl/NoOpPasswordManagementService.java

This logs a warning if the base "changeInternal()" for changing password runs. This almost certainly means that someone has not configured the appropriate password change implemenation and is probably not what they want. I think warn is appropriate so they see the message without having to turn on debug, and they can suppress via log4j config if they somehow want that no-op impl. 
Also move puppeteer docker shutdown until after CAS shutdown to avoid seeing errors in CAS logs (caused by backend shutdown, eg. LDAP server shutting down).

log warning when no-op running for change password

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/redis/BaseRedisProperties.java
api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/redis/RedisClusterProperties.java
support/cas-server-support-redis-core/src/main/java/org/apereo/cas/redis/core/RedisObjectFactory.java
support/cas-server-support-redis-core/src/test/java/org/apereo/cas/redis/core/RedisObjectFactoryTests.java

I initially wanted to add a way to set `dynamicRefreshSources` to true but in the process of doing this PR I realized the default is already true and that it must not be cause of my reconnect issue. My re-connect issues are probably due to me not setting enabled to true on the pool config so the testOnBorrow that I was setting to true was not being used. 
In the process of making this PR though I noticed a couple things that don't seem right. The "timeout" that was documented as a connection timeout was actually being used as command timeout. The default command timeout is 60 seconds but CAS was setting the default to 2 seconds which seems low. This PR adds a way to set the actual connect timeout and it leaves "timeout" as the command timeout, which is consistent with what spring boot …

add redis client connection options

---

api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/ServicesManager.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/AbstractServicesManager.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/ChainingServicesManager.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/AbstractServicesManagerTests.java
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/util/OAuth20Utils.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/web/controllers/jwks/OidcJwksEndpointController.java

PR adds method to ServicesManager to a return all services of a given Class with performance improvements over using a filter with a predicate.  Specifically in cases where ChainingServicesManager is uses separate managers for services of different type.
An approach we have found useful is have separate ServicesManagers for CAS, SAML and OAuth registered services.  This allows SAML and OAuth look ups to ignore the thousands of registered CAS services and apply matching to smaller, targeted sets to increase performance and avoid unintentional matches of services of different protocols.  
This would help performance of CAS Management as well, when listing and editing SAML and OAuth services.

Add getAllServicesOfType method to ServicesManager

---

api/cas-server-core-api-webflow/src/main/java/org/apereo/cas/web/flow/CasWebflowConstants.java
ci/tests/puppeteer/scenarios/saml2-idp-login-sp-logout-post/init.sh
ci/tests/puppeteer/scenarios/saml2-idp-login-sp-logout-post/script.js
ci/tests/puppeteer/scenarios/saml2-idp-login-sp-logout-post/script.json
ci/tests/puppeteer/scenarios/saml2-idp-login-sp-logout-post/services/cas-2.json
ci/tests/puppeteer/scenarios/saml2-idp-login-sp-logout-post/services/saml-1.json
ci/tests/puppeteer/scenarios/saml2-idp-login-sp-logout-redirect/init.sh
ci/tests/puppeteer/scenarios/saml2-idp-login-sp-logout-redirect/script.js
ci/tests/puppeteer/scenarios/saml2-idp-login-sp-logout-redirect/script.json
ci/tests/puppeteer/scenarios/saml2-idp-login-sp-logout-redirect/services/cas-2.json
ci/tests/puppeteer/scenarios/saml2-idp-login-sp-logout-redirect/services/saml-1.json
ci/tests/puppeteer/scenarios/saml2-idp-sp-logout-post/init.sh
ci/tests/puppeteer/scenarios/saml2-idp-sp-logout-post/script.js
ci/tests/puppeteer/scenarios/saml2-idp-sp-logout-post/script.json
ci/tests/puppeteer/scenarios/saml2-idp-sp-logout-post/services/saml-1.json
ci/tests/puppeteer/scenarios/saml2-idp-sp-logout-redirect/init.sh
ci/tests/puppeteer/scenarios/saml2-idp-sp-logout-redirect/script.js
ci/tests/puppeteer/scenarios/saml2-idp-sp-logout-redirect/script.json
ci/tests/puppeteer/scenarios/saml2-idp-sp-logout-redirect/services/saml-1.json
core/cas-server-core-web-api/src/main/java/org/apereo/cas/web/support/WebUtils.java
core/cas-server-core-web/src/test/java/org/apereo/cas/web/support/WebUtilsTests.java
core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/configurer/DefaultLogoutWebflowConfigurer.java
core/cas-server-core-webflow/src/test/java/org/apereo/cas/web/flow/DefaultLogoutWebflowConfigurerTests.java
support/cas-server-support-actions/src/main/java/org/apereo/cas/web/flow/logout/FinishLogoutAction.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/FinishLogoutActionTests.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/slo/SamlIdPSingleLogoutRedirectionStrategy.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/web/idp/profile/slo/SamlIdPSingleLogoutRedirectionStrategyPostBindingTests.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/web/idp/profile/slo/SamlIdPSingleLogoutRedirectionStrategyRedirectBindingTests.java
support/cas-server-support-thymeleaf/src/main/resources/templates/logout/casPropagateLogoutView.html

I have a SAML SP (pac4j app) integrated via the SAML protocol with a CAS server.
I define the POST binding for the SAML logout responses:
```yaml
cas.authn.saml-idp.logout.logout-response-binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
```
For the redirect binding, it is considered front channel and at the end of the logout process, the user is redirected to the SP with the SAML logout response.
For the post binding, it is considered back channel and the CAS server directly calls the SP with the SAML logout response and display its logout page at the end of the logout process.
This PR changes this behavior to consider the POST binding as a front channel communication. Thus, no direct call is made by the CAS server to the SP. At the end of the logout process, an HTTP POST is made …

Properly handle POST binding for SAML logout response

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/quartz/SchedulingProperties.java
core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasCoreTicketsSchedulingConfiguration.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/spring/boot/ConditionalOnMatchingHostname.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/spring/boot/MatchingHostCondition.java
core/cas-server-core-util-api/src/test/java/org/apereo/cas/AllUtilTestsSuite.java
core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/spring/boot/ConditionalOnMatchingHostnameTests.java
support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/config/MongoDbTicketRegistryConfiguration.java
support/cas-server-support-trusted-mfa-core/src/main/java/org/apereo/cas/trusted/authentication/storage/MultifactorAuthenticationTrustStorageCleaner.java
support/cas-server-support-trusted-mfa/src/main/java/org/apereo/cas/trusted/config/MultifactorAuthnTrustConfiguration.java

When running CAS via a docker image and/or with cloud configuration that is common across all servers, it can be difficult to enable a scheduled job like the ticket registry cleaner so that it only runs on a single server (since CAS isn't using a quartz DB afaik). This add a property that can contain a hostname and if the hostname in the property matches the hostname of the server where the server is starting up then it will enable the scheduled job, otherwise it will not. 
The first commit did this programmatically but then I changed it in the 2nd commit to use a custom `@ConditionalOnMatchingHostname` annotation. 
I removed the ticketRegistryCleaner bean from MongoDbTicketRegistryConfiguration b/c it looked to be the same as the bean defined in CasCoreTicketsSchedulingConfiguration. I …

Make easier to run scheduled jobs on single host

---

support/cas-server-support-saml-idp-core/src/main/java/org/apereo/cas/support/saml/services/idp/metadata/SamlRegisteredServiceServiceProviderMetadataFacade.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/idp/metadata/SamlRegisteredServiceServiceProviderMetadataFacadeTests.java
support/cas-server-support-saml-idp/src/test/resources/metadata/testshib-providers.xml

The `isDefault` attribute was not taken into account for an ACS definition.
This PR fixes this issue. One test has been updated to verify the behavior.

Fix isDefault support for SAML2 ACS

---

core/cas-server-core-logout/src/main/java/org/apereo/cas/logout/config/CasCoreLogoutConfiguration.java

As title:
`singleLogoutServiceLogoutUrlBuilder` (used in `defaultLogoutRedirectionStrategy`)  is being defined as variable while it is already available as function in the same class.
Suggestion:
- Remove `singleLogoutServiceLogoutUrlBuilder` variable
- Change `defaultLogoutRedirectionStrategy` to use the `singleLogoutServiceLogoutUrlBuilder` function instead of the varaible
See if is an applicable change, thanks.

Refractor duplicate definition of singleLogoutServiceLogoutUrlBuilder as variable and function

---

core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/AbstractServicesManager.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/AbstractServicesManagerTests.java

Improve cache invalidation during load and minimize the empty cache store duration.

Service registry: improve cache invalidation

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/token/OidcIdTokenGeneratorService.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/token/OidcIdTokenGeneratorServiceTests.java

I have a client app (pac4j) integrated via the OIDC protocol with a CAS server.
I have this service definition:
```json
{
"@class" : "org.apereo.cas.services.OidcRegisteredService",
"clientId": "myclient",
"clientSecret": "mysecret",
"serviceId" : "^http://localhost:.*",
"name": "OIDC",
"id": 1,
"scopes" : [ "java.util.HashSet",
[ "openid", "email", "profile" ]
],
"generateRefreshToken": true
}
```
I perform an authorization code flow login and receive an ID token, an access token and a refresh token.
I use this command to receive a new access token and ID token:
```shell
curl -XPOST -H "Authorization: Basic bXljbGllbnQ6bXlzZWNyZXQ=" 'http://localhost:8080/cas/oidc/token?grant_type=refresh_token&refresh_token=XXXXX'
```
The ID tokens have different values for the `auth_time` claim.
In the …

OIDC: Fix the auth_time claim in ID tokens

---

.github/workflows/puppeteer.yml
ci/tests/ldap/run-ad-server.sh
ci/tests/puppeteer/.npmrc
ci/tests/puppeteer/cas.js
ci/tests/puppeteer/run.sh
gradle/tests.gradle

These are some changes I made related to running puppeteer tests locally on windows and on a fork (without running all tests). 
- make it easier to run a sub-set of the puppeteer tests on your own fork (via regex)
- allow running puppeteer tests as HEADLESS without setting CI=true (the x509 test now does ldap auth too but the certificate prompt was causing problems in non-headless mode)
- made puppeteer tests timeout after 15 minutes
- added REBUILD env variable that if set to false will use existing cas.war to run puppeteer test rather than building again
- fixed run.sh so it works on Windows MSYS2 bash when a path is passed (to a cert bundle or script) on the command line

puppeteer build updates

---

core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/actions/ClearWebflowCredentialAction.java

I'm currently upgrading a CAS server using SPNEGO from v6.1 to v6.4.
In case of a SPNEGO failure, the login page was properly displayed in v6.1.
In v6.4.0-SNAPSHOT (or RC5), I get the following exception:
```java
ERROR [org.thymeleaf.TemplateEngine] - <[THYMELEAF][http-nio-8080-exec-1] Exception processing template "login/casLoginView": Error during execution of processor 'org.thymeleaf.spring5.processor.SpringInputGeneralFieldTagProcessor' (template: "fragments/loginform" - line 68, col 40)>
org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor
...
Caused by: org.springframework.beans.NotReadablePropertyException: Invalid property 'username' of bean class [org.apereo.cas.support.spnego.authentication.principal.SpnegoCredential]: Bean property …
```

Fix SPNEGO in case of failure

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/profile/OidcUserProfileDataCreator.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/profile/OidcUserProfileDataCreatorTests.java

A few days ago, I submitted the PR: https://github.com/apereo/cas/pull/5185 to always have the same `auth_time` in all ID tokens (for the same session).
Though, it has introduced a small inconsistency between the `auth_time` of the ID token and the `auth_time` of the user profile endpoint.
"accessToken" endpoint response:
```json
{
"access_token":"AT-6--HNfN3VYv7Bel28IwFu-fWol84taNSDN",
"id_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImxhbGFsYSJ9.eyJqdGkiOiJUR1QtNi1oLURHclhVMUhFUVhqcTBIZjZPMlZiWmliaUhiQ0xVVjA1eXJFZ3BKckNhamN2UlhzUXdvdDB0YWUtOU5HZjVIQ1JNLWNhc3Rlc3QiLCJzaWQiOiI4ZWRiMWI3Y2VlZDY0N2ViNGU3NjEyZjE2MWYyMzVjZTVhYTdiNWIxIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2Nhcy9vaWRjIiwiYXVkIjoibXljbGllbnQiLCJleHAiOjE2MjUxNzc4NDAsImlhdCI6MTYyNTE0OTA0MCwibmJmIjoxNjI1MTQ4NzQwLCJzdWIiOiJqb …
```

Fix the auth_time claim in the OIDC support

---

support/cas-server-support-pac4j-api/src/main/java/org/apereo/cas/pac4j/DistributedJEESessionStore.java
support/cas-server-support-pac4j-api/src/test/java/org/apereo/cas/integration/pac4j/DistributedJEESessionStoreTests.java

I have found an issue with the authentication delegation which comes from the `DistributedJEESessionStore`.
The source code has been refactored after the upgrade to pac4j v5 and there is a problem: the `set` operation should always create a session if it does not exist. Like in the `JEESessionStore`.
This PR fixes this issue. The tests have been updated accordingly.
Without this fix, before the authn delegation, the ticket used to save the session store is always `TST-null` (as `null` is the session id). It means that multiple new authentication processes will share the same ticket id and use the already existing session store (from another authn process).
You can check the issue with the following demo: https://github.com/casinthecloud/cas-pac4j-oauth-demo
- Set the version to …

Fix DistributedJEESessionStore

---

support/cas-server-support-rest-authentication/src/main/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandler.java

When CAS delegates and submits authentication requests to a remote REST endpoint, the username and password is swapped in the Authorization header.

Username and password swapped in REST authentication

---

.gitignore
ci/tests/puppeteer/scenarios/external-app-strapi-oidc/init.sh
ci/tests/puppeteer/scenarios/external-app-strapi-oidc/script.js
ci/tests/puppeteer/scenarios/external-app-strapi-oidc/script.json
ci/tests/puppeteer/scenarios/external-app-strapi-oidc/services/Strapi-1.json
ci/tests/puppeteer/scenarios/external-app-strapi-oidc/strapi-custom/bootstrap.js
ci/tests/puppeteer/scenarios/external-app-strapi-oidc/strapi-custom/server.js

This test installs strapi (a nodejs application) and configures it to use CAS for login via OIDC and then the puppeteer test hits endpoint in strapi that does OIDC login with CAS and returns a JWT which can then be used to hit strapi endpoints. Installing and starting strapi application takes about 2-3 minutes. There is an init.sh script that installs strapi and it copies a "bootstrap.js" file into the installed app with values pre-configured. Rather that checking in that file I could probably use the one from the installed app and do few `sed` commands to configure the clientid, clientsecret and enable the CAS auth provider.

add puppeteer test with strapi oidc app

---

support/cas-server-support-rest-authentication/src/main/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandler.java

The remote REST endpoint can send warnings back to the CAS server using custom headers.  However, when the X-CAS-PasswordExpirationDate header is not present, a NullPointerException is thrown.

Fix NullPointerException when X-CAS-PasswordExpirationDate header is not present for REST authentication.

---

.github/workflows/publish.yml
build.gradle
gradle.properties
gradle/springboot.gradle
gradle/webapp.gradle
release.sh

This changes references to "sonatype" to "repository" so that it is easier to use the defined maven repos and gradle parameters when publishing to repositories other than Sonatype Nexus repositories. This also adds a variable called publishFlag that is true if either publishReleases or publishSnapshots are true because they are or'd together in several places. 
I was going to change the secret names in publish.yml but I decided to leave them as SONATYPE_USER and SONATYPE_PWD which means no change is needed if this merged. The workflow would be more generic if the secret names were REPOSITORY_USER and REPOSITORY_PWD.

make maven publish repo variables type neutral

---

docs/cas-server-documentation/installation/OAuth-OpenId-Authentication.md

Attribute name is invalid: documentation says timeToLive and cas search for timeToKill
https://github.com/apereo/cas/blob/b1a805429dcff00415a9a3b7d8ebfa6d01809afc/support/cas-server-support-oauth-services/src/main/java/org/apereo/cas/support/oauth/services/DefaultRegisteredServiceOAuthAccessTokenExpirationPolicy.java#L31
https://github.com/apereo/cas/blob/b1a805429dcff00415a9a3b7d8ebfa6d01809afc/support/cas-server-support-oauth-services/src/main/java/org/apereo/cas/support/oauth/services/DefaultRegisteredServiceOAuthRefreshTokenExpirationPolicy.java#L29

oauth/oidc: token expiration policy attribute name

---

ci/tests/puppeteer/scenarios/saml-relay-state-caching/init.sh
ci/tests/puppeteer/scenarios/saml-relay-state-caching/script.js
ci/tests/puppeteer/scenarios/saml-relay-state-caching/script.json
ci/tests/puppeteer/scenarios/saml-relay-state-caching/services/Sample-1.json
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/AbstractSamlIdPProfileHandlerController.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/response/BaseSamlProfileSamlResponseBuilder.java

There is a bug in 6.3.x currently, where SAML2's RelayState is falsely
cached and re-used alongside other SSO attributes, as an optimization.
An SP sends the RelayState alongside their SAML Authn request, and they
expect the same value by the idP, once the user has successfully
completed the SAML auth flow.
An example of RelayState is Github.com and Github Enterprise.
They both use RelayState to verify that the SAML response corresponds to a
valid SAML request (originating from Github itself).
The issue appears when one attempts to login to service A, and then they
attempt to login to service B, and service B relies on RelayState.
Service A's RelayState is cached and reused for service B, and that
breaks the SAML2 auth flow.
If we grab the RelayState from the request that's passed around, …

saml: Fix RelayState caching issue

---

support/cas-server-support-thymeleaf/src/main/resources/messages_cs.properties

fix for username.required and password.required like other languages.. (was required.username, required.password before - only in cz translation)

cz translation - fix for required fields

---

support/cas-server-support-redis-core/src/main/java/org/apereo/cas/redis/core/RedisObjectFactory.java

This change removes a couple deprecations but the right fix would probably be to change the property names to not contain the "millis" suffix and use the CAS duration syntax for the property. Not sure if it is too late for 6.4 to change property names.

remove deprecated method calls in redis code

---

.github/workflows/publish-artifacts.yml
.github/workflows/publish-aws.yml
.github/workflows/publish-gpr.yml
.github/workflows/publish.yml
build.gradle

This adds two github action workflows, intended mainly for use in forks, one for publishing a tagged release from a fork to github package repo (which doesn't work, or hasn't yet worked) and one to publish to AWS CodeArtifact (which works). The Github Package Repo workflow fails with random 409 conflict errors but I figure it might have some value as an easy to recreate the problem so Github could fix the problem. With 250+ packages in CAS, every publish will likely fail. The AWS workflow seems to work reliably (or at least hasn't failed for two releases since I got it working) although it requires more work on the AWS side (creating repo and user with rights to the repo, generating an access key, and then creating secrets on the fork doing the publishing). 
I think this might encourage …

Add workflows for publishing private releases from forks to aws/github package repositories

---

docs/cas-server-documentation/integration/Attribute-Release-Consent-Activation.md
docs/cas-server-documentation/integration/Attribute-Release-Consent.md

From a quick algolia search in 6.4.x document, seems like `cas.consent.enabled`, `cas.consent.active` and properties at that level are missing in 6.4.x documentation.
For reference, in 6.3.x those properties are listed here:
* https://apereo.github.io/cas/6.3.x/configuration/Configuration-Properties.html#attribute-consent
And the `ConsentProperties` class specifying those properties in 6.4.x: 
* https://github.com/apereo/cas/blob/v6.4.0/api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/consent/ConsentProperties.java
While I do think those properties are missing, I do not know how can I add back those properties to 6.4.x documentation since is quite different then before.
Judging from the 6.4.x documentation files, I reckon this line will …

[Documentation] Add missing consent properties (e.g. cas.consent.active, cas.consent.enabled, etc...)

---

ci/tests/puppeteer/scenarios/reveal-password/script.js
ci/tests/puppeteer/scenarios/reveal-password/script.json
support/cas-server-support-thymeleaf/src/main/resources/static/js/cas.js

Same PR as #5227 but for the master.
On mobile, the "reveal password" button doesn't working.
This issue is described here :
https://www.mail-archive.com/cas-user@apereo.org/msg11852.html
With this PR, we propose to modify the behaviorof this button on desktop so that it also works on mobile.
With this commit, you have to click once to see the password, and another time to hide it.

Fix reveal password button on mobile

---

core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/AbstractServicesManager.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/AbstractServicesManagerTests.java

Fixes an issue where a service with a wildcard regex (such as `https://*.test.edu`) can interfere with a higher-priority (lower `evaluationOrder`) service with a regex which would also match the wildcard (such as `https://prod.test.edu`.) This occurred even if the service with the wildcard regex should not be active in the current environment.
The issue was caused by inadvertent "promotion" through the services cache, which is populated with a service *before* the service's environment is validated.
See `AbstractServicesManagerTests.verifyInvalidServiceNotPromotedByCache()` for details.

Wildcard service/cache issue fix.

---

api/cas-server-core-api-configuration-model/build.gradle
build.gradle
gradle.properties
gradle/springboot.gradle

I did an evaluation of the CAS build using Gradle Enterprise, and came across a few changes that I believe will improve the performance of the build.
* Enable parallel execution by default (`org.gradle.parallel=true`)
* Remove explicit setting of `org.gradle.vfs.watch=true` property (Gradle now enabled this by default)
* Address an issue with a declared task input that caused problems with cacheability
* Remove an unneeded optimization to avoid JAR assembly
* Add a `generateTimestamps` flag to the build, allowing for better UP-TO-DATE and build cache compatibility

Build performance tweaks

---

support/cas-server-support-oauth-uma/src/main/java/org/apereo/cas/config/CasOAuthUmaConfiguration.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20ThrottleConfiguration.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcEndpointsConfiguration.java

By default, in pac4j, a CSRF token is generated (by the default `csrfToken` matcher).
In the CAS server, this is useless. This PR removes this CSRF token generation by forcing the default matchers to `DefaultMatchers.SECURITYHEADERS` only.

Do not generate pac4j CSRF token

---

gradle.properties
gradle/dependencies.gradle
gradle/overrides.gradle

This is mainly cherry-pick of change on master plus two global exclusions in overrides.gradle. (commons-logging and jcl-over-slf4j).

backport commons-logging to spring-jcl change to 6.4

---

gradle.properties

Backs off the alpha versions of slf4j and logback which I don't think were doing much for CAS. In order to make progress on spring-native which has some support for logback, I think it is important to use the same versions of slf4j and logback that spring-native samples are working with. We probably need to wait for spring-boot 2.6.0 to come out so we can use the same version of spring-boot as spring-native's main branch but once that is out I am hoping to move past logger issues and onto other issues...

use released versions of loggers

---

gradle.properties
gradle/dependencies.gradle

I think the `wss4jVersion=2.5.0-SNAPSHOT` was trying to pull in xmlsec 2.3.0-SNAPSHOT which wasn't getting downloaded when I was trying to build. This sets the xmlsec version at the released 2.3.0 for both wss4j and opensaml.

avoid xmlsec snapshot that is no longer available

---

core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/config/CasWebflowContextConfiguration.java
core/cas-server-core-webflow/src/test/java/org/apereo/cas/web/flow/DefaultLoginWebflowConfigurerTests.java
core/cas-server-core-webflow/src/test/java/org/apereo/cas/web/flow/DefaultLogoutWebflowConfigurerTests.java

The Spring cache busting does not work on login/logout webflows: JS/CSS files do not have a version in their names.
Configuration example:
```
spring.web.resources.chain.strategy.content.enabled: true
spring.web.resources.chain.strategy.content.paths: /**
```
The `ResourceUrlProviderExposingInterceptor` interceptor is missing (to populate the `ResourceUrlProvider` in the HTTP request to be used by the `ResourceUrlEncodingFilter`).
This PR fixes this issue.

Fix cache busting on login/logout webflows

---

build.gradle

Porting forward build script change to make publishing plugin inclusion dependent on publishing to oss.sonatype.org.

port forward making nexus plugin conditional on publishing to sonatype

---

.github/workflows/test-ubuntu.yml
core/cas-server-core-web/src/main/java/org/apereo/cas/config/CasCoreHttpConfiguration.java
support/cas-server-support-service-registry-stream/src/main/java/org/apereo/cas/config/CasServicesStreamingConfiguration.java

Spring-native currently sees the destroy method set explicitly on a bean definition and then goes looking for the method and doesn't find it on the `FactoryBean` interface. If I am not mistaken we shouldn't need to set the destroy method on the bean if the bean implements the `DisposableBean` interface. `SimpleHttpClient` and the non no-op impl of `RegisteredServiceReplicationStrategy ` both implement DisposableBean. 
Could we add a pattern like `pr-*` (for pull request) to some of the workflows so it is easier to run workflows on a fork? It might make it easier for contributors to run tests on their fork before submitting a PR.

remove explicit destroy method from DisposableBean beans

---

support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/audit/SamlResponseAuditResourceResolver.java
support/cas-server-support-saml-idp-web/src/test/java/org/apereo/cas/support/saml/web/idp/audit/SamlResponseAuditResourceResolverTests.java

add SAML2 Response ID to audit message to facilitate traceability
Ex : 
{
"who" : "xxx",
"what" : "{\"destination\":\"xxx\",**\"ID\":\"_1268972478599884800\"**,\"issuer\":\"xxx\"}",
"action" : "SAML2_RESPONSE_CREATED",
"application" : "cas",
"when" : "Wed Nov 17 14:53:55 CET 2021",
"clientIpAddress" : "0:0:0:0:0:0:0:1",
"serverIpAddress" : "xxx"
}

add SAML2 Response ID to audit message

---

ci/tests/dynamodb/run-dynamodb-server.sh
support/cas-server-support-dynamodb-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/DynamoDbTicketRegistryFacilitator.java
support/cas-server-support-dynamodb-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/DynamoDbTicketRegistryFacilitatorTests.java

When creating DynamoDb tables with PAY_PER_REQUEST billing mode, the AWS API throws an exception if throughput (read capacity and write capacity) is populated in the create table request.  This error condition does not occur when testing against the dynamodb-local:1.13.6 docker image, but it does when running against DynamoDb in AWS.
With this change, throughput is only populated if billing mode is set to PROVISIONED.

DynamoDB: Only set throughput for PROVISIONED billing mode

---

support/cas-server-support-trusted-mfa-redis/src/main/java/org/apereo/cas/trusted/authentication/storage/RedisMultifactorAuthenticationTrustStorage.java
support/cas-server-support-trusted-mfa-redis/src/test/java/org/apereo/cas/trusted/authentication/storage/RedisMultifactorAuthenticationTrustStorageTests.java

Without this change, only one trusted device per user is taken into account. Whereas as trusted-mfa (memory or mongo for example) correctly handle multiple devices per user.

fix trusted-mfa-redis: correctly get multiple devices per user

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/ticket/accesstoken/OAuth20DefaultAccessTokenFactory.java
support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java
support/cas-server-support-simple-mfa-core/src/main/java/org/apereo/cas/mfa/simple/web/flow/CasSimpleMultifactorSendTokenAction.java

For customisations:
- I want to override the `OAuth20DefaultAccessTokenFactory` class to use a specific principal attribute as the access token identifier
- I want to override the `DelegatedClientAuthenticationAction` class to perform some initial operations when the login webflow starts and I need to access the `casProperties` which is already in the `configContext`
- I want to override the `CasSimpleMultifactorSendTokenAction` to send a SMS only with a token without the prefix.
Will backport.

Open some CAS classes

---

ci/tests/puppeteer/scenarios/oidc-login-strapi/init.sh

Strapi came out with 4.0 release and I think it has some pretty significant changes. I believe strapi still supports CAS but I haven't had time to play with it so I am pinning this test to strapi 3.6.8 until I can update the test to work with 4.0.0. This uses npx to install the strapi app instead of yarn b/c yarn doesn't seem to let you specify a version, or I don't know how to do it.

fix strapi puppeteer test

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20CallbackAuthorizeEndpointController.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20CallbackAuthorizeEndpointControllerTests.java

In a regular OAuth authorize process, the default URL defined at the callback logic level is never used as the `OAuth20CallbackLogic` relies on the pac4j requested URL saved in the session (which is the /authorize URL).
Nonetheless, if I bookmark the /login URL during the OAuth authorize process and call it back later on, I'm redirected to the /callbackAuthorize URL without nothing in session for the pac4j requested URL.
So it loops to the /callbackAuthorize URL itself again and again as the default URL is defined to the /callbackAuthorize URL itself (`context.getFullRequestURL()`).
This PR proposes to use the `redirect_uri` instead of the /callbackAuthorize URL itself as the default URL. I can't say this will always work but I think it's better (to try to return to the client app) than …

Fix the default URL in OAuth callback

---

.github/workflows/puppeteer.yml

Strapi 3.x doesn't work with Node 16 and Strapi 4.x OIDC support is currently broken but should be fixed in the next couple weeks. In the meantime, we can run the puppeteer tests with Node 14 and we will switch back to  Node 16 once Strapi 4.x OIDC is working. This adds caching for node_modules which appears to work, seems to be caching a 150MB of node_modules in the user's npm cache folder.

use node 14 for puppetteer tests for time being

---

gradle.properties
gradle/dependencies.gradle

The `pac4j-jee` artifact must be pulled instead of the `pac4j-core` artifact.

Upgrade to pac4j v5.2.0

---

support/cas-server-support-thymeleaf/src/main/resources/templates/delegated-authn/casDelegatedAuthnStopWebflow.html

```
ERROR [org.apereo.cas.authentication.DefaultAuthenticationManager] - <[DelegatedClientAuthenticationHandler]: [org.pac4j.core.exception.TechnicalException: id cannot be blank / id cannot be blank]>
......
ERROR [org.thymeleaf.TemplateEngine] - <[THYMELEAF][https-jsse-nio-8443-exec-5] Exception processing template "delegated-authn/casDelegatedAuthnStopWebflow": Exception evaluating SpringEL expression: "'screen.pac4j.authn.' + rootCauseException.class.simpleName" (template: "delegated-authn/casDelegatedAuthnStopWebflow" - line 23, col 27)>
```

fix: Exception evaluating SpringEL expression: "'screen.pac4j.authn.' + rootCauseException.class.simpleName"

---

gradle.properties

Cf
https://github.com/pac4j/pac4j/pull/1986
https://github.com/pac4j/pac4j/commit/bb241edc86e995715ec7a40efcf1c6b7ca4185a8
https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/commits/38f6959d698313b1b88993ae1f02d7b6f72fa5a8

pac4j >= 5.1.4 requires nimbus oidc >= 9.14

---

support/cas-server-support-pm-ldap/src/main/java/org/apereo/cas/pm/LdapPasswordManagementService.java
support/cas-server-support-pm-ldap/src/test/java/org/apereo/cas/pm/LdapPasswordManagementServiceTests.java
support/cas-server-support-pm-ldap/src/test/resources/ldif/ldap-pm.ldif

This PR fixes NPE in PM LDAP module when there is LDAP user entry without mail or phone attribute:
```
2021-12-27 13:17:56,909 ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]] - <Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.webflow.execution.ActionExecutionException: Exception thrown executing org.apereo.cas.pm.web.flow.actions.SendPasswordResetInstructionsAction@21c5c68a in state 'sendPasswordResetInstructions' of flow 'login' -- action execution attributes were 'map[[empty]]'] with root cause>
java.lang.NullPointerException: null
at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
at java.util.Optional.<init>(Unknown Source) …
```

Fix PM LDAP user lookup when the user is missing mail or phone.

---

core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/gen/CookieRetrievingCookieGenerator.java

Change the `addCookieHeaderToResponse` method from `private` to `protected`
Which will allow customization on `samesite=none` for compatibility for legacy browser 
* Some of our cookie need to be configured as `samesite=none`. 
* However with the current CAS implementation in `addCookieHeaderToResponse` method. 
* It will break some legacy browser (e.g. Chrome 51 to Chrome 66, iOS 12, etc) so they cannot login
* https://www.chromium.org/updates/same-site/incompatible-clients
* I understand that CAS should not be supporting legacy browser by default, so I don't think it is proper to submit our customization. 
* However I would like this `addCookieHeaderToResponse` to be set to `protected` so we can add in our customization for support of legacy browser ourselves.
Many thanks.

Update addCookieHeaderToResponse method from private to protected

---

support/cas-server-support-thymeleaf/src/main/resources/templates/acceptto/casAccepttoRegistrationView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/admin/casAdminLoginView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/aup/casAcceptableUsagePolicyView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/consent/casConsentView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/delegated-authn/casDelegatedAuthnStopWebflow.html
support/cas-server-support-thymeleaf/src/main/resources/templates/forgot-username/casForgotUsernameSendInfoView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/footer.html
support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/pwdupdateform.html
support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/webAuthnLogin.html
support/cas-server-support-thymeleaf/src/main/resources/templates/gauth/casGoogleAuthenticatorConfirmRegistrationView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/gauth/casGoogleAuthenticatorLoginView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/gauth/casGoogleAuthenticatorRegistrationView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/interrupt/casInterruptView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/login/casLoginMessageView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/mfa-trusted-devices/casMfaRegisterDeviceView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/mfa/casCompositeMfaProviderSelectionView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/password-reset/casPasswordUpdateSuccessView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/password-reset/casResetPasswordVerifyQuestionsView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/protocol/oidc/confirm.html
support/cas-server-support-thymeleaf/src/main/resources/templates/simple-mfa/casSimpleMfaLoginView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/surrogate/casSurrogateAuthnListView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/webauthn/casWebAuthnRegistrationView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/yubikey/casYubiKeyLoginView.html

Since Bootstrap 5.x, margin-right syntax moved from mr- to me- , cf. https://getbootstrap.com/docs/5.1/utilities/spacing/#margin-and-padding)

Fix bootstrap margins - backport to CAS 6.4

---

support/cas-server-support-thymeleaf/src/main/resources/templates/acceptto/casAccepttoRegistrationView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/acct-mgmt/casAccountSignupView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/acct-mgmt/casAccountSignupViewComplete.html
support/cas-server-support-thymeleaf/src/main/resources/templates/admin/casAdminLoginView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/aup/casAcceptableUsagePolicyView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/consent/casConsentView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/delegated-authn/casDelegatedAuthnStopWebflow.html
support/cas-server-support-thymeleaf/src/main/resources/templates/forgot-username/casForgotUsernameSendInfoView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/footer.html
support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/pwdupdateform.html
support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/webAuthnLogin.html
support/cas-server-support-thymeleaf/src/main/resources/templates/gauth/casGoogleAuthenticatorConfirmRegistrationView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/gauth/casGoogleAuthenticatorLoginView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/gauth/casGoogleAuthenticatorRegistrationView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/interrupt/casInterruptView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/login/casLoginMessageView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/mfa-trusted-devices/casMfaRegisterDeviceView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/mfa/casCompositeMfaProviderSelectionView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/password-reset/casPasswordUpdateSuccessView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/password-reset/casResetPasswordVerifyQuestionsView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/passwordless/casPasswordlessDisplayView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/protocol/oidc/confirm.html
support/cas-server-support-thymeleaf/src/main/resources/templates/simple-mfa/casSimpleMfaLoginView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/surrogate/casSurrogateAuthnListView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/webauthn/casWebAuthnRegistrationView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/yubikey/casYubiKeyLoginView.html

Since Bootstrap 5.x, margin-right syntax moved from mr- to me- , cf. https://getbootstrap.com/docs/5.1/utilities/spacing/#margin-and-padding)

Fix bootstrap margins with bootstrap 5.x syntax

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedAuthenticationClientFinishLogoutAction.java
support/cas-server-support-pac4j-webflow/src/test/java/org/apereo/cas/web/flow/DelegatedAuthenticationClientFinishLogoutActionTests.java

I noticed that the CAS `logoutRedirectUrl` overrides the pac4j default `postLogoutUrl` in the pac4j `LogoutValidator`.
I don't think this makes sense when the CAS `logoutRedirectUrl` is `null`.
This PR prevents this overrides in that case.

Authn delegation: fix post logout URL computation

---

support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/DefaultDelegatedClientAuthenticationWebflowManager.java
support/cas-server-support-pac4j-webflow/src/test/java/org/apereo/cas/web/flow/DefaultDelegatedClientAuthenticationWebflowManagerTests.java

Reviewing the source code in the authn delegation, I found out potential multi-threading issues if clients are lazy initialized (they are initialized once and for all at startup).
For OIDC and OAuth 2, the `ticketId` is saved into the state which belongs to the configuration which is a singleton while we can have multiple requests at the same time => replaced by the use of the session store.
For CAS, in addition of the session store, the `ticketId` is also saved in the custom parameters of the configuration which is a singleton while we can have multiple requests at the same time => removed.
This PR fixes both issues.

Authn delegation: fix multi-threading issues

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/jwks/generator/OidcDefaultJsonWebKeystoreGeneratorService.java

I got this exception and CAS stopped working, probably because it wasn't able to load the JWKS file. This change closes any existing watch before creating another one. I marked this WIP b/c I can't figure how to write a test for it. 
```
2022-01-05 19:30:43,570 WARN [org.apereo.cas.oidc.jwks.OidcDefaultJsonWebKeystoreCacheLoader] - <User limit of inotify instances reached or too many open files>
java.io.IOException: User limit of inotify instances reached or too many open files
at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:62) ~[?:?]
at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47) ~[?:?]
at org.apereo.cas.util.io.PathWatcherService.<init>(PathWatcherService.java:59) ~[cas-server-core-util-api-6.5.0-SNAPSHOT.jar!/:6.5.0-SNAPSHOT]
at …
```

WIP - close watch service before re-creating to release inotify watch resource

---

.github/workflows/analysis.yml
ci/checks/CheckAsyncAnnotationInInterface.java
core/cas-server-core-events-api/src/main/java/org/apereo/cas/support/events/listener/DefaultCasAuthenticationEventListener.java
core/cas-server-core-events-api/src/main/java/org/apereo/cas/support/events/listener/DefaultCasEventListener.java
core/cas-server-core-events-api/src/main/java/org/apereo/cas/support/events/listener/DefaultLoggingCasEventListener.java
core/cas-server-core-events-api/src/main/java/org/apereo/cas/support/events/listener/LoggingCasEventListener.java
core/cas-server-core-events-configuration-cloud-bus/src/main/java/org/apereo/cas/support/events/listener/CasCloudBusConfigurationEventListener.java
core/cas-server-core-events-configuration-cloud-bus/src/main/java/org/apereo/cas/support/events/listener/DefaultCasCloudBusConfigurationEventListener.java
core/cas-server-core-events-configuration/src/main/java/org/apereo/cas/support/events/listener/CasConfigurationEventListener.java
core/cas-server-core-events-configuration/src/main/java/org/apereo/cas/support/events/listener/DefaultCasConfigurationEventListener.java
core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/DefaultRegisteredServicesEventListener.java
core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/RegisteredServicesEventListener.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/DefaultServiceRegistryInitializerEventListener.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/ServiceRegistryInitializerEventListener.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/jwks/OidcDefaultJsonWebKeyStoreListener.java
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/jwks/OidcJsonWebKeyStoreListener.java
support/cas-server-support-service-registry-stream/src/main/java/org/apereo/cas/services/CasServicesRegistryStreamingEventListener.java
support/cas-server-support-service-registry-stream/src/main/java/org/apereo/cas/services/DefaultCasServicesRegistryStreamingEventListener.java
support/cas-server-support-surrogate-authentication/src/main/java/org/apereo/cas/authentication/event/DefaultSurrogateAuthenticationEventListener.java
support/cas-server-support-surrogate-authentication/src/main/java/org/apereo/cas/authentication/event/SurrogateAuthenticationEventListener.java
webapp/cas-server-webapp-init/src/main/java/org/apereo/cas/web/CasWebApplication.java
webapp/cas-server-webapp-init/src/main/java/org/apereo/cas/web/CasWebApplicationReadyListener.java

The `CasWebApplication` recently got an `@Aysnc` annotation which required a cglib generated class  since there was no interface. This adds an interface to CasWebApplication and I moved the `@Async` annotations for other classes to the associated interface so it would be easy to add a "check" that ensures `@Async` annotations are in interfaces. I moved `@EventListener` annotation to the interface but it probably doesn't need to be there.

Ensure @Async annotations used along with interface

---

support/cas-server-support-reports/src/test/java/org/apereo/cas/web/report/SingleSignOnSessionsEndpointTests.java

That's the port forward of #5359 
In master branch, singleSignOnSessionsEndpoint.destroySsoSessions is already ok : TGT is deleted - no need to fix

Test that TGT is deleted when singleSignOnSessionsEndpoint.destroySsoSessions is called

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/ResourceUtils.java
core/cas-server-core-util/src/test/java/org/apereo/cas/util/ResourceUtilsTests.java

I debugged and figured out why init-from-json wasn't working on Windows... The ResourceUtils.doesResourceExist() method was returning false for a directory that existed and it was moving on to create a services folder in temp directory and using the default service in that. I might look into whether the puppeteer tests could run on windows in Github Actions... I think msys2 is available, hopefully jq is installed, then it would just have to skip tests that require docker which would be doable.

fix ResourceUtils.doesResourceExist to detect directory on windows

---

support/cas-server-support-hazelcast-discovery-aws/src/main/java/org/apereo/cas/hz/HazelcastAwsDiscoveryStrategy.java
support/cas-server-support-hazelcast-discovery-aws/src/test/java/org/apereo/cas/hz/HazelcastAwsDiscoveryStrategyTests.java
support/cas-server-support-hazelcast-discovery-jclouds/src/main/java/org/apereo/cas/hz/HazelcastJCloudsDiscoveryStrategy.java
support/cas-server-support-hazelcast-discovery-jclouds/src/test/java/org/apereo/cas/hz/HazelcastJCloudsDiscoveryStrategyTests.java
support/cas-server-support-hazelcast-discovery-kubernetes/src/main/java/org/apereo/cas/hz/HazelcastKubernetesDiscoveryStrategy.java
support/cas-server-support-hazelcast-discovery-kubernetes/src/test/java/org/apereo/cas/hz/HazelcastKubernetesDiscoveryStrategyTests.java
support/cas-server-support-hazelcast-discovery-swarm/src/main/java/org/apereo/cas/hz/HazelcastDockerSwarmDiscoveryStrategy.java
support/cas-server-support-hazelcast-discovery-swarm/src/test/java/org/apereo/cas/hz/HazelcastDockerSwarmDiscoveryStrategyTests.java

When setting up a hazelcast ticket registry on kubernetes I noticed, that I couldn't provide a valid value for `api-retries`. I always got an exception like the following one:
```
Caused by: java.lang.IllegalArgumentException: Cannot convert to integer
at com.hazelcast.config.properties.PropertyTypeConverter$3.convert(PropertyTypeConverter.java:60) ~[hazelcast-4.2.2.jar:4.2.2]
at com.hazelcast.spi.discovery.impl.DiscoveryServicePropertiesUtil.prepareProperties(DiscoveryServicePropertiesUtil.java:72) ~[hazelcast-4.2.2.jar:4.2.2]
at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryStrategy(DefaultDiscoveryService.java:194) ~[hazelcast-4.2.2.jar:4.2.2]
at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:141) …
```

Hazelcast integer properties

---

support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20ThrottleConfiguration.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcEndpointsConfiguration.java

To make OAuth/OIDC interceptors refreshable as the `ticketRegistry` (they rely on) is.

Add missing @RefreshScope configuration

---

webapp/cas-server-webapp-init-tomcat/src/main/java/org/apereo/cas/config/CasEmbeddedContainerTomcatConfiguration.java
webapp/cas-server-webapp-init/src/main/java/org/apereo/cas/config/CasWebApplicationConfiguration.java
webapp/cas-server-webapp-init/src/main/java/org/apereo/cas/web/CasWebApplication.java
webapp/cas-server-webapp-init/src/main/java/org/apereo/cas/web/CasWebApplicationReady.java
webapp/cas-server-webapp-init/src/main/resources/META-INF/spring.factories

This moves the async application ready event method off of the CasWebApplication class. I think it may be confusing spring native but whether it is or not, I think it is better off in a bean.

Move Async methods off of CasWebApplication 

---

core/cas-server-core-util/src/main/java/org/apereo/cas/config/CasCoreUtilConfiguration.java

I am running into an error trying to build CAS with spring native that might be due to early bean initialization. One cause of that apparently is non-static BeanPostProcessor beans: https://stackoverflow.com/questions/68830586/should-we-use-spring-bean-with-static-method
https://github.com/spring-projects/spring-boot/issues/29747#issuecomment-1036322721
I don't know if it is worth adding a check for this because CAS doesn't seem to use these BeanPostProcessor  or BeanFactoryPostProcessor much.

Make BeanPostProcessor static

---

core/cas-server-core-configuration-api/src/main/java/org/apereo/cas/configuration/DefaultCasConfigurationPropertiesSourceLocator.java
core/cas-server-core-configuration/src/test/java/org/apereo/cas/configuration/support/DefaultCasConfigurationPropertiesSourceLocatorTests.java
core/cas-server-core-configuration/src/test/resources/directory/application.yml
docs/cas-server-documentation/configuration/Configuration-Management.md

Hello,
**Summary**: This PR will change the load order of CAS configuration so that System properties and env variables
override CAS configuration files.
**Details**:
When I'm using CAS in a docker environment (with a docker-compose file), I stumbled
upon the fact that I could not override a variable already defined in /etc/cas/config/application.yml
from my docker-compose file (i.e I'm used to override the spring boot configuration with environment variables defined in the docker compose)
For instance, if I have:
{code}
version: '3'
services:
cas:
image: apereo/cas
ports:
- "8443:8443"
- "8444:8444"
volumes:
- ./etc/cas/config:/etc/cas/config
environment:
- SERVER_PORT=8444
{code}
With my /etc/cas/config/application.yml being
{code}
server:
port: 8443
{code}
The CAS will start at port …

Configuration: change load order (system properties and environment variables first)

---

core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasCoreTicketsConfiguration.java

The unit tests all pass without this TransactionManagementConfigurer bean (last time I checked) so might as well remove it.

remove TransactionManagementConfigurer b/c not needed

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/token/OidcIdTokenGeneratorService.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/token/OidcIdTokenGeneratorServiceTests.java

Fixes the issue described on the cas-user mailing list here https://groups.google.com/a/apereo.org/g/cas-user/c/gqYDgnT2T5o

Fix OIDC claim mapping replacing the claim key.

---

support/cas-server-support-spnego/src/main/java/org/apereo/cas/support/spnego/authentication/principal/SpnegoCredential.java
support/cas-server-support-spnego/src/test/java/org/apereo/cas/support/spnego/authentication/principal/SpnegoCredentialsTests.java

Remove `initToken`and `nextToken` binary attributes from `SpnegoCredential` JSON Serialization.
These attributes pollute audit log when formatted in JSON because of their huge size
and finally it is maybe sensible information we want to hide in audit log.
This was fixed by [PR 4897](https://github.com/apereo/cas/pull/4897) but this is no longer the case (bug exists in 6.4.4.2)

Exclude initToken and nextToken from SpnegoCredential JSON Serialization

---

support/cas-server-support-saml-idp-discovery/src/main/java/org/apereo/cas/config/SamlIdentityProviderDiscoveryConfiguration.java

- [] Brief description of changes applied
Add ConditionalOnMissingBean to the factory method for SamlIdentityProviderDiscoveryFeedController to allow alternative implementations. It might have been nicer to add an interface, implementations etc for a service that a standard FeedController uses but this is my first pull request and this simple change works for me.
- [] Test cases for all modified changes, where applicable
I don't think a test case would prove very much as it is just meta data for a standard mechanism.
- [] The same pull request targeted at the master branch, if applicable
This targets master but I would like to backport it to 6.5.x as we are already pretty late upgrading.
Standard feature already heavily used in CAS?
- [] …

Allow alternative identityProviderDiscoveryFeedControllers

---

ci/tests/puppeteer/scenarios/oidc-authzcode-profile-jwt-format/script.js
ci/tests/puppeteer/scenarios/oidc-authzcode-profile-jwt-format/script.json
ci/tests/puppeteer/scenarios/oidc-authzcode-profile-jwt-format/services/Sample-1.json
support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/web/controllers/profile/OidcUserProfileEndpointController.java

The OIDC UserInfo endpoint can return a signed/encrypted JWT.
Some clients may send the `"Accept": "application/jwt"` header in the request to meet the response type.
Currently, the endpoint is only defined as producing JSON.
So Spring returns a 406 HTTP error.
This PR fixes the problem by adding the JWT format in addition to the JSON format.
I couldn't find any good unit test to confirm the fix, so I added an integration test for that.

Fix OIDC UserInfo in JWT format

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/cipher/BaseBinaryCipherExecutor.java
core/cas-server-core-util/src/test/java/org/apereo/cas/util/cipher/DefaultTicketCipherExecutorTests.java

Backport of: https://github.com/apereo/cas/pull/5445

Fix CipherExecutor backward compatibility with CAS 6.3

---

ci/tests/puppeteer/scenarios/saml2-idp-login-idp-initiated-authnrequestsigned/init.sh
ci/tests/puppeteer/scenarios/saml2-idp-login-idp-initiated-authnrequestsigned/ready.sh
ci/tests/puppeteer/scenarios/saml2-idp-login-idp-initiated-authnrequestsigned/script.js
ci/tests/puppeteer/scenarios/saml2-idp-login-idp-initiated-authnrequestsigned/script.json
ci/tests/puppeteer/scenarios/saml2-idp-login-idp-initiated-authnrequestsigned/services/Sample-1.json
ci/tests/saml2/authsources.php
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/SamlProfileHandlerConfigurationContext.java
support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/config/SamlIdPEndpointsConfiguration.java

There is an issue with the SAML IdP initiated support. When the auth requests are defined to be signed in the SP metadata, it fails with the following error: `ERROR [org.apereo.cas.support.saml.web.idp.profile.builders.enc.validate.SamlObjectSignatureValidator] - <No valid credentials could be found to verify the signature for [org.opensaml.saml.saml2.core.impl.IssuerImpl@xxx]>`.
Indeed, the `samlObjectSignatureValidator` is not the right one for the `SamlIdPInitiatedProfileHandlerController`: it must be the IdP one: `samlIdPObjectSignatureValidator` (instead of the SP one) like it used to be in version 6.4: https://github.com/apereo/cas/blob/6.4.x/support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/config/SamlIdPEndpointsConfiguration.java#L335
This PR fixes the problem with …

Fix SAML IdP initiated support when authn request is signed

---

support/cas-server-support-throttle-bucket4j/src/main/java/org/apereo/cas/web/Bucket4jThrottledRequestExecutor.java
support/cas-server-support-throttle-bucket4j/src/test/java/org/apereo/cas/web/BaseBucket4jThrottledRequestTests.java

I'm trying to upgrade CAS with the `cas-server-support-throttle-bucket4j` module from v6.4 to v6.5.
In v6.5 (and v6.6), I'm rejected in my first authentication attempt (even with a correct login/pwd).
The source code has significantly changed between v6.4 and v6.5.
- in v6.4, I see: "throttle = NOT consume" -> https://github.com/apereo/cas/blob/v6.4.6.3/support/cas-server-support-throttle-bucket4j/src/main/java/org/apereo/cas/web/Bucket4jThrottledRequestExecutor.java#L70
- in v6.5, it's the opposite: "throttle = consume" -> https://github.com/apereo/cas/blob/v6.5.3/support/cas-server-support-throttle-bucket4j/src/main/java/org/apereo/cas/web/Bucket4jThrottledRequestExecutor.java#L24
This PR tries to fix the problem.
I updated the tests to make them pass although I'm not really sure they …

Fix bucket4j throttling support

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/policy/GroovyScriptAuthenticationPolicy.java
core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/policy/GroovyScriptAuthenticationPolicyTests.java
core/cas-server-core-authentication-api/src/test/resources/GroovyAuthenticationPolicy.groovy

Same PR as #5453 but on 6.5.x branch.
----------------------
When defining a Groovy script from classpath from this configuration key `key cas.authn.policy.groovy[0].script=` (see [here](https://apereo.github.io/cas/6.5.x/authentication/Configuring-Authentication-Policy-Groovy.html) for details), the script cannot be loaded.
This was due to `org.apereo.cas.authentication.policy.GroovyScriptAuthenticationPolicy#initializeWatchableScriptIfNeeded()` that tried to create the resource from only a part of the provided URI (`classpath:/script.groovy` was loaded as `/script.groovy`), thus the code was trying to load the script from filesystem instead of classpath.
I used the full URI to load the resource, and added a test case to cover this case.

Fixes an issue that prevented using Groovy scripts from classpath in authentication

---

core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasCoreTicketComponentSerializationConfiguration.java

When using Memcached as the ticket registry, I encounter this error: `com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: org.apereo.cas.ticket.expiration.MultiTimeUseOrTimeoutExpirationPolicy$TransientSessionTicketExpirationPolicy`.
This PR fixes the problem.
I'm not sure about the v6.5.x backport: it's a bug, but it's also a breaking change. So what do we do?

Fix serialization configuration for Memcached

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/serialization/MessageSanitizationUtils.java
core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/serialization/MessageSanitizationUtilsTests.java

Sanitize OAuth2 refresh tokens in logs.
These informations are sensitive and should be sanitized
https://tools.ietf.org/id/draft-ietf-oauth-security-topics-12.html#compromised-resource-server

sanitize oauth refresh tokens in log

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/profile/OidcUserProfileViewRenderer.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/profile/OidcUserProfileViewRendererDefaultTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/profile/OidcUserProfileViewRendererFlatTests.java

On the OIDC user info endpoint, we return the user attributes in JSON format in a flat or not way.
For a single value attribute, I get: `"email": "jj@mail.com"` (FLAT) or `"attributes": { "email": "jj@mail.com" }` (none-FLAT).
When the response format is JWT (it means I get a JWS or JWE and not a JSON response), the attributes are arrays even if there is a single value in the array.
This PR fixes this consistency issue.
Two tests have been added (for the FLAT and none-FLAT modes).

Fix the consistency of the JWT attributes for the OIDC user info

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/profile/OidcUserProfileViewRenderer.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/profile/OidcUserProfileViewRendererDefaultTests.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/profile/OidcUserProfileViewRendererFlatTests.java

When the response is a JWS or JWE on the OIDC user info endpoint, the issuer is always `null`.
This PR fixes the problem. Tests have been updated accordingly.

Fix null issuer for JWS/JWE on the OIDC user info endpoint

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/introspection/OAuth20IntrospectionAccessTokenResponse.java

When introspecting an invalid or expired access token at /cas/oauth2.0/introspect the response body contains only the not null not 0 not false properties:
```
{
"scope": "CAS"
}
```
Previous version 6.1.x rendered this response:
```
{
"active": false,
"sub": null,
"scope": "CAS",
"iat": 0,
"exp": 0,
"realmName": null,
"uniqueSecurityName": null,
"tokenType": null,
"aud": "somehost/introspect",
"iss": "https://someotherhost/cas/oidc",
"client_id": "a_client_id",
"grant_type": null
}
```
It seems the JSON marshalling configuration was changed.
[https://datatracker.ietf.org/doc/html/rfc7662#section-2.2](https://datatracker.ietf.org/doc/html/rfc7662#section-2.2)
According to RFC7662 "OAuth 2.0 Token Introspection" section "2.2 Introspection Response" states
```
active
REQUIRED.
```
This can …

Fix oauth 2.0 introspection response according to rfc7662

---

support/cas-server-support-generic/src/main/java/org/apereo/cas/adaptors/generic/JsonResourceAuthenticationHandler.java
support/cas-server-support-generic/src/test/java/org/apereo/cas/adaptors/generic/JsonResourceAuthenticationHandlerTests.java
support/cas-server-support-generic/src/test/resources/sample-users.json

`JsonResourceAuthenticationHandler` did not work when using a `PasswordEncoder` (like MD5, SHA1, BCrypt ...) for storing encoded passwords in the JSON file.
This is because it didn't use the `originalPassword` when matching passwords, so it actually encoded it twice when doing the comparison. Existing test cases didn't cover the use of a `PasswordEncoder`, so I also added one.

Fix JsonResourceAuthenticationHandler to work with encoded passwords

---

support/cas-server-support-aup-couchdb/src/main/java/org/apereo/cas/config/CasAcceptableUsagePolicyCouchDbConfiguration.java
support/cas-server-support-dynamodb-service-registry/src/main/java/org/apereo/cas/config/DynamoDbServiceRegistryConfiguration.java
support/cas-server-support-events-couchdb/src/main/java/org/apereo/cas/config/CouchDbEventsConfiguration.java
support/cas-server-support-events-dynamodb/src/main/java/org/apereo/cas/config/CasEventsDynamoDbRepositoryConfiguration.java
support/cas-server-support-events-influxdb/src/main/java/org/apereo/cas/support/events/config/CasEventsInfluxDbRepositoryConfiguration.java
support/cas-server-support-events-mongo/src/main/java/org/apereo/cas/config/MongoDbEventsConfiguration.java
support/cas-server-support-saml-idp-metadata-couchdb/src/main/java/org/apereo/cas/config/CouchDbSamlIdPMetadataConfiguration.java
support/cas-server-support-saml-idp-metadata-mongo/src/main/java/org/apereo/cas/config/SamlIdPMongoDbIdPMetadataConfiguration.java

couch-db and couchDb is couchdb in most places
dynamodb class is specified with module as hazelcast
some modules had camelcase for Db while most did not
mongo is usually specified as mongo but was mongoDb in a couple places

change module attributes on features that are named differently elsewhere

---

ci/tests/redis/docker-compose.yml
support/cas-server-support-redis-service-registry/src/test/java/org/apereo/cas/adaptors/redis/services/RedisSentinelServerServiceRegistryTests.java
support/cas-server-support-redis-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/RedisSentinelServerTicketRegistryTests.java

This should fix the redis sentinel unit tests so they work with updated redis/sentinel. The tests work locally with docker for windows and I think they worked on linux once, although I might have made minor changes after that test.

fix redis sentinel tests

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/web/security/HttpHeadersRequestProperties.java
core/cas-server-core-web-api/src/main/java/org/apereo/cas/web/support/filters/ResponseHeadersEnforcementFilter.java
core/cas-server-core-web-api/src/test/java/org/apereo/cas/web/support/filters/ResponseHeadersEnforcementFilterTests.java
core/cas-server-core-web/src/test/java/org/apereo/cas/web/RegisteredServiceResponseHeadersEnforcementFilterTests.java
webapp/cas-server-webapp-config/src/main/java/org/apereo/cas/config/CasFiltersConfiguration.java

File extension of files that are considered as static resources, and therefore are cached, are hardcoded to CAS. With this change they can be dynamically changed with cas.http-web-request.header.cacheControlStaticResources application property. Its default value is css|js|png|txt|jpg|ico|jpeg|bmp|gif, which is the same value as the one that was hardcoded.

Allow to dynamically change which file extensions are considered as static resources.

---

ci/tests/puppeteer/cas.js
ci/tests/puppeteer/scenarios/x509-login-ldap-attributes/notusedattributes.groovy
ci/tests/puppeteer/scenarios/x509-login-ldap-attributes/script.js
ci/tests/puppeteer/scenarios/x509-login-ldap-attributes/script.json
core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/principal/resolvers/InternalGroovyScriptDao.java
core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/principal/resolvers/InternalGroovyScriptDaoTests.java
support/cas-server-support-person-directory/src/main/java/org/apereo/cas/config/CasPersonDirectoryGroovyConfiguration.java

When a groovy script is called and there are multiple groovy attribute repositories defined, they all get invoked by the `InternalGroovyScriptDao` without respect to whether they are in the active repository ids list and without respect to the order they are defined. I have another PR coming for person-directory that may help the case of groovy scripts that are defined but not in the active list, but this PR should take care of that case as long as the groovy DAOs are defined with ids.

fix groovy scripts so they are only run when they are the person dao under consideration

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/CoreAuthenticationUtils.java
core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/CoreAuthenticationUtilsTests.java

Pretty sure this method isn't used, and it can be distracting when trying to trace how CAS interacts with person directory.

remove unused method

---

support/cas-server-support-thymeleaf/src/main/resources/static/js/webauthn/webauthn.js

**Reason:** 
Currently, the WebAuthN flow allows to use devices which's attestations cannot be veryified/trusted, through the property `cas.authn.mfa.web-authn.core.allow-untrusted-attestation=true` . But when I enabled this flow, I realized that the UI wasn't receiving the attestationMetadata, which, from what I read at https://webauthn-doc.spomky-labs.com/webauthn-in-a-nutshell/attestation-and-metadata-statement, seems to make sense, as the attestation wasn't being checked. But the code between lines 541-546 at webauthn.js was assuming this metadatada was available, trying to access it, and breaking the authentication flow in the process.
**Changes:**
In order to avoid this problem, I added a check before the code that accessed the metadata, to execute it only when that metadata is …

support non-existence of deviceProperties in webauthn flow

---

api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/TransientSessionTicket.java
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/expiration/MultiTimeUseOrTimeoutExpirationPolicy.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/expiration/MultiTimeUseOrTimeoutExpirationPolicyTests.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/VerifyPasswordResetRequestAction.java

Following up https://github.com/apereo/cas/pull/5505
The `MultiTimeUseOrTimeoutExpirationPolicy` now uses a hard timeout.
BTW, the expiration test is revisited in `VerifyPasswordResetRequestAction`.
Waiting for the build to pass...

Use a hard timeout for the multi use policy

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/slo/OidcSingleLogoutServiceMessageHandler.java

This is a small fix, but the spec clearly states that the "The POST body uses the application/x-www-form-urlencoded encoding and must include a logout_token parameter" (not a request parameter).
See: https://openid.net/specs/openid-connect-backchannel-1_0.html#BCRequest

Fix the OIDC back channel logout

---

gradle.properties
support/cas-server-support-oauth-uma/src/main/java/org/apereo/cas/config/CasOAuthUmaConfiguration.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuth20ThrottleConfiguration.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcEndpointsConfiguration.java

Two things are done when upgrading:
- passing the `JEEHttpActionAdapter.INSTANCE` to the `SecurityInterceptor` is useless, it is the default `HttpActionAdapter`: https://github.com/pac4j/spring-webmvc-pac4j/blob/spring-webmvc-pac4j-6.1.0/src/main/java/org/pac4j/springframework/web/SecurityInterceptor.java#L89
- the "smart" builder `SecurityInterceptor.build` can be used for multiple input types: https://github.com/apereo/cas/compare/master...leleuj:cas:springwebmvcpac4j61?expand=1#diff-68d41d51d66f4e3c4fa771feef620c44c6482e98cc7f1549fed760706816ca0aR192
This is only a proposal. Keep what you think is clearer to you.

Upgrade to spring-webmvc-pac4j v6.1.0

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/git/services/BaseGitProperties.java
support/cas-server-support-git-core/src/main/java/org/apereo/cas/git/DefaultGitRepository.java
support/cas-server-support-git-core/src/main/java/org/apereo/cas/git/GitRepositoryBuilder.java
support/cas-server-support-git-core/src/test/java/org/apereo/cas/git/GitRepositoryTests.java

If CAS is configured with a git service registry but is not configured to push to the remote repo, and if it auto-generates a service (e.g. due to configured saml service provider metadata), then it can't pull any new services without someone manually resetting the local repository on each server to remove the local commits. By allowing CAS to rebase on pulls, the local commit stays local but doesn't prevent new services from being added.

Add rebase option to git

---

support/cas-server-support-saml-idp-metadata/src/main/java/org/apereo/cas/support/saml/services/idp/metadata/cache/resolver/MetadataQueryProtocolMetadataResolver.java
support/cas-server-support-saml-idp-metadata/src/main/java/org/apereo/cas/support/saml/services/idp/metadata/cache/resolver/UrlResourceMetadataResolver.java
support/cas-server-support-saml-idp-metadata/src/test/java/org/apereo/cas/support/saml/services/idp/metadata/cache/SamlRegisteredServiceDefaultCachingMetadataResolverTests.java
support/cas-server-support-saml-idp-metadata/src/test/java/org/apereo/cas/support/saml/services/idp/metadata/cache/resolver/MetadataQueryProtocolMetadataResolverTests.java
support/cas-server-support-saml-idp-metadata/src/test/java/org/apereo/cas/support/saml/services/idp/metadata/cache/resolver/UrlResourceMetadataResolverTests.java
support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/config/SamlIdPMetadataConfiguration.java

This allows to reuse the `httpClient` configuration in the SAML URL metadata fetching.

Use the HttpClient to fetch SAML metadata

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/authenticator/OAuth20UsernamePasswordAuthenticator.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/authenticator/OAuth20UsernamePasswordAuthenticatorTests.java

If I perform an OAuth authorization code grant type and then look at the data (`/cas/actuator/ssoSessions`), I see the `clientIpAddress` in the authentication attributes.
This is not the case if I perfom an OAuth resource password grant type.
In both cases, the authentication attributes have been properly computed by the CAS `authenticationManager`. The problem comes from the `OAuth20UsernamePasswordAuthenticator` which does not save into the `pac4j` profile the authentication attributes (which would then be retrieved by the `OAuth20DefaultCasAuthenticationBuilder` and put in the CAS `Authentication`).
This PR fixes the problem.

Add authentication attributes on resource password grant type

---

webapp/cas-server-webapp-config/src/main/java/org/apereo/cas/web/security/CasWebSecurityConfigurerAdapter.java
webapp/cas-server-webapp-config/src/test/java/org/apereo/cas/web/security/CasWebSecurityConfigurerAdapterWebTests.java

This is restoring the ability to use IP subnet patterns for the `requiredIpAddresses`  property on actuators, something that was supported in versions before 6.6. It also supports regular expressions. The stream through the various patterns filters out likely regular expressions, then creates an `IpAddressMatcher` to see if the value is an IP or subnet and if it is valid it creates `IpAddressMatcher` again and checks if it matches against the remote IP. If there is a way to get the `IpAddressMatcher` the first time it is created while ignoring the exception, that would be better. Alternatively, there could be two different properties for `requiredIpAddresses` and `requiredIpNetworks`.

restore support for IP subnet authz on actuators

---

webapp/cas-server-webapp-config/src/main/java/org/apereo/cas/web/security/CasWebSecurityConfigurerAdapter.java
webapp/cas-server-webapp-config/src/test/java/org/apereo/cas/web/security/CasWebSecurityConfigurerAdapterWebTests.java

Backport to 6.6.x for more compatibility with previous releases.

backport - restore support for IP subnet authz on actuators (#5523)

---

core/cas-server-core-events-api/src/main/java/org/apereo/cas/support/events/listener/CasAuthenticationAuthenticationEventListener.java
core/cas-server-core-events/src/test/java/org/apereo/cas/support/events/CasAuthenticationEventListenerTests.java

Set the correct event id in event DTO for `CasAuthenticationTransactionFailureEvent`

Correct event id for CasAuthenticationTransactionFailureEvent

---

build.gradle

Since Gradle 7, the `maven` plugin does no longer exist: https://docs.gradle.org/7.0/userguide/upgrading_version_6.html?_ga=2.160666173.1473045748.1668408332-1466678468.1668408332#removal_of_the_legacy_maven_plugin
This PR fixes the Maven support by upgrading to the `maven-publish` plugin.

Fix Maven support

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/DefaultLogMessageSummarizer.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/LoggingUtils.java

I had the logic wrong in the shouldSummarize method but the order of the FunctionUtils.doIf was also wrong to compensate, so it was working, but the method name didn't make sense (e.g. you would have to return true from shouldSummarize to turn off summarization).

fix so method name makes sense

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/passwordless/PasswordlessAuthenticationCoreProperties.java
support/cas-server-support-passwordless-authentication/src/main/java/org/apereo/cas/config/PasswordlessAuthenticationConfiguration.java
support/cas-server-support-passwordless-authentication/src/test/java/org/apereo/cas/AllTestsSuite.java
support/cas-server-support-passwordless-authentication/src/test/java/org/apereo/cas/authentication/DisablePasswordlessTokenAuthenticationTests.java

Use `cas.authn.passwordless.core.enabled` to turn passwordless authentication on or off.

Support for enabling or disabling passwordless authentication

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/function/FunctionUtils.java
webapp/cas-server-webapp-config/src/main/java/org/apereo/cas/web/security/CasWebSecurityConfigurerAdapter.java

I don't think these FunctionUtils.doAndHandle() methods should be doing warning logging, it seems like that is better left to the lambda error handler. At least in the case of `CasWebSecurityConfigurerAdapter.configureEndpointAccessByIpAddress()` [Here](https://github.com/apereo/cas/blob/master/webapp/cas-server-webapp-config/src/main/java/org/apereo/cas/web/security/CasWebSecurityConfigurerAdapter.java#L302) - it causes a problem because the method gets called over and over and will log stuff like:
```
2022-12-30 04:56:47,548 WARN [org.apereo.cas.util.function.FunctionUtils] - <Failed to parse address '10\..*'
IpAddressMatcher.java:parseAddress:96
IpAddressMatcher.java:<init>:58
CasWebSecurityConfigurerAdapter.java:lambda$configureEndpointAccessByIpAddress$8:303
```
repeatedly if the …

don't log warnings in FunctionUtils.doAndHandle

---

support/cas-server-support-sms-smsmode/src/main/java/org/apereo/cas/support/sms/SmsModeSmsSender.java
support/cas-server-support-sms-smsmode/src/test/java/org/apereo/cas/support/sms/SmsModeSmsSenderTests.java

The SmsMode support is broken as the access token is not sent.
This PR fixes the problem and adjusts the related test.
I'm wondering if this support has ever worked.

Fix the SmsMode support

---

core/cas-server-core-services/src/main/java/org/apereo/cas/config/CasCoreServicesConfiguration.java

Due to lazzy initialization, the service reloading scheduler must be marked `@Lazy(false)`.

Fix services reloading

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/sms/SmsModeProperties.java
support/cas-server-support-sms-smsmode/src/main/java/org/apereo/cas/support/sms/SmsModeSmsSender.java
support/cas-server-support-sms-smsmode/src/test/java/org/apereo/cas/support/sms/SmsModeSmsSenderTests.java

The current API of SmsMode is deprecated: https://dev.smsmode.com/http-api/reference/
This PR uses the appropriate SmsMode API: https://dev.smsmode.com/sms/v1/message/
The test has been updated as well.
I have of course made manual tests with a working API key I can't share publicly.

Upgrade the SmsMode support

---

support/cas-server-support-thymeleaf/src/main/resources/templates/interrupt/casInterruptView.html

Quick'n'dirty fix for exception below. There may be better solutions?
org.springframework.expression.EvaluationException: Calling
method 'next' is forbidden for type 'class java.util.LinkedHashMap$LinkedValueIterator'
in Thymeleaf expressions. Blocked classes are: [com.sun.*, jakarta.*, java.*, javax.*, jdk.*, org.ietf.jgss.*, org.omg.*, org.w3c.dom.*, org.xml.sax.*, sun.*].
Allowed classes are: [java.lang.Boolean, ..., java.util.LinkedHashMap, java.util.LinkedHashSet, java.util.LinkedList, java.util.List, java.util.Locale, java.util.Map, java.util.Map$Entry, ...].
at org.thymeleaf.spring6.expression.ThymeleafEvaluationContext$ThymeleafEvaluationContextACLMethodResolver.resolve(ThymeleafEvaluationContext.java:282)
NB: the list of allowed classes seems to come from …

fix casInterruptView.html autoRedirect (broken by new Thymeleaf?)

---

ci/tests/puppeteer/scenarios/oidc-authn-claims-scoped-subset-plusseparator/script.js
ci/tests/puppeteer/scenarios/oidc-authn-claims-scoped-subset-plusseparator/script.json
ci/tests/puppeteer/scenarios/oidc-authn-claims-scoped-subset-plusseparator/services/Sample-1.json
ci/tests/puppeteer/scenarios/oidc-authn-claims-scoped-subset/script.js
ci/tests/puppeteer/scenarios/oidc-authn-claims-scoped-subset/script.json
ci/tests/puppeteer/scenarios/oidc-authn-claims-scoped-subset/services/Sample-1.json

When doing integration tests between the pac4j OIDC client (6.0.0-RC5-SNAPSHOT) and the CAS server v7.0.0-SNAPSHOT for an OIDC service with approval, I noticed that the scopes were not properly taken into account.
This is due to the + between the scopes in the /authorize URL instead of %20.
My feeling is that it's better to use %20, but it may be interesting to support + as well for backward compatibility.
I can of course patch pac4j v6.0.0-RC5-SNAPSHOT (I already did that locally) if you prefer not to fix it on the CAS server side.
To demonstrate the problem, this PR adds 2 Puppeteer tests: one with %20 which passes and one with + which fails.

Support + as the scope separator in OIDC authorize URL

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/sms/SmsModeProperties.java
support/cas-server-support-sms-smsmode/src/main/java/org/apereo/cas/support/sms/SmsModeSmsSender.java

Small change to allow the use of a proxy for the `SmsModeSmsSender`.

Allow to define a proxy for the SmsMode support

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/saml/idp/SamlIdPLogoutProperties.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/slo/SamlIdPSingleLogoutServiceLogoutUrlBuilder.java
support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/config/SamlIdPConfiguration.java

The CAS server always tries to send a SAML logout request using the POST binding, then the REDIRECT binding and finally the SOAP binding.
This PR allows to configure that bindings order.
Notice that the `logoutRequestBindings` property of the `SamlIdPLogoutProperties` class does not contain any default values to avoid pulling the `opensaml-saml-api` dependency.
The default values are computed in the `SamlIdPSingleLogoutServiceLogoutUrlBuilder` component.

Allow to configure the SAML logout request bindings

---

api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/registry/TicketRegistry.java

This PR fixes a small typo I found while reviewing the ticket registry API update (`getSessionsWithAttributes`).

Fix typo in TicketRegistry

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/response/OAuth20JwtAccessTokenEncoder.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/OAuth20TestsSuite.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/response/accesstoken/response/OAuth20JwtAccessTokenEncoderTests.java

While trying to get OIDC login to Rancher working with CAS, their OIDC library wanted the access token in JWT format and it wanted the audience(s) in the token to contain the client id, but CAS was returning something else. Per the specification CAS could return a list of audiences but if it is only returning one, it needs to be the client id.
https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.2
aud:
REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.
This …

make sure audience in jwt access token contains client id

---

docs/cas-server-documentation/installation/Logout-Single-Signout.md
docs/cas-server-documentation/protocol/CAS-Protocol-Specification.md

In the latest CAS server versions, the `NameID` in the CAS logout request is the principal identifier and no longer the constant `@NOT_USED@`.
This PR fixes this inconsistency in the spec.

Fix inconsistency in spec

---

README.md
docs/cas-server-documentation/authentication/OIDC-Authentication-DPoP.md
docs/cas-server-documentation/authentication/X509-Authentication.md
docs/cas-server-documentation/configuration/Configuration-Management-Clustered.md
docs/cas-server-documentation/configuration/Configuration-Server-Management-SpringCloud-Default.md
docs/cas-server-documentation/configuration/Configuration-Server-Management-SpringCloud-HashiCorpConsul.md
docs/cas-server-documentation/developer/Build-Process.md
docs/cas-server-documentation/developer/Contributor-Guidelines.md
docs/cas-server-documentation/protocol/CAS-Protocol-Specification.md
docs/cas-server-documentation/protocol/CAS-Protocol-V2-Specification.md
docs/cas-server-documentation/release_notes/RC4.md

Firstly, I was about to fix just `This page MUST include a form with the parameters, "username", "password", and "lt"` which doesn't seem to be true (as LT is no longer used by CAS itself), in the "docs/cas-server-documentation/protocol/CAS-Protocol-Specification.md". But then IDEA gave me hints on some other typos, so I decided to fix some of them beforehand.
I have focused basically on some basic MD files + fixed some of the typos also in other MD files by using "Replace in files"...

docs: fix grammatical and name typos

---

ci/tests/puppeteer/scenarios/oidc-par-authzcode-login/script.js
ci/tests/puppeteer/scenarios/oidc-par-authzcode-login/script.json
ci/tests/puppeteer/scenarios/oidc-par-authzcode-login/services/Sample-1.json

This PR is a Puppeteer test demonstrating the expected behavior for the PAR support:
1) A request is made to `/oidcPushAuthorize` to get the `request_uri`
2) A request is made to `/authorize` with the `client_id` and `request_uri`: a login is performed for `casuser`/`Mellon`
3) The `code` is retrieved to get the `access token`
4) The profile is retrieved thanks to the `access token`.
The profile should be the one of `casuser`, not of the OIDC `client`. This is where it currently fails: https://github.com/apereo/cas/compare/master...leleuj:cas:par?expand=1#diff-79f0ef8304f34731da561bfb8a1d0302cccac54ca82ed524033ae11c14f24ab4R63

Expected PAR behavior

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/web/view/ViewProperties.java
support/cas-server-support-themes-core/src/main/java/org/apereo/cas/services/web/AggregateCasThemeSource.java
support/cas-server-support-themes/src/main/java/org/apereo/cas/services/web/config/CasThemesConfiguration.java
support/cas-server-support-themes/src/test/java/org/apereo/cas/ThemesTestsSuite.java
support/cas-server-support-themes/src/test/java/org/apereo/cas/services/web/AggregateCasThemeSourceTests.java
support/cas-server-support-themes/src/test/resources/more-ext-templates/my-theme.properties

From what I can tell the default theme source for resource bundles only gets the first theme it finds (across the different them prefix locations). I would like to have a default set of values for a theme in the classpath but then override some values in different deployments externally. This PR adds a themeSourceType of "AGGREGATE" that merges all the found bundles for the theme, with the default location used as the parent bundle.
Since the properties are added to the bundle in order that they are found, values from the first template prefixes will be overridden by the same value in later prefixes. That might be different than what happens for other template resources. This could be changed by looping through the template prefixes in reverse order or someone could just store their theme …

add aggregate theme source

---

support/cas-server-support-thymeleaf/src/main/java/org/apereo/cas/config/CasThymeleafConfiguration.java
support/cas-server-support-thymeleaf/src/test/java/org/apereo/cas/web/view/CasThymeleafConfigurationTests.java

```
val prefixPath = ResourceUtils.getFile(prefix).getCanonicalPath();
```
That fails if the classpath template prefix is inside war or jar so this change avoids calling it for classpath entries.
The `ThemeClassLoaderTemplateResolver` doesn't want the `classpath:` prefix so that needs to be stripped off.

update template view resolver

---

support/cas-server-support-saml-idp-core/src/main/java/org/apereo/cas/support/saml/services/idp/metadata/SamlRegisteredServiceServiceProviderMetadataFacade.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/nameid/SamlProfileSamlNameIdBuilder.java
support/cas-server-support-themes-core/src/main/java/org/apereo/cas/services/web/RegisteredServiceThemeResolver.java

An application I am using produces SP metadata with no NameID in the metadata and a short expiration that requires me to use a url to download it from the server (via service metadataLocation). Based on debug output, the `supportedNameFormats` collection contains a null entry and my theory is that a NameIDFormat must be getting created somewhere with a null URI. I haven't figured out where that is yet and haven't been able to re-create in a unit test yet. 
```
2023-04-27 13:22:49,380 WARN [org.apereo.cas.support.saml.web.idp.profile.builders.nameid.SamlProfileSamlNameIdBuilder] - <Required NameID format [urn:oasis:names:tc:SAML:2.0:nameid-format:transient] in the AuthN request issued by [https://rke2.mgmt.example.com/v1-saml/shibboleth/saml/metadata] is not supported based on the metadata …
```

WIP - SAML NPE when sp metadata doesn't contain nameid

---

support/cas-server-support-saml-core-api/src/main/java/org/apereo/cas/support/saml/util/AbstractSaml20ObjectBuilder.java
support/cas-server-support-saml-core/src/test/java/org/apereo/cas/support/saml/util/NonInflatingSaml20ObjectBuilderTests.java

I was seeing stack trace warnings logged during a saml login when the code was trying to parse a guid in the `inResponseTo` as a URL. This change tries to get an IP address by parsing the `recipient` which can be URL if it isn't blank. If there is a scenario where the `inResponseTo` starts with a URL, maybe we could parse it if it contains a colon?

update saml to avoid unnecessary stack trace

---

ci/tests/puppeteer/scenarios/login-success-double-renew/script.js
ci/tests/puppeteer/scenarios/login-success-double-renew/script.json
support/cas-server-support-actions-core/src/main/java/org/apereo/cas/web/flow/login/InitialFlowSetupAction.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/InitialFlowSetupActionTests.java

One of my clients reported me an issue in this scenario:
1) `/cas/login` : log in
2) `/cas/login?renew=true`
3) `/cas/login?renew=true`
On the second call to `/cas/login?renew=true`, the message "Welcome back, xxx" is no longer displayed.
The problem comes from this commit: https://github.com/apereo/cas/commit/a0287d7d4b45099e86ef6d59d8c75f7514d2a14b#diff-284e7c342f29ec14acba7e243063917a451cc6ba18f2e1c170f3c7e1d12355d7R184
So I have replaced the full TGT removal (cookie + ticket registry + webflow) by a simple removal in the webflow.
I have added a Puppeteer test to confirm the correct behavior and I have checked that this PR does not break the following scenarios (related to "renew"): `sso-globally-disabled`, `renew-existing-sso` and `ticket-validation-cas-renew`.
The unit test has been …

Fix the double renew call

---

.github/workflows/puppeteer.yml
ci/tests/puppeteer/scenarios/oidc-login-sonarqube/script.js
ci/tests/puppeteer/scenarios/oidc-login-sonarqube/sonarqube-test-values.yaml

This works locally and it worked on my fork when I increased the retry timeout to 20 minutes, at that time it worked in less than 15 minutes. It seemed like it was allowed to run for 20 minutes when it was failing on the main project. I thought the problem was that they were disabling all plugins until an admin logged in once and accepted the risk, although I not 100% sure that was the issue, but I set a property to accept risk. Going directly to the link that sonarqube redirects to seemed to help and so did increasing the timeout.

fix sonarqube puppeteer test

---

core/cas-server-core-web-api/src/main/java/org/apereo/cas/web/support/CasLocaleChangeInterceptor.java
core/cas-server-core-web/src/test/java/org/apereo/cas/web/support/CasLocaleChangeInterceptorTests.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/PasswordChangeAction.java

I have encountered an issue with the `locale` parameter when upgrading from CAS v5 to CAS v6.
In CAS v5, the `LocaleChangeInterceptor` was based (by default) on `StringUtils.parseLocaleString(locale)`, meaning that the region is separated from the language by `_` (underscore).
In CAS v6, the `CasLocaleChangeSeparator` is based on `Locale.forLanguageTag`, meaning that the region is separated from the language by `-` (dash).
As I cannot control old CAS clients still using the `_` (underscore) in URLs, I propose this PR to bring backward compatibility.

Add backward compatibility for the locale parameter

---

support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/util/LdapUtils.java

One of my clients has reported me a tricky bug with LDAP direct binding.
I have been able to reproduce it with OpenLDAP. Here is my Docker configuration:
```
version: '2'
services:
openldap:
image: docker.io/bitnami/openldap:2.6
ports:
- '1389:1389'
- '1636:1636'
environment:
- LDAP_ROOT=dc=example,dc=com
- LDAP_USER_DC=people
- LDAP_USERS=jleleu
- LDAP_PASSWORDS=password
- LDAP_ALLOW_ANON_BINDING=no
volumes:
- './data:/bitnami/openldap'
```
And my CAS configuration:
```
cas.authn.ldap[0].type: DIRECT
cas.authn.ldap[0].principal-attribute-list: cn,sn,displayName
cas.authn.ldap[0].ldap-url: ldap://localhost:1389
cas.authn.ldap[0].base-dn: ou=people,dc=example,dc=com
cas.authn.ldap[0].dn-format: cn=%s,ou=people,dc=example,dc=com
```
With both settings, the authentication works great and I …

Fix LDAP direct bind

---

support/cas-server-support-webauthn-core-webflow/src/main/java/org/apereo/cas/webauthn/web/flow/WebAuthnMultifactorDeviceProviderAction.java

If a MFA device has no attestation metadata (like WebAuthn via Android FIDO2 API), this leads to a NullpointerException when calling Account Management --> Multifactor Devices.
Registration of such devices is only possible via `cas.authn.mfa.web-authn.core.allow-untrusted-attestation=true`.

Fixing potential NullpointerException

---

webapp/cas-server-webapp-resources/src/main/resources/application.properties

With background-processor-delay=0s, tomcat background process is disabled. All org.apache.catalina.session.StandardSession objects are kept in memory, resulting in a small but steady increase in memory usage, ending in OutOfMemory after some time (one month in our case)
NB: it only impacts spring-boot embedded tomcat.

tomcat background process is needed to cleanup sessions

---

support/cas-server-support-thymeleaf/src/main/resources/messages_de.properties

PR #5550 changed the file enconding of the german translation to ISO-8859-1, which means, that `spring.thymeleaf.encoding=ISO-8859-1` and `cas.message-bundle.encoding=ISO-8859-1` has to be set. This seems inconsistent with all other languages files, which are UTF-8 of course.
This PR contains a UTF-8 version of all changes @ThomasSeliger did (thank you!) by using `iconv -f ISO-8859-1 -t UTF-8`.
Afterwards no more custom encoding setting via `spring.thymeleaf.encoding` and  `cas.message-bundle.encoding` is needed.

Use UTF-8 for german message bundle, like it was before PR #5550

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/redis/BaseRedisProperties.java
support/cas-server-support-redis-core/src/main/java/org/apereo/cas/redis/core/RedisObjectFactory.java
support/cas-server-support-redis-core/src/test/java/org/apereo/cas/redis/core/RedisObjectFactoryTests.java

For some Redis cloud providers, it is useful to be able to use a Redis URI to connect to the database.
This PR allows to use a URI to connect to Redis.

Support URI for Redis

---

core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/ResourceUtils.java
core/cas-server-core-util/src/test/java/org/apereo/cas/util/ResourceUtilsTests.java
support/cas-server-support-themes-core/src/main/java/org/apereo/cas/services/web/RegisteredServiceThemeResolver.java

I was looking at this class and the Javadoc had a sentence that didn't make sense, so I tried to describe what the logic was in the class. While doing so I noticed that if the theme is returned from a script or url, there is no check to make sure a property file exists for that theme. It wouldn't be hard to pass the theme to `resolveThemeForService()` and check for the file in the prefix locations or as a resource bundle, but I didn't do that.
I also noticed two places in ResourceUtils where a stream is passed to a method that doesn't close it and it is outside of a resource try block. I was sort of on the lookout for resource leaks because I had a CAS server in dev stop working due to what looked like a resource leak shortly after I configured template prefixes and …

update javadoc and close stream resources

---

webapp/cas-server-webapp-resources/src/main/resources/log4j2.xml

I believe CAS should supply somewhat more reasonable settings in the default log4j2.xml. This is the 1st package of the possible improvements, regarding the **log patterns**:
* fix: logging to file used a non-standard format (missing milliseconds, time hardcoded to "GMT-7"). Use the same log pattern with pre-defined `%highlight` for both appenders instead.
* have stacktraces colored as well (when they are turned on) - by wrapping `%throwable` into the `%highlight` as in the Log4j documentation examples
* make the highlighting being on/off configurable per appender AND switch the defaults to the more common one: highlights in console, not in file. Note: To get highlighting e.g. in IDEA console on Windows, `disableAnsi=false` needs to be set explicitly.
---
Sources:
* …

feat: make console and file log patterns consistent and more configurable

---

docs/cas-server-documentation/mfa/GoogleAuthenticator-Authentication.md

Remove the misleading chapter "Repository Cleaner" and move the `cas.authn.mfa.gauth.cleaner` properties section to the chapter for which it is actually valid: "Token Repository".
---
I apologize if I overlooked something, but from the code for the Google Authenticator (GAuth) MFA, it really looks like there is no cleanup job for the expired device registrations (search [here](https://github.com/search?q=repo%3Aapereo%2Fcas%20%22cas.authn.mfa.gauth.cleaner%22&type=code)). Maybe it was there some time ago and got removed?

docs: there is no "expired device registrations" cleaner for GAuth

---

webapp/cas-server-webapp-resources/src/main/resources/log4j2.xml

This change follows the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). This setting also defaults to `true` in the log4j2.xml of the CAS Initializr (WAR overlay) project.

feat: set `log.console.stacktraces` to `true` by default

---

support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/util/LdapUtils.java

Both DigestMD5 and CramMD5 require DN and password.

Support DN and password for LDAP SASL.

---

api/cas-server-core-api-authentication/src/main/java/org/apereo/cas/authentication/RootCasException.java
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/registry/AbstractTicketRegistry.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/InvalidTicketExceptionTests.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/BaseTicketRegistryTests.java

This changes the RootCasException to print out the code rather than a null message, e.g. when InvalidTicketException is created with the code. InvalidTicketException could do something with the ticketId but it doesn't. 
I also added a check to getTicket() to warn when it sees tickets created in the future. In a cluster of two servers, if the time is out of sync between the two servers, any service tickets that originate on the ahead server will be expired on the behind server when they are validated. This might not be obvious right away because about 25% of the ticket validations will fail. By checking for future dated tickets and logging a warning, this can be prevented. Since the default service ticket is only good for 10 seconds, it doesn't take much of a time sync issue to start …

add logging to catch time sync issues - 6.6.x

---

api/cas-server-core-api-authentication/src/main/java/org/apereo/cas/authentication/RootCasException.java
core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/registry/AbstractTicketRegistry.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/InvalidTicketExceptionTests.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/BaseTicketRegistryTests.java

Port forward of #5715 
I removed the null check in the getTicket() predicate since it was no longer there on master - may not be necessary in 6.6.x either but I will leave it in 6.6.x.

add logging to catch time sync issues

---

webapp/cas-server-webapp-resources/src/main/resources/application.properties

With background-processor-delay=0s, tomcat background process is disabled. All org.apache.catalina.session.StandardSession objects are kept in memory, resulting in a small but steady increase in memory usage, ending in OutOfMemory after some time (one month in our case)
NB: it only impacts spring-boot embedded tomcat.
master: https://github.com/apereo/cas/pull/5652

 tomcat background process is needed to cleanup sessions

---

gradle/dependencies.gradle

I don't think this dependency is used by CAS and cqengine uses a fairly old version of the dependency. 
This says that users of cqengine are welcome to either exclude or update the version of the dependency. https://github.com/npgall/cqengine/issues/317

remove unused sqlite dependency

---

docs/cas-server-documentation/authentication/OAuth-Authentication-TokenExpirationPolicy.md

```
master: https://github.com/apereo/cas/pull/5760
```

Fix typo in OAuth doc

---

core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/GroovyScriptAttributeReleasePolicy.java
core/cas-server-core-authentication-attributes/src/test/java/org/apereo/cas/services/GroovyScriptAttributeReleasePolicyTests.java

I was noticing a lot of Groovy script parsing in my deployment, and it turned out that the scripts I was mapping into CAS container via k8s config map were getting "modified" frequently but not actually changing - presumably as a result of k8s doing something but I don't know what. Those modify events were triggering script parsing of cached scripts and that was taking a long time (>5 seconds per script), possibly because of various locks and what looked like classpath scanning. Anyway, I turned off the flag that added watches to all the scripts and then I noticed that one particular type of script was still getting re-parsed every time it was accessed. I will change the way I get scripts into my container to avoid the watch/modify issue, but this change employs the …

Don't reparse script in GroovyScriptAttributeReleasePolicy

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/redis/RedisSentinelProperties.java
ci/tests/redis/docker-compose.yml
support/cas-server-support-redis-core/src/main/java/org/apereo/cas/redis/core/RedisObjectFactory.java
support/cas-server-support-redis-service-registry/src/test/java/org/apereo/cas/adaptors/redis/services/RedisSentinelServerServiceRegistryTests.java
support/cas-server-support-redis-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/RedisSentinelServerTicketRegistryTests.java

Redis sentinel deployments can utilize separate passwords for connecting to redis and the sentinel service.
Expose property to set the sentinel password setting of on RedisSentinelConfiguration

optional usage of redis sentinel password

---

support/cas-server-support-oidc/src/main/java/org/apereo/cas/config/OidcConfiguration.java

This PR makes the `oidcAuthorizationSecurityLogic` bean overridable.

Open up for multihost

---

support/cas-server-support-webconfig/src/main/java/org/apereo/cas/web/security/CasWebSecurityConfigurerAdapter.java
support/cas-server-support-webconfig/src/test/java/org/apereo/cas/web/security/CasWebSecurityConfigurerAdapterWebTests.java

On CAS 7.x I am seeing several OIDC applications that are passing clientid/clientSecret as Basic auth header on the `POST /cas/oidc/oidcAccessToken`. Spring Security has basic auth filter that will try to authenticate that user against default authentication provider that doesn't know about the oidc service users so it will fail authentication and spring security returns a 401. 
The test `verifyCasLoginBasicAuth()` simulates this issue using the `/login` method which is configured similarly to `/oidc/oidcAccessToken` and it would fail if not for the change I made to move all the protocol methods to the ignoring list rather than the permitAll list. I think permitAll only works if there is no credential that spring security has a filter to verify and I don't know how to get rid of the …

WIP - Test basic auth for cas endpoints.

---

ci/tests/puppeteer/scenarios/oidc-login-sonarqube/init.sh
ci/tests/puppeteer/scenarios/oidc-login-sonarqube/sonarqube-test-values.yaml

This test was failing because the init container that installs the oidc plugin didn't have curl to download the plugin.

fix sonarqube functional test

---

support/cas-server-support-pac4j-core/src/main/java/org/apereo/cas/web/flow/DelegatedAuthenticationSingleSignOnParticipationStrategy.java
support/cas-server-support-pac4j-core/src/test/java/org/apereo/cas/web/flow/DelegatedAuthenticationSingleSignOnParticipationStrategyTests.java

[2023-11-24 17:04:33.705+08:00]-[ERROR]-[https-jsse-nio-172.18.0.44-18443-exec-5]-[dspcas_rest_1700816673684_e2b65365cd8149f0b6e52785dd7d0763]-[]-[org.apereo.cas.web.flow.actions.DelegatedClientAuthenticationAction()] No value present[N] null:orElseThrow:-1[N] DelegatedAuthenticationSingleSignOnParticipationStrategy.java:isParticipating:48[N] ChainingSingleSignOnParticipationStrategy.java:lambda$isParticipating$0:46[N]
When tgt is expired after execute method org.apereo.cas.web.flow.DelegatedAuthenticationSingleSignOnEvaluator#getSingleSignOnAuthenticationFrom, org.apereo.cas.web.flow.DelegatedAuthenticationSingleSignOnParticipationStrategy#isParticipating will throw NoSuchElementException exception, singleSignOnSessionExists method can't catch this exception.

fix NoSuchElementException is throwed when tgt is expired 

---

support/cas-server-support-palantir/client/src/index.scss
support/cas-server-support-thymeleaf/src/main/resources/static/css/cas.css
support/cas-server-support-thymeleaf/src/main/resources/templates/adaptive-authn/casRiskAuthenticationBlockedView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/adaptive-authn/casRiskAuthenticationVerifiedView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/delegated-authn/casDelegatedAuthnErrorView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/delegated-authn/casDelegatedAuthnStopWebflow.html
support/cas-server-support-thymeleaf/src/main/resources/templates/error/casServiceErrorView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/error/casUnauthorizedServiceRedirectView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/error/casWebflowConfigErrorView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/accountprofileoverview.html
support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/loginform.html
support/cas-server-support-thymeleaf/src/main/resources/templates/login-error/casAuthenticationBlockedView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/login-error/casBadHoursView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/login-error/casBadWorkstationView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/login/casGenericSuccessView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/mfa/casMfaDeniedView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/mfa/casMfaUnavailableView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/password-reset/casResetPasswordErrorView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/password-reset/casWeakPasswordDetectedView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/protocol/oauth/sessionStaleMismatchError.html
support/cas-server-support-thymeleaf/src/main/resources/templates/saml2-idp/casSamlIdPErrorView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/storage/casSessionStorageReadView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/storage/casSessionStorageWriteView.html
support/cas-server-support-thymeleaf/src/main/resources/templates/wsfed/casWsFedStopWebflow.html

This is the first part of Accessibility improvements for CAS. (Initiated by #5875)
This one focus only on styles changes and do not modify any CAS behavior.
Detailed corrections:
* Correct default contrast color (use https://app.contrast-finder.org/ ) (alert panels, buttons, etc...)
* Remove border-radius between password input and reveal-password button
* Increase notification font size (no font can be below 11px for proper a11y )
* Remove every "text-justify" occurences (W3C recommends to never justify text for a11y. See https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Supplemental_Guidance:_Text_Justification)

Improve style for A11y

---

gradle/dependencies.gradle

`checker-qual` is pulled by `guava` in v3.33.0 and pully by `caffeine` in v3.37.0.
This PR removes the duplication.

Remove duplicate checker-qual

---

gradle.properties

To avoid stack overflow errors for bad YAML.

Upgrade the snakeyaml library

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/response/OAuth20JwtAccessTokenEncoder.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/token/OidcJwtAccessTokenEncoderTests.java

I see an exception logged fairly regularly I think, but things seem to be working. The OAuth20JwtAccessTokenEncoder.decode method seems to expect non-encoded tokens because if there is an exception it returns the token as-is, if I am reading things right. I was initially going to add logging to figure out what was wrong with the token, but the fact that the handling of the exception consists of using the token as-is, I decided to look for ways to avoid the exception or avoid logging the exception. The first thing JWTParser.parse() does is check for a "." in the token so I am doing that to avoid calling the method so FunctionUtils doesn't log the exception. An alternative would be to not use FunctionUtils in this case. 
Unrelated, but it is unfortunate that exceptions logged by …

update decode method to avoid warning stack trace

---

ci/tests/puppeteer/scenarios/oauth2-login-jwt-at/script.js
support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileEndpointController.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileEndpointControllerTests.java

Depending on the malformed JWT access token sent to the OAuth /profile endpoint, a direct stack trace can be returned.
This PR sanitizes this issue by returning a generic "invalid_request" error.

Avoid strack traces on OAuth /profile

---

gradle/dependencies.gradle
gradle/overrides.gradle

This jakartaee-migration dependency doesn't sound like something CAS needs (since it is a utility for upgrading tomcat from 8 to 10), and it brings in a slightly old version of commons-compress which CAS doesn't otherwise use. 
I removed the code in overrides.gradle that avoids changing the version on jakartaee-migration because if something else somewhere decides to pull it in, this would fail and we could exclude it. 
I ran a puppeteer test after removing it and it worked.

remove jakartaee-migration dependency

---

gradle/dependencies.gradle

By default, the version `3.0.0-SNAPSHOT` of the `jackson-dataformat-cbor` dependency is pulled when using the WebAuthn dependency.
This PR fixes the version of the `jackson-dataformat-cbor` dependency.

Fix the jackson-dataformat-cbor dependency for WebAuthn

---

support/cas-server-support-redis-core/src/main/java/org/apereo/cas/redis/core/RedisObjectFactory.java
support/cas-server-support-redis-core/src/test/java/org/apereo/cas/redis/core/RedisObjectFactoryTests.java

Within the class RedisObjectFactory and the method newRedisModulesCommands there was a property setting missing on uriBuilder. Once the property "useSSL" has been defined and set on BaseRedisProperties object this property was never provided to the RedisURIBuilder. In our cas the missing of this setting led to connection exception to a redis instance. Also added missing test case for the change.

fixed setting ssl property to redis uriBuilder

---

api/cas-server-core-api-configuration-model/build.gradle

- Created an ad-hoc copy task for copying the modified spring configuration metadata to break the cyclic dependency. 
- Removed the generated file from sourceSets
The changes introduced here mean that Gradle doesn't track the inputs and outputs of the new `copyConfigurationMetadata` task - it is executed purely because of task dependencies configured - which are now configured in both ways - using `finalizedBy`, as well as `dependsOn`. I also marked `copyConfigurationMetadata` as not cacheable, as setting inputs and outputs will get picked up by the rest of the `compileJava` tasks (from modules that depend on `:api:cas-server-core-api-configuration-model`), which introduces a cyclic dependency problem.

Fixed generateConfigurationMetadata task setup

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/validator/DefaultOAuth20ClientSecretValidator.java

On client side (pac4j), I have:
```java
oidcConfiguration.setSecret(null);
oidcConfiguration.setDisablePkce(false);
```
On the CAS server side, I have:
```java
{
"@class" : "org.apereo.cas.services.OidcRegisteredService",
"clientId": "myclient",
"clientSecret": "mysecret",
"serviceId" : "^http://localhost:.*",
"name": "OIDC",
"id": 1,
"scopes" : [ "java.util.HashSet",
[ "openid", "email", "profile" ]
]
}
```
And I get the following error on the _authorization_code_ grant type : _Wrong client secret for service: [xxx]_ which is quite normal.
Though, I think we could improve the error log here with an extended message related to PKCE: _Wrong client secret for service: [xxx]. If you use PKCE and no client secret on client side, you need to set "clientSecret": null on the CAS server side_ …

Improve error log for PKCE

---

gradle/dependencies.gradle

In my basic CAS overlay based on the latest CAS WAR `7.1.0-SNAPSHOT`, I see the following dependencies:
```shell
jakarta.mail-2.0.1.jar
jakarta.mail-2.0.2.jar
micrometer-jakarta9-1.12.1.jar
micrometer-jakarta9-1.12.2.jar
```
In the CAS `gradle.properties`, there are:
```shell
jakartaMailVersion=2.0.1
micrometerVersion=1.12.2
```
This PR cleans the unwanted dependencies (`jakarta.mail-2.0.2.jar` and `micrometer-jakarta9-1.12.1.jar`).

Fix some Jakarta dependencies

---

gradle/dependencies.gradle

Reverts apereo/cas#5954
Breaks build with:
```
Caused by: java.lang.RuntimeException: Provider for jakarta.activation.spi.MimeTypeRegistryProvider cannot be found
at jakarta.activation.FactoryFinder.find(FactoryFinder.java:95)
at jakarta.activation.MimetypesFileTypeMap.getImplementation(MimetypesFileTypeMap.java:397)
at jakarta.activation.MimetypesFileTypeMap.loadFile(MimetypesFileTypeMap.java:270)
at jakarta.activation.MimetypesFileTypeMap.<init>(MimetypesFileTypeMap.java:107)
at jakarta.activation.MimetypesFileTypeMap.<init>(MimetypesFileTypeMap.java:312)
at org.springframework.mail.javamail.ConfigurableMimeFileTypeMap.createFileTypeMap(ConfigurableMimeFileTypeMap.java:150)
at org.springframework.mail.javamail.ConfigurableMimeFileTypeMap.getFileTypeMap(ConfigurableMimeFileTypeMap.java:12 …
```

Revert "Fix some Jakarta dependencies"

---

gradle/dependencies.gradle

In my basic CAS overlay based on the latest CAS WAR `7.1.0-SNAPSHOT`, I see the following dependencies:
```shell
micrometer-jakarta9-1.12.1.jar
micrometer-jakarta9-1.12.2.jar
```
In the CAS `gradle.properties`, there is:
```shell
micrometerVersion=1.12.2
```
This PR cleans the unwanted dependency (`micrometer-jakarta9-1.12.1.jar`).

Fix a Jakarta dependency

---

core/cas-server-core-web-api/src/main/java/org/apereo/cas/web/support/WebUtils.java
core/cas-server-core-web/src/test/java/org/apereo/cas/web/support/WebUtilsTests.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java
support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/AccountProfilePreparePasswordManagementAction.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurerTests.java
support/cas-server-support-pm-webflow/src/test/java/org/apereo/cas/pm/web/flow/actions/AccountProfilePreparePasswordManagementActionTests.java
support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/pmlinks.html

The display of the "Forgot username?" link should be tied to the `cas.authn.pm.forgot-username.enabled` property and not to the `cas.authn.pm.core.enabled` property.

Fix the 'forgot username' feature

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/passwordless/account/PasswordlessAuthenticationLdapAccountsProperties.java
support/cas-server-support-passwordless-ldap/src/main/java/org/apereo/cas/impl/account/LdapPasswordlessUserAccountStore.java
support/cas-server-support-passwordless-ldap/src/test/java/org/apereo/cas/impl/account/LdapPasswordlessUserAccountStoreTests.java

This PR adds a configuration to be able to choose the final username for the passwordless LDAP support.
The integration test has been updated accordingly.

For passwordless LDAP, allow to choose the final username

---

ci/tests/puppeteer/scenarios/passwordless-login-with-simplemfa/accounts.json
ci/tests/puppeteer/scenarios/passwordless-login-with-simplemfa/script.js
ci/tests/puppeteer/scenarios/passwordless-login-with-simplemfa/script.json
support/cas-server-support-simple-mfa/src/main/java/org/apereo/cas/config/CasSimpleMultifactorAuthenticationEventExecutionPlanConfiguration.java

In the specific use case of passwordless with MFA only, person directory is not called (in the Puppeteer test, it's a static attribute repository).

Problem with person directory when passwordless MFA only

---

ci/tests/puppeteer/scenarios/authn-throttle-with-username-authndelegation-enabled/script.js
ci/tests/puppeteer/scenarios/authn-throttle-with-username-authndelegation-enabled/script.json
support/cas-server-support-pac4j-core/src/main/java/org/apereo/cas/web/flow/error/DefaultDelegatedClientAuthenticationFailureEvaluator.java
support/cas-server-support-pac4j-core/src/test/java/org/apereo/cas/web/flow/error/DefaultDelegatedClientAuthenticationFailureEvaluatorTests.java

When using authn delegation, if a login is throtlled, the 423 error is returned and the `delegated-authn/casDelegatedAuthnStopWebflow.html` page is displayed instead of the `error/423.html` page.
This PR fixes the issue.

Fix authn delegation + throttling

---

support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/RedisTicketRegistry.java
support/cas-server-support-redis-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/RedisServerTicketRegistryTests.java

One of my customers has reported me a random issue with the Redis ticket registry although it happens rarely.
The error is: "Member count must be zero".
I have been able to reproduce it when performing multiple logins concurrently with the same user.
After removing the check on the size, it no longer occurs.
A unit test confirms the fix.

Fix the Redis ticket registry

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/web/security/HttpRequestProperties.java
core/cas-server-core-web-api/src/main/java/org/apereo/cas/web/support/filters/RequestParameterPolicyEnforcementFilter.java
core/cas-server-core-web-api/src/test/java/org/apereo/cas/web/support/filters/RequestParameterPolicyEnforcementFilterTests.java

master: https://github.com/apereo/cas/pull/5938
- Fix "parameters-to-check" property parsing to be comma-delimited so the default property value will work as expected
- Allow characters below 0x20 to be blocked by the filter by parsing the "characters-to-forbid" property as delimited only by the space character, rather than by any whitespace character
- Update unit tests as needed.

Fix RequestParameterPolicyEnforcementFilter configuration logic for 7.0.x branch

---

support/cas-server-support-pac4j-core-clients/src/test/java/org/apereo/cas/support/pac4j/authentication/clients/DelegatedAuthenticationClientsTestConfiguration.java
support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/actions/DelegatedClientAuthenticationAction.java
support/cas-server-support-pac4j-webflow/src/test/java/org/apereo/cas/web/flow/actions/DelegatedClientAuthenticationActionTests.java

In 6.6.x, when a pac4j client failed to validate its credentials (e.g. after receiving a SAML error response from the IdP, failing to verify the signature on a SAML response, etc.), the ``DelegatedClientAuthenticationAction`` handled the error by returning a ``stop`` event, causing the webflow to move to the ``stopWebflow`` state.  In 7.0.x and 7.1.x, it will return a ``generate`` event, which does not indicate an error, and the webflow continues on to ``viewLoginForm`` with no error messages, which would be terribly confusing to my users.
This PR restores the 6.6.x behavior.   A test has been added to verify (which fails without the change to ``DelegatedClientAuthenticationAction``).

Stop webflow when pac4j client getCredentials() fails

---

support/cas-server-support-pac4j-core-clients/src/test/java/org/apereo/cas/support/pac4j/authentication/clients/DelegatedAuthenticationClientsTestConfiguration.java
support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/actions/DelegatedClientAuthenticationAction.java
support/cas-server-support-pac4j-webflow/src/test/java/org/apereo/cas/web/flow/actions/DelegatedClientAuthenticationActionTests.java

master: https://github.com/apereo/cas/pull/5987
In 6.6.x, when a pac4j client failed to validate its credentials (e.g. after receiving a SAML error response from the IdP, failing to verify the signature on a SAML response, etc.), the ``DelegatedClientAuthenticationAction`` handled the error by returning a ``stop`` event, causing the webflow to move to the ``stopWebflow`` state.  In 7.0.x and 7.1.x, it will return a ``generate`` event, which does not indicate an error, and the webflow continues on to ``viewLoginForm`` with no error messages, which would be terribly confusing to my users.
This PR restores the 6.6.x behavior.   A test has been added to verify (which fails without the change to ``DelegatedClientAuthenticationAction``).

Stop webflow when pac4j client getCredentials() fails (7.0.x)

---

support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/web/response/callback/OAuth20TokenAuthorizationResponseBuilder.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/response/callback/OAuth20TokenAuthorizationResponseBuilderTests.java

I have this very simple OAuth service:
```json
{
"@class" : "org.apereo.cas.support.oauth.services.OAuthRegisteredService",
"clientId": "myclient",
"clientSecret": "clientSecret",
"serviceId" : "^http?://.*",
"name" : "OAuthService",
"id" : 1,
"bypassApprovalPrompt": true
}
```
I call: `http://localhost:8080/cas/oauth2.0/authorize?response_type=token&client_id=myclient&redirect_uri=http%3A%2F%2Ftest&scope=openid+profile+email+phone&state=%7B%22d%22%3A%22value%22%7D`
I get the following error:
```java
ERROR [org.apereo.cas.web.support.filters.AbstractSecurityFilter] - <Request processing failed: java.lang.IllegalArgumentException: Model has no value for key '"d":"value"'
FrameworkServlet.java:processRequest:1022
FrameworkServlet.java:doGet:903
HttpServlet.java:service:564
>
```
The …

URL encode parameters in frgament

---

support/cas-server-support-webauthn/src/main/java/org/apereo/cas/config/WebAuthnConfiguration.java
support/cas-server-support-webauthn/src/test/java/org/apereo/cas/webauthn/web/WebAuthnControllerMvcTests.java
support/cas-server-support-webauthn/src/test/java/org/apereo/cas/webauthn/web/flow/WebAuthnPopulateCsrfTokenActionTests.java

In the latest CAS server versions, we always prefer the distributed approach and enable the distributed configuration.
So we should do the same for the CSRF tokens of Spring Security by using the `CookieCsrfTokenRepository` instead of the `HttpSessionCsrfTokenRepository`.

Use CookieCsrfTokenRepository

---

ci/tests/puppeteer/scenarios/login-success/script.json
support/cas-server-support-sentry/src/main/java/org/apereo/cas/sentry/SentryMonitoringAspect.java
webapp/cas-server-webapp-init-tomcat/src/main/java/org/apereo/cas/config/CasEmbeddedContainerTomcatConfiguration.java

This PR fixes an incompatibility with Sentry and defining the property `management.server.port`.
The solution was to change the interface used for bean creation (like https://github.com/apereo/cas/commit/827ccd8585797fb3b36d987a7a461d97c2ef0f15).
The `login-success` Puppeteer has been updated to confirm the fix (`./ci/tests/puppeteer/run.sh --rebuild --scenario ./ci/tests/puppeteer/scenarios/login-success`).
Locally, I also successfully run:
- `./gradlew cleanTest testWebApp --no-configuration-cache -p webapp/cas-server-webapp-init-tomcat`
- `./gradlew clean build check javadoc -no-configuration-cache -p support/cas-server-support-sentry`
- `./gradlew clean build check javadoc -no-configuration-cache -p  webapp/cas-server-webapp-init-tomcat`

Fix incompatibility with Sentry

---

api/cas-server-core-api-monitor/src/main/java/org/apereo/cas/monitor/NotMonitorable.java
support/cas-server-support-sentry/src/main/java/org/apereo/cas/sentry/SentryMonitoringAspect.java
webapp/cas-server-webapp-init-tomcat/src/main/java/org/apereo/cas/config/CasEmbeddedContainerTomcatConfiguration.java
webapp/cas-server-webapp-init-tomcat/src/main/java/org/apereo/cas/tomcat/CasTomcatServletWebServerFactory.java

https://github.com/apereo/cas/pull/6044 has broken the `tomcat-port-redirect` scenario.
This PR reverts the change in `CasEmbeddedContainerTomcatConfiguration` and marks the `CasTomcatServletWebServerFactory` class as `NotMonitorable`.
Both scenarios: `login-success` and `tomcat-port-redirect` now pass.

Fix Sentry incompatibility

---

support/cas-server-support-webauthn-core/src/main/java/com/yubico/core/DefaultSessionManager.java
support/cas-server-support-webauthn/src/main/java/org/apereo/cas/config/WebAuthnConfiguration.java

The idea of this PR is to allow customisations by replacing the current local Caffeine `Cache` by a clustered one (based on the ticket registry for example).
No new test is needed.

Small refactoring for the WebAuthn support

---

core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/TicketGrantingTicketImpl.java
support/cas-server-support-redis-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/RedisServerTicketRegistryTests.java

This problem was discovered on a real production environment where many proxy tickets can be granted for the same PGT.
I have created a new `ConcurrentAddProxyTicketTests` test to reproduce the issue.
The map of services of the TGT has been turned into a `ConcurrentHashMap` to fix the issue.

Fix ConcurrentModificationException on Redis / PT

---

core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/BaseTicketRegistryTests.java
support/cas-server-support-hazelcast-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/HazelcastTicketRegistry.java

The performance of the sessions counting can be greatly improved by using Jet for the Hazelcast ticket registry.
The `HazelcastTicketRegistryTests` already covered this use case.

Improve sessions counting by using Jet for the Hazelcast ticket registry

---

docs/cas-server-documentation/planning/Getting-Started.md
docs/cas-server-documentation/release_notes/RC2.md
support/cas-server-support-thymeleaf/src/main/resources/messages.properties

According to the Grammarist [1],"therefor is an archaic form meaning for that object or purpose, in exchange for this or that or it".
These example sentences by content writer Gina Rancaño [2] illustrate the distinction:
A - I returned the damaged item and received store credit therefor. B - I returned the damaged item and received store credit (in return) for that.
[1] https://grammarist.com/usage/therefore-vs-therefor/
[2] https://languagetool.org/insights/post/word-choice-therefore-or-therefor/

update: replace 'therefor' with 'therefore'

---

support/cas-server-support-gcp-firestore-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/GoogleCloudFirestoreTicketRegistry.java
support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java

NB: org.hjson can be quite costly. This change increases >10% CAS ST generation throughput

improve performance of MongoDb/GoogleCloudFirestore ticket registry

---

gradle/dependencies.gradle

This is not an exhaustive cleaning as some other duplicate dependencies are pulled by milestone dependencies which will be upgraded before the final release.

Clean duplicate dependencies

---

support/cas-server-support-passwordless-webflow/src/main/java/org/apereo/cas/web/flow/CreatePasswordlessAuthenticationTokenAction.java
support/cas-server-support-passwordless-webflow/src/test/java/org/apereo/cas/web/flow/CreatePasswordlessAuthenticationTokenActionTest.java

Pass the token value into the SmsBodyBuilder so that is what is added to the sms message that is generated and not the toString() value of the PasswordlessAuthenticationToken

[fix-passwordless-sms-token] add the token value to the message

---

ci/tests/puppeteer/scenarios/saml2-idp-login-metadata-aws-s3/script.json
support/cas-server-support-saml-idp-metadata-aws-s3/src/main/java/org/apereo/cas/support/saml/idp/metadata/AmazonS3SamlIdPMetadataLocator.java
support/cas-server-support-saml-idp-metadata-aws-s3/src/main/java/org/apereo/cas/support/saml/idp/metadata/AmazonS3SamlIdPMetadataUtils.java

When saving and retrieving IdP metadata in S3, new lines (`\n`) are lost.
This PR prevents this issue by turning new lines into the string `<br/>` and back to the original new lines.

Fix S3 metadata support without crypto

---

support/cas-server-support-trusted-mfa-mongo/src/main/java/org/apereo/cas/trusted/authentication/storage/MongoDbMultifactorAuthenticationTrustStorage.java

Added code to set a unique ID for trusted MFA devices when stored to MongoDB. MongoDB is not assigning an auto incrementing ID.

7.1.x MongoDB trusted MFA Id -1 Fix

---

core/cas-server-core-logging/src/main/java/org/apereo/cas/logging/web/ThreadContextMDCServletFilter.java
core/cas-server-core-logging/src/test/java/org/apereo/cas/logging/web/ThreadContextMDCServletFilterTests.java

Being able to correlate log events across not just a single request but across a session is invaluable for quickly drilling down on errors when users encounter them. To that end, this PR adds automatic population of session ID, using the built-in HttpServletRequest API. A minimal test is included.
In use, this allows for configuring a log4j2 pattern (for example) as follows:
```xml
<PatternLayout pattern=".... %X{sessionId} ...." />
```
We at Bard have been running a filter that accomplishes the same thing for several years, and it's been immensely helpful.

Populate sessionId in MDC

---

webapp/cas-server-webapp-resources/src/main/resources/application.properties

With CAS 7.1.0 RC1 (https://github.com/apereo/cas/commit/3e84b9d22f7d23da4195bfd08d3d377257822179), `server.tomcat.max-http-form-post-size` was reduced from Tomcat's default of 2MiB to 40KiB. As a result of this change, SAMLResponses from one of our identity providers were no longer parsed, resulting in failed logins.
This PR reverts the change to fix the regression.

Reset maxPostSize to Tomcat default to not fail SAML responses

---

ci/tests/puppeteer/scenarios/delegated-login-cas-idp-scim/script.json

I was going through the commit's, and just saw this small mistake.

fix(typo): replace 2 comma's with 1

---

support/cas-server-support-thymeleaf/src/main/resources/templates/fragments/recaptcha.html

Friendly Captcha ships at the moment with 29 different languages. English, French, German and many more are available.
This PR supports this language feature.
See: https://support.friendlycaptcha.com/en/article/can-i-translate-the-friendly-captcha-widget-1eeyiwu/

Handle languages for Friendly Captcha

---

support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/AbstractSamlIdPProfileHandlerController.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/SamlProfileBuilderContext.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/authn/SamlProfileSamlAuthNStatementBuilder.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/ecp/ECPSamlIdPProfileHandlerController.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/sso/SSOSamlIdPProfileCallbackHandlerController.java

After fixing the SAML (front channel) logout support (https://github.com/apereo/cas/pull/6205), I'm focusing my efforts on the back channel way.
It partially works. I still have a CAS server delegating via SAML to another CAS server and after a successful login, I perform a logout on the second CAS server expecting it to send a logout call to the first CAS server.
The logout propagation works if I log in during the authn delegation, but not if I'm already authenticated on the second CAS server before the authn delegation.
This comes from the way we compute the session index at the authentication stage. Getting the "ticket" parameter only works half of the time, it looks and is fragile.
This PR proposes to **explicitly** pass the service ticket as the session index in the …

Fix the SAML logout support (back channel) in authentication delegation

---

core/cas-server-core-services-authentication/src/main/java/org/apereo/cas/authentication/principal/AbstractWebApplicationService.java
core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/resolver/impl/DefaultCasDelegatingWebflowEventResolver.java
core/cas-server-core-webflow-mfa/src/test/java/org/apereo/cas/web/flow/resolver/impl/DefaultCasDelegatingWebflowEventResolverTests.java

Fixing a backwards incompatibility regression introduced in https://github.com/apereo/cas/commit/83a68848bf2a808ae149ce27e4c84fafd901a061 that was subsequently released as part of 7.1.1 patch release.
Given an example URL, where the service contains query string parameters with illegal characters, or any other means which generate an exception upon parsing into the UriBuilder object:
https://localhost:8443/cas/login?service=https%3A%2F%2Finit.cas.org%2F%3Fquery%3D%2FInvalid%20Format
Prior, CAS would process the request and log the following ERROR:
`ERROR [org.apereo.cas.authentication.principal.AbstractServiceFactory] - <Unable to extract query parameters from [https://init.cas.org/?query=/Invalid Format]: [java.net.URISyntaxException: Illegal character in query at index 36: …

Handle URISyntaxException in setting of service fragment

---

support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/slo/OidcSingleLogoutMessageCreator.java
support/cas-server-support-oidc/src/test/java/org/apereo/cas/oidc/slo/OidcSingleLogoutMessageCreatorTests.java

After fixing the SAML back channel logout support (https://github.com/apereo/cas/pull/6213), I'm now focusing on the OIDC back channel logout support.
I always perform the same test: one CAS server acting as the OIDC client and another CAS server acting as the OIDC server. After an authentication delegation, the logout is not transmitted from the OIDC server to the OIDC client because of two inconsistencies in the OIDC logout request:
1) the "exp" claim is missing (mandatory in the spec: https://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken)
2) the "sid" claim is not properly computed for the logout: it should be a SHA of the "jwtId" which is itself a SHA512 of the TGT identifier (like in the `OidcIdTokenGeneratorService`).
This PR fixes these two issues in the …

Fix the OIDC logout support (back channel) in authentication delegation

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/mongo/ticketregistry/MongoDbTicketRegistryProperties.java
support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java
support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/util/MongoDbTicketRegistryFacilitator.java
support/cas-server-support-mongo-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistryTests.java

Currently, the MongoDbTicketRegistry creates a "text" mongo index on the full json contents of the ticket. That index is large and expensive to maintain: it our environment the index is larger than the ticket storage itself, and load testing shows a 50% reduction in tickets-generated-per-second throughput when the index is present. (Updating this index is the bottleneck in how many authentication transactions CAS can perform).
The only use of the text index is in `MongoDbTicketRegistry.getSessionsFor()`, which does a TextQuery of the ticket document to search by`principal`. Since `principal` is already an field in the ticket document in mongo (with its own index!) there is no need to do a full-text search to find it.
- in `getSessionsFor`, query the `principal` directly instead of a text …

Remove text index from mongo ticket repository

---

support/cas-server-support-simple-mfa-core/src/main/java/org/apereo/cas/mfa/simple/validation/RestfulCasSimpleMultifactorAuthenticationService.java

Currently, the `RestfulCasSimpleMultifactorAuthenticationService` component performs GET calls with entities.
This is inconsistent: bodies should be POSTed.
This PR changes the HTTP method from GET to POST wherever a body is used.

Use POST instead of GET for calls with entities

---

support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/slo/SamlIdPProfileSingleLogoutMessageCreator.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/logout/SamlIdPProfileSingleLogoutMessageCreatorTests.java

The NameID value in the logout request is always the value of the "Principal" that CAS builds during authentication. 
It can happen that in a service, the NameID doesn't match the principal, which means that during logout flow the service provider cannot identify the user.
In my PR, during the construction of the response, I retrieve the attribute from the service definition to include in the logout response. If the NameID has not been defined in the service, CAS will insert the principal.
Here are the steps to reproduce my issue:
1. The user authenticates with the "uid" on CAS.
2. The user accesses the webapp (SP) via SAML2, where the NameID is the email.
3. The user logs out, but in the logoutRequest CAS includes the "uid".
4. The SP is unable to identify the user and doesn't terminate …

Provide the ability to retrieve NameId from the service during SLO

---

api/cas-server-core-api-protocol/src/main/java/org/apereo/cas/CasProtocolConstants.java
core/cas-server-core-logout-api/src/main/java/org/apereo/cas/logout/LogoutHttpMessage.java
core/cas-server-core-logout-api/src/main/java/org/apereo/cas/logout/slo/BaseSingleLogoutServiceMessageHandler.java
core/cas-server-core-logout/src/test/java/org/apereo/cas/logout/LogoutHttpMessageTests.java
support/cas-server-support-pac4j-saml/src/main/java/org/apereo/cas/web/flow/actions/logout/DelegatedSaml2ClientLogoutAction.java
support/cas-server-support-pac4j-saml/src/test/java/org/apereo/cas/web/saml2/DelegatedSaml2ClientLogoutActionTests.java
support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/slo/SamlIdPSingleLogoutServiceMessageHandler.java

To follow up my previous PR on this topic: https://github.com/apereo/cas/pull/6206, I realized that the logout parameter used to send the SAML request in the front-channel way was incorrect: it is "logoutRequest" instead of "SAMLRequest" (pac4j being versatile enough to accept both parameters).
This PR fixes this issue and takes it into account to consider it's a direct logout call.

Fix parameter name for SAML authn delegation logout call

---

support/cas-server-support-throttle-core/src/main/java/org/apereo/cas/throttle/InMemoryThrottledSubmissionCleaner.java

There is a typo in the CRON keys for the throttling feature: https://github.com/apereo/cas/blob/master/api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/throttle/ThrottleProperties.java#L70 + https://github.com/apereo/cas/blob/master/api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/quartz/SchedulingProperties.java#L70

Fix throttling CRON keys

---

support/cas-server-support-throttle-core/src/main/java/org/apereo/cas/throttle/AbstractInMemoryThrottledSubmissionHandlerInterceptorAdapter.java

In v7.1, there is a bug related to the expiration date of the throttling submission.
The `submission` is read from the request: https://github.com/apereo/cas/blob/v7.1.4/support/cas-server-support-throttle-core/src/main/java/org/apereo/cas/throttle/AbstractThrottledSubmissionHandlerInterceptorAdapter.java#L179, but never set to it in v7.1 while it is in master: https://github.com/apereo/cas/blob/master/support/cas-server-support-throttle-core/src/main/java/org/apereo/cas/throttle/AbstractInMemoryThrottledSubmissionHandlerInterceptorAdapter.java#L68
This PR backports the fixed behavior available in the master branch.
Notice that in master, the key is `ThrottledSubmission.class.getSimpleName()` while it is: `ThrottledSubmission.class.getName()` in v7.1.

Fix throttling expiration

---

support/cas-server-support-throttle-core/src/main/java/org/apereo/cas/throttle/ThrottledSubmissionHandlerEndpoint.java
support/cas-server-support-throttle/src/test/java/org/apereo/cas/web/support/ThrottledSubmissionHandlerEndpointTests.java
support/cas-server-support-thymeleaf/src/main/resources/static/js/palantir.js

When using Palantir, I'm unable to remove a specific throttled record when the key is the IP and the username.
This happens because the key is directly used in the path.
This PR changes this behavior to receive the key as an URL parameter.

Fix throttling endpoint deleteByKey

---

core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/OpenFGARegisteredServiceAccessStrategy.java
docs/cas-server-documentation/services/Service-Access-Strategy-OpenFGA.md

With the current code, the following `check` request to OpenFGA is sent:
```json
{
"tuple_key": {
"user": "bellini",
"relation": "member",
"object": "GROUP:managingDirector"
}
}
```
This returns the error:
```json
{
"code": "validation_error",
"message": "the 'user' field must be an object (e.g. document:1) or an 'object#relation' or a typed wildcard (e.g. group:*)"
}
```
So, the request payload should be changed to something like:
```json
{
"tuple_key": {
"user": "USER:bellini",
"relation": "member",
"object": "GROUP:managingDirector"
}
}
```
where `USER` is the type of `bellini` as specified by https://openfga.dev/docs/concepts#what-is-a-user
This change will allow to specify the user type, or fallback to `user` if none is specified.

Fixing OpenFGA check call

---

core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/MockWebServer.java
support/cas-server-support-rest-authentication/src/main/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandler.java
support/cas-server-support-rest-authentication/src/test/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandlerTests.java

Currently a (failed) login is attempted 3 times, which causes one failed login attempt on cas to be 3 failed login attempts in the backend. This is a problem when the backend uses rate-limiting or locks accounts after too many failed attempts.
```
master: https://github.com/apereo/cas/pull/6638
7.2.x: https://github.com/apereo/cas/pull/6637
7.1.x: https://github.com/apereo/cas/pull/6636
```

Don't retry failed login attempts in order to avoid premature account locking.

---

core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/MockWebServer.java
support/cas-server-support-rest-authentication/src/main/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandler.java
support/cas-server-support-rest-authentication/src/test/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandlerTests.java

Currently a (failed) login is attempted 3 times, which causes one failed login attempt on cas to be 3 failed login attempts in the backend. This is a problem when the backend uses rate-limiting or locks accounts after too many failed attempts.
Backport of #6637 and #6638 
```
master: https://github.com/apereo/cas/pull/6638
7.2.x: https://github.com/apereo/cas/pull/6637
7.1.x: https://github.com/apereo/cas/pull/6636
```
Recreated PR as requested in https://github.com/apereo/cas/pull/6636#issuecomment-2760344213

Don't retry failed login attempts in order to avoid premature account locking

---

support/cas-server-support-twilio-mfa/src/main/java/org/apereo/cas/mfa/twilio/CasDefaultTwilioMultifactorAuthenticationService.java

Brief description of changes applied:
Sends the Twilio verification channel value in lowercase to the Twilio API (using the enum value instead of the enum name).
The Twilio API throws an "Invalid parameter: Channel" error when the request contains an uppercase channel value (e.g., "Channel=SMS"). It requires the value to be lowercase (e.g., "Channel=sms"), so the com.twilio.rest.verify.v2.service.Verification.Channel enum value should be used instead of the enum name.

Fixes an issue where the Twilio API requires the verification channel to be lowercase value

---

core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/gen/CookieRetrievingCookieGenerator.java
core/cas-server-core-cookie/src/test/java/org/apereo/cas/web/support/CookieRetrievingCookieGeneratorTests.java

Since CAS version 7.1, the "remember me" UI element was changed from a `<input type="checkbox">` to a switch-style button that manipulates a hidden `<input type="hidden">`. This change causes the `rememberme` HTTP parameter to always be present in form submissions, even when the user does **not** explicitly request to be remembered.
However, in the current code, the decision to make the TGC (Ticket Granting Cookie) persistent is based solely on the **presence** of the `rememberme` parameter, not on its **value**.
As a result, CAS sets a long-lived TGC cookie even when the user did not intend to enable the "remember me" option. This breaks expected session behavior: closing the browser no longer logs the user out, which is problematic on shared devices.
This PR updates the condition so …

Fix: TGC cookie should not be persistent when remember-me is unchecked

---

ci/tests/puppeteer/scenarios/interrupt-afterauthn-groovy/interrupt.groovy
ci/tests/puppeteer/scenarios/interrupt-afterauthn-groovy/script.js
support/cas-server-support-thymeleaf/src/main/resources/templates/interrupt/casInterruptView.html

This PR improves the robustness of the casInterruptView.html Thymeleaf view by sanitizing the generated HTML id for each interrupt link.
Previously, the linkid was derived from the link text using only a .replace(' ', '') operation. As a result, special characters such as colon, accented letters (é), ampersand, or at signs were preserved in the computed id, leading to invalid selectors and client-side issues ; the link would not work properly.
For example, a link labeled "Test link with special symbols: é & @" would previously generate the id testlinkwithspecialsymbols:é&@, which is problematic when referenced by a selector or script.
With this fix, the id is now generated as testlinkwithspecialsymbols.
A Puppeteer scenario has been updated accordingly to assert this behavior, ensuring …

Fix: CAS Interrupt Thymeleaf View – Sanitize link ID to handle special characters

---

support/cas-server-support-webauthn-core-webflow/src/main/java/org/apereo/cas/webauthn/web/flow/WebAuthnMultifactorWebflowConfigurer.java
support/cas-server-support-webauthn-core/src/main/java/org/apereo/cas/webauthn/web/WebAuthnController.java

This PR does two things:
1) Improve logs in the `WebAuthnController`: the changes are quite obvious here
2) Fix a bug in the WebAuthn support:
The `authenticatedPrincipal` in the `startAuthentication` method of the `WebAuthnController` was only populated during the registration and not for a regular MFA authentication. Thanks to the change in the `WebAuthnMultifactorWebflowConfigurer`, the `authenticatedPrincipal` in the `startAuthentication` method of the `WebAuthnController` is also now populated in any regular MFA authentication (much later after the registration).

Improve logs and fix bug in WebAuthn support

---

support/cas-server-support-thymeleaf/src/main/resources/static/js/palantir.js

When there are more rows in the `applicationsTable` (service entries) than DataTables will render on it's first draw, those non-rendered rows are not actually in the DOM, so `initializeServiceButtons()` does not apply the click event handlers to them. 
Those event handlers should be re-applied to the rows rendered in the DOM after the table is re-drawn at any point (due to filtering or pagination).

Palantir: Initialize the services buttons each time the table is re-drawn

---

support/cas-server-support-thymeleaf/src/main/resources/static/js/palantir.js

This changed was merged into master in https://github.com/apereo/cas/pull/7146. This PR is to backport this fix into the 7.2.x maintenance branch for a future patch.
When there are more rows in the applicationsTable (service entries) than DataTables will render on it's first draw, those non-rendered rows are not actually in the DOM, so initializeServiceButtons() does not apply the click event handlers to them.
Those event handlers should be re-applied to the rows rendered in the DOM after the table is re-drawn at any point (due to filtering or pagination).

Palantir 7.2.x: Initialize the services buttons each time the table is re-drawn

---

gradle/maven.gradle

The Apache Snapshots repository is quite unstable and I sometimes have such errors:
```
Downloading from apache-snapshot: https://repository.apache.org/content/repositories/snapshots/org/bouncycastle/bcutil-jdk18on/maven-metadata.xml
[WARNING] Could not transfer metadata org.bouncycastle:bcutil-jdk18on/maven-metadata.xml from/to apache-snapshot (https://repository.apache.org/content/repositories/snapshots): Connect to repository.apache.org:443 [repository.apache.org/65.109.119.155] failed: Connection refused
```
I'm not sure it is really used for the build. This PR removes it.

Remove the apache-snapshots repository

---

support/cas-server-support-pm-rest/src/main/java/org/apereo/cas/config/CasRestPasswordManagementAutoConfiguration.java
support/cas-server-support-pm-rest/src/main/java/org/apereo/cas/pm/rest/RestPasswordManagementService.java
support/cas-server-support-pm-rest/src/test/java/org/apereo/cas/pm/rest/RestPasswordManagementServiceTests.java

Set the Content-Type header at request Level to avoid sending XML.
Before this fix, RestTemplate has Choosen an XML Message Converter, while still sending Content-Type: application/json.

Fix password reset content type

---

api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/redis/RedisPoolProperties.java
support/cas-server-support-redis-core/src/main/java/org/apereo/cas/redis/core/RedisObjectFactory.java
support/cas-server-support-redis-core/src/test/java/org/apereo/cas/redis/core/RedisObjectFactoryTests.java

My understanding is that the timeBetweenEvictionRuns in commons pool 2 is defaulting to -1 which means there is no eviction thread running. That would seemingly make properties like  minEvictableIdleTimeMillis and numTestsPerEvictionRun not work. This change allows for specifying a positive time for the timeBetweenEvictionRuns.

allow timeBetweenEvictionRuns to be set so other eviction related properties can be used
