cas-server-core/src/main/java/org/jasig/cas/CasEnvironmentContextListener.java
cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/applicationContext.xml
cas-server-webapp/src/main/webapp/WEB-INF/web.xml

Handles https://github.com/Jasig/cas/issues/817

Context listener to report on CAS environment info.

---

cas-server-core/src/main/java/org/jasig/cas/web/flow/AbstractNonInteractiveCredentialsAction.java
cas-server-core/src/main/java/org/jasig/cas/web/support/WebUtils.java
cas-server-support-pac4j/src/main/java/org/jasig/cas/support/pac4j/web/flow/ClientAction.java
cas-server-webapp-support/src/main/java/org/jasig/cas/web/flow/AuthenticationViaFormAction.java
cas-server-webapp-support/src/main/java/org/jasig/cas/web/flow/InitialFlowSetupAction.java
cas-server-webapp-support/src/test/java/org/jasig/cas/web/flow/AuthenticationViaFormActionTests.java
cas-server-webapp-support/src/test/java/org/jasig/cas/web/flow/GenerateServiceTicketActionTests.java
cas-server-webapp-support/src/test/java/org/jasig/cas/web/flow/SendTicketGrantingTicketActionTests.java
cas-server-webapp-support/src/test/java/org/jasig/cas/web/flow/TicketGrantingTicketCheckActionTests.java

Issue-825: Always add the TGT in request AND flow scope

---

cas-server-documentation/protocol/CAS-Protocol-Specification.md

This pull does the following:
1. Recommends the use of service management tool as a best practice to filter all service urls. 
2. Adds new CAS P3 endpoints
3. Fixes error codes and code formatting. 
4. Adds TGT to the CAS entities.

Protocol Update: endpoints, TGT, error code, Svc Mgmt warning

---

cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/ticketGrantingTicketCookieGenerator.xml

Handles https://github.com/Jasig/cas/issues/837

Changed TGC name to match protocol spec.

---

cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/util/AbstractSamlObjectBuilder.java

Based on https://github.com/Jasig/java-cas-client/pull/96 proposed by @serac

Make OpenSAML bootstrap conditional

---

cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
cas-server-core/src/main/java/org/jasig/cas/util/UniqueTicketIdGenerator.java
cas-server-core/src/test/java/org/jasig/cas/CentralAuthenticationServiceImplTests.java

This pull addresses issue https://github.com/Jasig/cas/issues/509

CASImpl with Default TicketId Generator

---

pom.xml

Keeping up with the latest of Spring.

Spring 4.1.4 upgrade

---

pom.xml

Also, fixed an issue with a misnamed property. buildhelper->buildnumber.

Updated a selection of maven plugins

---

cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationService.java
cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
cas-server-core/src/main/java/org/jasig/cas/util/http/HttpClient.java
cas-server-core/src/main/java/org/jasig/cas/util/http/SimpleHttpClient.java
pom.xml

Upgrades hibernate dependencies for core and validators.
When I bumped the validator version, I ran into this issue:
> HV000151 error being thrown - "A method overriding another method must not alter the parameter constraint configuration"
To solve the issue, I added the constraints to the interface method instead of the implementation method.
Ref: https://forum.hibernate.org/viewtopic.php?f=9&t=1026897

Hibernate dependency upgrades

---

cas-server-core/src/main/java/org/jasig/cas/util/http/HttpMessage.java
cas-server-core/src/test/java/org/jasig/cas/util/http/HttpMessageTest.java
cas-server-core/src/test/java/org/jasig/cas/util/http/HttpMessageTests.java

Here a small patch for #858 .
Regards

Fix: Async parameter in HttpClient is not taken into account.

---

cas-server-webapp/src/main/resources/messages.properties
cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/casLoginView.jsp

Handles https://github.com/Jasig/cas/issues/867

Moved the "non-secure connection" message to bundles

---

pom.xml

Changelog:
http://www.ldaptive.org/changelog
Recently had to troubleshoot this issue:
https://github.com/vt-middleware/ldaptive/issues/24

Ldaptive upgrade to v1.0.6

---

cas-server-documentation/protocol/OpenID-Protocol.md
cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/casLoginView.jsp

cas-882: Update OpenID support

---

cas-server-webapp/src/main/resources/messages.properties
cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/casLoginView.jsp
cas-server-webapp/src/main/webapp/css/cas.css
cas-server-webapp/src/main/webapp/js/cas.js

Handles https://github.com/Jasig/cas/issues/537

Added warning for when cookies are disabled

---

cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/web/flow/SpnegoNegociateCredentialsAction.java

Handles https://github.com/Jasig/cas/issues/478
Also updated javadocs, instructed CAS's Logger to be used and added more log statements.

IE11 support for SPNEGO: User Agent added

---

cas-server-webapp-support/src/main/java/org/jasig/cas/web/view/CasReloadableMessageBundle.java

Handles https://github.com/Jasig/cas/issues/906

Use full locale language/dialect when resolving messages

---

cas-server-support-x509/src/main/java/org/jasig/cas/adaptors/x509/authentication/handler/support/CRLDistributionPointRevocationChecker.java

Handles https://github.com/Jasig/cas/issues/522
>An alternative that is much more straightforward would be caching the encoded bytes of the CRL, which is accessible via X509CRL#getEncoded(). Since byte arrays are perfectly serializable, this would work for both memory and persistent caches.

Cache encoded X509CRL to allow disk persistence

---

.gitignore
cas-server-documentation/integration/Delegate-Authentication.md
cas-server-support-pac4j/pom.xml
cas-server-support-pac4j/src/main/java/org/jasig/cas/support/pac4j/web/flow/ClientAction.java
cas-server-support-pac4j/src/test/java/org/jasig/cas/support/pac4j/web/flow/ClientActionTests.java
pom.xml

Release notes: https://github.com/pac4j/pac4j/wiki/Versions

Update to pac4j v1.7

---

cas-server-webapp-support/src/main/java/org/jasig/cas/web/flow/InitialFlowSetupAction.java
cas-server-webapp-support/src/test/java/org/jasig/cas/web/flow/InitialFlowSetupActionTests.java
cas-server-webapp/src/main/resources/messages.properties
cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml
cas-server-webapp/src/main/webapp/WEB-INF/cas.properties

Handles https://github.com/Jasig/cas/issues/549

Disable authn flow if no service is found, optionally

---

cas-server-core/src/main/java/org/slf4j/impl/CasDelegatingLogger.java
pom.xml

Required for this https://github.com/Jasig/cas-server-security-filter/issues/11

Added support for JUL; Protected logger from null exceptions

---

pom.xml

Security filter update

---

cas-server-webapp-support/src/main/java/org/jasig/cas/web/support/AbstractThrottledSubmissionHandlerInterceptorAdapter.java

Handles https://github.com/Jasig/cas/issues/719

Clarified throttling log message & added toString

---

cas-server-core/src/test/java/org/jasig/cas/ticket/proxy/support/Cas20ProxyHandlerTests.java
cas-server-integration-memcached/pom.xml
cas-server-integration-memcached/src/main/java/org/jasig/cas/ticket/registry/support/kryo/KryoTranscoder.java
cas-server-integration-memcached/src/test/java/org/jasig/cas/ticket/registry/MemCacheTicketRegistryTests.java
cas-server-integration-memcached/src/test/resources/log4j2.xml
cas-server-integration-memcached/src/test/resources/ticketRegistry-test.xml

Handles https://github.com/Jasig/cas/issues/942

Added integration tests for Memcached. Fixed NotNull issue

---

cas-server-support-pac4j/src/main/java/org/jasig/cas/support/pac4j/authentication/handler/support/AbstractClientAuthenticationHandler.java
cas-server-support-pac4j/src/main/java/org/jasig/cas/support/pac4j/authentication/handler/support/ClientAuthenticationHandler.java

cas897: Allow the ClientAuthenticationHandler to become extensible

---

cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
cas-server-core/src/main/java/org/jasig/cas/ticket/ServiceTicketImpl.java
cas-server-core/src/main/java/org/jasig/cas/ticket/TicketGrantingTicket.java
cas-server-core/src/main/java/org/jasig/cas/ticket/TicketGrantingTicketImpl.java
cas-server-core/src/main/java/org/jasig/cas/ticket/registry/AbstractDistributedTicketRegistry.java
cas-server-core/src/test/java/org/jasig/cas/CentralAuthenticationServiceImplWithMockitoTests.java
cas-server-core/src/test/java/org/jasig/cas/mock/MockTicketGrantingTicket.java
cas-server-core/src/test/java/org/jasig/cas/ticket/TicketGrantingTicketImplTests.java
cas-server-integration-memcached/src/test/java/org/jasig/cas/ticket/registry/support/kryo/KryoTranscoderTests.java

Merged https://github.com/Jasig/cas/pull/933 into master/4.1 to address #904

Fix scope of allowedToProxy flag

---

cas-server-core/src/main/java/org/jasig/cas/authentication/HandlerResult.java

Handles https://github.com/Jasig/cas/issues/981
Will be merged into 4.0.2

Added warnings param to HandlerResult

---

cas-server-support-spnego/pom.xml

Upgrade JCIFS Library

---

cas-management-webapp/src/main/resources/messages_pl.properties
cas-server-webapp/src/main/resources/messages_pl.properties

Please accept Polish translation File for CAS / CAS Management, completed with all missing entries (based on the English version).

Updated Polish translations for version 4.1.x; issue #994

---

cas-server-documentation/installation/Trusted-Authentication.md

Documentation had an extra dot. Removed it.

Fixed typo in documentation

---

cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/filters.xml
cas-server-webapp/src/main/webapp/WEB-INF/web.xml
pom.xml

Move request security filter to filters.xml

---

cas-server-core/src/main/java/org/jasig/cas/services/JsonServiceRegistryConfigWatcher.java
cas-server-core/src/main/java/org/jasig/cas/services/JsonServiceRegistryDao.java
cas-server-core/src/main/java/org/jasig/cas/util/AbstractJacksonBackedJsonSerializer.java
cas-server-webapp/src/main/resources/services/https-imaps.json

Allows the JSON service registry to auto detect changes and reload the service registry using JDK7 APIs

Allow JsonSvcReg to auto-detect changes

---

cas-server-support-pac4j/pom.xml
cas-server-support-pac4j/src/main/java/org/jasig/cas/support/pac4j/authentication/handler/support/ClientAuthenticationHandler.java
cas-server-support-pac4j/src/main/java/org/jasig/cas/support/pac4j/web/flow/ClientAction.java
cas-server-support-pac4j/src/test/java/org/jasig/cas/support/pac4j/web/flow/ClientActionTests.java

Upgrade CAS 4.0.4 with pac4j 1.7.0

Upgrade CAS 4.0.x to Pac4j 1.7.x

---

cas-server-documentation/installation/LDAP-Authentication.md
cas-server-documentation/installation/X509-Authentication.md

Fixes #1038  added the close method on abstract pool to free the resource on undeploy.

Issues-1038 added the close method on abstract pool to free the resource on undeploy

---

cas-server-core/src/main/java/org/jasig/cas/services/JsonServiceRegistryConfigWatcher.java
cas-server-core/src/main/java/org/jasig/cas/services/JsonServiceRegistryDao.java

This PR makes sure that:
1. JSON files created by the registry have no spaces in them
2. Files that are loaded are not empty, exist and can be read.

JSON Service Registry Checks

---

cas-server-core/src/main/java/org/jasig/cas/ticket/registry/AbstractTicketRegistry.java
cas-server-documentation/installation/Hazelcast-Ticket-Registry.md
cas-server-integration-hazelcast/NOTICE
cas-server-integration-hazelcast/pom.xml
cas-server-integration-hazelcast/src/main/java/org/jasig/cas/ticket/registry/HazelcastTicketRegistry.java
cas-server-integration-hazelcast/src/main/resources/META-INF/spring/hazelcast-ticket-registry.xml
cas-server-integration-hazelcast/src/site/site.xml
cas-server-integration-hazelcast/src/test/java/org/jasig/cas/ticket/registry/HazelcastTicketRegistryTests.java
cas-server-integration-hazelcast/src/test/resources/log4j2.xml
cas-server-integration-hazelcast/src/test/resources/org/jasig/cas/ticket/registry/HazelcastTicketRegistryTests-context.xml
pom.xml

Hazelcast Ticket Registry implementation.

---

pom.xml

CAS-1056 Updated Spring to version 3.2.9 due to SPR-11719

---

cas-server-documentation/installation/Service-Management.md
cas-server-webapp/src/main/resources/services/Apereo-10000002.json
cas-server-webapp/src/main/resources/services/HTTPSandIMAPS-10000001.json
cas-server-webapp/src/main/resources/services/apereo.json
cas-server-webapp/src/main/resources/services/https-imaps.json

Json file naming convention

---

cas-server-core/src/main/java/org/jasig/cas/authentication/SuccessfulHandlerMetaDataPopulator.java

#1049 - Fix serialization bug with EhcacheTicketRegistry

---

cas-server-integration-memcached/pom.xml
cas-server-integration-memcached/src/main/java/org/jasig/cas/ticket/registry/support/kryo/KryoTranscoder.java
cas-server-integration-memcached/src/main/java/org/jasig/cas/ticket/registry/support/kryo/serial/AbstractWebApplicationServiceSerializer.java
cas-server-integration-memcached/src/main/java/org/jasig/cas/ticket/registry/support/kryo/serial/GoogleAccountsServiceSerializer.java
cas-server-integration-memcached/src/main/java/org/jasig/cas/ticket/registry/support/kryo/serial/RegisteredServiceSerializer.java
cas-server-integration-memcached/src/main/java/org/jasig/cas/ticket/registry/support/kryo/serial/SamlServiceSerializer.java
cas-server-integration-memcached/src/main/java/org/jasig/cas/ticket/registry/support/kryo/serial/URLSerializer.java
cas-server-integration-memcached/src/test/java/org/jasig/cas/ticket/registry/support/kryo/KryoTranscoderTests.java

The changes are backported from master to account for serialization issues with collections. Closes #1066

Backported memcached+kryo update to 4.0.4

---

cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/protocol/openid/casOpenIdServiceSuccessView.jsp

Removed extra linebreak to allow openid4java parsing

---

cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/web/view/Saml10SuccessResponseView.java

Closes https://github.com/Jasig/cas/issues/1077

SAML attributes should be fetched off of primary authN

---

cas-server-webapp/src/main/webapp/WEB-INF/web.xml

Closes https://github.com/Jasig/cas/issues/886

Exclude Restlet endpoints from Security Filter Mapping

---

cas-server-documentation/integration/ClearPass-Proxy-Authentication.md

Typo : bean tag already closed

Doc : ClearPass-Proxy-Authentication.md - typo

---

cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/top.jsp

Should be merged into 4.0.5 too

Add missing viewport meta tag

---

cas-server-webapp/src/main/resources/messages.properties

Closes https://github.com/Jasig/cas/issues/1137

Update CAS unavailable message

---

checkstyle-rules.xml

Relax checkstyle rules for javadocs

---

cas-server-documentation/protocol/CAS-Protocol-Specification.md

Closes https://github.com/Jasig/cas/issues/1125

Protocol update to include new format parameter

---

cas-server-documentation/planning/Security-Guide.md
cas-server-support-openid/pom.xml
cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/filters.xml
cas-server-webapp/src/main/webapp/WEB-INF/web.xml
pom.xml

Will update once this issues is closed and release is available:
https://github.com/Jasig/cas-server-security-filter/issues/17

Update security filter to 2.0.4

---

cas-server-support-x509/pom.xml
cas-server-support-x509/src/main/java/org/jasig/cas/adaptors/x509/authentication/handler/support/CRLDistributionPointRevocationChecker.java
cas-server-support-x509/src/main/java/org/jasig/cas/adaptors/x509/authentication/principal/X509SubjectAlternativeNameUPNPrincipalResolver.java
cas-server-support-x509/src/main/java/org/jasig/cas/adaptors/x509/authentication/principal/X509SubjectPrincipalResolver.java
cas-server-support-x509/src/main/java/org/jasig/cas/adaptors/x509/util/CertUtils.java
cas-server-support-x509/src/test/java/org/jasig/cas/adaptors/x509/authentication/handler/support/X509CredentialsAuthenticationHandlerTests.java
pom.xml

Closes https://github.com/Jasig/cas/issues/1180
Changes to migrate vt-crypt dependency to cryptacular, addressing issue 1180 (https://github.com/Jasig/cas/issues/1180), thus resolving dependency conflict between different versions needed of BouncyCastle

Changes to migrate vt-crypt dependency to cryptacular

---

pom.xml

Upgrade ldaptive to 1.0.7

---

cas-server-documentation/protocol/REST-Protocol.md
cas-server-support-rest/pom.xml
cas-server-support-rest/src/main/java/org/jasig/cas/support/rest/RegisteredServiceResource.java
cas-server-support-rest/src/main/java/org/jasig/cas/support/rest/TicketsResource.java
cas-server-support-rest/src/test/java/org/jasig/cas/support/rest/RegisteredServiceResourceTests.java
cas-server-webapp/src/main/webapp/WEB-INF/cas.properties

Closes https://github.com/Jasig/cas/issues/596
In order to invoke this API, a TGT is required, and the principal must be authorized to do via configuration of attributes in cas.properties.

REST API to register CAS services

---

cas-server-core/src/main/java/org/jasig/cas/util/CompressionUtils.java
cas-server-core/src/main/java/org/jasig/cas/util/PrivateKeyFactoryBean.java
cas-server-core/src/main/java/org/jasig/cas/util/PublicKeyFactoryBean.java
cas-server-core/src/test/java/org/jasig/cas/TestUtils.java
cas-server-documentation/integration/Google-Apps-Integration.md
cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/SamlServletContextListener.java
cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsServiceFactory.java
cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsServiceResponseBuilder.java
cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/util/AbstractSamlObjectBuilder.java
cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/util/GoogleSaml20ObjectBuilder.java
cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/util/Saml10ObjectBuilder.java

Fixed issue with inflation of saml authN request

---

cas-server-core-api/src/main/java/org/jasig/cas/authentication/principal/PrincipalAttributesRepository.java
cas-server-core/src/main/java/org/jasig/cas/authentication/principal/CachingPrincipalAttributesRepository.java
cas-server-core/src/test/resources/core-context.xml

Closes https://github.com/Jasig/cas/issues/1208
Added the bean declaration to the context so we can run validation tests automatically in the future.

Removed NotNull annotation from PrincipalAttributeRepository

---

cas-server-webapp/src/main/webapp/js/cas.js

Removed js debug lib

---

cas-management-webapp/src/main/java/org/jasig/cas/services/web/beans/RegisteredServiceEditBean.java
cas-server-core-api/src/main/java/org/jasig/cas/authentication/principal/PrincipalAttributesRepository.java
cas-server-core/src/main/java/org/jasig/cas/authentication/principal/cache/AbstractPrincipalAttributesRepository.java
cas-server-core/src/main/java/org/jasig/cas/authentication/principal/cache/CachingPrincipalAttributesRepository.java
cas-server-core/src/test/java/org/jasig/cas/TestUtils.java
cas-server-core/src/test/java/org/jasig/cas/authentication/principal/cache/AbstractCachingPrincipalAttributesRepositoryTests.java
cas-server-core/src/test/java/org/jasig/cas/authentication/principal/cache/CachingPrincipalAttributesRepositoryTests.java
cas-server-core/src/test/java/org/jasig/cas/services/AttributeReleasePolicyTests.java
cas-server-core/src/test/java/org/jasig/cas/services/JsonServiceRegistryDaoTests.java
cas-server-core/src/test/resources/core-context.xml
cas-server-documentation/integration/Attribute-Release.md

This pull ports forward the changeset that was applied for https://github.com/Jasig/cas/commit/766b3052191e43a9ff9048c709e3ae8f5c713270
and https://github.com/Jasig/cas/pull/1210

Caching attribute repository cannot be serialized

---

4.1.x/planning/Upgrade-Guide.md

without HTTP:// URL is https://jasig.github.io/cas/4.1.x/planning/www.sublimetext.com

Fix missing http

---

cas-server-webapp/src/main/webapp/WEB-INF/logout-webflow.xml

Closes https://github.com/Jasig/cas/issues/1239

#1239 Wrong state type for logoutView in logout-webflow

---

cas-server-documentation/installation/Memcached-Ticket-Registry.md
cas-server-integration-memcached/src/main/resources/META-INF/spring/memcached-registry-config.xml
cas-server-webapp/src/main/webapp/WEB-INF/cas.properties

Closes https://github.com/Jasig/cas/issues/1252

Memcached support fails at startup due to a bad KryoTranscoder init

---

cas-server-webapp/pom.xml
cas-server-webapp/src/main/resources/log4j2.xml
pom.xml

Closes https://github.com/Jasig/cas/issues/1256 
See http://logging.apache.org/log4j/2.x/manual/async.html#MixedSync-Async

Allow log events to be process in async mode by default

---

cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsService.java
cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/web/support/GoogleAccountsArgumentExtractor.java
cas-server-support-saml/src/test/java/org/jasig/cas/support/saml/web/support/GoogleAccountsArgumentExtractorTests.java

Closes https://github.com/Jasig/cas/issues/1266
Should be ported forward for master.

Provide a skewAllowance for SAML2 google apps

---

cas-server-webapp-support/src/main/java/org/jasig/cas/web/support/CookieRetrievingCookieGenerator.java
etc/jetty/jetty-https.xml
etc/jetty/jetty-ssl.xml
etc/jetty/jetty.xml
etc/jetty/web.xml
pom.xml

Closes https://github.com/Jasig/cas/issues/1230

HttpOnly / Secure not set when "removing" CAS cookies

---

cas-management-webapp/build.gradle
cas-management-webapp/src/main/java/org/jasig/cas/services/web/RegisteredServiceSimpleFormController.java
cas-management-webapp/src/main/webapp/WEB-INF/cas-management-servlet.xml
cas-management-webapp/src/main/webapp/WEB-INF/spring-configuration/applicationContext.xml
cas-server-core-web/src/main/java/org/jasig/cas/web/AbstractServletContextInitializer.java
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/OAuthServletContextListener.java
gradle.properties
gradle/tasks.gradle

Port of https://github.com/Jasig/cas/pull/1264 for master
1. Added the gretty plugin to mgmt app
2. Fixed issues with context scans and bean resolution
3. Fixed a bug with oauth callback service where auto-insertion of the callback could not be loaded by the management app due to caching. Forcing a reload.

Do not delete services first before saving them in the management app

---

cas-server-support-saml-googleapps/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsServiceFactory.java
cas-server-support-saml-googleapps/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsServiceResponseBuilder.java
cas-server-support-saml-googleapps/src/test/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsServiceFactoryTests.java
cas-server-support-saml-googleapps/src/test/resources/cas.properties

Added skew allowance for googleapps

---

cas-server-core-api/src/main/java/org/jasig/cas/CasProtocolConstants.java
cas-server-core-api/src/main/java/org/jasig/cas/authentication/principal/WebApplicationService.java
cas-server-core-api/src/main/java/org/jasig/cas/services/web/view/CasViewConstants.java
cas-server-core-api/src/main/java/org/jasig/cas/validation/ValidationResponseType.java
cas-server-core-services/src/main/java/org/jasig/cas/authentication/principal/AbstractWebApplicationService.java
cas-server-core-services/src/main/java/org/jasig/cas/authentication/principal/WebApplicationServiceFactory.java
cas-server-core-web/src/main/java/org/jasig/cas/services/web/view/AbstractCasView.java
cas-server-core-web/src/main/java/org/jasig/cas/services/web/view/AbstractDelegatingCasView.java
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/OAuthServletContextListener.java
cas-server-webapp-validation/src/main/java/org/jasig/cas/web/AbstractServiceValidateController.java
cas-server-webapp-validation/src/main/java/org/jasig/cas/web/view/Cas30JsonResponseView.java
cas-server-webapp-validation/src/main/java/org/jasig/cas/web/view/Cas30ResponseView.java
cas-server-webapp-validation/src/test/java/org/jasig/cas/web/AbstractServiceValidateControllerTests.java
cas-server-webapp-validation/src/test/java/org/jasig/cas/web/view/Cas30ResponseViewTests.java
cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml

Closes https://github.com/Jasig/cas/issues/1126

Allow CAS to produce Json for the validation response

---

pom.xml

Patch to block potential serialization attacks.

Updated Spring lib version

---

cas-management-webapp/build.gradle
cas-server-core-authentication/src/main/java/org/jasig/cas/services/AbstractRegisteredServiceAttributeReleasePolicy.java
cas-server-core-services/src/main/java/org/jasig/cas/services/PrincipalAttributeRegisteredServiceUsernameProvider.java
cas-server-core-services/src/test/java/org/jasig/cas/services/PrincipalAttributeRegisteredServiceUsernameProviderTests.java
cas-server-documentation/integration/Google-Apps-Integration.md
cas-server-documentation/protocol/CAS-Protocol-Specification.md
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/OAuthServletContextListener.java

Closes #1261 
Shall be backported to 4.1 and 4.0

Principal-attribute for service username shall pass through attribute release policy

---

cas-server-core-api-ticket/src/main/java/org/jasig/cas/ticket/ProxyGrantingTicket.java
cas-server-core-api-ticket/src/main/java/org/jasig/cas/ticket/ServiceTicket.java
cas-server-core-api-ticket/src/main/java/org/jasig/cas/ticket/TicketGrantingTicket.java
cas-server-core-logging/src/main/java/org/slf4j/impl/CasDelegatingLogger.java
cas-server-core-logging/src/test/java/org/slf4j/impl/CasLoggerFactoryTests.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/ProxyGrantingTicketImpl.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/ServiceTicketImpl.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/TicketGrantingTicketImpl.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/proxy/support/Cas20ProxyHandler.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/AbstractDistributedTicketRegistry.java
cas-server-core-tickets/src/test/java/org/jasig/cas/mock/MockServiceTicket.java
cas-server-core-tickets/src/test/java/org/jasig/cas/ticket/ServiceTicketImplTests.java
cas-server-core-tickets/src/test/java/org/jasig/cas/ticket/registry/DistributedTicketRegistryTests.java
cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
cas-server-core/src/test/java/org/jasig/cas/CentralAuthenticationServiceImplTests.java
cas-server-integration-hazelcast/src/test/java/org/jasig/cas/ticket/registry/HazelcastTicketRegistryTests.java
cas-server-integration-memcached/src/test/java/org/jasig/cas/ticket/registry/support/kryo/KryoTranscoderTests.java

This pull introduces a PGT abstraction to clearly indicate the presence of PGTs in the CAS api and domain model. This pull is partially relevant to #492  and #1143

Introduce a new PGT abstraction

---

cas-server-core-webflow/src/main/java/org/jasig/cas/web/flow/AbstractCasWebflowConfigurer.java
cas-server-integration-mongo/src/main/java/org/jasig/cas/services/MongoServiceRegistryDao.java
cas-server-support-jdbc/src/main/java/org/jasig/cas/adaptors/jdbc/SearchModeSearchDatabaseAuthenticationHandler.java
cas-server-support-ldap/src/test/java/org/jasig/cas/util/ldap/uboundid/InMemoryTestLdapDirectoryServer.java
cas-server-support-saml-googleapps/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsServiceFactory.java
cas-server-support-saml-mdui/src/main/java/org/jasig/cas/support/saml/web/flow/mdui/StaticMetadataResolverAdapter.java
cas-server-support-yubikey/src/main/java/org/jasig/cas/adaptors/yubikey/YubiKeyAuthenticationHandler.java

Closes https://github.com/Jasig/cas/issues/1312

Removed checked exceptions from lifecycle methods

---

cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/AbstractManagementController.java
cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/ManageRegisteredServicesMultiActionController.java
cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/RegisteredServiceSimpleFormController.java
cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/beans/RegisteredServiceEditBean.java
cas-management-webapp/src/main/java/org/jasig/cas/services/web/package-info.java
cas-server-core-services/src/main/java/org/jasig/cas/authentication/principal/ShibbolethCompatiblePersistentIdGenerator.java
cas-server-core-services/src/main/java/org/jasig/cas/services/AbstractRegisteredService.java
cas-server-core-services/src/main/java/org/jasig/cas/services/DefaultServicesManagerImpl.java
cas-server-integration-mongo/build.gradle
cas-server-integration-mongo/src/test/java/org/jasig/cas/services/MongoServiceRegistryDaoTests.java
cas-server-support-jpa-service-registry/build.gradle
cas-server-support-jpa-service-registry/src/main/resources/META-INF/spring/jpa-svc-reg-context.xml
cas-server-support-jpa-service-registry/src/test/java/org/jasig/cas/services/JpaServiceRegistryDaoImplTests.java
cas-server-support-jpa-service-registry/src/test/resources/jpaSpringContext.xml
cas-server-support-ldap-service-registry/build.gradle
cas-server-support-ldap-service-registry/src/test/java/org/jasig/cas/adaptors/ldap/services/LdapServiceRegistryDaoTests.java
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/services/OAuthCallbackAuthorizeService.java
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/services/OAuthRegisteredCallbackAuthorizeService.java
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/services/OAuthRegisteredService.java

Closes #1288 
Also fixes a a couple of other issues with salt storage and the loader job scheduler, all of which are related to the original issue.

Management webapp does not reload services

---

cas-server-documentation/installation/Service-Management.md

Added into Service-Management.md for JPA config (for 4.1.x branch)
See #1319

#1319 added missing namespace declaration into doc for JPA

---

cas-server-support-saml-googleapps/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsServiceResponseBuilder.java
cas-server-support-saml-googleapps/src/test/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsServiceTests.java

Closes https://github.com/Jasig/cas/issues/1322

Bug fix in googleapps skew allowance.

---

cas-server-support-saml-googleapps/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsServiceResponseBuilder.java

Ported https://github.com/Jasig/cas/pull/1330 forward for master

GoogleApps skew datetime fix for the saml response

---

cas-server-core-services/src/main/java/org/jasig/cas/authentication/principal/ShibbolethCompatiblePersistentIdGenerator.java
cas-server-core-services/src/test/java/org/jasig/cas/services/JsonServiceRegistryDaoTests.java

Fix JsonServiceRegistryDao serialization/deserialization of the salt

---

cas-server-documentation/installation/Configuring-LongTerm-Authentication.md

Closes https://github.com/Jasig/cas/issues/1351
According to
http://jasig.github.io/cas/4.1.x/installation/Configuring-LongTerm-Authentication.html

Configuring-LongTerm-Authentication documentation fix

---

cas-server-webapp-throttle/src/main/java/org/jasig/cas/web/support/InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter.java

Closes https://github.com/Jasig/cas/issues/1347
Should be ported to 4.1

Use clientInfo object when determining remote client address

---

cas-server-core-web/src/main/java/org/jasig/cas/web/flow/AbstractNonInteractiveCredentialsAction.java
cas-server-core-web/src/main/java/org/jasig/cas/web/support/WebUtils.java
cas-server-webapp-actions/build.gradle
cas-server-webapp-actions/src/main/java/org/jasig/cas/web/flow/AuthenticationViaFormAction.java

Allow the warning cookie to be set conditionally in non-interactive actions

---

cas-server-core-util/src/main/java/org/jasig/cas/util/http/SimpleHttpClientFactoryBean.java

...when sending messages to endpoints.

Allow SLO messages to reach into the CAS truststore

---

cas-server-core-web/src/main/java/org/jasig/cas/services/web/view/AbstractCasView.java
cas-server-support-pac4j/src/test/java/org/jasig/cas/support/pac4j/web/flow/ClientActionTests.java
cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/web/SamlValidateController.java
cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/web/view/Saml10SuccessResponseView.java
cas-server-support-saml/src/main/resources/META-INF/spring/saml-protocol-views.xml
cas-server-webapp-validation/src/main/java/org/jasig/cas/web/view/Cas30JsonResponseView.java
cas-server-webapp-validation/src/main/java/org/jasig/cas/web/view/Cas30ResponseView.java

This pull fixes he following bugs:
1. Ensure samlValidate responds to POST requests
2. Ensure all SAML/JSON attributes are properly encoded.

Ensure attributes are encoded

---

cas-server-core-authentication/src/test/java/org/jasig/cas/TestOneTimePasswordAuthenticationHandler.java
cas-server-core/src/test/java/org/jasig/cas/CentralAuthenticationServiceImplTests.java
cas-server-integration-memcached/src/test/java/org/jasig/cas/ticket/registry/support/kryo/KryoTranscoderTests.java
cas-server-support-duo/src/main/java/com/duosecurity/duoweb/DuoWeb.java
cas-server-support-ldap-service-registry/src/test/java/org/jasig/cas/adaptors/ldap/services/LdapServiceRegistryDaoTests.java
cas-server-support-ldap/src/main/java/org/jasig/cas/authorization/generator/LdapAuthorizationGenerator.java
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/services/OAuthCallbackAuthorizeService.java
cas-server-support-pac4j/src/test/java/org/jasig/cas/support/pac4j/web/flow/ClientActionTests.java
cas-server-support-saml/src/test/java/org/jasig/cas/support/saml/web/view/Saml10SuccessResponseViewTests.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1854 - Dead stores should be removed
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1854
Please let me know if you have any questions.
Kirill Vlasov

Dead stores should be removed

---

cas-server-documentation/installation/JPA-Ticket-Registry.md
cas-server-support-jdbc/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java

JPA EntityManager Fix

---

cas-server-webapp-actions/src/main/java/org/jasig/cas/web/flow/SendTicketGrantingTicketAction.java

Adds a debug statement to help with debugging things like #1392.

add debug statement

---

cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/applicationContext.xml

...when sending SLO messages
Closes #1389

Allow the logout manager to use CAS local truststore

---

cas-server-core/src/main/java/org/jasig/cas/authentication/UsernamePasswordCredential.java
cas-server-core/src/main/java/org/jasig/cas/services/RegexRegisteredService.java
cas-server-webapp-support/src/main/java/org/jasig/cas/web/support/InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter.java

Resolves #1347 
- Modified InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter  to use the correct username format.
- Modified UsernamePasswordCredential to return just the username in toString() method.

Issue fix 1347 - Login throttling using JdbcAuditTrailManager won't work

---

cas-server-documentation/installation/LDAP-Authentication.md

Configuring LDAP over CAS version 4.1.3 required me to add the lines.

Update LDAP Documentation

---

cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/factory/DefaultProxyPolicyMapper.java
cas-server-core-services/src/main/java/org/jasig/cas/services/DefaultRegisteredServiceAccessStrategy.java
cas-server-core-services/src/test/java/org/jasig/cas/services/DefaultRegisteredServiceAccessStrategyTests.java
cas-server-core-util/src/main/java/org/jasig/cas/util/RegexUtils.java
cas-server-documentation/installation/Configuring-Service-Access-Strategy.md
cas-server-support-ldap-service-registry/src/main/java/org/jasig/cas/adaptors/ldap/services/DefaultLdapRegisteredServiceMapper.java

Allow attribute values for access strategy to support regex

---

cas-management-webapp/src/main/java/org/jasig/cas/services/web/beans/RegisteredServiceEditBean.java
cas-management-webapp/src/main/java/org/jasig/cas/services/web/beans/RegisteredServiceSupportAccessEditBean.java
cas-management-webapp/src/main/resources/messages.properties
cas-management-webapp/src/main/resources/user-details.properties
cas-management-webapp/src/main/webapp/WEB-INF/cas-management.properties
cas-management-webapp/src/main/webapp/WEB-INF/view/jsp/includes/header.jsp
cas-management-webapp/src/main/webapp/WEB-INF/view/jsp/includes/service-form.jsp
cas-server-core/src/test/java/org/jasig/cas/services/JsonServiceRegistryDaoTests.java
cas-server-documentation/installation/Configuring-Service-Access-Strategy.md
cas-server-documentation/installation/Configuring-Service-Custom-Properties.md
cas-server-documentation/installation/Installing-ServicesMgmt-Webapp.md
cas-server-documentation/installation/Service-Management.md

1. Update management webapp docs for 4.1
2. Backport UI changes for time-based access strategy

Management webapp docs; time-based access strategy UI changes

---

cas-server-support-saml-googleapps/src/test/resources/META-INF/spring/opensaml-config.xml
cas-server-support-saml-mdui/src/test/resources/META-INF/spring/opensaml-config.xml
cas-server-support-saml/src/main/resources/META-INF/spring/opensaml-config.xml
cas-server-support-saml/src/test/resources/META-INF/spring/opensaml-config.xml

See https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing

Disable external entities, includes, and entity reference expansion for SAML parsers

---

cas-server-core-api-authentication/src/main/java/org/jasig/cas/authentication/AuthenticationSystemSupport.java
cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/DefaultAuthenticationSystemSupport.java
cas-server-core-authentication/src/test/java/org/jasig/cas/authentication/TestUtils.java
cas-server-core-web/src/main/java/org/jasig/cas/web/flow/AbstractNonInteractiveCredentialsAction.java
cas-server-core/src/test/java/org/jasig/cas/MultifactorAuthenticationTests.java
cas-server-support-pac4j/src/main/java/org/jasig/cas/support/pac4j/web/flow/ClientAction.java
cas-server-support-rest/src/main/java/org/jasig/cas/support/rest/TicketsResource.java
cas-server-support-token/src/main/java/org/jasig/cas/web/flow/token/TokenAuthenticationAction.java
cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/web/flow/WsFederationAction.java
cas-server-webapp-actions/src/main/java/org/jasig/cas/web/flow/AuthenticationViaFormAction.java
cas-server-webapp-actions/src/main/java/org/jasig/cas/web/flow/GenerateServiceTicketAction.java
cas-server-webapp-actions/src/test/java/org/jasig/cas/web/flow/GenerateServiceTicketActionTests.java
cas-server-webapp-validation/src/main/java/org/jasig/cas/web/AbstractServiceValidateController.java

Introduce Authentication subsystem facade methods.

---

cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/principal/PersonDirectoryPrincipalResolver.java

This should be merged back into 4.1 and master.

Allow the person-directory resolver to be extended

---

cas-server-core-webflow/src/main/java/org/jasig/cas/web/flow/AbstractCasWebflowConfigurer.java
cas-server-webapp-actions/src/main/java/org/jasig/cas/web/flow/InitialFlowSetupAction.java
cas-server-webapp-actions/src/test/java/org/jasig/cas/web/flow/InitialFlowSetupActionTests.java
cas-server-webapp-cookie/src/main/java/org/jasig/cas/web/WarningCookieRetrievingCookieGenerator.java
cas-server-webapp-cookie/src/main/java/org/jasig/cas/web/support/TGCCookieRetrievingCookieGenerator.java

Closes https://github.com/Jasig/cas/issues/1457
Should be merged to 4.1 and master.

Allow the TGC path to be configured

---

cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/applicationContext.xml

also try to interrupt any interruptable jobs

wait for Quartz to shutdown

---

cas-server-core-services/src/main/java/org/jasig/cas/services/JsonServiceRegistryConfigWatcher.java
cas-server-core-services/src/main/java/org/jasig/cas/services/JsonServiceRegistryDao.java
cas-server-core-util/src/main/java/org/jasig/cas/util/http/SimpleHttpClientFactoryBean.java
cas-server-support-rest/src/main/java/org/jasig/cas/support/rest/TicketsResource.java
gradle.properties

Closes #1458 
Should be merged into 4.2 and likely 4.1.

Clean up leaking threads

---

cas-management-webapp/src/main/webapp/WEB-INF/spring-configuration/propertyFileConfigurer.xml
cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/propertyFileConfigurer.xml

So it could be set via external property, with an old default value if no external property is provided.

More flexible config location setting

---

cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/beans/RegisteredServiceEditBean.java
cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/beans/RegisteredServiceViewBean.java
cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/factory/DefaultRegisteredServiceMapper.java

represent assignedId as a String for Services Management

---

build.gradle
cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/web/view/AbstractSaml10ResponseView.java

Should be merged back into 4.1 and 4.2

Ensure SAML1 InResponseTo field is valid as a CName

---

build.gradle
gradle.properties

Jackson 2.7 does not work with Spring 4.2.3:
http://stackoverflow.com/questions/34721851/spring-4-2-3-and-fasterxml-jackson-2-7-0-are-incompatible

Switch jackson dependency to 2.6.x

---

cas-management-webapp/src/main/webapp/WEB-INF/web.xml
cas-server-core-logging/src/main/java/org/jasig/cas/util/CasLoggerContextInitializer.java
cas-server-core-util/src/main/java/org/jasig/cas/util/http/SimpleHttpClientFactoryBean.java
cas-server-webapp/src/main/webapp/WEB-INF/web.xml

Log4j2 reconfig

---

cas-server-documentation/installation/JPA-Ticket-Registry.md
cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java
cas-server-support-jpa-ticket-registry/src/test/java/org/jasig/cas/ticket/registry/JpaTicketRegistryTests.java
cas-server-support-jpa-ticket-registry/src/test/resources/jpaSpringContext.xml
cas-server-webapp/src/main/webapp/WEB-INF/cas.properties

JPA deadlock prevention

---

cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java

minor generic fix up I noticed while reviewing other code.

fix generics usage in JpaTicketRegistry

---

cas-management-webapp/src/main/java/org/jasig/cas/services/web/beans/RegisteredServiceEditBean.java
cas-management-webapp/src/main/java/org/jasig/cas/services/web/beans/RegisteredServiceViewBean.java
cas-server-documentation/installation/Blacklist-Authentication.md
cas-server-support-generic/src/main/java/org/jasig/cas/adaptors/generic/RejectUsersAuthenticationHandler.java

Closes https://github.com/Jasig/cas/issues/1484

Fixed configuration of RejectUsersAuthenticationHandler

---

build.gradle
cas-management-webapp/src/main/resources/log4j2.xml

Closes https://github.com/Jasig/cas/issues/1491

Fix aspectj weaving dependencies

---

cas-server-support-saml-idp/src/main/java/org/jasig/cas/support/saml/web/idp/profile/builders/SamlProfileObjectBuilder.java
cas-server-support-saml-idp/src/main/java/org/jasig/cas/support/saml/web/idp/profile/builders/SamlProfileSamlNameIdBuilder.java

Saml missing NameIDFormat

---

cas-server-documentation/protocol/CAS-Protocol-Specification.md
cas-server-documentation/protocol/CAS-Protocol.md

Closes https://github.com/Jasig/cas/issues/1513

Mark LT as optional in CAS spec

---

cas-server-integration-memcached/src/main/java/org/jasig/cas/monitor/MemcachedMonitor.java
cas-server-webapp-support/src/main/java/org/jasig/cas/web/flow/GenerateServiceTicketAction.java

Disallow double authN when generating STs

---

cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/factory/DefaultAttributeReleasePolicyMapper.java
cas-server-core-logging/src/main/java/org/jasig/cas/util/CasLoggerContextInitializer.java
cas-server-core-services/src/main/java/org/jasig/cas/util/services/DefaultRegisteredServiceCipherExecutor.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/DefaultTicketRegistry.java
cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
cas-server-core/src/test/java/org/jasig/cas/AbstractCentralAuthenticationServiceTests.java
cas-server-integration-ehcache/src/main/java/org/jasig/cas/ticket/registry/EhCacheTicketRegistry.java
cas-server-integration-hazelcast/src/main/java/org/jasig/cas/ticket/registry/config/HazelcastInstanceConfiguration.java
cas-server-support-openid/src/main/java/org/jasig/cas/support/openid/authentication/principal/OpenIdServiceResponseBuilder.java
cas-server-webapp-actions/src/main/java/org/jasig/cas/web/flow/GenerateServiceTicketAction.java
cas-server-webapp-actions/src/test/java/org/jasig/cas/web/flow/GenerateServiceTicketActionTests.java

Closes #1506 
Patch for 4.2
Fixed a number of javadoc issues as well.

disallow double authN when ST is generated

---

cas-server-core-logging/src/main/java/org/jasig/cas/util/CasLoggerContextInitializer.java
cas-server-core-logging/src/main/java/org/slf4j/impl/CasDelegatingLogger.java

Logging Fixes

---

cas-server-support-ldap/src/main/java/org/jasig/cas/adaptors/ldap/services/LdapServiceRegistryDao.java

LDAP service registry opens to connections when attempting to update services: one to search and one to modify. This patch closes the first connection early before attempting to obtain the second connection. If the ldap instance does not allow connection pooling, (or if the pool size is set to 1) the current behavior causes updates to hang.

Drop search connection early for ldap service registry during updates

---

cas-server-webapp-support/src/main/java/org/jasig/cas/web/flow/InitialFlowSetupAction.java
cas-server-webapp-support/src/test/java/org/jasig/cas/web/flow/InitialFlowSetupActionTests.java

fixes #1531 - InitialFlowSetupAction will only set cookie paths if paths are not configured

---

cas-server-core/src/main/java/org/jasig/cas/authentication/principal/package.html

Update of really outdated documentation, issue #1532

Updating documantation by adopting master (4.2.x) doc #1532

---

cas-server-webapp-support/src/main/java/org/jasig/cas/web/flow/AuthenticationViaFormAction.java
cas-server-webapp-support/src/main/java/org/jasig/cas/web/flow/GenerateServiceTicketAction.java

Opened to utilize travis to check the build

Expose TicketExceptions to webflow

---

cas-server-documentation/installation/OAuth-OpenId-Authentication.md
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/ticket/accesstoken/OAuthAccessTokenExpirationPolicy.java
cas-server-support-oauth/src/main/resources/META-INF/spring/cas-servlet-oauth.xml
cas-server-webapp/src/main/webapp/WEB-INF/cas.properties

Closes #1505 
@leleuj You should review this. 
Note that expiration policy for codes is handled already.

OAuth expiration policy for access tokens. 

---

cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/principal/PersonDirectoryPrincipalResolver.java

Fix bad logger call in PD resolver

---

cas-management-webapp-support/src/test/java/org/jasig/cas/services/web/RegisteredServiceSimpleFormControllerTests.java
cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/DefaultAuthenticationResultBuilder.java
cas-server-core-authentication/src/main/java/org/jasig/cas/services/ReturnAllowedAttributeReleasePolicy.java
cas-server-core-authentication/src/main/java/org/jasig/cas/services/ReturnMappedAttributeReleasePolicy.java
cas-server-core-services/src/main/java/org/jasig/cas/authentication/principal/AbstractWebApplicationService.java
cas-server-core-services/src/test/java/org/jasig/cas/services/DefaultRegisteredServiceAccessStrategyTests.java
cas-server-core-services/src/test/java/org/jasig/cas/services/JsonServiceRegistryDaoTests.java
cas-server-core-services/src/test/java/org/jasig/cas/services/support/RegisteredServiceRegexAttributeFilterTests.java
cas-server-core-util/src/main/java/org/jasig/cas/util/http/SimpleHttpClientFactoryBean.java
cas-server-core/src/test/java/org/jasig/cas/CentralAuthenticationServiceImplWithMockitoTests.java
cas-server-extension-clearpass/src/main/java/org/jasig/cas/extension/clearpass/EhcacheBackedMap.java
cas-server-integration-memcached/src/test/java/org/jasig/cas/ticket/registry/support/kryo/KryoTranscoderTests.java
cas-server-support-duo/src/main/java/org/jasig/cas/adaptors/duo/DuoAuthenticationHandler.java
cas-server-support-oauth/src/test/java/org/jasig/cas/support/oauth/web/OAuth20ProfileControllerTests.java
cas-server-support-radius/src/main/java/org/jasig/cas/adaptors/radius/authentication/handler/support/RadiusAuthenticationHandler.java
cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/authentication/handler/support/WsFederationAuthenticationHandler.java
cas-server-support-x509/src/main/java/org/jasig/cas/adaptors/x509/authentication/handler/support/ResourceCRLRevocationChecker.java
cas-server-support-x509/src/main/java/org/jasig/cas/adaptors/x509/authentication/principal/X509SubjectPrincipalResolver.java
cas-server-webapp-actions/src/main/java/org/jasig/cas/web/flow/CasDefaultFlowUrlHandler.java
cas-server-webapp-actions/src/main/java/org/jasig/cas/web/flow/GenerateServiceTicketAction.java
cas-server-webapp-reports/src/main/java/org/jasig/cas/web/report/StatisticsController.java
checkstyle-rules.xml

So this:
```java
Map<String, Object> EMPTY_MAP = Collections.unmodifiableMap(new HashMap<String, Object>());
```
Becomes:
```java
Map<String, Object> EMPTY_MAP = Collections.unmodifiableMap(new HashMap<>());
```

Remove explicit typecast and replace with <>

---

cas-server-core-services/src/main/java/org/jasig/cas/authentication/principal/AbstractWebApplicationService.java

Change EMPTY_MAP to use native immutables

---

cas-server-support-ldap/src/main/java/org/jasig/cas/authorization/generator/LdapAuthorizationGenerator.java

Allow LdapAuthorizationGenerator to be extended for profile roles

---

cas-server-documentation/installation/Configuring-SSO-Session-Cookie.md
cas-server-webapp-cookie/src/main/java/org/jasig/cas/web/support/TGCCookieRetrievingCookieGenerator.java
cas-server-webapp/src/main/webapp/WEB-INF/cas.properties

Allows setting the domain parameter of the TGC.

Add domain configuration for TGC

---

cas-server-documentation/protocol/OpenID-Protocol.md
cas-server-support-openid/src/main/java/org/jasig/cas/support/openid/authentication/principal/OpenIdServiceResponseBuilder.java
cas-server-support-openid/src/main/java/org/jasig/cas/support/openid/web/OpenIdProviderController.java
cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/protocol/openid/casOpenIdAssociationSuccessView.jsp
cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/protocol/openid/user.jsp

Complements https://github.com/Jasig/cas/pull/1557

Support non-assoc mode of openid

---

cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/AbstractTicketRegistry.java
cas-server-integration-memcached/src/main/java/org/jasig/cas/ticket/registry/MemCacheTicketRegistry.java
cas-server-support-couchbase-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/CouchbaseTicketRegistry.java

Closes https://github.com/Jasig/cas/issues/1585

Enable the Ticket Cleaner by default

---

cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/DefaultTicketRegistry.java

Closes https://github.com/Jasig/cas/issues/1596

Remove bad integer casts

---

cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/support/HardTimeoutExpirationPolicy.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/support/MultiTimeUseOrTimeoutExpirationPolicy.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/support/ThrottledUseAndTimeoutExpirationPolicy.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/support/TicketGrantingTicketExpirationPolicy.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/support/TimeoutExpirationPolicy.java

Fix integer overflow when specifying long timeouts

---

cas-server-webapp-cookie/src/main/java/org/jasig/cas/web/support/CookieRetrievingCookieGenerator.java

Null out TGC domain if blank

---

cas-server-webapp-throttle/src/main/java/org/jasig/cas/web/support/AbstractInMemoryThrottledSubmissionHandlerInterceptorAdapter.java

Fix interval in throttling configuration

---

cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/PolicyBasedAuthenticationManager.java
cas-server-core/src/main/java/org/jasig/cas/AbstractCentralAuthenticationService.java

Remove the final keyword from audit annotations

---

cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
cas-server-core/src/test/java/org/jasig/cas/CentralAuthenticationServiceImplTests.java

Allow ssoEnabled false to activate only if TGT is used once

---

cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java

Fix default interval and logmessage of JpaTicketRegistry

---

cas-server-webapp-actions/src/main/java/org/jasig/cas/web/flow/CasDefaultFlowUrlHandler.java
cas-server-webapp-actions/src/test/java/org/jasig/cas/web/flow/AllTestsSuite.java
cas-server-webapp-actions/src/test/java/org/jasig/cas/web/flow/CasDefaultFlowUrlHandlerTests.java

Closes #1593 for the master branch.

Fix query string parameters in webflow redirect

---

cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
cas-server-core/src/test/java/org/jasig/cas/CentralAuthenticationServiceImplTests.java

Port https://github.com/Jasig/cas/issues/1610 to 4.2

Fix: Grant ST always fails when ssoEnabled flag is unset 

---

cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java

Related to https://github.com/Jasig/cas/issues/1610

Ensure proxy authN is taken into account when using ssoEnabled=false

---

cas-server-webapp-config/src/main/java/org/jasig/cas/config/CasWebAppConfiguration.java

Remove extra slash from path prefix

---

cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/support/HardTimeoutExpirationPolicy.java

Wrong expiration computation in HardTimeoutExpirationPolicy

---

cas-server-documentation/installation/User-Interface-Customization.md
cas-server-webapp-config/src/main/java/org/jasig/cas/config/CasWebAppConfiguration.java
cas-server-webapp-config/src/main/java/org/jasig/cas/config/CasWebflowContextConfiguration.java
cas-server-webapp-themes/src/main/java/org/jasig/cas/services/web/RegisteredServiceThemeBasedViewResolver.java
cas-server-webapp-themes/src/test/java/org/jasig/cas/services/web/RegisteredServiceThemeBasedViewResolverTests.java

Reorganize the webflow view resolvers

---

cas-server-core/src/main/java/org/jasig/cas/web/support/WebUtils.java
cas-server-webapp-support/src/main/java/org/jasig/cas/web/flow/InitialFlowSetupAction.java
cas-server-webapp/src/main/webapp/WEB-INF/webflow/login/login-webflow.xml

issue-1634: correctly accessing unauthorizedRedirectUrl

---

cas-server-core/src/main/java/org/jasig/cas/CasVersion.java

Closes https://github.com/Jasig/cas/issues/1651

Handle vfs resource when checking for CAS date/time

---

cas-server-core/src/main/java/org/jasig/cas/CasVersion.java

get the VirtualFile object from the vfs URL

---

cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/top.jsp

Closes #1667
Quick change to close the meta tag that some CAS clients have reported as an issue.

Update top.jsp meta tag for correct closing tag

---

cas-server-support-oauth/src/main/resources/META-INF/spring/cas-servlet-oauth.xml

When using OAuth support, the pac4j logout hides the CAS logout

---

cas-server-core-authentication/src/main/java/org/jasig/cas/web/flow/AuthenticationExceptionHandler.java
cas-server-core-authentication/src/test/java/org/jasig/cas/authentication/FileTrustStoreSslSocketFactoryTests.java
cas-server-core-authentication/src/test/java/org/jasig/cas/util/TrustedProxyAuthenticationTrustStoreSslSocketFactoryTests.java
cas-server-core-authentication/src/test/java/org/jasig/cas/web/flow/AuthenticationExceptionHandlerTests.java
cas-server-documentation/installation/Webflow-Customization.md
cas-server-webapp/src/main/webapp/WEB-INF/cas.properties

Flexible custom authentication exceptions configuration

---

gradle.properties

update PersonDirectory to v1.7.1

---

cas-server-support-jdbc/src/main/java/org/jasig/cas/adaptors/jdbc/QueryAndEncodeDatabaseAuthenticationHandler.java
cas-server-support-jdbc/src/test/java/org/jasig/cas/adaptors/jdbc/QueryAndEncodeDatabaseAuthenticationHandlerTests.java

Allow QueryAndEncodeDatabaseAuthenticationHandler to be optional

---

cas-server-core-services/src/main/java/org/jasig/cas/services/DefaultRegisteredServiceAccessStrategy.java
cas-server-core-services/src/main/java/org/jasig/cas/services/TimeBasedRegisteredServiceAccessStrategy.java
cas-server-integration-grouper/src/main/java/org/jasig/cas/grouper/services/GrouperRegisteredServiceAccessStrategy.java

JPA Service Registry: Changed loggers to be static

---

cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/authentication/handler/support/JcifsConfig.java
cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/web/flow/SpnegoCredentialsAction.java

Fixes #1696

---

cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/DefaultTicketRegistry.java

Allow the ticket cleaning process to operate on the same registry instance

---

cas-server-webapp/src/main/resources/messages_sk.properties
cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/casLoginView.jsp

adds messages for slovak language
adds Slovak option to casLoginView.jsp

provide slovak localization

---

cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/BaseOAuthWrapperController.java
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20AccessTokenController.java
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20AuthorizeController.java
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20ProfileController.java
cas-server-support-oauth/src/test/java/org/jasig/cas/support/oauth/web/OAuth20AuthorizeControllerTests.java

OAuth support should take into account CAS services definition

---

cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/support/TicketGrantingTicketExpirationPolicy.java
cas-server-integration-ehcache/src/main/java/org/jasig/cas/ticket/registry/EhCacheTicketRegistry.java
cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/authentication/handler/support/JcifsConfig.java
cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/web/flow/SpnegoCredentialsAction.java
cas-server-webapp-throttle/src/main/java/org/jasig/cas/web/support/AbstractThrottledSubmissionHandlerInterceptorAdapter.java

Closes https://github.com/Jasig/cas/issues/1696#issuecomment-216932461

Backport #1696 into 4.2.x. Handles missing spnego annotations

---

cas-management-webapp-support/build.gradle

Closes https://github.com/Jasig/cas/issues/1741

Add missing 'disruptor' dependency to management webapp

---

cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20AccessTokenController.java
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20AuthorizeController.java
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20CallbackAuthorizeController.java
cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20ProfileController.java
cas-server-webapp-config/src/main/java/org/jasig/cas/config/CasProtocolViewsConfiguration.java
cas-server-webapp/src/main/resources/templates/fragments/loginsidebar.html

The default display custom pac4j client.
fix remove refresh_token errors, modifications may have worked, of course, the best way is not to judge by type.
OAuth has been unable to work, add some missing annotations.

OAuth endpoints need @Controller annotations.

---

cas-server-core-api-ticket/src/main/java/org/jasig/cas/ticket/TicketGrantingTicket.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/TicketGrantingTicketImpl.java
cas-server-core-tickets/src/test/java/org/jasig/cas/mock/MockTicketGrantingTicket.java
cas-server-core/src/main/java/org/jasig/cas/AbstractCentralAuthenticationService.java
cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
cas-server-core/src/test/java/org/jasig/cas/CentralAuthenticationServiceImplTests.java
cas-server-core/src/test/java/org/jasig/cas/MultifactorAuthenticationTests.java

Removed Supplemental Authentications

---

cas-server-core-web/src/main/java/org/apereo/cas/web/support/WebUtils.java
cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/Pac4jConfiguration.java
cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/Pac4jProperties.java
cas-server-webapp-actions/src/main/java/org/apereo/cas/web/flow/InitialFlowSetupAction.java
cas-server-webapp/src/main/java/org/apereo/cas/web/CasWebApplication.java

@mmoayyed  These modifications in #1732 are missing，#1745

fix refactor top level package to org.apereo error

---

cas-server-core-authentication/src/main/java/org/jasig/cas/services/AbstractRegisteredServiceAttributeReleasePolicy.java
cas-server-core-authentication/src/main/java/org/jasig/cas/services/ReturnAllowedAttributeReleasePolicy.java
cas-server-core-authentication/src/main/java/org/jasig/cas/services/ReturnMappedAttributeReleasePolicy.java
cas-server-core-services/src/main/java/org/jasig/cas/services/DefaultRegisteredServiceUsernameProvider.java

Closes #1736 
use static loggers for principal attribute repository config

use static loggers for principal attribute repository config

---

gradle.properties

Spring Boot 1.3.4 introduced some regression and they have quickly released 1.3.5

Update Spring Boot to 1.3.5

---

cas-server-webapp/src/main/resources/webflow/login/login-webflow.xml

Fixes an error in the webflow that prevented correct handling of password expiration.

fix webflow for LPPE

---

cas-server-webapp-cookie/src/main/java/org/jasig/cas/web/support/CookieRetrievingCookieGenerator.java

4.2.x
Please refer to fix for 4.1.x: [PR#1796](https://github.com/apereo/cas/pull/1769).

[WIP][Fix][4.2.x] Add HttpOnly to CookieRetrievingCookieGenerator

---

cas-server-webapp-cookie/src/main/java/org/apereo/cas/web/support/CookieRetrievingCookieGenerator.java

Master
Please refer to #1769  and #1774.

[WIP][Fix][Master] Add HttpOnly to CookieRetrievingCookieGenerator

---

cas-server-core-services/src/main/java/org/apereo/cas/services/RegexRegisteredService.java
cas-server-core-util/src/main/java/org/apereo/cas/util/RegexUtils.java

Ignore bad regex patterns for services when executing service match ops

---

cas-server-support-spnego-webflow/src/main/java/org/apereo/cas/web/flow/SpengoWebflowConfigurer.java

Fix for #1797 - Typo in SpengoWebflowConfigurer

---

cas-server-support-oauth/src/main/java/org/apereo/cas/OAuthApplicationContextWrapper.java

Fix issue with incorrect generation of the OAuth Calllback URL

---

cas-server-core-audit/src/main/java/org/apereo/cas/audit/spi/AssertionAsReturnValuePrincipalResolver.java
cas-server-core-audit/src/main/java/org/apereo/cas/audit/spi/TicketOrCredentialPrincipalResolver.java
cas-server-core-audit/src/test/java/org/apereo/cas/audit/spi/AssertionAsReturnValuePrincipalResolverTests.java
cas-server-webapp-config/src/main/java/org/apereo/cas/config/CasAuditTrailConfiguration.java

Closes #1784
This should also be back ported to `4.2.3` and `4.1.9`

Resolve proper Inspektr principal at serviceValidate joinpoint

---

build.gradle
gradle.properties

Update shiro version; fixed build jar compilation issue

---

cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/SamlProfileSamlAssertionBuilder.java
cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/SamlProfileSamlResponseBuilder.java
cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/SamlProfileSamlSubjectBuilder.java

Closes #1829 
Use $skewAllowance for add to SubjectConformationData/NotOnOrAfter

Fix for issue #1829 

---

cas-server-core-api-services/src/main/java/org/jasig/cas/services/RegisteredServicePublicKey.java
cas-server-core-services/src/main/java/org/jasig/cas/services/RegisteredServicePublicKeyImpl.java
cas-server-support-jpa-service-registry/src/test/java/org/jasig/cas/services/JpaServiceRegistryDaoImplTests.java

Fix JPA Service Registry: Public Key Location cast to Blob

---

cas-server-core-audit/src/main/resources/inspektr-jdbc-audit-config.xml
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/ProxyGrantingTicketDelegator.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/ServiceTicketDelegator.java
cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/TicketGrantingTicketDelegator.java
cas-server-core-util/build.gradle
cas-server-core-util/src/main/java/org/jasig/cas/util/PseudoTransactionManager.java
cas-server-core/build.gradle
cas-server-core/src/main/java/org/jasig/cas/AbstractCentralAuthenticationService.java
cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java
cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/support/JpaLockingStrategy.java
cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/applicationContext.xml

Closes https://github.com/apereo/cas/issues/1850

Fixed issue with missing transaction mgmr when more than one is expected

---

cas-server-core-logging/build.gradle
cas-server-core-monitor/build.gradle
cas-server-core-services/build.gradle
cas-server-core-tickets/build.gradle
cas-server-core/build.gradle
cas-server-support-ldap/build.gradle
cas-server-support-yubikey/build.gradle
cas-server-webapp-throttle/build.gradle
gradle.properties

Removed duplicate javassist dependencies

---

cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java

Fix for #1893

---

cas-server-support-spnego-webflow/src/main/java/org/jasig/cas/web/flow/SpengoWebflowConfigurer.java

Resolve #1982

---

cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/authentication/handler/support/JcifsConfig.java
cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/authentication/handler/support/JcifsSpnegoAuthenticationHandler.java
cas-server-support-spnego/src/test/java/org/jasig/cas/support/spnego/authentication/handler/support/JcifsSpnegoAuthenticationHandlerTests.java

Closes https://github.com/apereo/cas/issues/1909

JAAS Login config not found by Spnego

---

cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/RegisteredServiceSimpleFormController.java
cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/beans/RegisteredServiceEditBean.java
cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/factory/DefaultRegisteredServiceFactory.java

Closes https://github.com/apereo/cas/issues/1663 https://github.com/apereo/cas/issues/1631

Remove files before renaming them. Preserve properties

---

cas-server-support-ldap/src/main/java/org/apereo/cas/config/LdapAuthenticationConfiguration.java

Fix SearchEntryResolver config issue

---

cas-server-support-ldap/src/main/java/org/apereo/cas/config/LdapAuthenticationConfiguration.java

Ldaptive 1.2: Support pooled search entry resolvers and authenticator attributes

---

cas-server-support-jpa-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/JpaTicketRegistry.java

For CAS Server 5.0.0.M3. Fix JpaTicketRegistry can't retrieve RefreshToken.

Fix JpaTicketRegistry can't retrieve RefreshToken

---

cas-server-documentation/installation/Hazelcast-Ticket-Registry.md
cas-server-integration-hazelcast/src/main/java/org/jasig/cas/ticket/registry/config/HazelcastInstanceConfiguration.java
cas-server-integration-hazelcast/src/main/java/org/jasig/cas/ticket/registry/config/HazelcastProperties.java
gradle.properties

Also, update the hazelcast version.

Let CAS configure backup settings for Hazelcast

---

cas-server-webapp-reports/src/main/java/org/jasig/cas/web/report/HealthCheckController.java
cas-server-webapp/src/main/webapp/WEB-INF/web.xml

This behavior already exists in master. Just porting back.

Let the /status endpoint run in async mode.

---

cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/ldap/AbstractLdapProperties.java
cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/ldap/LdapAuthenticationProperties.java
cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java
cas-server-documentation/installation/Configuration-Properties.md
cas-server-support-ldap/src/main/java/org/apereo/cas/config/LdapAuthenticationConfiguration.java

- [none] Any possible limitations, side effects, etc
- [none] Reference any other pull requests that might be related.
adds logic to configure ldaptive's sasl bindings

add sasl support

---

cas-server-documentation/installation/SPNEGO-Authentication.md

Here's my little update for SPNEGO documentation as suggested by @mmoayyed

updated SPNEGO Documentation

---

cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/oidc/OidcProperties.java
cas-server-documentation/installation/OIDC-Authentication.md
cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/OAuth20AccessTokenResponseGenerator.java
cas-server-support-oidc/src/main/java/org/apereo/cas/OidcConstants.java
cas-server-support-oidc/src/main/java/org/apereo/cas/config/OidcConfiguration.java
cas-server-support-oidc/src/main/java/org/apereo/cas/config/OidcServerDiscoverySettings.java
cas-server-support-oidc/src/main/java/org/apereo/cas/web/OidcAccessTokenResponseGenerator.java
cas-server-support-oidc/src/main/java/org/apereo/cas/web/controllers/OidcAccessTokenEndpointController.java
cas-server-support-oidc/src/main/java/org/apereo/cas/web/controllers/OidcAuthorizeEndpointController.java
cas-server-support-oidc/src/main/java/org/apereo/cas/web/controllers/OidcProfileEndpointController.java
cas-server-support-oidc/src/main/java/org/apereo/cas/web/controllers/OidcWellKnownEndpointController.java

Fixing OAuth / OIDC support

---

cas-server-support-oauth-core/src/main/java/org/apereo/cas/support/oauth/OAuthConstants.java
cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/OAuth20AccessTokenResponseGenerator.java
cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/OAuth20AuthorizeController.java
cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/OAuth20AccessTokenControllerTests.java

see https://tools.ietf.org/html/rfc6749

OAuth2 Using RFC Name "expires_in"

---

cas-server-webapp-config/src/main/java/org/apereo/cas/config/CasWebAppConfiguration.java

You should use the user's selection

fixed issue with locales

---

cas-server-documentation/installation/OIDC-Authentication.md

OIDC: Update endpoints in the docs

---

cas-server-core-util/src/main/java/org/apereo/cas/util/http/SimpleHttpClient.java

If logout is synchornous, check for the status code rather than the response

---

cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/oidc/OidcProperties.java
cas-server-documentation/installation/OIDC-Authentication.md
cas-server-support-oidc/src/main/java/org/apereo/cas/web/controllers/OidcWellKnownEndpointController.java
gradle.properties

I let #1976 open for UI updates.

OIDC: set the signing algorithms

---

cas-server-documentation/installation/OAuth-OpenId-Authentication.md

Documentation improvement.
This has to be added in order for OAuth to works
This configuration block has to be added in web.xml to make OAuth work

Add required servlet-mapping config in OAuth guide

---

docs/cas-server-documentation/installation/Configuration-Properties.md

resource: file support for SAML is broken

---

cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/protocol/openid/casOpenIdAssociationSuccessView.jsp

Restores previous` casOpenIdAssociationSuccessView.jsp` contents (before cleanup).
Closes #2006.

Send valid OpenID association session response

---

docs/cas-server-documentation/installation/SPNEGO-Authentication.md

Documentation update related to #2018

Update webflow configuration documentation for SPNEGO

---

core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jProperties.java
docs/cas-server-documentation/installation/Configuration-Properties.md
gradle.properties
support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/Pac4jConfiguration.java
support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/web/flow/ClientAction.java

SAML authentication delegation is broken

---

api/cas-server-core-api-events/src/main/java/org/apereo/cas/support/events/CasAuditActionContextRecordedEvent.java

Closes #IssueNumber
- [] Brief description of changes applied
- [] Reference any other pull requests that might be related.

Adding this. to getAuditActionContext() method

---

docs/cas-server-documentation/installation/Basic-Authentication.md

Fixed Maven groupId to: org.apereo.cas (was: org.aapereo.cas)

Fixed groupId

---

core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/DefaultWebflowConfigurer.java

Fixes gatewayServicesManagementCheck action state creation

---

support/cas-server-support-oidc/src/main/java/org/apereo/cas/web/OidcAccessTokenResponseGenerator.java

Fix OIDC expiration date unit

---

support/cas-server-support-oidc/src/main/java/org/apereo/cas/web/OidcAccessTokenResponseGenerator.java

Fix after #2057 
Was unable to run the project locally, I wanted to wait for travis-ci but you were too fast sorry !
Should be better...

Bad usage of NumerciDate for OIDC

---

core/cas-server-core-util/src/main/java/org/apereo/cas/util/http/SimpleHttpClientFactoryBean.java

Consider 204 an acceptable HTTP code

---

gradle.properties

Upgrade to spring-webmvc-pac4j v1.1.3

---

gradle.properties

Security issue: upgrade to pac4j v1.9.4 and spring-webmvc-pac4j v1.1.4

---

core/cas-server-core-authentication/src/main/java/org/apereo/cas/authentication/handler/support/AbstractUsernamePasswordAuthenticationHandler.java
support/cas-server-support-jdbc/src/main/java/org/apereo/cas/adaptors/jdbc/QueryDatabaseAuthenticationHandler.java
support/cas-server-support-jdbc/src/test/java/org/apereo/cas/adaptors/jdbc/QueryDatabaseAuthenticationHandlerTests.java

Closes #2112 IssueNumber
port fixes from release 5.0.x

port of fixes related to #2112 from release 5.0.x

---

core/cas-server-core-tickets/src/main/java/org/apereo/cas/util/DefaultUniqueTicketIdGenerator.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/util/DefaultUniqueTicketIdGeneratorTests.java

This PR doesn't close any issue, it's just an improvement
- Code a bit cleaner
- Make suffix not null, so no more null checks needed

Unique id generator improvements

---

core/cas-server-core-services/src/main/java/org/apereo/cas/services/DefaultServicesManagerImpl.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/DefaultServicesManagerImplTests.java

Closes #2133 
- Cache the ordered services tree

Improve service registry performance by caching ordered services

---

core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java
support/cas-server-support-gauth/src/main/java/org/apereo/cas/adaptors/gauth/GoogleAuthenticatorAuthenticationHandler.java
support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/util/LdapUtils.java
support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/IdPInitiatedProfileHandlerController.java

Closes #2170 
Replace deprecated method with suggested alternatives

Cleaning some deprecated

---

core/cas-server-core-services/src/main/java/org/apereo/cas/services/DefaultServicesManagerImpl.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/DefaultServicesManagerImplTests.java

Closes #2166 
Changes:
- recreate the ordered Set 
- add tests for this cases

Changes to json file in JSONServiceRegistry are not dynamically loaded into CAS Server

---

support/cas-server-support-generic/src/main/java/org/apereo/cas/adaptors/generic/FileAuthenticationHandler.java

Read file the Java 8 way

---

core/cas-server-core-services/src/main/java/org/apereo/cas/services/RegisteredServiceAccessStrategyUtils.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/AbstractServiceValidateController.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/LegacyValidateController.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/ProxyController.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/ProxyValidateController.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/ServiceValidateController.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/config/CasProtocolViewsConfiguration.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/config/CasValidationConfiguration.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/v3/V3ProxyValidateController.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/v3/V3ServiceValidateController.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/view/Cas10ResponseView.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/view/Cas30ResponseView.java
support/cas-server-support-validation/src/test/java/org/apereo/cas/web/AbstractServiceValidateControllerTests.java
support/cas-server-support-validation/src/test/java/org/apereo/cas/web/view/Cas10ResponseViewTests.java
support/cas-server-support-validation/src/test/java/org/apereo/cas/web/view/Cas20ResponseViewTests.java
support/cas-server-support-validation/src/test/java/org/apereo/cas/web/view/Cas30ResponseViewTests.java

Formatting validation module

---

core/cas-server-core-monitor/src/main/java/org/apereo/cas/monitor/HealthCheckMonitor.java
core/cas-server-core-monitor/src/main/java/org/apereo/cas/monitor/MemoryMonitor.java
core/cas-server-core-monitor/src/main/java/org/apereo/cas/monitor/SessionMonitor.java
core/cas-server-core-monitor/src/main/java/org/apereo/cas/monitor/config/CasCoreMonitorConfiguration.java
core/cas-server-core-monitor/src/test/java/org/apereo/cas/monitor/HealthCheckMonitorTests.java
core/cas-server-core-monitor/src/test/java/org/apereo/cas/monitor/MemoryMonitorTests.java
core/cas-server-core-monitor/src/test/java/org/apereo/cas/monitor/SessionMonitorTests.java
core/cas-server-core-services/src/main/java/org/apereo/cas/authentication/DefaultMultifactorTriggerSelectionStrategy.java
core/cas-server-core-services/src/main/java/org/apereo/cas/authentication/support/DefaultCasAttributeEncoder.java
core/cas-server-core-services/src/main/java/org/apereo/cas/config/CasCoreServicesConfiguration.java
core/cas-server-core-services/src/main/java/org/apereo/cas/services/DefaultServicesManagerImpl.java
core/cas-server-core-services/src/test/java/org/apereo/cas/authentication/DefaultMultifactorTriggerSelectionStrategyTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/DefaultServicesManagerImplTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/RegisteredServiceAuthenticationHandlerResolverTests.java
core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasCoreTicketsConfiguration.java
core/cas-server-core-tickets/src/main/java/org/apereo/cas/ticket/DefaultProxyTicketFactory.java
core/cas-server-core-tickets/src/main/java/org/apereo/cas/ticket/proxy/support/Cas20ProxyHandler.java
core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/proxy/support/Cas20ProxyHandlerTests.java
core/cas-server-core/src/test/java/org/apereo/cas/CentralAuthenticationServiceImplWithMockitoTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/LogoutActionTests.java
support/cas-server-support-jpa-ticket-registry/src/test/java/org/apereo/cas/monitor/SessionMonitorJpaTests.java
support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/SamlRegisteredServiceTests.java
support/cas-server-support-saml/src/test/java/org/apereo/cas/support/saml/web/view/Saml10SuccessResponseViewTests.java
support/cas-server-support-saml/src/test/resources/opensaml-config.xml
support/cas-server-support-themes/src/test/java/org/apereo/cas/services/web/ServiceThemeResolverTests.java
support/cas-server-support-validation/src/test/java/org/apereo/cas/web/AbstractServiceValidateControllerTests.java
webapp-mgmt/cas-management-webapp-support/src/test/java/org/apereo/cas/services/web/ManageRegisteredServicesMultiActionControllerTests.java
webapp-mgmt/cas-management-webapp-support/src/test/java/org/apereo/cas/services/web/RegisteredServiceSimpleFormControllerTests.java

Part of #2184 
Move to constructor based injection all beans created in CasCoreServicesConfiguration.java and CasCoreMonitorConfiguration.java

Use constructor based injection

---

support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/authorization/LdapAuthorizationGenerator.java
webapp-mgmt/cas-management-webapp-support-ldap/src/main/java/org/apereo/cas/mgmt/config/CasManagementLdapAuthorizationConfiguration.java

Part of #2184
Move to constructor based injection all beans created in LdapAuthorizationGenerator.java

Use constructor based injection 

---

core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/resolver/impl/InitialAuthenticationAttemptWebflowEventResolver.java

Closes no issue
Just a tiny change replacing logic with a stream

Replace with a stream

---

core/cas-server-core-authentication/src/main/java/org/apereo/cas/config/CasCoreAuthenticationConfiguration.java

Use streams to improve readability

Extract a method for retrieving the parsed users, using streams

---

core/cas-server-core-audit/src/main/java/org/apereo/cas/audit/spi/MessageBundleAwareResourceResolver.java

Parta of #2212 
Improve stream readability

Improving stream readability

---

core/cas-server-core/src/test/java/org/apereo/cas/MultifactorAuthenticationTests.java

Part of #2212
replacing Guava in core module

Replacing Guava with java collections

---

checkstyle-rules.xml
core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/core/web/security/AdminPagesSecurityProperties.java
support/cas-server-support-grouper/src/main/java/org/apereo/cas/web/flow/GrouperMultifactorAuthenticationPolicyEventResolver.java

Part of #2212
Replacing:
```new HashSet<>(Collections.singletonList(element));```
with:
```Collection.singleton(element)```
Added rule for this

Use Collections.singleton where possible

---

core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/core/ticket/registry/TicketRegistryProperties.java
core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/redis/RedisTicketRegistryProperties.java
docs/cas-server-documentation/installation/Configuration-Properties.md
docs/cas-server-documentation/installation/Redis-Ticket-Registry.md
docs/cas-server-documentation/sidebar.md
gradle.properties
gradle/dependencies.gradle
settings.gradle
support/cas-server-support-redis-ticket-registry/build.gradle
support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/config/RedisTicketRegistryConfiguration.java
support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/RedisTicketRegistry.java
support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/TicketRedisTemplate.java
support/cas-server-support-redis-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/RedisTicketRegistryTests.java
support/cas-server-support-redis-ticket-registry/src/test/resources/application.properties

pull request is reopen for #1968
thanks!

redis ticket registry

---

support/cas-server-support-memcached-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/support/kryo/serial/RegisteredServiceSerializer.java

Part of # 2212
Replace Guava in cas-server-support-memcached-ticket-registry module

Replace Guava with Java collections

---

core/cas-server-core-services/src/main/java/org/apereo/cas/services/TimeBasedRegisteredServiceAccessStrategy.java
support/cas-server-support-grouper/src/main/java/org/apereo/cas/grouper/GrouperFacade.java
support/cas-server-support-grouper/src/main/java/org/apereo/cas/grouper/services/GrouperRegisteredServiceAccessStrategy.java

Part of #2212
- Use ```anyMatch``` method
- cleaning a bit

Use anyMatch method. Cleaning a bit

---

support/cas-server-support-yubikey/src/main/java/org/apereo/cas/adaptors/yubikey/YubiKeyAuthenticationHandler.java
support/cas-server-support-yubikey/src/main/java/org/apereo/cas/adaptors/yubikey/YubiKeyAuthenticationMetaDataPopulator.java
support/cas-server-support-yubikey/src/main/java/org/apereo/cas/adaptors/yubikey/YubiKeyCredential.java
support/cas-server-support-yubikey/src/main/java/org/apereo/cas/adaptors/yubikey/YubiKeyMultifactorAuthenticationProvider.java
support/cas-server-support-yubikey/src/main/java/org/apereo/cas/config/YubiKeyConfiguration.java
support/cas-server-support-yubikey/src/test/java/org/apereo/cas/adaptors/yubikey/YubiKeyAuthenticationHandlerTests.java

Part of #2184
Remove setters from support yubikey module

Remove setters

---

support/cas-server-support-wsfederation/src/main/java/org/apereo/cas/support/wsfederation/config/WsFederationAuthenticationConfiguration.java
support/cas-server-support-wsfederation/src/main/java/org/apereo/cas/support/wsfederation/web/flow/WsFederationAction.java

Part of #2184
Remove setters and improve performance of support wsfederation module

Remove setters and improve performance

---

support/cas-server-support-throttle-jdbc/src/main/java/org/apereo/cas/web/support/InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter.java
support/cas-server-support-throttle-jdbc/src/main/java/org/apereo/cas/web/support/config/CasJdbcThrottlingConfiguration.java
support/cas-server-support-throttle-jdbc/src/test/java/org/apereo/cas/web/support/InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapterTests.java

Part of #2184
Remove setters from support throttle-jdbc module

Remove setters and inline @PostConstruct method

---

support/cas-server-support-digest-authentication/src/main/java/org/apereo/cas/digest/DefaultDigestHashedCredentialRetriever.java
support/cas-server-support-digest-authentication/src/main/java/org/apereo/cas/digest/config/DigestAuthenticationConfiguration.java
support/cas-server-support-digest-authentication/src/test/java/org/apereo/cas/digest/DefaultDigestHashedCredentialRetrieverTests.java

Closes #2252 
Also related to #2212 and #2184 
Changes:
- Use a ```Map``` as a better structure, was a Guava ```Table```
- Make this map final and inject it through constructor

Replace guava Table with Map

---

core/cas-server-core-services/src/main/java/org/apereo/cas/services/AbstractRegisteredService.java
support/cas-server-support-oauth-core/src/main/java/org/apereo/cas/support/oauth/services/OAuthRegisteredService.java

Fixes #2250 
- [] Changes the column length of String fields back to 255.
- [] Removes the column length of Boolean fields.

CAS-2250 Registered services field lengths at 255

---

support/cas-server-support-rest-services/src/main/java/org/apereo/cas/support/rest/RegisteredServiceResource.java
support/cas-server-support-rest-services/src/main/java/org/apereo/cas/support/rest/config/RestServicesConfiguration.java
support/cas-server-support-rest-services/src/test/java/org/apereo/cas/support/rest/RegisteredServiceResourceTests.java

Part of #2184
Remove setters from support rest-services modules

Remove setters 

---

core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/CoreAuthenticationTestUtils.java
core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/PolicyBasedAuthenticationManagerTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/authentication/DefaultMultifactorTriggerSelectionStrategyTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/authentication/principal/ResponseTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/authentication/principal/ShibbolethCompatiblePersistentIdGeneratorTests.java

Closes #2243 
Changes:
- move method to common util test class
- cleaning a bit

Move method to common test util class

---

core/cas-server-core-web/build.gradle
gradle/dependencies.gradle
support/cas-server-support-cookie/build.gradle
support/cas-server-support-themes/build.gradle
support/cas-server-support-validation/build.gradle
webapp-mgmt/cas-management-webapp/build.gradle
webapp/cas-server-webapp/build.gradle

thmyeleaf is wrong,    
It should be thymeleaf.

thmyeleaf is wrong

---

core/cas-server-core-monitor/src/main/java/org/apereo/cas/monitor/HealthCheckMonitor.java

Closes no issue
Just moving to a more functional code.

Move to a more functional-cleaner code

---

CONTRIBUTING.md

Just fixing an old link I bumped into earlier :)

Fix up broken link to contributor guidelines

---

webapp/cas-server-webapp/src/main/resources/messages_sk.properties

These translations are complementing previous PR #2332 
I think that translations of user land messages are now complete.

update slovak translations

---

webapp/cas-server-webapp/src/main/resources/static/css/cas.css
webapp/cas-server-webapp/src/main/resources/static/css/ssosessions.css
webapp/cas-server-webapp/src/main/resources/static/sass/components/_buttons.scss
webapp/cas-server-webapp/src/main/resources/static/sass/components/_dashboard-view.scss
webapp/cas-server-webapp/src/main/resources/static/sass/partials/_base.scss

Closes #IssueNumber
- [] Brief description of changes applied
- [] Reference any other pull requests that might be related.

Fix for IAMSE-42 tooltips getting cut off

---

stylesheets/stylesheet.scss

Closes IAMSE-41
Adding styling for the "image cloud" on the Configuring-SAML-SP-Integrations.md page

Adding styles for image cloud

---

webapp/cas-server-webapp/src/main/resources/static/js/loggingDashboard.js

Added a check to see if the selected value matches the current value, if it does then do nothing, otherwise make AJAX call.
Also added an auto-close to the status message so it disappears after 2 seconds.

Enhancements to the logging dashboard

---

core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java

Requirement of basedn #2374

---

docs/cas-server-documentation/installation/Configuration-Properties.md

Update link to webflow-customization-aup file in documentation for 5.0.x branch

Fix link for webflow customization in 5.0.x branch

---

docs/cas-server-documentation/installation/SPNEGO-Authentication.md

it may need to add the config for gradle

Update repository for maven

---

core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/RedirectToServiceAction.java
core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/config/CasCoreWebflowConfiguration.java
support/cas-server-support-actions-aup-webflow/src/main/java/org/apereo/cas/web/config/CasSupportActionsAcceptableUsagePolicyConfiguration.java
support/cas-server-support-actions-aup-webflow/src/main/java/org/apereo/cas/web/flow/AcceptableUsagePolicyFormAction.java
support/cas-server-support-actions/src/main/java/org/apereo/cas/web/config/CasSupportActionsConfiguration.java
support/cas-server-support-actions/src/main/java/org/apereo/cas/web/flow/SendTicketGrantingTicketAction.java
support/cas-server-support-actions/src/main/java/org/apereo/cas/web/flow/TerminateSessionAction.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/LogoutActionTests.java
support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/SendTicketGrantingTicketActionTests.java
support/cas-server-support-gua/src/main/java/org/apereo/cas/gua/config/GraphicalUserAuthenticationConfiguration.java
support/cas-server-support-gua/src/main/java/org/apereo/cas/web/flow/AcceptUserGraphicsForAuthenticationAction.java
support/cas-server-support-gua/src/main/java/org/apereo/cas/web/flow/DisplayUserGraphicsBeforeAuthenticationAction.java
support/cas-server-support-gua/src/main/java/org/apereo/cas/web/flow/GraphicalUserAuthenticationWebflowConfigurer.java
support/cas-server-support-gua/src/main/java/org/apereo/cas/web/flow/PrepareForGraphicalAuthenticationAction.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20CallbackAuthorizeEndpointController.java

Closes not issues.
Changes:
- Remove not needed fields

Remove not needed fields

---

core/cas-server-core-authentication/src/main/java/org/apereo/cas/services/DefaultVariegatedMultifactorAuthenticationProvider.java
core/cas-server-core-monitor/src/main/java/org/apereo/cas/monitor/AbstractNamedMonitor.java
core/cas-server-core-services/src/main/java/org/apereo/cas/services/InMemoryServiceRegistry.java
core/cas-server-core-services/src/test/java/org/apereo/cas/authentication/DefaultMultifactorTriggerSelectionStrategyTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/DefaultServicesManagerTests.java
core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasDefaultServiceTicketIdGeneratorsConfiguration.java
core/cas-server-core-web/src/main/java/org/apereo/cas/web/AbstractDelegateController.java
core/cas-server-core/src/test/java/org/apereo/cas/AbstractCentralAuthenticationServiceTests.java
core/cas-server-core/src/test/java/org/apereo/cas/CentralAuthenticationServiceImplWithMockitoTests.java
support/cas-server-support-actions/src/main/java/org/apereo/cas/web/config/CasSupportActionsConfiguration.java
support/cas-server-support-authy/src/main/java/org/apereo/cas/adaptors/authy/config/support/authentication/AuthyAuthenticationEventExecutionPlanConfiguration.java
support/cas-server-support-duo/src/main/java/org/apereo/cas/adaptors/duo/config/DuoSecurityAuthenticationEventExecutionPlanConfiguration.java
support/cas-server-support-ldap/src/test/java/org/apereo/cas/adaptors/ldap/AbstractLdapTests.java
support/cas-server-support-memcached-ticket-registry/src/test/java/org/apereo/cas/AbstractMemcachedTests.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
support/cas-server-support-openid/src/test/java/org/apereo/cas/support/openid/AbstractOpenIdTests.java
support/cas-server-support-openid/src/test/java/org/apereo/cas/support/openid/web/mvc/SmartOpenIdControllerTests.java
support/cas-server-support-pac4j-core-clients/src/test/java/org/apereo/cas/support/pac4j/web/flow/DelegatedClientAuthenticationActionTests.java
support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/rest/RestPasswordManagementService.java
support/cas-server-support-radius-mfa/src/main/java/org/apereo/cas/config/support/authentication/RadiusTokenAuthenticationEventExecutionPlanConfiguration.java
support/cas-server-support-reports/src/main/java/org/apereo/cas/web/report/DashboardController.java
support/cas-server-support-reports/src/main/java/org/apereo/cas/web/report/LoggingOutputSocketMessagingController.java
support/cas-server-support-sms-clickatell/src/main/java/org/apereo/cas/support/sms/ClickatellSmsSender.java
support/cas-server-support-u2f/src/main/java/org/apereo/cas/adaptors/u2f/web/flow/U2FStartAuthenticationAction.java
support/cas-server-support-x509/src/test/java/org/apereo/cas/adaptors/x509/authentication/handler/support/AbstractCRLRevocationCheckerTests.java
webapp-mgmt/cas-management-webapp-support/src/main/java/org/apereo/cas/mgmt/config/CasManagementAuditConfiguration.java

Closes no issues.
Changes:
- Remove some "Avoid unused private fields"
- Remove some "Unnecessary use of fully qualified name"
- Remove some "Avoid unused imports"
- Remove some "Use assertSame(x, y) instead of assertTrue(x == y)"

Cleaning codacy

---

support/cas-server-support-oauth-webflow/src/main/java/org/apereo/cas/config/CasOAuthWebflowConfiguration.java

Just fixing a typo leading to a `org.springframework.beans.factory.UnsatisfiedDependencyException`.

Fixed typo in CasOAuthWebflowConfiguration

---

docs/cas-server-documentation/protocol/REST-Protocol.md

Docs fix to #2449

---

docs/cas-server-documentation/installation/Configuration-Management.md

Show how to use command line arguments

Add an example

---

core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java
core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/ConnectionPoolingProperties.java
docs/cas-server-documentation/installation/Configuration-Properties.md

Closes #2459 on 5.0x
set minimium idle count on datasource correctly

set minimium idle count on datasource correctly

---

support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/util/AbstractSaml20ObjectBuilder.java
support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/util/AbstractSamlObjectBuilder.java
support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/util/Saml10ObjectBuilder.java

Closses #2476 
Make sure `InResponseTo` is set to SAML2 response
* check for provided `RequestId` and use it as `InResponseTo`
* add debug logging
* cleanup of `setInResponseToForSamlResponseIfNeeded`

Saml2 in response fix

---

webapp-mgmt/cas-management-webapp/src/main/resources/static/js/app/app-angular.js
webapp-mgmt/cas-management-webapp/src/main/resources/templates/fragments/serviceform/propertiesPane.html

The changes affect to Service Management Webapp. Currently you can not manage the service properties via webapp. It seems that worked in the past but some refactoring broke the functionality. In our project we need it  and I fix it. And I thought I'd be great to share with you.
The changes are really simple, in the template propertiesPane.html instead of repeat over "data" that is not present in the PropertiesController (AngularJs) I changed to serviceFormCtrl.serviceData.properties that is a parent Controller of the propertiesController and then I changed in the propertiesController to update serviceFormCtrl.serviceData.properties.
If you need more information you can contact me.
Thanks in advance,

fixPropertiesPane

---

docs/cas-server-documentation/installation/Configuration-Management-Reload.md

That part was not clear for me so I guess it could be very useful to add it instead of waiting 4 min at every restart, I really suffered for a long time not knowing how to do it... :p
Thanks

Give information about how to reload config

---

core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/core/CasServerProperties.java
docs/cas-server-documentation/installation/Configuration-Properties.md
webapp/cas-server-webapp-tomcat/src/main/java/org/apereo/cas/config/CasEmbeddedContainerTomcatConfiguration.java

I am going to go ahead and submit this so I can reference it from the ticket you opened in spring boot. I haven't quite tested this yet but I was using the valve in a customizer and it worked.

Add ssl valve support for embedded tomcat

---

support/cas-server-support-saml-googleapps-core/src/main/java/org/apereo/cas/support/saml/authentication/principal/GoogleAccountsServiceResponseBuilder.java
support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/SamlProfileSamlSubjectBuilder.java
support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/util/AbstractSaml20ObjectBuilder.java

Set missing notBefore property in SAML2 SubjectConfirmation

---

support/cas-server-support-saml-googleapps-core/src/main/java/org/apereo/cas/support/saml/authentication/principal/GoogleAccountsServiceResponseBuilder.java
support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/SamlProfileSamlSubjectBuilder.java
support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/util/AbstractSaml20ObjectBuilder.java

Revert "Set missing notBefore property in SAML2 SubjectConfirmation"

---

docs/cas-server-documentation/installation/Configuration-Properties.md

Add details for cas.authn.attributeRepository.defaultAttributesToRelease

Add details on Protocol use

---

docs/cas-server-documentation/installation/Configuration-Properties.md

Make it easier to produce results

Add details on ldap[0].principalAttributeList

---

webapp/resources/messages_sk.properties

in this patch are
- some typo errors corrected
- new translations added

correct typos in Slovak localization

---

support/cas-server-support-oauth-core/src/main/java/org/apereo/cas/ticket/code/OAuthCodeImpl.java

Fix OAuthCodeImpl TGT deserialization

---

support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/profile/OidcProfileScopeToAttributesFilter.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/web/OidcConsentApprovalViewResolver.java

Fix #2543: pure OAuth2 will not work if OIDC is enabled

---

support/cas-server-support-x509-webflow/src/main/java/org/apereo/cas/web/flow/X509WebflowConfigurer.java

Auth failure may happen in cases where certificate is valid but not found in attribute repository and 
cas.authn.x509.principal.returnNull=true
Closes #2554
This just sends user to the login form, which is a slight improvement over the error page, but it would be better if there was a message for the user about why their certificate didn't work. Is that something that would happen if they were sent to handleAuthenticationFailure?
I didn't intend to remove:
registerMultifactorProvidersStateTransitionsIntoWebflow(actionState);
I thought I was working with latest code but apparently not.

Handle authenticationFailure in x509 webflow

---

support/cas-server-support-openid/src/main/java/org/apereo/cas/support/openid/web/mvc/OpenIdValidateController.java
support/cas-server-support-openid/src/main/java/org/apereo/cas/support/openid/web/mvc/SmartOpenIdController.java
webapp/resources/templates/protocol/openid/casOpenIdAssociationSuccessView.html
webapp/resources/templates/protocol/openid/casOpenIdServiceFailureView.html
webapp/resources/templates/protocol/openid/casOpenIdServiceSuccessView.html

Even though with this fix, OpenID is still not working, CAS throws out missing service error but it seems that I have no way to register OpenID service...

Fix thymeleaf template syntax for #2564 (master)

---

support/cas-server-support-openid/src/main/java/org/apereo/cas/support/openid/web/mvc/OpenIdValidateController.java
support/cas-server-support-openid/src/main/java/org/apereo/cas/support/openid/web/mvc/SmartOpenIdController.java
webapp/cas-server-webapp/src/main/resources/templates/protocol/openid/casOpenIdAssociationSuccessView.html
webapp/cas-server-webapp/src/main/resources/templates/protocol/openid/casOpenIdServiceFailureView.html
webapp/cas-server-webapp/src/main/resources/templates/protocol/openid/casOpenIdServiceSuccessView.html

Fix thymeleaf template syntax for #2564 (5.0.x)

---

webapp/cas-server-webapp/src/main/resources/application.properties

Fix #2578: suppress HTTP response header X-Application-Context (5.0.x)

---

webapp/resources/application.properties

I accidentally closed #2580 by force-pushing my fork

Fix #2578: suppress HTTP response header X-Application-Context (master)

---

gradle.properties

Upgrade to pac4j v2.0.0-RC3-SNAPSHOT for final tests

---

core/cas-server-core-services/src/main/java/org/apereo/cas/services/AbstractResourceBasedServiceRegistryDao.java
support/cas-server-support-ldap-service-registry/src/main/java/org/apereo/cas/adaptors/ldap/services/DefaultLdapRegisteredServiceMapper.java

Fix #2590: hjson will lose precision if id is too large (master)

---

core/cas-server-core-services/src/main/java/org/apereo/cas/services/AbstractResourceBasedServiceRegistryDao.java
support/cas-server-support-ldap-service-registry/src/main/java/org/apereo/cas/adaptors/ldap/services/DefaultLdapRegisteredServiceMapper.java

Fix #2590: hjson will lose precision if id is too large (5.0.x)

---

core/cas-server-core/src/main/java/org/apereo/cas/config/CasCoreConfiguration.java
support/cas-server-support-actions/src/main/java/org/apereo/cas/web/config/CasSupportActionsConfiguration.java
support/cas-server-support-jdbc/src/main/java/org/apereo/cas/adaptors/jdbc/config/CasJdbcConfiguration.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/config/CasValidationConfiguration.java

Mark beans conditional to allow redefinition by implementors

---

support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java

OIDC Configuration Error

---

core/cas-server-core/src/main/java/org/apereo/cas/config/CasCoreConfiguration.java
support/cas-server-support-validation/src/main/java/org/apereo/cas/web/config/CasValidationConfiguration.java

same as #2601 but for master.
see #2600

Mark beans conditional to allow redefinition by implementors (master)

---

support/cas-server-support-validation/src/main/java/org/apereo/cas/web/view/Cas30ResponseView.java

Avoid NPE in Cas30ResponseView when attribute value is null

---

core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/DefaultWebflowConfigurer.java

whereas currently those are just "dangling" transitions

Associate transitions with approprate action state

---

support/cas-server-support-ldap/src/main/java/org/apereo/cas/config/LdapAuthenticationConfiguration.java

LdapAuthenticationConfiguration

---

core/cas-server-core-util/src/main/java/org/apereo/cas/util/ResourceUtils.java

Closes #2651
This should be merged to 5.1 branch too.

Fix regression in previous commit that made https not work

---

webapp/gradle/webapp.gradle
webapp/resources/static/sass/components/_cas.scss
webapp/resources/static/sass/partials/_fonts.scss
webapp/resources/static/themes/apereo/css/cas.css
webapp/resources/templates/casAzureAuthenticatorLoginView.html

Make webjars library runtime intead of implementation so they are
available when running gradle bootRun
Remove some references to Lato fonts via CDN b/c they are downloaded
from webjar in layout.html

Fix some webjars issues

---

core/cas-server-core-authentication/src/main/java/org/apereo/cas/services/AbstractRegisteredServiceAttributeReleasePolicy.java

Add more debug log instrumentation

---

support/cas-server-support-throttle-jdbc/src/main/java/org/apereo/cas/web/support/InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter.java

Hello CAS developers!
This pull request should fix a strange behavior of the Inspektr JDBC throttling adapter that I described in the CAS Community discussion group here: https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/HAvywDMpWKA
The problem was that the adapter did not distinguish between failed login attempts and actual throttling, which typically happens after N failed login attempts. So every failed login was reported as throttling, both in the database and in the log.
After the fix, the Inspektr JDBC adapter now reports failed logins correctly, not as throttled login attempts anymore. A new action "FAILED_LOGIN_ATTEMPT" is written to the database. "THROTTLED_LOGIN_ATTEMPT" is used only for actual throttling.
A possible alternative solution would be not to log any …

Inspektr Audit - Do not report failed authentications like throttling

---

support/cas-server-support-throttle-jdbc/src/main/java/org/apereo/cas/web/support/InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter.java

This is the same pull request as
https://github.com/apereo/cas/pull/2667
but for branch 5.1.

Inspektr Audit - Do not report failed authentications like throttling [5.1.x]

---

support/cas-server-support-throttle-jdbc/src/main/java/org/apereo/cas/web/support/InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter.java

This is the same pull request as
#2667
but for branch 'master'.

Inspektr Audit - Do not report failed authentications like throttling [master]

---

core/cas-server-core-services/src/main/java/org/apereo/cas/services/AbstractResourceBasedServiceRegistryDao.java

Changes:
- make load() method a bit more functional
- do not create intermediate collection
- do not iterate twice on the same data

ServiceRegistryDao improvements

---

CODE_OF_CONDUCT.md

Adds a `CODE_OF_CONDUCT.md` acknowledging that the Apereo Welcoming Policy applies.
Does not update the substance of the contributing guidelines, which as I understand it will need to be updated via a separate pull request against the separate `gh_pages` branch.

Acknowledge Apereo Welcoming Policy.

---

support/cas-server-support-electrofence/src/main/resources/META-INF/spring.factories

Add spring.factories to enable autoconfiguration
for risk-based authentication.

Add missing file

---

docs/cas-server-documentation/installation/Configuration-Properties.md

Removing old/unused property

---

docs/cas-server-documentation/installation/Configuration-Properties.md

Fixed typo

---

support/cas-server-support-gauth-core/src/main/java/org/apereo/cas/adaptors/gauth/GoogleAuthenticatorAuthenticationHandler.java

Update GoogleAuthenticatorAuthenticationHandler.java - 5.1

---

support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenPasswordGrantRequestExtractor.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenRequestDataHolder.java
support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/OAuth20AccessTokenControllerTests.java

Closes #2731 in branch 5.1.x
Refresh tokens are now generated for Resource Owner flow.

 Refresh tokens are now generated for Resource Owner flow.

---

core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/jpa/AbstractJpaProperties.java
docs/cas-server-documentation/installation/Configuration-Properties.md

allow hibernate specific properties

---

api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/ServicesManager.java
core/cas-server-core-services/src/main/java/org/apereo/cas/config/CasCoreServicesConfiguration.java
core/cas-server-core-services/src/main/java/org/apereo/cas/services/DomainServicesManager.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/DomainServicesManagerTests.java

Implementation of a ServicesManager that groups services into list by domain and provides a hash lookup to services by domain name.  This reduces the overhead of looking up services when a registry size becomes large.

New Feature: Domain Services Manager

---

webapp/resources/templates/casExpiredPassView.html
webapp/resources/templates/fragments/pwdupdateform.html

Add/set expiredPass variable in casExpiredPassView, so that
expired message/heading can be selected/presented by pwdupdateform.

Add expiredPass variable, to show expiredpassword messages

---

core/cas-server-core-util/src/main/java/org/apereo/cas/util/CollectionUtils.java
core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/resolver/impl/InitialAuthenticationAttemptWebflowEventResolver.java
core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/resolver/impl/RankedAuthenticationProviderWebflowEventResolver.java
core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/resolver/impl/ServiceTicketRequestWebflowEventResolver.java
support/cas-server-support-saml-mdui-core/src/main/java/org/apereo/cas/support/saml/mdui/MetadataUIUtils.java
support/cas-server-support-saml-mdui/build.gradle
support/cas-server-support-saml-mdui/src/main/java/org/apereo/cas/support/saml/mdui/web/flow/SamlMetadataUIParserAction.java
support/cas-server-support-saml-mdui/src/test/java/org/apereo/cas/support/saml/mdui/web/flow/SamlMetadataUIParserActionTests.java

Backport some PR from 5.2.x to 5.1.x

---

core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/jpa/AbstractJpaProperties.java

(refactor) some opportunities to use diamond operator

---

api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/registry/TicketRegistry.java
core/cas-server-core-tickets/src/main/java/org/apereo/cas/ticket/registry/DefaultTicketRegistryCleaner.java

Following discussions in #2779 I have added a ```Stream<Ticket> getTicketsStream()``` method to the ```TicketRegistry``` interface and used it in the ```DefaultTicketRegistry```

Add and use getTicketsStream method

---

webapp/resources/templates/casAuthyLoginView.html
webapp/resources/templates/casAzureAuthenticatorLoginView.html
webapp/resources/templates/casDuoLoginView.html
webapp/resources/templates/casGoogleAuthenticatorLoginView.html
webapp/resources/templates/casRadiusLoginView.html
webapp/resources/templates/casU2fLoginView.html
webapp/resources/templates/casYubiKeyLoginView.html

Without this input, geolocation info is not recorded for the TGT creation event.

Add missing geolocation hidden input

---

support/cas-server-support-throttle/src/main/java/org/apereo/cas/web/support/AbstractThrottledSubmissionHandlerInterceptorAdapter.java
webapp/resources/templates/error/423.html

Use HttpStatus.SC_LOCKED, instead of SC_FORBIDDEN.
Add 423.html to display messages about throttled logins.

Changes for showing throttled login related info.

---

support/cas-server-support-rest/src/main/java/org/apereo/cas/support/rest/TicketsResource.java
support/cas-server-support-rest/src/test/java/org/apereo/cas/support/rest/TicketsResourceTests.java

Closes #2809 
- [] Provides fair header processing
- [] Provide Accept: header of your choise
- [] Default response content is text/html
- [] None

Respect Accept header in REST

---

core/cas-server-core-logout/src/main/java/org/apereo/cas/logout/DefaultLogoutManager.java

Changes:
- Make DefaultLogoutManager more functional
- Performance improved because of removed recursion

improve the way DefaultLogoutManager gets the services to be logged out

---

webapp/package.json
webapp/resources/static/js/StatisticsApp.js

Fixed an issue where the time was not displayed properly.
Also refactored the props scope

Authngraph refactor time handling

---

core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jCasProperties.java
core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jGenericClientProperties.java
docs/cas-server-documentation/installation/Configuration-Properties.md
support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/web/flow/DelegatedClientAuthenticationAction.java
support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/support/authentication/Pac4jAuthenticationEventExecutionPlanConfiguration.java
webapp/resources/application.properties

This applies #2820 to the master branch

Use 'Google' name for Google2 pac4j client

---

docs/cas-server-documentation/installation/GoogleAuthenticator-Authentication.md

Add GoogleAuthenticator JPA Galera workarounds to doc

---

support/cas-server-support-ehcache-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/EhCacheTicketRegistry.java

Prevent expensive mass eviction from EhCache

---

core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/ignite/IgniteProperties.java
docs/cas-server-documentation/installation/Configuration-Properties.md
support/cas-server-support-ignite-ticket-registry/src/main/java/org/apereo/cas/config/IgniteTicketRegistryConfiguration.java
support/cas-server-support-ignite-ticket-registry/src/test/resources/igniteregistry.properties

- [] Brief description of changes applied
~~~
cas.ticket.registry.ignite.igniteAddresses=localhost:47500
~~~
to
~~~
cas.ticket.registry.ignite.igniteAddress[0]=localhost:47500
cas.ticket.registry.ignite.igniteAddress[1]=
~~~
Docs included and test updated.
config change for users

use list property for igniteAddresses

---

webapp/.eslintrc.json
webapp/package-lock.json
webapp/package.json
webapp/resources/static/js/StatisticsApp.jsx
webapp/resources/static/js/components/authnaudit/AuthnAttemptsGraph.jsx

Changes the eslint from Standard to airbnb
Refactored and cleaned up the React component to bring it more inline of modern best practices

eslint & react cleanup

---

support/cas-server-support-saml-mdui-core/src/main/java/org/apereo/cas/support/saml/mdui/SamlMetadataUIInfo.java

Adapted this PR https://github.com/apereo/cas/pull/2832 for 5.1.x.

avoid NPE when mdui not available (5.1.x)

---

support/cas-server-support-rest/src/main/java/org/apereo/cas/support/rest/TicketsResource.java

I'm happy you don't consider it to be a hack any more.

Fix rest NPE get tgt once

---

support/cas-server-support-rest/src/test/java/org/apereo/cas/support/rest/TicketsResourceTests.java

Tests has been fixed for #2884.

Fix rest ST tests

---

support/cas-server-support-reports/src/main/java/org/apereo/cas/web/report/HealthCheckController.java

This PR changes the cas/status endpoint from running asynchronously to synchronous.  We encountered problems with our monitoring when calling this endpoint repeatedly under heavy load.

Synchronous status

---

support/cas-server-support-saml-mdui-core/src/main/java/org/apereo/cas/support/saml/mdui/SamlMetadataUIInfo.java

this is https://github.com/apereo/cas/pull/2894 for 5.1.x
* call uiinfo for localized names
* check if uiinfo is null

MDUI fix Null and Cast Exceptions 5.1.x

---

docs/cas-server-documentation/installation/Configuration-Management-Reload.md

Add tip for forcing reload of changes using `touch`

---

support/cas-server-support-gauth-core/src/main/java/org/apereo/cas/adaptors/gauth/repository/credentials/GoogleAuthenticatorAccount.java
support/cas-server-support-gauth-mongo/src/test/java/org/apereo/cas/adaptors/gauth/MongoDbGoogleAuthenticatorTokenCredentialRepositoryTests.java
support/cas-server-support-otp-mfa/src/main/java/org/apereo/cas/otp/repository/credentials/OneTimeTokenAccount.java

Hi,
To follow the PR #2904, I correct the bug in master branch.
I see @mmoayyed, you have created test case for that. Thanks.
All is-it ok ?

Unique ID gauth MFA

---

docs/cas-server-documentation/installation/Configuration-Properties.md

Clarify where Management Webapp settings should be defined

---

api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/ServicesManager.java
core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/DomainServicesManager.java
webapp-mgmt/cas-management-webapp-support/src/main/java/org/apereo/cas/mgmt/services/web/ManageRegisteredServicesMultiActionController.java
webapp-mgmt/cas-management-webapp/src/app/app-routing.module.ts
webapp-mgmt/cas-management-webapp/src/app/app.component.html
webapp-mgmt/cas-management-webapp/src/app/app.component.ts
webapp-mgmt/cas-management-webapp/src/app/header/header.component.html
webapp-mgmt/cas-management-webapp/src/app/header/header.component.ts
webapp-mgmt/cas-management-webapp/src/app/services/services.component.html
webapp-mgmt/cas-management-webapp/src/app/services/services.component.ts
webapp-mgmt/cas-management-webapp/src/manage.html

Ensures domains only contain valid domain characters. This branch also has front-end changes that will removes Domains page when the service registry management type is set to DEFAULT.

Management Webapp: domain services manager and regex

---

api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/ServiceRegistryDao.java
core/cas-server-core-services/src/main/java/org/apereo/cas/services/AbstractServiceRegistryDao.java
core/cas-server-core-services/src/main/java/org/apereo/cas/services/ServiceRegistryInitializer.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/ServiceRegistryInitializerTests.java

initFromJson creates duplicate records when ids are assigned by the DAO

---

docs/cas-server-documentation/protocol/SAML-Protocol.md

I found out that's how it is working on my cas 5.0.6

Is it an error in the doc ?

---

docs/cas-server-documentation/installation/Configuration-Properties-Common.md

Documentation warning about create-drop

---

support/cas-server-support-trusted-mfa-jdbc/src/main/java/org/apereo/cas/trusted/authentication/storage/JpaMultifactorAuthenticationTrustStorage.java
support/cas-server-support-trusted-mfa/src/main/java/org/apereo/cas/trusted/authentication/api/MultifactorAuthenticationTrustRecord.java
support/cas-server-support-trusted-mfa/src/main/java/org/apereo/cas/trusted/authentication/storage/BaseMultifactorAuthenticationTrustStorage.java
support/cas-server-support-trusted-mfa/src/main/java/org/apereo/cas/trusted/authentication/storage/InMemoryMultifactorAuthenticationTrustStorage.java

Closes #2998
Renamed Columns in table MultifactorAuthenticationTrustRecord from Date to recordDate and key to recordKey to remove conflict with MariaDb Reserved keywords,

fix schema issues with reserved keywords

---

docs/cas-server-documentation/installation/Surrogate-Authentication.md

There is significant change in packaging and without modification of overlay it will not work.
I don't see it in release notes.

Correct tables and warn on dependencies change

---

docs/cas-server-documentation/installation/Logout-Single-Signout.md

There should be emphasized state of implementation on various cas clients.

correct description of front channel SLO

---

support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/slo/AbstractSamlSLOProfileHandlerController.java

bug that this patch is fixing:
when verifying the signature of an incoming SAML SLO request, SAML metadata for all services had to be resolved. In case another service's metadata was unavailable at logout time, this caused an exception screen to be returned to the user and no logout to happen.
Now, only the requesting service's metadata is required to validate the signature.

SAML SLO: get metadata for requesting service only

---

docs/cas-server-documentation/installation/Installing-ServicesMgmt-Webapp.md

Adding documentation for user attributes in the services management webapp.

Adding section on configuring user attributes

---

support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/token/OidcIdTokenGeneratorService.java
support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/token/OidcIdTokenSigningAndEncryptionService.java

fix OIDC protocol implementation
- Error in `at_hash` (id_token attribute) generation
- Error in `kid` (id_token JWT header attribute) generation

OIDC protocol implementation fix

---

support/cas-server-support-electrofence/src/main/java/org/apereo/cas/impl/calcs/DateTimeAuthenticationRequestRiskCalculator.java

Count all TGT related events that happened between "windowInHours before" and
"windowInHours after" current authentication attempt. Currently many false
positives alarms arise as the check takes into account only those events that
happened exactly at "windowInHours before" or "windowInHours after" or at the
same hour.

Fix windowInHours checking.

---

core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/core/CasServerProperties.java
docs/cas-server-documentation/installation/Configuration-Properties.md
support/cas-server-support-shell/src/main/java/org/apereo/cas/shell/commands/AddPropertiesToConfigurationCommand.java

Here is the same fix you merged to master, for 5.2.x branch.

Shellfix52

---

docs/cas-server-documentation/installation/User-Interface-Customization-Localization.md

Modifies documentation to link to the proper configuration section.

Fix localization/message bundles anchor

---

docs/cas-server-documentation/installation/YAML-Service-Management.md

Add empty map indicator to example YAML service description so CAS can parse it correctly. Add a note about validators with the tags as well.

Update YAML service registry example

---

webapp/resources/messages_pl.properties

I translated all missing messages Keys.
HTH.

Full messages_pl.properties Polish translation for CAS 5.2.x version

---

webapp/cas-server-webapp-config/src/main/java/org/apereo/cas/config/CasWebAppConfiguration.java
webapp/cas-server-webapp-config/src/test/java/org/apereo/cas/WiringConfigurationTests.java

This is https://github.com/apereo/cas/pull/3104 for master.
Allows for locale change on the MVC endpoints,
e.g. /consentReview, /error.

Add localeChangeInterceptor to root context

---

api/cas-server-core-api-configuration/src/main/java/org/apereo/cas/configuration/model/support/mfa/U2FMultifactorProperties.java
docs/cas-server-documentation/installation/Configuration-Properties.md
support/cas-server-support-trusted-mfa/src/main/java/org/apereo/cas/trusted/authentication/MultifactorAuthenticationTrustCipherExecutor.java
support/cas-server-support-u2f-jpa/src/main/java/org/apereo/cas/adaptors/u2f/storage/U2FJpaDeviceRepository.java
support/cas-server-support-u2f-jpa/src/main/java/org/apereo/cas/config/U2FJpaConfiguration.java
support/cas-server-support-u2f-jpa/src/test/java/org/apereo/cas/adaptors/u2f/storage/U2FJpaDeviceRepositoryTests.java
support/cas-server-support-u2f-mongo/src/main/java/org/apereo/cas/adaptors/u2f/storage/U2FMongoDbDeviceRepository.java
support/cas-server-support-u2f-mongo/src/main/java/org/apereo/cas/config/U2FMongoDbConfiguration.java
support/cas-server-support-u2f-mongo/src/test/java/org/apereo/cas/adaptors/u2f/storage/U2FMongoDbDeviceRepositoryTests.java
support/cas-server-support-u2f/src/main/java/org/apereo/cas/adaptors/u2f/U2FAuthenticationRegistrationRecordCipherExecutor.java
support/cas-server-support-u2f/src/main/java/org/apereo/cas/adaptors/u2f/storage/BaseU2FDeviceRepository.java
support/cas-server-support-u2f/src/main/java/org/apereo/cas/adaptors/u2f/storage/U2FDeviceRegistration.java
support/cas-server-support-u2f/src/main/java/org/apereo/cas/config/U2FConfiguration.java

This PR introduces encryption/decryption support for u2f device registration records for both RDBMS and Mongo repositories

Encrypted u2f mfa registration data

---

support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/services/SamlIdPEntityIdAuthenticationServiceSelectionStrategy.java

Refactor un-necessary regex re-calc

---

docs/cas-server-documentation/installation/Configuration-Properties.md

I made it more explicit for the users, in order to understand those are only strings and not variables like it seems to show

Changes on Stub attributes

---

webapp/resources/messages_sk.properties

[5.2.x] Update slovak translation

---

core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/DefaultAuthenticationEventExecutionPlan.java
core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/PolicyBasedAuthenticationManager.java

take account of AuthenticationHandler order in DefaultAuthenticationEventExecutionPlan

---

core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/resolver/impl/AbstractCasWebflowEventResolver.java

cherry pick PR #3075 into 5.3.x

---

webapp/resources/messages_vi.properties

Add language pack for Vietnamese

Add language pack: Vietnamese

---

support/cas-server-support-consent-webflow/src/main/java/org/apereo/cas/web/consent/CasConsentReviewController.java

This https://github.com/apereo/cas/pull/3156 for master

add principal to Model for /consentReview

---

support/cas-server-support-consent-webflow/src/main/java/org/apereo/cas/web/consent/CasConsentReviewController.java

This adds the principal to the model for /consentReview. To be used with thymeleaf to signal "logged in" information to the user.
I'm happy to do it for master if approved.

[5.2.x] add principal to Model for /consentReview 

---

webapp/cas-server-webapp-tomcat/src/main/java/org/apereo/cas/config/CasEmbeddedContainerTomcatConfiguration.java

This is the pull request you already merged to master, I could use it on 5.2.x branch if you are planning to do more releases there.

Add sslvalve as context valve (#3151)

---

core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/DefaultRegisteredServiceAccessStrategy.java

Same as https://github.com/apereo/cas/pull/3173 on 5.2.X branch

Replace private by protected in order to be extend it easily on 5.2.X branch

---

core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/DefaultRegisteredServiceAccessStrategy.java

Make it easier to extend the class when replacing it in the service file

Replace private by protected in order to be extend it easily

---

support/cas-server-support-cookie/src/main/java/org/apereo/cas/web/support/CookieRetrievingCookieGenerator.java

Fix the TGC cookie expiration when remember me is enabled (5.2.x)

---

docs/cas-server-documentation/installation/Couchbase-Authentication.md

Fixing title copy/paste issue

---

docs/cas-server-documentation/installation/Couchbase-Authentication.md

Fixing copy paste title issues

---

core/cas-server-core-tickets/src/main/java/org/apereo/cas/ticket/BaseTicketSerializers.java

Cherry picked my fix (https://github.com/apereo/cas/pull/3183) to 5.2.x

Ticket serialization performance fix for 5.2.x

---

webapp-mgmt/cas-management-webapp/src/app/controls/controls.component.ts
webapp-mgmt/cas-management-webapp/src/app/form/access-strategy/access-strategy.component.html
webapp-mgmt/cas-management-webapp/src/app/form/form.component.html
webapp-mgmt/cas-management-webapp/src/app/header/header.component.html
webapp-mgmt/cas-management-webapp/src/app/services/services.component.html

Fixes the issue of not being able to save when duplicating a service

Fixed Duplicate not being able to save

---

support/cas-server-support-jdbc-monitor/src/main/java/org/apereo/cas/monitor/JdbcDataSourceHealthIndicator.java
support/cas-server-support-jdbc-monitor/src/main/java/org/apereo/cas/monitor/config/CasJdbcMonitorConfiguration.java
support/cas-server-support-ldap-monitor/src/main/java/org/apereo/cas/monitor/PooledLdapConnectionFactoryHealthIndicator.java
support/cas-server-support-ldap-monitor/src/main/java/org/apereo/cas/monitor/config/LdapMonitorConfiguration.java

pool monitor parameter tweak

---

docker/Dockerfile

The original url of the file ZuluJCEPolicies.zip has not found

Update url of the file ZuluJCEPolicies.zip

---

support/cas-server-support-azure/src/main/java/org/apereo/cas/adaptors/azure/AzureAuthenticatorAuthenticationHandler.java
support/cas-server-support-fortress/src/main/java/org/apereo/cas/adaptors/fortress/FortressAuthenticationHandler.java
support/cas-server-support-gauth-core/src/main/java/org/apereo/cas/adaptors/gauth/GoogleAuthenticatorAuthenticationHandler.java
support/cas-server-support-swivel/src/main/java/org/apereo/cas/adaptors/swivel/SwivelAuthenticationHandler.java
support/cas-server-support-u2f/src/main/java/org/apereo/cas/adaptors/u2f/U2FAuthenticationHandler.java
support/cas-server-support-yubikey-core/src/main/java/org/apereo/cas/adaptors/yubikey/YubiKeyAuthenticationHandler.java

fix an NPE in the GoogleAuthenticatorAuthenticationHandler

---

core/cas-server-core-authentication/src/main/java/org/apereo/cas/authentication/DefaultAuthenticationEventExecutionPlan.java

Hello,
That PR fixes issue with the "AuthenticationHandler" order. 
The order calculated on the previous line is losted by the Collectors.set convertion.
Bye

fix : authentificationHandler order

---

webapp/resources/static/sass/ssosessions.scss
webapp/resources/templates/monitoring/viewSsoSessions.html

added styling for Bootstrap 4.  Removed unused classes from scss

SSO Sessions Monitoring Page update

---

docs/cas-server-documentation/installation/Configuration-Properties-Security.md
docs/cas-server-documentation/installation/Configuration-Server-Management.md
docs/cas-server-documentation/installation/Maven-Overlay-Installation.md

Just fixing a few minor typos in the docs

fix minor typos

---

support/cas-server-support-trusted-mfa-jdbc/build.gradle
support/cas-server-support-trusted-mfa-jdbc/src/main/java/org/apereo/cas/trusted/authentication/storage/JpaMultifactorAuthenticationTrustStorage.java
support/cas-server-support-trusted-mfa-jdbc/src/test/java/org/apereo/cas/trusted/authentication/storage/JpaMultifactorAuthenticationTrustStorageTests.java
support/cas-server-support-trusted-mfa-jdbc/src/test/resources/log4j2.xml

fix the JPA MFA Trust Storage class and add tests

---

api/cas-server-core-api-authentication/src/main/java/org/apereo/cas/authentication/AuthenticationTransaction.java

simplify a couple methods in AuthenticationTransaction

---

support/cas-server-support-gauth/src/main/java/org/apereo/cas/config/support/authentication/GoogleAuthenticatorAuthenticationEventExecutionPlanConfiguration.java

Add AuthenticationHandlerResolver for google authenticator

---

api/cas-server-core-api-authentication/src/main/java/org/apereo/cas/authentication/AuthenticationTransaction.java
api/cas-server-core-api-authentication/src/test/java/org/apereo/cas/authentication/AuthenticationTransactionTests.java
core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/DefaultAuthenticationSystemSupport.java
core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/AuthenticationCredentialTypeMetaDataPopulatorTests.java
core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/CacheCredentialsMetaDataPopulatorTests.java
core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/PolicyBasedAuthenticationManagerTests.java
core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/principal/RememberMeAuthenticationMetaDataPopulatorTests.java
core/cas-server-core-services/src/test/java/org/apereo/cas/services/RegisteredServiceAuthenticationHandlerResolverTests.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/CollectionUtils.java
core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/RandomUtils.java
support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/authenticator/OAuth20CasAuthenticationBuilder.java
support/cas-server-support-saml/src/test/java/org/apereo/cas/support/saml/authentication/SamlAuthenticationMetaDataPopulatorTests.java
support/cas-server-support-throttle-jdbc/src/test/java/org/apereo/cas/web/support/JdbcThrottledSubmissionHandlerInterceptorAdapterTests.java

Rename the factory method to `of`

Rename factory method

---

core/cas-server-core-cookie-api/src/test/java/org/apereo/cas/web/support/DefaultCasCookieValueManagerTests.java

Checkstyle fixes

---

support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/validator/token/OAuth20AuthorizationCodeGrantTypeTokenRequestValidator.java

Currently, the check between the service of the code and the service used on the token endpoint always fails as there is a mismatch between the clientId and the serviceId.

Fix the check between the OAuth code and client services

---

core/cas-server-core-cookie/src/main/java/org/apereo/cas/web/config/CasCookieConfiguration.java
core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/resolver/impl/ServiceTicketRequestWebflowEventResolver.java

Adding @ConditionalOnMissingBean on ticketGrantingTicketCookieGenerator to allow TGCCookieRetrievingCookieGenerator extension

Overriding ticketGrantingTicketCookieGenerator

---

Mailing-Lists.md

Fixed a few typos in the document

Fixed typos

---

core/cas-server-core-web-api/src/main/java/org/apereo/cas/services/web/support/RegisteredServiceResponseHeadersEnforcementFilter.java

fix an NPE being thrown when the specified service doesn't match a Registered Service

---

support/cas-server-support-pac4j-core/src/main/java/org/apereo/cas/web/pac4j/DelegatedSessionCookieCipherExecutor.java

Fix pac4j cookie encryption key setting typo

---

support/cas-server-support-u2f/src/main/java/org/apereo/cas/adaptors/u2f/storage/BaseResourceU2FDeviceRepository.java

when a new registration of a user is added, it overrode all registrations

Fix u2f device registrations

---

gradle.properties

Pivotal Software Spring Security : List of security vulnerabilities
Security vulnerabilities of Pivotal Software Spring Security : List of all related CVE security vulnerabilities.
CVSS Scores, vulnerability details and links to full CVE details and references.
Ref : https://www.cvedetails.com/vulnerability-list/vendor_id-15183/product_id-35566/Pivotal-Software-Spring-Security.html
There is a one security update(https://github.com/spring-projects/spring-security/issues/2325), but it looks we can use 4.2.4 too.

Update spring security version

---

webapp/resources/messages_fr.properties

This is an updated French message bundle for CAS.

Updated French translation

---

webapp/resources/messages_fr.properties

This is a backport of #3302 to 5.2.x

Updated French translation (5.2.x)

---

support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/web/controllers/OidcRevocationEndpointController.java

This is a backport of #3303 to 5.2.x

Fix OIDC token revocation to better respect RFC 7009 (5.2.x)

---

docs/cas-server-documentation/installation/Configuration-Properties.md

This isn't needed in Groovy and doesn't match the style of the surrounding code.

Why the semi-colon?

---

support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/web/flow/DelegatedClientAuthenticationAction.java
support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/Pac4jWebflowConfigurer.java

Backport of #3309 to 5.2.x branch

Allow delegated auth transaction to transition to the handle authentication failure state (5.2.x)

---

build.gradle

do not replace default excludeDirs; append to it
