apereo/cas

- cas-server-documentation/protocol/CAS-Protocol-Specification.md
CAS protocol is updated with the following changes:
- Changed JASIG references to Apereo
- Added code tags to URL endpoints, etc.
> CAS protocol format and Apereo refs

- cas-server-support-ldap/src/main/java/org/jasig/cas/util/LdapUtils.java
This prevents LDAP injection attacks. Note this patch is only relevant for the 3.5.x branch since master is based on ldaptive, which properly handles character escaping.
> CAS-1429 Escape inputs into LDAP filter expressions.

- cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
This pull request attempts to verify that a service request is eligible for authentication and more, before locating its ST from the ticket registry. This should help reduce the burden that is put on the ticket registry.
> Check service eligibility before asking for ST

- developer/Contributor-Guidelines.md
Point new contributors to the Apereo agreement rather than the Jasig agreement to fix #847.
> Update ICLA Link

- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/bottom.jsp
- cas-server-webapp/src/main/webapp/js/cas.js
Resolves https://github.com/Jasig/cas/issues/734
This pull does the following:
1. Loads javascript references asynchronously
2. Attempts to call a global callback fucntion `jqueryReady` when defined, to signal the CAS UI that it is now safe to execute custom JS code based on jquery.
> Async loading of scripts with a global callback

- cas-server-webapp/src/main/resources/messages_ca.properties
- cas-server-webapp/src/main/resources/messages_es.properties
This will probably be the last translation update I submit to CAS, for a few reasons:
* Converting accented characters to Unicode escape sequences is tedious, cumbersome, and error-prone.
* Unlike PO files, the original English string is not displayed next to the translated string.
* Strings that have changed in the original English are not marked for review in the translation file.
* In a few months I will no longer be using CAS.
Nevertheless, I hope that my efforts to provide accurate and up-to-date translations will help other CAS users in the future.
> Correct and update Spanish and Catalan translations

- cas-server-support-ldap/src/main/java/org/jasig/cas/persondir/LdapPersonAttributeDao.java
- cas-server-support-ldap/src/test/java/org/jasig/cas/persondir/LdapPersonAttributeDaoTests.java
- cas-server-support-ldap/src/test/resources/ldap-persondir-test.xml
~~Discovered a bug with the LdapPersonAttributeDao where the result attribute map is not taken into account when renaming retrieved attributes. The value-set should be used when prepping person attributes.~~
Improved tests to ensure we are getting back the retrieved attributes and that they are properly renamed.
> Improve LdapPersonAttributeDaoTest: ensure attributes are correctly renamed

- cas-server-support-ldap/src/main/java/org/jasig/cas/authentication/LdapAuthenticationHandler.java
- cas-server-support-ldap/src/test/resources/authn-context.xml
For the majority of deployments, the ldap authn handler can be used to retrieve attributes. While these attributes are now supported as a map, this pull adds support for lists as well. Most deployments would simply just define the list of attributes returned and have no need for a mapping.
> Allow Ldap AuthN handler to specify attributes as a list

- cas-server-core/src/test/java/org/jasig/cas/AbstractCentralAuthenticationServiceTest.java
- cas-server-webapp-support/src/main/java/org/jasig/cas/web/flow/SendTicketGrantingTicketAction.java
- cas-server-webapp-support/src/test/java/org/jasig/cas/web/flow/SendTicketGrantingTicketActionTests.java
- cas-server-webapp/src/main/resources/services/sample-access-strategy.json.sample
- cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml
- cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
Handles #564 
Optionally, logging in via CAS to non-SSO-participating applications should not create a CAS SSO session. This pull provides an option to disable the generation of the SSO cookie, in case the authentication was forced/renewed for the service/request.
> Disable SSO session for non-SSO-participating apps

- cas-server-core/src/main/java/org/jasig/cas/util/DefaultCipherExecutor.java
- cas-server-core/src/test/java/org/jasig/cas/util/DefaultCipherExecutorTests.java
- cas-server-webapp-support/src/main/java/org/jasig/cas/web/support/DefaultCasCookieValueManager.java
- cas-server-webapp-support/src/test/java/org/jasig/cas/web/support/DefaultCasCookieValueManagerTests.java
- cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
- cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/ticketGrantingTicketCookieGenerator.xml
As I was testing the TGC encryption, I ran across the following issues:
If the server is restarted, CAS is unable to properly parse the cookie and crashes. Because secret keys for encryption and signing are only kept in memory, restarts generate new keys. Also HA deployments would also not work via in-memory keys. So this pull does the following:
1. Provide secret keys via cas.properties as JSON web tokens:
https://github.com/mitreid-connect/json-web-key-generator
2. Ensures that CAS can gracefully recover if there is an issue with the decryption (like a bad or missing value)
> TGC encryption: fixed issue with shared secret key generation

- cas-server-webapp-support/pom.xml
- pom.xml
Deploying CAS/master on Tomcat 7.0.20, causes a crash, with the following error:
```Provider com.ctc.wstx.stax.WstxInputFactory cannot be located.``` 
This seems to be required by the hibernate validator. This pull adds the missing dependency explicitly. I have also excluded few other dependencies for logging and caching APIs to reduce conflicts. 
Tested deployment on both TC7 and 8.
> Missing dependency for Tomcat 8.x causes crash

- cas-server-core/src/main/java/org/jasig/cas/ticket/registry/support/DefaultTicketRegistryCleaner.java
- cas-server-core/src/test/java/org/jasig/cas/ticket/registry/support/DefaultTicketRegistryCleanerTests.java
- cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/ticketRegistry.xml
The default ticket registry cleaner calls CAS.destroyTicketGrantingTicket() when an expired ST is found to be cleaned. The result causes an exception to be thrown because that method can only work with TGTs. Long term, the CAS interface should be revised to handle ticket registry ops better, but in the interest of keeping this pull small and not wanting to modify that interface, I simply added a PR to delete the expired ST for now.
> Default ticket cleaner throws error when removing STs

- cas-server-webapp-support/src/main/java/org/jasig/cas/web/flow/AcceptableUsagePolicyFormAction.java
- cas-server-webapp-support/src/main/java/org/jasig/cas/web/support/CookieRetrievingCookieGenerator.java
- cas-server-webapp/src/main/resources/messages.properties
- cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml
- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/casAcceptableUsagePolicyView.jsp
- cas-server-webapp/src/main/webapp/WEB-INF/webflow/login/login-webflow.xml
Handles https://github.com/Jasig/cas/issues/467
Allow the user to accept the usage policy before moving on to the application. In this PR, the remembering of the policy acceptable is recorded per credential id into map kept in memory. Other sophisticated impls can extend the `AcceptableUsagePolicyFormAction` class to verify and record this
behavior via an external flag such as an ldap attribute, etc.
> Support Acceptable Usage Policy (AUP) workflows

- cas-management-webapp/src/main/java/org/jasig/cas/services/web/ManageRegisteredServicesMultiActionController.java
- cas-management-webapp/src/main/java/org/jasig/cas/services/web/RegisteredServiceSimpleFormController.java
- cas-management-webapp/src/main/resources/default_views.properties
- cas-management-webapp/src/main/resources/messages.properties
- cas-management-webapp/src/main/webapp/WEB-INF/cas-management-servlet.xml
- cas-management-webapp/src/main/webapp/WEB-INF/spring-configuration/applicationContext.xml
- cas-management-webapp/src/main/webapp/WEB-INF/view/jsp/authorizationFailure.jsp
- cas-management-webapp/src/main/webapp/WEB-INF/view/jsp/includes/bottom.jsp
- cas-management-webapp/src/main/webapp/WEB-INF/web.xml
- cas-management-webapp/src/test/java/org/jasig/cas/services/web/WebAppContextConfigurationTests.java
- cas-server-webapp-support/src/main/java/org/jasig/cas/web/support/AbstractThrottledSubmissionHandlerInterceptorAdapter.java
- cas-server-webapp-support/src/main/java/org/jasig/cas/web/view/CasReloadableMessageBundle.java
- cas-server-webapp/src/main/resources/messages.properties
- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/authorizationFailure.jsp
Handles https://github.com/Jasig/cas/issues/501
When throttling is enabled, the authorization failure views do not explain any details. The message key that was expected in the view could never be found. 
This pull does the following:
1. Allowed the authz failure view to explain itself when throttling is enabled
2. Added additional error messages to the authz failure view for the /status endpoint
3. Applied the same changes to the management app when user is not authorized to access resources
Given the way controllers are annotated in the management app, I had to move around the declarations of views a bit to make sure spring security does not interfere with spring webmvc. As a result, views are not automatically picked up, and there is no need to explicitly declare them, which is similar …
> Authz failure views do not show details

- cas-server-webapp-support/src/main/java/org/jasig/cas/web/flow/AuthenticationViaFormAction.java
- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/casLoginView.jsp
- cas-server-webapp/src/main/webapp/css/cas.css
Handles https://github.com/Jasig/cas/issues/907
I also noticed that none of the other error messages are actually displayed on the page, because the css class `errors` is/was set to hide them all by default. I made sure the class is back to normal, and only added specific style info to the block that wanted off the screen initially.
> Missing LT error is not reported back 

- cas-server-core/src/main/java/org/jasig/cas/ticket/support/AbstractCasExpirationPolicy.java
- cas-server-webapp-support/src/main/java/org/jasig/cas/web/report/InternalConfigStateController.java
- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/monitoring/viewConfig.jsp
- cas-server-webapp/src/main/webapp/WEB-INF/web.xml
Adds a "Config State" report to the `/status/config` endpoint. The report presents a JSON representation of the "runtime" CAS server configuration as well as all available properties. This is useful for determining the state of the CAS configuration without fishing for settings inside the xml configuration files, etc and allows administrators to quickly determine CAS behavior based on configuration. 
Important to note that only `org.jasig` components are reported back and everything else is filtered. 
The screenshot above shows a filtered list of view of the CAS state and properties.
> Internal Config State Report

- cas-server-compatibility/pom.xml
- cas-server-core/pom.xml
- cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
- cas-server-core/src/main/java/org/jasig/cas/ticket/ServiceTicketImpl.java
- cas-server-core/src/main/java/org/jasig/cas/ticket/TicketGrantingTicket.java
- cas-server-core/src/main/java/org/jasig/cas/ticket/TicketGrantingTicketImpl.java
- cas-server-core/src/main/java/org/jasig/cas/ticket/registry/AbstractDistributedTicketRegistry.java
- cas-server-core/src/test/java/org/jasig/cas/CentralAuthenticationServiceImplWithMokitoTests.java
- cas-server-core/src/test/java/org/jasig/cas/mock/MockTicketGrantingTicket.java
- cas-server-core/src/test/java/org/jasig/cas/ticket/TicketGrantingTicketImplTests.java
- cas-server-documentation/pom.xml
- cas-server-extension-clearpass/pom.xml
- cas-server-integration-ehcache/pom.xml
- cas-server-integration-jboss/pom.xml
- cas-server-integration-memcached/pom.xml
- cas-server-integration-restlet/pom.xml
- cas-server-support-generic/pom.xml
- cas-server-support-jdbc/pom.xml
- cas-server-support-ldap/pom.xml
- cas-server-support-legacy/pom.xml
- cas-server-support-oauth/pom.xml
- cas-server-support-openid/pom.xml
- cas-server-support-radius/pom.xml
- cas-server-support-spnego/pom.xml
- cas-server-support-trusted/pom.xml
- cas-server-support-x509/pom.xml
- cas-server-uber-webapp/pom.xml
- cas-server-webapp/pom.xml
- pom.xml
A new field, proxiedBy, is introduced on TicketGrantingTicket to track the service that generates a proxy-granting ticket to facilitate looking up the corresponding RegisteredService at the time proxy tickets are issued. The allowedToProxy flag on the proxiedBy service determines whether or not the proxy ticket request can proceed.
> Issue #904 Fix scope of allowedToProxy flag.

- cas-server-webapp/src/main/resources/messages.properties
Handles https://github.com/Jasig/cas/issues/866 
To convey the actual message back would possibly require some major API work to note missing parameters into the messages. This pull should try to generalize the error message, while exact details are available in the cas log.
> Updated error message for invalid validation requests

- cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/authentication/principal/SpnegoCredential.java
- cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/util/SpnegoConstants.java
Fixes #947 by tweaking storage and checking of NTLMSSP_SIGNATURE.  Short version: different comparison method; different storage method.
> CAS #947 -- NTLMSSP_SIGNATURE Casting Exception

- cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/authentication/principal/SpnegoCredential.java
- cas-server-support-spnego/src/test/java/org/jasig/cas/support/spnego/authentication/principal/SpnegoCredentialsTests.java
Fixes #948.  Modify hashCode function of SpnegoCredential in order to avoid NPE when principal has not yet been resolved.
> CAS 948 -- NPE during SPNEGO Authentication

- cas-server-documentation/installation/X509-Authentication.md
```regExTrustedIssuerDnPattern``` and ```regExSubjectDnPattern``` are variable name and does not match setters. 
The properties to set on deployerConfigContext.xml must be ```trustedIssuerDnPattern``` and ```regExSubjectDnPattern```.
A real minor change but avoid to have to read the source :)
> Corrected properties name to match setters

- cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/OAuthConstants.java
- cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20ProfileController.java
Hello,
I'm not sure if this is the right place, yet I'm still encountering problems with how "Bearer" keyword is used. Changing "bearer" to "Bearer" fixed some issues yet it introduced another. Please take a look at:
https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/client/DefaultOAuth2RequestAuthenticator.java#L39
when authorizing request tokenType from Oauth2AccessToken is used (if it exists), default implementation lowercases the "Bearer" keyword:
https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/common/DefaultOAuth2AccessToken.java#L27
Bottom line - being case sensitive in here will probably lead to such …
> OAuth2 - Bearer token handling - Ignore case comparision of bearer token authorization header

- cas-server-webapp/src/main/webapp/WEB-INF/classes/default_views.properties
- cas-server-webapp/src/main/webapp/WEB-INF/login-webflow.xml
- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/casWarnPostView.jsp
This adds a new view to display the LPPE password warning message and submit the authentication response to the requested service in a POST.  This is required for services using SAML 2 such as GoogleApps. 
JIRA issue: https://issues.jasig.org/browse/CAS-1368
> CAS-1368: Support POST response to service after password warning check

- cas-server-webapp/src/main/webapp/WEB-INF/web.xml
The validation error #986 resolved by including the new listener-class in its own listener tag in web.xml
> CAS-986 Schema validation error on web.xml

- cas-server-core/src/main/java/org/jasig/cas/ticket/TicketGrantingTicket.java
- cas-server-core/src/main/java/org/jasig/cas/ticket/proxy/support/Cas20ProxyHandler.java
- cas-server-core/src/main/java/org/jasig/cas/web/view/AbstractCasView.java
- cas-server-core/src/main/java/org/slf4j/impl/CasDelegatingLogger.java
- cas-server-core/src/test/java/org/slf4j/impl/CasLoggerFactoryTests.java
- cas-server-webapp/src/main/webapp/WEB-INF/unused-spring-configuration/clearpass-configuration.xml
Troubleshooting an issue with Clearpass that had to do with a missing proxy block in the CAS response. Turns out that there is a bug in the way chained authentications are handled and passed down to the view in that the index from which the chain starts is incorrectly calculated. This pull fixes that. 
In the course of applying the fix, I discovered and made the following fixes:
1. Made sure PGTIOUs are correctly formatted in logs.
2. Updated clearpass sample configuration to denote use of proxy lists and acceptance. 
This issue only affects master as far as I can tell.
> Proxy block missing from CAS response

- cas-management-webapp/src/main/java/org/jasig/cas/services/web/RegisteredServiceSimpleFormController.java
- cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
- cas-server-support-pac4j/src/main/java/org/jasig/cas/support/pac4j/web/flow/ClientAction.java
- cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/web/flow/SpnegoCredentialsAction.java
- cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/web/flow/SpnegoNegociateCredentialsAction.java
- cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/web/flow/client/HostNameSpnegoKnownClientSystemsFilterAction.java
- cas-server-support-x509/src/main/java/org/jasig/cas/adaptors/x509/authentication/principal/X509SubjectPrincipalResolver.java
Regarding #957, I updated HTML tags in javadocs to make them compatible with JDK 8 javadoc doclient standards. Changes include:
- Removing self-close tags (like `<br/>`)
- Pairing each single `<p>` tag with corresponding closing tag (`</p>`)
- Removing or fixing any invalid references in `{@link}` doclets
- Adding missed `@params` doclets
It worth reading [Javadoc doclint](http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html) by Stephen Colebourne to have better understanding of Java 8 doclint
> CAS-957 Switch the build to use Java 8 by default

- cas-server-webapp/src/main/webapp/WEB-INF/webflow/login/login-webflow.xml
When an invalid TGT is present on the client, gateway=true was being ignored.
> Check for gateway mode on invalid TGT

- pom.xml
To avoid incompatibility issues between SAML supports (available via the `cas-server-support-saml` module and the `cas-server-support-pac4j` + `pac4j-saml` libraries)
> Update pac4j to version 1.7.1

- cas-server-documentation/installation/Webflow-Customization.md
- cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml
- cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
Updates documentation and config to note the settings used to transcode the login flow state. This allows adopters to easily change them via properties if need be. Defaults are still in place for all.
> Login flow Transcoding config

- pom.xml
v40 updates plugin versions; specially the release and javadoc plugins that affect the CAS project during its own release cycle.
> Upgrade to Apereo parent v40.

- cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/util/AbstractSamlObjectBuilder.java
- cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/web/view/AbstractSaml10ResponseView.java
A number of classes attempt to manually init opensaml.
All init functionality is handled via the opensaml config bean.
> Fix OpenSAML initialization error

- cas-server-core/src/main/java/org/jasig/cas/authentication/handler/support/AbstractPreAndPostProcessingAuthenticationHandler.java
- cas-server-core/src/main/java/org/jasig/cas/authentication/handler/support/AbstractUsernamePasswordAuthenticationHandler.java
The method that allows a given handler to create a HandlerResult object is presently placed in the wrong spot. Its placement is incorrect because the method has nothing to do with username/password authentication. In this PR, it is moved up the chain so it's available in a more generic place applicable to all credential.
> Move creation of HandlerResult up the chain

- cas-server-core/src/main/java/org/jasig/cas/authentication/principal/CachingPrincipalAttributesRepository.java
- cas-server-core/src/main/java/org/jasig/cas/authentication/principal/DefaultPrincipalAttributesRepository.java
- cas-server-core/src/main/java/org/jasig/cas/services/AbstractAttributeReleasePolicy.java
- cas-server-core/src/main/java/org/jasig/cas/services/AbstractRegisteredService.java
- cas-server-core/src/main/java/org/jasig/cas/services/DefaultRegisteredServiceAccessStrategy.java
- cas-server-core/src/main/java/org/jasig/cas/services/RefuseRegisteredServiceProxyPolicy.java
- cas-server-core/src/main/java/org/jasig/cas/services/ReturnAllAttributeReleasePolicy.java
- cas-server-core/src/main/java/org/jasig/cas/services/ReturnAllowedAttributeReleasePolicy.java
- cas-server-core/src/main/java/org/jasig/cas/services/ReturnMappedAttributeReleasePolicy.java
- cas-server-core/src/test/java/org/jasig/cas/TestUtils.java
- cas-server-core/src/test/java/org/jasig/cas/services/AbstractRegisteredServiceTests.java
While working on a different issue, I realized that the equality/hashCode rules for two registered services do not fully take into account all correct fields. Fixed, and also added missing toString() methods.
> BugFix: registered services equality mismatch

- cas-management-webapp/src/main/webapp/js/app/app-angular.js
The management webapp assumes a static `cas-management` context path. This is not true everywhere, because the app can take on any context path, or none if it's deployed at the root. This pull dynamically determines what the path is going to be, and adjusts AJAX calls accordingly.
> Determine management app context path dynamically

- cas-server-documentation/integration/Google-Apps-Integration.md
The package name for the GoogleAccountsArgumentExtractor changed at some point (probably when it was moved out of the primary repo) and the docs didn't follow the change.  Without this change, you get a class not found exception.
> Documentation: Update Package Name for SAML.

- 4.0.x/installation/Configuring-Authentication-Components.html
- 4.1.x/installation/Configuring-Authentication-Throttling.md
- development/installation/Configuring-Authentication-Throttling.md
The code samples given in documentation of the
InMemoryThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter
class are invalid, featuring the similar
InMemoryThrottledSubmissionByIpAddressHandlerInterceptorAdapter
class instead
> Incorrect class in code samples for throttling doc

- cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/authentication/handler/support/JCIFSSpnegoAuthenticationHandler.java
If your localhost is ipv6, with default configuration JCIFS NTLM process will try to connect to a pseudo-random server:
http://article.gmane.org/gmane.network.samba.java/9539
> if NTLM is not allowed, refuse NTLM ASAP instead of going to JCIFS code

- cas-server-support-spnego/src/main/java/org/jasig/cas/support/spnego/authentication/handler/support/JCIFSSpnegoAuthenticationHandler.java
Commit "CAS-1238 Port handlers to new AuthenticationHandler interface" reworked the code, replacing "return" with "success" variable, but it surely broke NTLM (maybe the breakage is no real pb though)
> fix regression introduced in commit "CAS-1238 ..."

- cas-server-support-openid/pom.xml
excludes xerces dependency from openid4java in cas-cerver-support-openid
> exclude xerces dependency

- cas-server-documentation/protocol/SAML-Protocol.md
- cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml
Add missing `servicesManager` property to the SAML validator.
> Add missing SAML property: servicesManager

- cas-server-documentation/installation/LDAP-Authentication.md
The doc uses at the moment :
* ldap.baseDn in spring xml context configuration 
* ldap.authn.baseDn in the property file example
We suggest here to use only ldap.authn.baseDn
> Doc : ldap.baseDn vs ldap.authn.baseDn

- cas-server-documentation/installation/Configuring-Authentication-Throttling.md
In spring 4.1, org.springframework.scheduling.quartz.SimpleTriggerBean doesn't exist anymore (ClassNotFoundEx) - we have to use org.springframework.scheduling.quartz.SimpleTriggerFactoryBean instead.
SimpleTriggerBean was dreprecated since some time : 
https://jira.spring.io/browse/SPR-10209
> Doc : Throttling - SimpleTriggerFactoryBean

- cas-server-webapp/src/main/webapp/WEB-INF/deployerConfigContext.xml
Re-arranges the deployerConfigContext, fixes formatting issues and gives a number of beans explicit ids, so that sub modules can manipulate them automatically when needed.
> Reformat configuration of deployerConfigContext

- cas-server-documentation/protocol/SAML-Protocol.md
- cas-server-support-saml/src/main/java/org/jasig/cas/SamlApplicationContextInitializer.java
- cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/OpenSamlConfigBean.java
- cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/SamlProtocolConstants.java
- cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/SamlServletContextListener.java
- cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/util/SamlCompliantUniqueTicketIdGenerator.java
- cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/web/support/SamlArgumentExtractor.java
- cas-server-support-saml/src/main/resources/META-INF/cas-servlet-saml.xml
- cas-server-support-saml/src/main/resources/META-INF/spring/saml-protocol-views.xml
- cas-server-support-saml/src/test/java/org/jasig/cas/support/saml/util/SamlCompliantUniqueTicketIdGeneratorTests.java
- cas-server-support-saml/src/test/resources/META-INF/spring/opensaml-config.xml
- cas-server-support-saml/src/test/resources/cas.properties
- cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml
- cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
- cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/argumentExtractorsConfiguration.xml
- cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/uniqueIdGenerators.xml
- cas-server-webapp/src/main/webapp/WEB-INF/web.xml
This pull reduces the SAML configuration noise down to one step: including the dependency. That's it. No more manual steps are actually required. There are also a few settings that are now exposed via the cas.properties file. This should grealy simplify the configuration, and reduce maven overlay sizes. 
All functionality works just as it did before. 
This depends on #1118
> Reduce SAML configuration noise

- cas-server-documentation/installation/RADIUS-Authentication.md
- cas-server-support-openid/pom.xml
- cas-server-support-radius/pom.xml
- cas-server-support-radius/src/main/java/org/jasig/cas/adaptors/radius/authentication/handler/support/RadiusAuthenticationHandler.java
- cas-server-support-radius/src/main/resources/META-INF/spring/radius-server-config.xml
- cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
Automates the configuration radius servers and clients, so that only declaring the authN handler is needed, and configuration is moved to the cas.properties. Adopters can still define additional servers and clients if they need to, just like before.
> Radius context config automated

- cas-server-core/src/main/java/org/jasig/cas/util/ApplicationContextProvider.java
- cas-server-core/src/main/java/org/jasig/cas/util/CompressionUtils.java
- cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsService.java
- cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/util/AbstractSaml20ObjectBuilder.java
- cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/web/support/GoogleAccountsArgumentExtractor.java
- cas-server-support-saml/src/main/resources/META-INF/spring/opensaml-config.xml
- cas-server-support-saml/src/test/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsServiceTests.java
- cas-server-support-saml/src/test/java/org/jasig/cas/support/saml/web/support/GoogleAccountsArgumentExtractorTests.java
- cas-server-support-saml/src/test/resources/META-INF/spring/opensaml-config.xml
Closes #1205 
This is a problem with inflation of saml request that is now fixed. I also had to make the change to move the services manager out of the google service, and have it be dynamically looked up because I ran into serialization issues. 
This should be backported to 4.0.x and master.
> Google Apps SAML authN request is not parsed correctly

- cas-server-support-ldap/src/main/java/org/jasig/cas/adaptors/ldap/services/LdapServiceRegistryDao.java
- cas-server-support-ldap/src/main/java/org/jasig/cas/monitor/ConnectionFactoryMonitor.java
- cas-server-support-ldap/src/main/java/org/jasig/cas/monitor/PooledConnectionFactoryMonitor.java
- cas-server-support-ldap/src/main/java/org/jasig/cas/util/LdapUtils.java
Given the upgrade to ldaptive 1.1, we can now use the TryResource on LDAP connections, which removes the need to maintain LdapUtils.closeConnection.
> Use TryResource syntax for LDAP connections

- cas-management-webapp/src/main/webapp/js/app/app-angular.js
Validation always fails if regexp is non-empty.
Closes https://github.com/Jasig/cas/issues/1247
> Fix bug in form validation for proxy service regex. CAS-1498

- cas-server-core-audit/src/main/resources/inspektr-jdbc-audit-config.xml
- cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/UsernamePasswordCredential.java
- cas-server-documentation/installation/Audits.md
- cas-server-documentation/installation/Configuring-Authentication-Throttling.md
- cas-server-documentation/installation/Logging.md
- cas-server-documentation/sidebar.html
- cas-server-webapp-throttle/pom.xml
- cas-server-webapp-throttle/src/main/java/org/jasig/cas/web/support/AbstractThrottledSubmissionHandlerInterceptorAdapter.java
- cas-server-webapp-throttle/src/main/java/org/jasig/cas/web/support/InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter.java
- cas-server-webapp-throttle/src/main/java/org/jasig/cas/web/support/entity/AuditTrailEntity.java
- cas-server-webapp-throttle/src/main/resources/inspektr-throttle-jdbc-config.xml
- cas-server-webapp/pom.xml
- cas-server-webapp/src/main/resources/log4j2.xml
- cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
- cas-server-webapp/src/main/webapp/WEB-INF/deployerConfigContext.xml
Closes https://github.com/Jasig/cas/issues/1173
* Updated docs and added support for auto-config
* Made sure attempts are recorded by the audit manager
* Default config is switched to point to a local hsqldb database for simplicity
* Logging just the userid now, rather than a formatted version
> Changes to InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter

- cas-management-webapp/src/main/java/org/jasig/cas/services/web/RegisteredServiceSimpleFormController.java
- cas-server-core/src/test/java/org/jasig/cas/services/InMemoryServiceRegistryDaoImplTests.java
- cas-server-core/src/test/java/org/jasig/cas/services/JsonServiceRegistryDaoTests.java
- cas-server-integration-mongo/src/test/java/org/jasig/cas/services/MongoServiceRegistryDaoTests.java
- cas-server-support-jdbc/src/test/java/org/jasig/cas/services/JpaServiceRegistryDaoImplTests.java
Removes an extra delete from the edit workflow since the DAO uses a modify not an add for edits.
Without this, the service management web app will delete the service then the DAO will fail to find it for updating.
> Ldap services fix

- cas-server-documentation/protocol/CAS-Protocol-Specification.md
Fixed semantic typo and added an example custom attribute snippet to the spec doc.
(my previous local branch GH_1274 was published to the jasig repo by my beloved Tower git client - grr). Deleted the branch in the cas repo and published into my gh clone repo.)
> #1274 fix typo in cas protocol 3 spec and add example response

- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/casLoginMessageView.jsp
Enabling LPPE causes a redirect loop. This is due to the `execution` parameter not being URL encoded causing it to decode improperly when it includes `+` characters. These get decoded to spaces by the web server before it gets passed to the application.
> fix redirect loop on password expiration warning

- cas-server-core-logging/src/main/java/org/slf4j/impl/CasDelegatingLogger.java
the source args Array may not be a superclass of the String class.
Closes #1300
> create a new Array for modified args

- cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsService.java
Fix an issue with the time zone being ignored, which caused the googleapps auth to expire. Removing the ISOStandardDateFormat seems to fix it
> Fix a possible issue with Google Apps SAML2 timezones

- cas-server-core-audit/src/main/java/org/jasig/cas/audit/spi/PrincipalIdProvider.java
- cas-server-core-audit/src/main/java/org/jasig/cas/audit/spi/TicketOrCredentialPrincipalResolver.java
This is a pluggable strategy interface that would be useful for use cases that require more audit logging of more complex principal ids (authenticated entities) in case of more complex authentication scenarios - for example a "surrogate" authentication scenario where there is a "real" and "surrogate" principal ids involved. With the current implementation of just getting the `principal#id` that would not be possible. With this strategy API, a custom implementation would be provided that would compute the compound principal id to display in the `WHO` field based on the provided `Authentication` metadata available for that scenario, etc.
With a custom implementation, the "surrogate" case might look like this:
```bash
=============================================================
WHO: (Real …
```
> Introduce PrincipalIdProvider strategy

- cas-server-documentation/installation/LDAP-Authentication.md
- names of properties,
- $cas.version->$project.version,
- ldap.trustedCert should be in sample cas.properties file
- startTLS should be set to false, because sample config is for ldap://
> Correction of LDAP AuthN documentation

- cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/beans/RegisteredServiceEditBean.java
- cas-server-core-logout/src/main/java/org/jasig/cas/logout/LogoutManagerImpl.java
- cas-server-core-tickets/src/test/java/org/jasig/cas/mock/MockServiceTicket.java
- cas-server-core-util/src/main/java/org/jasig/cas/util/AbstractJacksonBackedJsonSerializer.java
- cas-server-integration-memcached/src/main/java/org/jasig/cas/ticket/registry/support/kryo/KryoTranscoder.java
- cas-server-support-ldap/src/main/java/org/jasig/cas/util/LdapUtils.java
- cas-server-support-ldap/src/test/java/org/jasig/cas/util/LdapTestUtils.java
- cas-server-support-saml-googleapps/src/main/java/org/jasig/cas/support/saml/SamlGoogleAppsServletContextListener.java
- cas-server-support-saml-googleapps/src/test/java/org/jasig/cas/support/saml/authentication/principal/GoogleAccountsServiceTests.java
- cas-server-webapp-reports/src/main/java/org/jasig/cas/web/report/InternalConfigStateController.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1068 - Unused private fields should be removed
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1068
Please let me know if you have any questions.
Kirill Vlasov
> Unused private fields should be removed

- cas-server-core-logging/src/main/java/org/slf4j/impl/CasLoggerFactory.java
- cas-server-core-logging/src/test/java/org/slf4j/impl/CasLoggerFactoryTests.java
- cas-server-core-services/src/main/java/org/jasig/cas/services/RegexRegisteredService.java
- cas-server-core-services/src/test/java/org/jasig/cas/authentication/support/DefaultCasAttributeEncoderTests.java
- cas-server-core-util/src/main/java/org/jasig/cas/util/DefaultRandomStringGenerator.java
- cas-server-core-web/src/main/java/org/jasig/cas/services/web/view/AbstractCasView.java
- cas-server-extension-clearpass/src/main/java/org/jasig/cas/extension/clearpass/EncryptedMapDecorator.java
- cas-server-integration-memcached/src/main/java/org/jasig/cas/ticket/registry/support/kryo/serial/RegisteredServiceSerializer.java
- cas-server-support-jdbc/src/test/java/org/jasig/cas/adaptors/jdbc/QueryAndEncodeDatabaseAuthenticationHandlerTests.java
- cas-server-support-jdbc/src/test/java/org/jasig/cas/adaptors/jdbc/QueryDatabaseAuthenticationHandlerTests.java
- cas-server-support-jdbc/src/test/java/org/jasig/cas/adaptors/jdbc/SearchModeSearchDatabaseAuthenticationHandlerTests.java
- cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java
- cas-server-support-pac4j/src/main/java/org/jasig/cas/support/pac4j/web/flow/ClientAction.java
- cas-server-support-x509/src/test/java/org/jasig/cas/adaptors/x509/util/MockWebServer.java
- cas-server-webapp-reports/src/main/java/org/jasig/cas/web/report/StatisticsController.java
- cas-server-webapp-throttle/src/main/java/org/jasig/cas/web/support/AbstractInMemoryThrottledSubmissionHandlerInterceptorAdapter.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2325 - "private" methods that don't access instance data should be "static"
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2325
Please let me know if you have any questions.
Kirill Vlasov
> "private" methods that don't access instance data should be "static"

- cas-server-core-services/src/main/java/org/jasig/cas/services/RegexRegisteredService.java
I don't think there are currently any code paths that would trigger this corner case, but it's a simple corner case to protect against.
> Reset regex servicePattern when the serviceId is changed

- cas-management-webapp-support/src/main/java/org/jasig/cas/services/web/ManageRegisteredServicesMultiActionController.java
- cas-management-webapp/src/main/resources/user-details.properties
- cas-management-webapp/src/main/webapp/WEB-INF/cas-management.properties
- cas-management-webapp/src/main/webapp/WEB-INF/managementConfigContext.xml
- cas-management-webapp/src/main/webapp/WEB-INF/spring-configuration/securityContext.xml
- cas-server-core-logging/src/main/java/org/slf4j/impl/CasLoggerFactory.java
- cas-server-documentation/installation/Installing-ServicesMgmt-Webapp.md
- cas-server-documentation/installation/Service-Management.md
This pull:
1. Updates the documentation for the cas services management webapp
2. Presents a sample overlay for the webapp in the docs
3. Describes how access to the webapp may be granted via various options
4. Enabled access to the webapp by default, and authenticates against the heroku CAS instance.
> Updated docs for mgmt webapp

- cas-server-webapp/src/main/webapp/WEB-INF/web.xml
Without this, occasionally, `/login` gets the `jsessionid` appended to the URL. Also some local javascript or css loads.
> force cookie only session tracking

- .travis.yml
- cas-server-integration-memcached/src/test/java/org/jasig/cas/ticket/registry/support/kryo/KryoTranscoderTests.java
- cas-server-support-saml/src/main/java/org/jasig/cas/support/saml/web/view/Saml10SuccessResponseView.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1848 - Objects should not be created to be dropped immediately without being used
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1848
Please let me know if you have any questions.
Kirill Vlasov
> Objects should not be created to be dropped immediately without being used

- cas-server-core-api/src/main/java/org/jasig/cas/services/RegisteredService.java
- cas-server-core-api/src/main/java/org/jasig/cas/services/RegisteredServiceProperty.java
- cas-server-core/src/main/java/org/jasig/cas/services/AbstractRegisteredService.java
- cas-server-core/src/main/java/org/jasig/cas/services/DefaultRegisteredServiceProperty.java
- cas-server-core/src/test/java/org/jasig/cas/services/JsonServiceRegistryDaoTests.java
- cas-server-documentation/installation/Configuring-LongTerm-Authentication.md
- cas-server-documentation/installation/Service-Management.md
This is a change backported from 4.1 allowing a service to carry arbitrary properties. This is required to support cas-MFA's upgrade to 4.1
> Registered Service properties backported to 4.1

- cas-server-core/src/test/java/org/jasig/cas/CentralAuthenticationServiceImplTests.java
- cas-server-core/src/test/resources/core-context.xml
- cas-server-integration-pac4j-core/src/main/java/org/jasig/cas/authentication/handler/support/AbstractPac4jAuthenticationHandler.java
- cas-server-integration-pac4j-core/src/main/java/org/jasig/cas/authentication/principal/ClientCredential.java
Closes https://github.com/Jasig/cas/issues/1413
The ClientCredential does always use the typedId, which causes issues down the road for PrincipalResolvers that work separately from the Principal produced by the ClientAuthenticationHandler. 
This should be ported back to 4.2 and 4.1,
> Allow the ClientCredential to ignore the typedid if configured

- cas-server-documentation/installation/X509-Authentication.md
**NOTE:** This replaces PR #1431 
--------
When attempting to follow the X.509 Authentication Guide, I found some errors in the documentation and code snippets. This included:
This PR addresses these concerns. I have validated the included configurations worked on my clean configuration, of which the details are below:
* Fedora 23
* Oracle JRE 1.8.0_66
* Apache Tomcat 8
* Jasig CAS 4.1.3
* CAS X509 Handler 4.1.3
> Update X.509 Authentication Guide

- cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/OAuthConstants.java
the error view names were changed in https://github.com/Jasig/cas/commit/c941a083875e96b79a951dec5b8cf1c44e8ea03c but not updated for OAuth.
This will need to be backported to 4.1 and 4.2
> Update the OAuth error view name

- cas-management-webapp-support/build.gradle
- cas-server-webapp/build.gradle
- gradle.properties
taglibs/standard is no longer necessary since it is in the jstl 1.2 jar
see: http://stackoverflow.com/tags/jstl/info
> jstl 1.2 embeds the taglibs/standard dependency

- cas-server-webapp/src/main/webapp/js/cas.js
Rawgit recomends use: https://cdn.rawgit.com/cowboy/javascript-debug/master/ba-debug.min.js instead of https://rawgithub.com/cowboy/javascript-debug/master/ba-debug.min.js
Extract from https://rawgit.com/faq FAQ:
Can I use a rawgit.com URL on a production website?
No. Please use cdn.rawgit.com for anything that might result in heavy traffic. Only use rawgit.com URLs for low-traffic testing and sharing temporary examples or demos during development. When people misuse rawgit.com, it costs me money. Please don't be a jerk.
> Fix for ba-debug JS dependency

- cas-server-core-services/src/main/java/org/jasig/cas/services/DefaultServicesManagerImpl.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/DefaultTicketRegistry.java
- cas-server-core-util/src/main/java/org/jasig/cas/util/CasSpringBeanJobFactory.java
- cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java
- cas-server-support-saml-mdui/src/main/java/org/jasig/cas/support/saml/web/flow/mdui/StaticMetadataResolverAdapter.java
- cas-server-support-saml-mdui/src/test/resources/META-INF/spring/opensaml-config.xml
- cas-server-webapp-throttle/src/main/java/org/jasig/cas/web/support/AbstractInMemoryThrottledSubmissionHandlerInterceptorAdapter.java
- cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
- cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/applicationContext.xml
Centralize the Quartz scheduler in spring config to better be able to manage the scheduler lifecycle.
> Quartz shutdown on 4.2

- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/serviceErrorSsoView.jsp
You should not have to HTML escape here, and in fact it might even be buggy for some inputs. 
The `<c:url />` tag  (line 2) will URL encode the value so it generates a valid query string parameter value. 
The `${fn:escapeXml(url)}` on line 9 should then *HTML* escape the complete URL. (Actually you can probably use `htmlEscape="true"` as well on the `<spring:message />` tag.
That should do.
> Remove HTML escaping from the URL

- cas-server-support-saml-idp/build.gradle
> no need to include cas-server-support-saml as a compile and test dependency

- cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/principal/PersonDirectoryPrincipalResolver.java
- cas-server-core-webflow/src/main/java/org/jasig/cas/web/flow/AbstractCasWebflowConfigurer.java
- cas-server-documentation/integration/ADFS-Integration.md
- cas-server-support-wsfederation-webflow/src/main/java/org/jasig/cas/web/flow/WsFederationWebflowConfigurer.java
- cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/WsFedServletContextListener.java
- cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/WsFederationAttributeMutator.java
- cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/WsFederationConfiguration.java
- cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/WsFederationHelper.java
- cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/authentication/handler/support/WsFederationAuthenticationHandler.java
- cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/authentication/principal/WsFederationCredential.java
- cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/authentication/principal/WsFederationCredentialsToPrincipalResolver.java
- cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/web/flow/WsFederationAction.java
- cas-server-support-wsfederation/src/test/java/org/jasig/cas/support/wsfederation/WsFederationAttributeMutatorTests.java
- cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
Closes #1483 
- Make use the WSFED principal resolver optional
- Fix flow bug with redirect to the IDP
- When/If WSFED resolver is used, provide options to dictate how attributes should be resolved.
> Allow more control over WS-FED principal resolver

- cas-management-webapp/build.gradle
- cas-server-core-logging/build.gradle
- cas-server-core-logging/src/main/java/org/jasig/cas/util/CasLoggerContextInitializer.java
- cas-server-core-logging/src/main/java/org/slf4j/impl/CasLoggerFactory.java
- cas-server-documentation/installation/Logging.md
- cas-server-webapp/build.gradle
- cas-server-webapp/src/main/resources/log4j2.xml
Closes https://github.com/Jasig/cas/issues/1493
- Add support for a `loggerFactory` environment property to allow specific selection of logger binding, in cases where CAS ends up with more than one binding and the environment is not amenable to changes. This should also help with faster startup times rather than initial context scans. The property is optional and if none is provided, CAS will fallback to the current behavior. 
- Reorganize the logger initialization logic to be consistent with the remaining servlet initializers.
- Updated docs to explain how an alternative framework such as Logback can be used.
> Allow alternative logger selection

- cas-server-support-jpa-ticket-registry/src/main/resources/META-INF/spring/jpa-ticket-reg-context.xml
When a TGT is loaded it is checked if it has expired, if it has it will be deleted which fails in a readonly TX
> mark CAS.getTicket() calls not readonly

- cas-server-core-api-authentication/src/main/java/org/jasig/cas/authentication/AuthenticationException.java
- cas-server-core-api-authentication/src/main/java/org/jasig/cas/authentication/AuthenticationSystemSupport.java
- cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/DefaultAuthenticationSystemSupport.java
- cas-server-core/src/test/java/org/jasig/cas/AbstractCentralAuthenticationServiceTests.java
- cas-server-integration-hazelcast/src/main/java/org/jasig/cas/ticket/registry/config/HazelcastInstanceConfiguration.java
- cas-server-webapp-actions/src/main/java/org/jasig/cas/web/flow/GenerateServiceTicketAction.java
- cas-server-webapp-actions/src/test/java/org/jasig/cas/web/flow/GenerateServiceTicketActionTests.java
- checkstyle-rules.xml
Closes #1506 
Grabs the authentication object from the existing TGT and builds a result out of that, rather than authenticating the credentials again.
> Remove double authentication when generating STs

- cas-server-core-web/src/main/java/org/jasig/cas/web/support/WebUtils.java
Should be ported to 4.2 and possibly 4.1. I bumped into this while working on MFA for 4.1
> Mark putTicketGrantingTicketIntoMap() public

- cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
We store the original `Authentication` object only in the root `TGT`. In order for `AuthenticationPolicies` to be correctly enforced for issued `PT`s we need to check the policy against the root `Authentication` object.
> always use the root TGT for checking the AuthenticationPolicy

- cas-server-support-token/src/main/java/org/jasig/cas/authentication/handler/support/TokenAuthenticationHandler.java
Closes #1555 
Fix Description:
- _getAuthenticator_ method calls correct _getRegisteredServiceJwtEncryptionSecret_ method to retrieve _encryptionSecret_ value.
- _getRegisteredServiceJwtSigningSecret_ method uses correct constant value _TokenConstants.PROPERTY_NAME_TOKEN_SECRET_SIGNING_.
Tested using generated war including these modifications wrapped with cas-overlay on apache-tomee-jaxrs-1.7.3. Using a JWT generated with JwtGenerator. Login request result: AUTHENTICATION_SUCCESS.
> Let TokenAuthenticationHandler pick the correct signing secret. 

- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/AbstractTicketRegistry.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/DefaultTicketRegistry.java
- cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java
- cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
so it can be supported by all registries when/if needed. 
This partially handles #1254 . There have also been a number of reports, particularly be Ehcache (and some for Hazelcast) where expired entries are not immediately removed from the cache. Also, in certain cases if the eviction policy of the cache is different from the ticket expiration policy of CAS, where the latter is quicker to expire elements, we'd want entries in the cache gone as soon as possible and not rely on the cache policy to consume and allocate memory for what would effectively be dead objects for CAS. 
This cleaning behavior is on by default, but for certain registries that do not need it, can be disabled.
> Move ticket cleaner process up the chain

- build.gradle
- cas-server-documentation/installation/Maven-Overlay-Installation.md
- cas-server-webapp/src/main/webapp/WEB-INF/deployerConfigContext.xml
- cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/applicationContext.groovy
- cas-server-webapp/src/main/webapp/WEB-INF/web.xml
Closes #1130 
The following changes are packed in this patch:
1. Add the `lang` namespace to the deployer file so that dynamic refreshable beans via Groovy can be defined via `lang:groovy`
2. Allow `.groovy` files to be loaded as part of the Spring web application context.
> Allow CAS configuration to be defined via Groovy

- cas-server-core-util/src/main/java/org/jasig/cas/util/SerializationUtils.java
- cas-server-support-saml-idp/src/main/java/org/jasig/cas/support/saml/SamlIdPUtils.java
- cas-server-support-saml-idp/src/main/java/org/jasig/cas/support/saml/web/idp/profile/AbstractSamlProfileHandlerController.java
- cas-server-support-saml-idp/src/main/java/org/jasig/cas/support/saml/web/idp/profile/SSOPostProfileCallbackHandlerController.java
- cas-server-support-saml-idp/src/main/java/org/jasig/cas/support/saml/web/idp/profile/SSOPostProfileHandlerController.java
Closes https://github.com/Jasig/cas/issues/1570
Removes the need to store the authn request into the websession. Instead, passes it back to the CAS login endpoint, and picks it up on the return again, as an encoded parameter, as if the parameter was originally sent to the login endpoint to begin with.
> Remove session sharing requirement from saml idp impl

- cas-management-webapp-support/src/main/java/org/jasig/cas/config/CasManagementWebAppConfiguration.java
- cas-server-webapp-config/src/main/java/org/jasig/cas/config/CasApplicationContextConfiguration.java
- cas-server-webapp-config/src/main/java/org/jasig/cas/config/CasAuditTrailConfiguration.java
- cas-server-webapp-config/src/main/java/org/jasig/cas/config/CasFiltersConfiguration.java
- cas-server-webapp-config/src/main/java/org/jasig/cas/config/CasProtocolViewsConfiguration.java
- cas-server-webapp-config/src/main/java/org/jasig/cas/config/CasSecurityContextConfiguration.java
- cas-server-webapp-config/src/main/java/org/jasig/cas/config/CasWebAppConfiguration.java
- cas-server-webapp-config/src/main/java/org/jasig/cas/config/CasWebflowContextConfiguration.java
- cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml
- cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/applicationContext.xml
Follow up to the previous PR, this patch does the following:
1. Opts for lazy evaluation of the application context for webapp and management webapp
2. Moves a number of other beans defined in cas-servlet over to @Configuration class.
3. Moves remaining beans defined in cas-servlet.xml over to the applicationContext, so the root parent has access to all beans which may be required by modules. 
4. The cas-servlet.xml serves as an empty placeholder for config changes, if/when needed. 
Given the circular dependency injection of the following beans, they continue to live in the XML context, where Spring is able to "take care of references":
```xml
<bean name="loginFlowExecutor" class="org.springframework.webflow.executor.FlowExecutorImpl"
c:definitionLocator-ref="loginFlowRegistry" …
```
> Adjustments to @Configuration of DispatcherServlet context

- cas-management-webapp/src/main/resources/messages.properties
- cas-management-webapp/src/main/webapp/WEB-INF/view/jsp/includes/header.jsp
- cas-management-webapp/src/main/webapp/WEB-INF/view/jsp/includes/services.jsp
- cas-management-webapp/src/main/webapp/js/app/app-angular.js
- cas-server-core-services/src/main/java/org/jasig/cas/services/AbstractRegisteredService.java
- cas-server-core-services/src/test/java/org/jasig/cas/services/DefaultServicesManagerImplTests.java
Closes #1581 
This adds a duplicate button to the CAS management UI. This allows quick configuration of a new service off of a pre-existing service.
I had to update `AbstractRegisteredService` because the `TreeSet` used in `DefaultServicesManagerImpl` eliminates any services that compare as equal (same eval order, name, & serviceId).
This corner case in a properly configured CAS server should never exist, but the duplicate service functionality exposed the corner case when those values aren't updated in the new duplicate service definition. This led to the new duplicate service not appearing on the admin UI.
> Duplicate RegisteredService

- cas-server-core-api-ticket/src/main/java/org/jasig/cas/ticket/registry/TicketRegistry.java
- cas-server-core-api/src/main/java/org/jasig/cas/CentralAuthenticationService.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/AbstractTicketDelegator.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/AbstractTicketRegistry.java
- cas-server-core-tickets/src/test/java/org/jasig/cas/MockOnlyOneTicketRegistry.java
- cas-server-core/src/main/java/org/jasig/cas/AbstractCentralAuthenticationService.java
I ran into an issue where this code
```
centralAuthenticationService.getTicket(tgtId, TicketGrantingTicket.class).getAuthentication();
```
didn't work without an explicit cast that should have been unnecessary.
This addresses that issue by being able to pick up the return ticket class from the provided class parameter.
> Fix generics on `TicketRegistry.getTicket()` and `CentralAuthenticationService.getTicket()`

- cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/securityContext.xml
It used to match "127.0..1" instead.
> Use the correct localhost pattern

- cas-server-webapp-actions/src/main/java/org/jasig/cas/web/flow/CasDefaultFlowUrlHandler.java
- cas-server-webapp-actions/src/test/java/org/jasig/cas/web/flow/AllTestsSuite.java
- cas-server-webapp-actions/src/test/java/org/jasig/cas/web/flow/CasDefaultFlowUrlHandlerTests.java
Closes #1593 for the 4.2.x branch (java 7). This is essentially a backport of #1597 which I created earlier using Java 8, before I realised that 4.2.x was still on Java 7.
> Fix query string parameters in webflow redirect

- cas-server-documentation/installation/JPA-Ticket-Registry.md
- cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
The abstractJpaEntityManagerFactory bean in jpaTicketRegistryContext.xml expects these options to be:
ticketreg.database.dialect
ticketreg.database.batchSize
> Correctly name ticketreg.database hibernate options

- cas-server-core-services/src/main/java/org/jasig/cas/services/AbstractRegisteredService.java
Closes #1652. Simply rename the table slightly to avoid the identifier being too long. Since
we rely on Hibernate to create/update our database objects, there isn't a good way to migrate
existing tables. However, since there already isn't a good way to migrate any existing data,
this doesn't seem like a big deal.
> Closes #1652: "RegisteredServiceImpl_Properties" is too long for Oracle.

- cas-server-documentation/installation/JPA-Ticket-Registry.md
The default value of 'create-drop' is probably not desirable for use in production, so provide a note in the documentation for other option values that can be used.
Includes the information referenced in #1647
> Add note about ticketreg.database.ddl.auto options to doco

- cas-server-core-tickets/src/main/java/org/jasig/cas/util/DefaultUniqueTicketIdGenerator.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/util/HostNameBasedUniqueTicketIdGenerator.java
- cas-server-core-tickets/src/test/java/org/jasig/cas/util/HostNameBasedUniqueTicketIdGeneratorTests.java
- cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
In order to reduce the noise in `cas.properties` in clustered deployments, allow `host.name` to be calculated automatically, if left undefined.
> Allow host.name to be auto-detected if left undefined

- cas-server-support-ldap/src/main/java/org/jasig/cas/authentication/LdapAuthenticationHandler.java
When the principal id attribute is not found for LDAP authentication, log an explicit error.  Presently, errors as such are marked under DEBUG to reduce log noise.
> Log under ERROR when principal id attribute is not found during LDAP AuthN

- cas-server-core-api-ticket/src/main/java/org/jasig/cas/ticket/Ticket.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/AbstractTicket.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/AbstractTicketDelegator.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/DefaultTicketRegistry.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/encrypt/EncodedTicket.java
- cas-server-core-tickets/src/test/java/org/jasig/cas/mock/MockServiceTicket.java
- cas-server-core-tickets/src/test/java/org/jasig/cas/mock/MockTicketGrantingTicket.java
- cas-server-integration-hazelcast/build.gradle
- cas-server-integration-hazelcast/src/main/java/org/jasig/cas/ticket/registry/HazelcastTicketRegistry.java
- cas-server-integration-hazelcast/src/test/java/org/jasig/cas/ticket/registry/HazelcastTicketRegistryTests.java
- cas-server-integration-hazelcast/src/test/resources/HazelcastTicketRegistryTests-context.xml
- cas-server-integration-memcached/build.gradle
- cas-server-integration-memcached/src/test/java/org/jasig/cas/ticket/registry/support/kryo/KryoTranscoderTests.java
- cas-server-webapp-validation/src/main/java/org/jasig/cas/web/view/Cas30JsonResponseView.java
- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/monitoring/viewSsoSessions.jsp
- gradle.properties
Allow Hazelcast ticket registry to support session/service ticket count operations. 
Also fixed an issue with the sso sessions report where ops could not be completed due to missing CSRF settings.
this will be selectively ported forward to master.
> Let hazelcast handle session and service ticket counts

- cas-server-documentation/installation/User-Interface-Customization.md
- cas-server-documentation/installation/Webflow-Customization.md
- cas-server-webapp-themes/src/main/java/org/jasig/cas/services/web/RegisteredServiceThemeBasedViewResolver.java
- cas-server-webapp-themes/src/test/java/org/jasig/cas/services/web/RegisteredServiceThemeBasedViewResolverTests.java
- cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml
- cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/webflowContext.xml
This patch allows the deployer to automatically create theme-specific views without having to configure the actual resolver configuration. By default, CAS native views are used. If a theme is found with views that exist, those are rendered instead. 
Once the views are selected and rendered, the `theme` parameter may also be used to decorate settings by CSS, etc.
> Let RegisteredServiceThemeBasedViewResolver be default

- cas-server-core-api-ticket/src/main/java/org/jasig/cas/ticket/TicketGrantingTicket.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/TicketGrantingTicketDelegator.java
- cas-server-core/src/main/java/org/jasig/cas/CentralAuthenticationServiceImpl.java
Closes #1714
Keeps a single authN instance in history.
> Deprecate Supplemental Authentications

- cas-server-core-services/src/main/java/org/jasig/cas/services/PrincipalAttributeRegisteredServiceUsernameProvider.java
Closes #1738 
Today, if a username attribute is selected for a service definition in CAS, that attribute must also be authorized via the service attribute policy, such that goes through the attribute repository to retrieve, cache and update the value and then return it. If the attribute is not authorized, the service is not able to use it even though it may already be available as a simple principal attribute. 
This pull allows CAS to fallback and selects the username attribute value from the collection of principal attributes as they are. The attribute repository is tried first and if the attribute is not authorized for release, the fallback scenario is activated and a log message is generated.
> Allow the service username attribute to be retrieved as a principal attribute

- cas-server-core-authentication/src/main/java/org/apereo/cas/authentication/principal/DefaultPrincipalAttributesRepository.java
- cas-server-core-authentication/src/main/java/org/apereo/cas/authentication/principal/cache/AbstractPrincipalAttributesRepository.java
- cas-server-core-authentication/src/main/java/org/apereo/cas/authentication/principal/cache/CachingPrincipalAttributesRepository.java
This should be backported to 4.2.x. Fixes the NPE issue with serialization-based ops.
> Use static loggers for the principal repositories

- build.gradle
- cas-server-support-gauth/src/main/java/org/apereo/cas/adaptors/gauth/GoogleAuthenticatorInstance.java
- gradle.properties
Upgrading a number of CAS dependencies prior to the M1 release. Leaving out Thymeleaf v3 for now.
> Dependency upgrades prior to M1

- cas-server-webapp-support/src/main/java/org/jasig/cas/web/support/CookieRetrievingCookieGenerator.java
- cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/warnCookieGenerator.xml
4.1.x
Current `CookieRetrievingCookieGenerator` does not set `HttpOnly` flag when `RememberMe` is true.
Move the `HttpOnly` container check from the constructor to `addCookie()` where setting `HttpOnly` flag is added.
```
if (isCookieHttpOnly()) {
final Method setHttpOnlyMethod = ReflectionUtils.findMethod(Cookie.class, "setHttpOnly", boolean.class);
if(setHttpOnlyMethod != null) {
cookie.setHttpOnly(true);
} else {
logger.debug("Cookie cannot be marked as HttpOnly; container is not using servlet 3.0.");
}
}
```
Need to explicitly set `cookieHttpOnly=true` in `warnCookieGenerator.xml` for `CASPRIVACY`.
No active related issue or open PR found.
- `HttpOnly` in [CookieGenerator](https://github.com/spring-projects/spring-framework/blob/v4.1.6.RELEASE/spring-web/src/main/java/org/springframewo …
> [Fix][4.1.x] Add HttpOnly support CookieRetrievingCookieGenerator

- cas-server-webapp/build.gradle
- cas-server-webapp/gulpfile.js
- cas-server-webapp/package.json
- gradle/node.gradle
- gradle/tasks.gradle
This patch cleans up the build to allow SASS-generated CSS files to be included into the final CAS web artifact without cluttering the actual project directory.
> CSS generation via Node/SASS cleanup

- cas-server-webapp-cookie/src/main/java/org/jasig/cas/web/support/CookieRetrievingCookieGenerator.java
- cas-server-webapp/src/main/webapp/WEB-INF/web.xml
4.2.x
Add `HttpOnly` flag to JSESSIONID:
```
<cookie-config>
<http-only>true</http-only>
</cookie-config>
```
This does not affect the `Secure` flag. For our CAS, it will be `true` for production (https) and `false` for development (http). We guess that the jetty server internally configure the `Secure` flag.
Version 4.1.x: https://github.com/apereo/cas/pull/1796
> [fix][4.2.x] Add HttpOnly flag for JSESSIONID

- build.gradle
Without this change, build took about 3 minutes to complete. With the change, 1 minute 10 seconds. The idea here is to only update the jar manifest if the module jar was actually changed and compiled.
We probably have to do the same sort of trick to the war artifacts; I'll track that separately.
> Only update jar manifest if jar was compiled/changed

- cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/SamlProfileSamlAssertionBuilder.java
- cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/SamlProfileSamlResponseBuilder.java
Closes #1827 
I put "_" in front of ID. Because IDs starts with a number are invalid.
With this modification messages have successful validation on Weblogic 12c client of CAS Server SAML2 Provider
> SAML Response is invalid message #1827

- cas-server-support-ldap-core/src/main/java/org/jasig/cas/authentication/support/DefaultAccountStateHandler.java
Closes #1844
When used with OpenLDAP, an AccountPasswordMustChangeException should be throw instead of CredentialExpiredException if pwdReset attribute is set to TRUE
> Throw AccountPasswordMustChangeException if pwdReset attribute is set to TRU

- cas-server-documentation/installation/JSON-Service-Management.md
- cas-server-webapp/build.gradle
- cas-server-webapp/src/main/resources/log4j2.xml
- cas-server-webapp/src/main/webapp/WEB-INF/spring-configuration/filters.xml
- gradle.properties
Closes https://github.com/apereo/cas/issues/1848
Upgrades the security filter to ensure errors logged and produced by the filter are routed back to the CAS logging configuration and controlled in one spot.
> updated security filter to 2.0.6 to fix issue with double logging

- cas-server-core-authentication/src/main/java/org/jasig/cas/web/flow/AuthenticationExceptionHandler.java
- gradle.properties
Reorder the list of handled authentication exceptions such that account-policy errors are processed and handled first prior to CAS moving onto more generic errors. See the comments in the patch for more info please.
> Reorder account policy exception handling

- cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/PolicyBasedAuthenticationManager.java
- cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/principal/PersonDirectoryPrincipalResolver.java
- cas-server-documentation/integration/ADFS-Integration.md
- cas-server-support-wsfederation/build.gradle
- cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/WsFederationConfiguration.java
- cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/WsFederationHelper.java
- cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/authentication/principal/WsFederationCredentialsToPrincipalResolver.java
- cas-server-support-wsfederation/src/main/java/org/jasig/cas/support/wsfederation/web/flow/WsFederationAction.java
- cas-server-support-wsfederation/src/test/java/org/jasig/cas/support/wsfederation/WsFederationHelperTests.java
- cas-server-webapp/src/main/webapp/WEB-INF/cas.properties
- checkstyle-rules.xml
Closes #1887 
CAS is able to automatically decrypt SAML assertions that are issued by ADFS. To do this, 
you will first need to generate a private/public keypair:
```bash
openssl genrsa -out private.key 1024
openssl rsa -pubout -in private.key -out public.key -inform PEM -outform DER
openssl pkcs8 -topk8 -inform PER -outform DER -nocrypt -in private.key -out private.p8
openssl req -new -x509 -key private.key -out x509.pem -days 365
openssl x509 -outform der -in x509.pem -out certificate.crt
```
Configure CAS to reference the keypair, and configure the relying party trust settings
in ADFS use the `certificate.crt` file for encryption.
> WS-FED: Support encrypted assertions

- cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
- cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/OAuth20AccessTokenControllerTests.java
- cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/OAuth20ProfileControllerTests.java
OAuth tokens can't be deserialize, because all of these tokens' ExpirationPolicy has been wrapped by spring with CGILib.
I suggests we should avoid by defining spring bean to create any persisted entity.
> Fix oauth token deserialize issue

- cas-server-documentation/installation/JPA-Service-Management.md
This changes the JPA Service Registry documentation by renaming 2 configuration properties (`dialect` and `batchSize`) to match [jpa-svc-reg-context.xml](https://github.com/apereo/cas/blob/4.2.x/cas-server-support-jpa-service-registry/src/main/resources/META-INF/spring/jpa-svc-reg-context.xml). Without this change, setting the properties suggested by the documentaion will result in you not being able to change `dialect` or `batchSize` from the default.
I have signed the ICLA.
> corrected dialect and batchSize property names

- cas-server-support-jpa-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/JpaTicketRegistry.java
CAS Server: 5.0.0.RC1 SNAPSHOT
DefaultTicketCleaner can't clean expired OAuthTokens, when using JpaTicketRegistry as default tickets registry.
Caused by: The implement of getTickets in JpaTicketRegistry never loads OAuthTokens.
> Fix TicketCleaner can't clean expired OAuthTokens

- cas-server-core-authentication/src/main/java/org/apereo/cas/config/CasPersonDirectoryAttributeRepositoryConfiguration.java
Closes -- Issue not submitted --
> Calling @PostConstruct method of LdaptivePersonAttributeDao manually

- cas-server-core-authentication/src/main/java/org/apereo/cas/services/ReturnAllowedAttributeReleasePolicy.java
- cas-server-core-authentication/src/main/java/org/apereo/cas/services/ReturnMappedAttributeReleasePolicy.java
- cas-server-core-authentication/src/test/java/org/apereo/cas/services/RegisteredServiceAttributeReleasePolicyTests.java
Presently, when attributes are calculated for release the comparison between what is allowed in the policy and what is available as a principal attribute is case sensitive. For instance, you may have an attribute defined as `givenName` that becomes `givenname` retrieved from LDAP as it may ignore case. You are then today forced to make sure your release policy for the service also matches `givenname`. This is difficult to troubleshoot as it may not be immediately obvious why attributes are not released. 
This patch makes sure the comparison rules for attribute release are done in a case insensitive manner. 
Example with `ReturnAllowedAttributeReleasePolicy`:
- Define `givenName`
- Retrieved as `givenname`
- May be released as `givenName` (as it was defined)
Example with …
> Ignore case when comparing attributes for release

- cas-server-core-api-ticket/src/main/java/org/jasig/cas/ticket/TicketGrantingTicket.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/ServiceTicketImpl.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/TicketGrantingTicketImpl.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/AbstractTicketRegistry.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/DefaultTicketRegistry.java
- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/TicketGrantingTicketDelegator.java
- cas-server-core-tickets/src/test/java/org/jasig/cas/mock/MockServiceTicket.java
- cas-server-core-tickets/src/test/java/org/jasig/cas/mock/MockTicketGrantingTicket.java
- cas-server-core-tickets/src/test/java/org/jasig/cas/ticket/registry/DistributedTicketRegistryTests.java
- cas-server-extension-clearpass/src/main/java/org/jasig/cas/extension/clearpass/TicketRegistryDecorator.java
- cas-server-integration-ehcache/src/main/java/org/jasig/cas/ticket/registry/EhCacheTicketRegistry.java
- cas-server-integration-ehcache/src/test/java/org/jasig/cas/ticket/registry/EhCacheTicketRegistryTests.java
- cas-server-integration-hazelcast/src/main/java/org/jasig/cas/ticket/registry/HazelcastTicketRegistry.java
- cas-server-integration-hazelcast/src/test/java/org/jasig/cas/ticket/registry/HazelcastTicketRegistryTests.java
- cas-server-integration-ignite/src/main/java/org/jasig/cas/ticket/registry/IgniteTicketRegistry.java
- cas-server-integration-ignite/src/test/java/org/jasig/cas/ticket/registry/IgniteTicketRegistryTests.java
- cas-server-integration-infinispan/src/main/java/org/jasig/cas/ticket/registry/InfinispanTicketRegistry.java
- cas-server-integration-infinispan/src/test/java/org/jasig/cas/ticket/registry/InfinispanTicketRegistryTests.java
- cas-server-integration-memcached/src/main/java/org/jasig/cas/ticket/registry/MemCacheTicketRegistry.java
- cas-server-integration-memcached/src/test/java/org/jasig/cas/ticket/registry/MemCacheTicketRegistryTests.java
- cas-server-support-couchbase-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/CouchbaseTicketRegistry.java
- cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java
Closes #1869 
- Back-ported CAS 5.0 TicketRegistry changes into 4.2.5 to fix issue with Proxy Granting Tickets not being deleted with the Ticket Granting Ticket is destroyed.
- Unit tests are included in the build. Check each TicketRegistry's test that has a new unit test: verifyDeleteTicketWithPGT(). No unit tests for Couchbase though as that will be coming later on.
- No known possible limitations or side effects.
> Fix for Issue #1869 Destroying the TGT Does Not Remove the PGT

- cas-management-webapp/src/main/resources/bootstrap.properties
- cas-server-support-validation/src/main/java/org/apereo/cas/web/config/CasValidationConfiguration.java
- cas-server-webapp/src/main/resources/bootstrap.properties
Closes #1966 and #1963 
- Brief description of changes applied: Set the ProxyValidateController's `validationSpecification `field (on line 198) to `cas20ProtocolValidationSpecification` instead of `this.cas20WithoutProxyProtocolValidationSpecification`.
- Any documentation on how to configure, test: Run [MultiLevelProxySpec.groovy](https://github.com/wcrowell/cas-functional-tests/blob/master/src/test/groovy/org/jasig/cas/test/validation/MultiLevelProxySpec.groovy) to validate.
- Any possible limitations, side effects, etc: None/Unknown
- Reference any other pull requests that might be related: Includes a fix for #1963 where the Travis build failed for some unknown issue.
> Fix Proxy Tickets Issue Where After Being Issued They Are Already Used/Expired Immediately

- cas-server-core/src/main/java/org/apereo/cas/CentralAuthenticationServiceImpl.java
Although the current service ticket is one active, but if there can be used multiple times Ticket should record usage.
This is useful when the user's own custom Ticket
> record not expired ticket usage。

- cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/AbstractTicketRegistry.java
- cas-server-core-tickets/src/test/java/org/jasig/cas/MockOnlyOneTicketRegistry.java
- cas-server-core-tickets/src/test/java/org/jasig/cas/ticket/registry/DistributedTicketRegistryTests.java
- cas-server-integration-ehcache/src/test/java/org/jasig/cas/ticket/registry/EhCacheTicketRegistryTests.java
- cas-server-integration-infinispan/src/test/java/org/jasig/cas/ticket/registry/InfinispanTicketRegistryTests.java
Closes #1969
- Reported deleted ticket counts may not include PGTs in the final cumulative count. This would not affect TGTs and STs.
- Test cases have been updated to add PGTs to the registry after they are created. The counts are checked to make sure of accuracy.
- Related pull request: #1978
> Deleted ticket counts should include PGTs in the final cumulative count

- gradle.properties
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/DefaultOAuthCasClientRedirectActionBuilder.java
- support/cas-server-support-pac4j-authentication/src/main/java/org/apereo/cas/integration/pac4j/authentication/handler/support/UsernamePasswordWrapperAuthenticationHandler.java
- support/cas-server-support-stormpath/src/main/java/org/apereo/cas/authentication/StormpathAuthenticationHandler.java
- support/cas-server-support-stormpath/src/main/java/org/apereo/cas/config/StormpathAuthenticationConfiguration.java
The CAS server widely uses pac4j and some changes in 1.9.2 are breaking ones for CAS. So it's better to upgrade to this version and be more cautious for 1.9.3, 1.9.4...
> Update to pac4j v1.9.2 and spring-webmvc v1.1.2

- support/cas-server-support-actions/src/main/java/org/apereo/cas/web/config/CasSupportActionsConfiguration.java
Closes #2011
Pass the servicesManager as an argument while creating the GatewayServicesManagementCheck.
> Adds missing argument in the constructor

- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/protocol/openid/casOpenIdAssociationFailureView.jsp
- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/protocol/openid/casOpenIdAssociationSuccessView.jsp
- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/protocol/openid/casOpenIdServiceFailureView.jsp
- cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/protocol/openid/casOpenIdServiceSuccessView.jsp
As mentioned in PR #2007, this change removes remaining unbalanced comment-close JSP tags.
> Remove unbalanced comment-close JSP tags

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
Seems like a typo, which will throw `No qualifying bean of type 'org.apereo.cas.validation.AuthenticationRequestServiceSelectionStrategy' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=oauth20AuthenticationRequestServiceSelectionStrategy)}` without context xml, which is used in tests-
> Fix typo in CasOAuthConfiguration.java

- core/cas-server-core-tickets/src/main/java/org/apereo/cas/ticket/support/TimeoutExpirationPolicy.java
I didn't open an issue but this is an issue I encountered debugging TGT expiration. 
This timeout expiration policy is never expiring the TGT.  It wasn't looking at the ticket state last time used when trying to determine if the ticket expired.
I didn't update the test but if you look at the test it use a negative time to kill which is why either of these version passes.  Negative time to kill is in my opinion an unrealistic use case and might be a good idea to validate that constraint during the construction of TimeoutExpirationPolicy.
> TimeoutExpirationPolicy must consider TicketState's lastTimeUsed()

- cas-server-integration-ehcache/src/main/resources/META-INF/spring/ehcache-ticket-registry.xml
Closes #2144
When using EhCache as Ticket Registry, ticketGrantingTicketsCache doesn't inherit from abstractTicketCache and the properties such as persitence, eviction policy, max elements hold in memory, etc, are not applied to TGT, resulting on heavy ticketing load server to SSO lifetime issue.
> ticketGrantingTicketsCache inherits from abstractTicketCache

- core/cas-server-core-authentication/src/main/java/org/apereo/cas/services/ReturnMappedAttributeReleasePolicy.java
- core/cas-server-core-services/src/main/java/org/apereo/cas/services/DefaultRegisteredServiceAccessStrategy.java
- core/cas-server-core-services/src/main/java/org/apereo/cas/services/RegexRegisteredService.java
- core/cas-server-core-services/src/test/java/org/apereo/cas/services/AbstractRegisteredServiceTests.java
- core/cas-server-core-util/src/main/java/org/apereo/cas/util/RegexUtils.java
- core/cas-server-core-util/src/test/java/org/apereo/cas/util/RegexUtilsTest.java
- core/cas-server-core-util/src/test/java/org/apereo/cas/util/RegexUtilsTests.java
This PR doesn't close any issue, it's just an improvement
- Return a pattern that matches nothing instead of an empty optional, so the rest of checks are not needed (null/present, blank serviceId, ...)
- Remove useless code, as it was just checking for null. Method maintained for future additions
> Rework how service pattern matching is conditionally handled

- cas-server-webapp-throttle/src/main/java/org/jasig/cas/web/support/AbstractThrottledSubmissionHandlerInterceptorAdapter.java
- cas-server-webapp/src/main/webapp/WEB-INF/webflow/login/login-webflow.xml
Closes #2149
The result of the password submission is stored in the flowScope to be reused in the throttle submission handler.
> Incorrect password submission is not detected via throttling

- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/AbstractSamlProfileHandlerController.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/SSOPostProfileCallbackHandlerController.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/SamlProfileSamlResponseBuilder.java
> Handle RelayState Parameter in SAML correctly

- support/cas-server-support-rest-authentication/src/main/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandler.java
Changes:
- Don't call .value() method when comparing HttpStatus as they are enums
> Do not call .value() method when comparing HttpStatus as they are enums

- support/cas-server-support-x509/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/X509CertificateCredential.java
Changes:
- Use Java method for copying arrays instead of the Guava one
> Use Java method to copy array

- support/cas-server-support-gauth/src/main/java/org/apereo/cas/adaptors/gauth/web/flow/rest/GoogleAuthenticatorQRGeneratorController.java
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/OAuth20AuthorizeController.java
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/OAuth20ProfileController.java
- support/cas-server-support-reports/src/main/java/org/apereo/cas/web/report/DashboardController.java
Closes #2189 
Changes:
- Replace ```@RequestMapping``` with the equivalent GET/POST Spring annotation
Note that the remaining ```@RequestMapping``` are used at class scope and can not be replaced.
> Replace RequestMapping with the equivalent Spring annotation

- docs/cas-server-documentation/integration/Attribute-Resolution.md
Add missing "e" to the end of "Therefor" in first paragraph.
> Fix typo in Attribute-Resolution.md

- docs/cas-server-documentation/installation/Configuration-Management.md
After struggling with this for a few days, I discovered that the spring cloud config server only loads \<application-name\>.properties files or application.properties files when using the native profile. The CAS documentation mentioned that it would load all *.properties or *.yml files in that config directory and that the names didn't matter.
This pull request is to correct that documentation and include information on how to use multiple properties file if you desire. 
Suggestions are welcome as I am not sure the method I mentioned is the best. 
On another note, is it possible to have CAS to load all properties file in a directory? Or is this a limitation of the config server?
> Updated Documentation to match Spring Cloud Native profile behavior

- support/cas-server-support-trusted-mfa-jdbc/src/main/java/org/apereo/cas/trusted/authentication/storage/JpaMultifactorAuthenticationTrustStorage.java
- support/cas-server-support-trusted-mfa-mongo/src/main/java/org/apereo/cas/trusted/authentication/storage/MongoDbMultifactorAuthenticationTrustStorage.java
- support/cas-server-support-trusted-mfa-rest/src/main/java/org/apereo/cas/trusted/authentication/storage/RestMultifactorAuthenticationTrustStorage.java
Part of #2212
replacing Guava in  modules:
- Cas-server-support-trusted-mfa-jdbc
- Cas-server-support-trusted-mfa-mongo
- Cas-server-support-trusted-mfa-rest
> Replacing Guava with java collections

- core/cas-server-core-authentication/src/main/java/org/apereo/cas/authentication/handler/support/AbstractUsernamePasswordAuthenticationHandler.java
Closes #2229 
Main change: Ensure that each authentication handler copies the incoming credential object, so that the original credentials aren't lost. Required for authenticating bcrypt passwords, and also prevents one authentication handler's encoder from mangling the password that the next handler needs to use.
Also including a small optimization to encode the password only once in the handler. Previous behaviour was to encode the password, check that the encoded form wasn't blank, and encode the original password again. Not a big deal for fast encoders but makes a big difference for slow ones like bcrypt.
> Fix JDBC authentication using encoded passwords

- docs/cas-server-documentation/installation/Ehcache-Ticket-Registry.md
Looks like original snippet was copied from one of 4.x branches, but there is no such module in CAS 5.0.x branch so I have corrected the doc to reflect current structure of CAS 5.0.x modules for Ehcache support.
> Correct Maven snippet in installation guide for Ehcache ticket registry support

- support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/authentication/support/DefaultAccountStateHandler.java
Issue #2249 
1. Updated support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/authentication/support/DefaultAccountStateHandler.java to map ActiveDirectoryAccountState.Error.ACCOUNT_EXPIRED to "new AccountExpiredException()".
> CAS-2249 Add mapping to handle Active Directory Account Expired Error

- webapp/cas-server-webapp/src/main/resources/messages_sk.properties
missing translations to Slovak (most of user area) are provided
messages in management area are intentionally left untranslated
> add user facing translations for 5.0.x version

- support/cas-server-support-radius/src/main/java/org/apereo/cas/config/RadiusConfiguration.java
Currently in 5.0.x there's no way to include cas-server-support-radius while leaving it disabled. If the properties aren't configured, this makes login hang indefinitely because the handler gets set up with a default address of localhost and 0 timeout (unless there just happens to be a RADIUS server listening there with the same secret).
Even if I specify cas.authn.radius.client.inetAddress= (no value), it eventually gets passed to a getAllByName method that interprets an empty value as a special case and returns a loopback address.
This change follows the pattern I see in several other handler configuration classes, where the handler isn't added to the handler map if some crucial value (here, the RADIUS server address) is blank.
I haven't changed the RadiusProperties class that sets the …
> Don't enable the RADIUS auth handler if it has no server address

- support/cas-server-support-rest-authentication/src/main/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandler.java
Resolves #2362
Populate CAS Principal Attributes with ones received over REST auth.
> Fix REST Authentication discards Principal attributes #2362

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/radius/RadiusProperties.java
- support/cas-server-support-radius/src/main/java/org/apereo/cas/config/RadiusConfiguration.java
Port of #2336 from 5.0.x into master.
- cas.authn.radius.client.inetAddress is now unset by default instead of trying to authenticate against localhost
- If CAS was built with RADIUS support but inetAddress isn't set, skip enabling the handler and warn:
`WARN [org.apereo.cas.config.RadiusConfiguration] - <No RADIUS address is defined. RADIUS support will be disabled.>`
> Disable RADIUS auth handler unless server address is defined

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- gradle.properties
- support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/Pac4jConfiguration.java
- webapp/cas-server-webapp/src/main/resources/templates/fragments/loginProviders.html
Closes #2101 
**Description**
add LinkedIn support for CAS 5.0.x.
**Configuration**
To enable, add following config to application.properites
`cas.authn.pac4j.linkedIn.id=`
`cas.authn.pac4j.linkedIn.secret=`
`cas.authn.pac4j.linkedIn.fields=`
`cas.authn.pac4j.linkedIn.scope=`
> Add LinkedIn delegated authN support for CAS 5.0.x

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java
> Correct ldap urls parsing

- cas-server-documentation/installation/MongoDb-Authentication.md
Additional info how to add sha512 password encoder from pac4j to mongoAuthenticationHandler.
> information how to enable sha512 password encoder

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java
Ldap connections are not working properly. The authenticator takes the same  pool for each operation: Bind,Search etc. This is not correct because Search (for dn) often uses a different username (with super permissions) to Bind. If you have one connection, first you Bind by special user in order to Search, then you try to Bind another (target) user in the same connection. This may be very dangerous
> New connection pool for every operation

- docs/cas-server-documentation/installation/Webflow-Customization-AUP.md
The dependency names in the documentation are wrong, this fixes it.
> Fix acceptable use dependency names in docs

- webapp/cas-server-webapp/src/main/resources/templates/casAcceptableUsagePolicyView.html
${flowExecutionKey} wasn't being evaluated and was causing 500 error.
This should probably be merged to 5.0 branch too.
> Fix acceptable use template to use th:value

- webapp/cas-server-webapp-config-security/src/main/java/org/apereo/cas/config/CasWebApplicationSecurityConfiguration.java
Fixes a typo in CasWebApplicationSecurityConfiguration
role || role -> role || group
> correct typo

- core/cas-server-core-tickets/src/main/java/org/apereo/cas/ticket/TicketGrantingTicketImpl.java
- core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/resolver/impl/InitialAuthenticationAttemptWebflowEventResolver.java
- core/cas-server-core/src/main/java/org/apereo/cas/AbstractCentralAuthenticationService.java
Closes no issue
Changes:
- Order collection when it's created so it's not needed to sort it on every method call.
- Remove blank lines
- Check for nulls during item insertion instead of doing it when we need to use the collection
> Source Code cleanup, null checks and collection ordering

- docs/cas-server-documentation/installation/Configuration-Management.md
Adding documentation explaining how to set Unicode properties so implementors know the difference between using .properties files (ISO-8859-1 encoding) and .yml files (UTF-8 encoding).
> Explaining how to use Unicode property values

- support/cas-server-support-actions-aup-ldap/src/main/java/org/apereo/cas/web/config/CasSupportActionsAcceptableUsagePolicyLdapConfiguration.java
- support/cas-server-support-actions-aup-ldap/src/main/java/org/apereo/cas/web/flow/LdapAcceptableUsagePolicyRepository.java
- support/cas-server-support-actions-aup-webflow/src/main/java/org/apereo/cas/web/config/CasSupportActionsAcceptableUsagePolicyConfiguration.java
- support/cas-server-support-actions-aup-webflow/src/main/java/org/apereo/cas/web/flow/AbstractPrincipalAttributeAcceptableUsagePolicyRepository.java
- support/cas-server-support-actions-aup-webflow/src/main/java/org/apereo/cas/web/flow/DefaultAcceptableUsagePolicyRepository.java
Closes #2442 
I haven't actually tested this yet, it's taking forever to run gradlew.bat install so I can test it in my overlay project. Is there a faster way to compile and get jars in local maven repo? Seems to spend lots of time doing compileKotlin but is there any kotlin code?
Let me know if you don't want the new constructors and I can just use the setter.
> Avoid NPE when using Acceptable Use Policy without repository

- core/cas-server-core-tickets/src/main/java/org/apereo/cas/ticket/TicketGrantingTicketImpl.java
- core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/TicketGrantingTicketImplTests.java
Closes #2445 
Changes:
- make TicketGrantingTicketImpl.getRoot method "recursive" and clearer
- add test to verify the correct root is returned
> make TicketGrantingTicketImpl.getRoot method "recursive" and clearer

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/ConnectionPoolingProperties.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
Closes https://github.com/apereo/cas/issues/2459
min idle count was being set to max idle time
This change stops using "jpaProperties.getPool().getMaxIdleTime()).intValue()". I don't know where to use that other than on  bean.setIdleTimeout(jpaProperties.getIdleTimeout()); which already has it's own property. I assume some of properties are broken out into the pool object since they are shared with LDAP pools? Which of the idle timeout properties would you like to use for JPA or should it look at both properties and use the larger (or smaller?) of the two?
I also removed a deprecated method and called the method that the deprecated method currently calls.
> set minimium idle count on datasource correctly

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/core/authentication/PersonDirPrincipalResolverProperties.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/x509/X509Properties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-x509/src/main/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SerialNumberPrincipalResolver.java
- support/cas-server-support-x509/src/main/java/org/apereo/cas/adaptors/x509/config/X509AuthenticationConfiguration.java
- support/cas-server-support-x509/src/test/java/org/apereo/cas/adaptors/x509/authentication/principal/X509SerialNumberPrincipalResolverTests.java
Closes #2469 
- [] X509SerialNumberPrincipalResolver extended to support HEX and other configurable radixes.
- [] cas.authn.x509.principal.radix=16
cas.authn.x509.principal.hexZeroPadding=true
- [] Character.MIN_RADIX <= radix <= Character.MAX_RADIX
- [] N/A.
> Principal Serial Number Radix feature

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/ldap/AbstractLdapAuthenticationProperties.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
Consolidates startup logic. Removes need for separate `SASL` authentication type option, folding it neatly into `AUTHENTICATED`
> consolidate search authenticator logic

- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/services/SamlIdPEntityIdAuthenticationServiceSelectionStrategy.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/flow/SamlIdPMetadataUIAction.java
- support/cas-server-support-ws-idp/src/main/java/org/apereo/cas/ws/idp/authentication/WSFederationAuthenticationServiceSelectionStrategy.java
Closes #2472
* `SamlIdPEntityIdAuthenticationServiceSelectionStrategy` and `WSFederationAuthenticationServiceSelectionStrategy`
don't support `null` services anymore
* make sure `RegisteredServiceAccessStrategyUtils.ensureServiceAccessIsAllowed()` is not called with `null` service in `SamlIdPMetadataUIAction`
> Handle missing service

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/config/CasCoreBootstrapStandaloneConfiguration.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/CasConfigurationJasyptDecryptor.java
Closes #2471
* make methods `decryptProperties` and `loadYamlProperties` use a typed map in `CasCoreBootstrapStandaloneConfiguration`
* handle map with objects in `CasConfigurationJasyptDecryptor#decrypt` and check for decryption only if the property value is of type `String`
> Fix type mismatch during YAML properties decrypting

- docs/cas-server-documentation/installation/Configuring-Multifactor-Authentication.md
If name is missing, when user accesses the page and service, page displays "the state 'null' of flow 'login' -- action execution attributes were 'map[[empty]]'"
> Name is missing

- support/cas-server-support-actions-aup-webflow/src/main/java/org/apereo/cas/web/flow/AcceptableUsagePolicyFormAction.java
- support/cas-server-support-actions-aup-webflow/src/main/java/org/apereo/cas/web/flow/AcceptableUsagePolicyWebflowConfigurer.java
Closes #2464
It turns out that acceptable use wasn't working at all in 5.1, as far as I could tell, just using the default repository (none). It didn't have to do with using it in combination with x509. If you needed to accept the flow was just sending you back to the login page. 
Should I be trying to share the "mustAccept" string constant across the two classes where it is used? I added a new transition for "mustAccept" but should I have just changed the default transition? 
I would still like to have the option of acceptable use popping-up when users are doing x509 authentication but I can open another issue for that since that is more of a new feature.
> Fix for acceptable use to handle case where user mustAccept

- support/cas-server-support-hazelcast-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/HazelcastTicketRegistry.java
Closes #2528 for master.
Tickets are stored with encrypted ticket ID as key, so we also need to encrypt the ticket id when deleting.
> Fix Hazelcast ticket deletion when ticket encryption is enabled

- support/cas-server-support-hazelcast-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/HazelcastTicketRegistry.java
Closes #2528 for 5.0.x
Tickets are stored with encrypted ticket ID as key, so we also need to encrypt the ticket id when deleting.
> Fix Hazelcast ticket deletion when ticket encryption is enabled for 5.0.x

- .gitignore
- core/cas-server-core-authentication/src/main/java/org/apereo/cas/config/CasPersonDirectoryConfiguration.java
- core/cas-server-core-configuration-cloud-jdbc/src/main/java/org/apereo/cas/config/JdbcCloudConfigBootstrapConfiguration.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/jpa/AbstractJpaProperties.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-audit-jdbc/src/main/java/org/apereo/cas/audit/config/CasSupportJdbcAuditConfiguration.java
- support/cas-server-support-events-jpa/src/main/java/org/apereo/cas/config/JpaEventsConfiguration.java
- support/cas-server-support-gauth-jpa/src/main/java/org/apereo/cas/config/GoogleAuthenticatorJpaConfiguration.java
- support/cas-server-support-jdbc-monitor/src/main/java/org/apereo/cas/monitor/config/CasJdbcMonitorConfiguration.java
- support/cas-server-support-jdbc/src/main/java/org/apereo/cas/adaptors/jdbc/config/CasJdbcAuthenticationConfiguration.java
- support/cas-server-support-jpa-service-registry/src/main/java/org/apereo/cas/config/JpaServiceRegistryConfiguration.java
- support/cas-server-support-jpa-ticket-registry/src/main/java/org/apereo/cas/config/JpaTicketRegistryConfiguration.java
- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/config/PasswordManagementConfiguration.java
- support/cas-server-support-throttle-jdbc/src/main/java/org/apereo/cas/web/support/config/CasJdbcThrottlingConfiguration.java
- support/cas-server-support-trusted-mfa-jdbc/src/main/java/org/apereo/cas/trusted/config/JdbcMultifactorAuthnTrustConfiguration.java
- webapp/cas-server-webapp-config-security/src/main/java/org/apereo/cas/web/security/CasJdbcUserDetailsManagerConfigurer.java
This isn't ready to merge yet because I haven't tested it (at all) or updated the documentation. I just wanted to see if you thought it was worthwhile before I spent any time on it. 
I am planning to deploy CAS to a set of Tomcat servers that store datasources outside the applications and I think it would be nice if the configuration for CAS's datasource was in the same place as all the other applications' datasource configs. 
This would add "dataSourceName" to all JPA modules and if it was set, then it would be used to lookup a datasource via resource reference or jndi name instead of using the hickari datasource. If dataSourceName was set but lookup failed then it would fall back hickari. Not sure if that behavior makes sense or not, but I can see running with hickari when testing …
> Support container provided datasource lookup for all JPA sources

- docs/cas-server-documentation/installation/Configuration-Properties.md
The links to the anchor weren't working, probably because they are in a formatted code block.
> Documentation fix, remove links to anchors that aren't working

- support/cas-server-support-hazelcast-ticket-registry/src/main/java/org/apereo/cas/config/HazelcastInstanceConfiguration.java
Remove `@RefreshScope` anotation from `org.apereo.cas.config.HazelcastInstanceConfiguration.hazelcastTicketRegistry` to avoid issues on configuration reload.
Closes #2539
> Disable HazelcastTicketRegistry configuration reload

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/jpa/AbstractJpaProperties.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/DataSourceProxy.java
- docs/cas-server-documentation/installation/Configuration-Properties-Common.md
- docs/cas-server-documentation/installation/Configuration-Properties.md
Closes #2549
By proxying the datasource with a class loaded by the app classloader, it resolves some classloading issues, but now by default it won't proxy the datasource. Tomcat currently requires the proxy option to be turned on. 
This may be tricking Hikari into thinking it is delegating to an existing Hikari datasource but it is really a non-Hikari datasource. Might be better to just add a small datasource proxy class rather than using Hikari in a way it probably doesn't intend for people to use it. Since I am creating the datasource with a HikariConfig object, the HikariDataSource sets a fastPathPool instance variable and when getConnection is called it just delegates to that (the non-hikari container datasource). 
I didn't document this yet, but it adds one new configuration …
> Closes #2549 Allow container datasource to be used directly or proxied

- support/cas-server-support-openid/src/main/java/org/apereo/cas/support/openid/web/mvc/YadisController.java
As noted in #2570, OpenID 2.0 specification states that yadis.xml should have MIME type application/xrds+xml
> OpenID yadis.xml should have MIME type application/xrds+xml

- webapp-mgmt/cas-management-webapp-support/src/main/java/org/apereo/cas/mgmt/services/web/RegisteredServiceSimpleFormController.java
This is in response to issue [2572](https://github.com/apereo/cas/issues/2572). 
Drops the deletion statement in the mgmt webapp controller as in this former [pull request](https://github.com/apereo/cas/pull/1264). I checked back couchbase, dynamo and mongo and believe that mongodb should be the only one expecting a deleted service when saving. This might require some extra work. There are no test cases for the collaboration of mgmt webapp and each ServiceRegistryDAO though.
The DAO tests from the old pull request don't fit into the current design of test cases, so I left them out.
> drop service deletion from mgmt webapp controller

- webapp-mgmt/cas-management-webapp-support/src/main/java/org/apereo/cas/mgmt/config/CasManagementWebAppConfiguration.java
Without fixing this URL a new installation will have a hard time messing underlying service registry to properly register cas-management
> Fix cas-management default service URL

- core/cas-server-core-web/src/main/java/org/apereo/cas/web/AbstractDelegateController.java
- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/AbstractServiceValidateController.java
- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/LegacyValidateController.java
- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/ProxyValidateController.java
- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/ServiceValidateController.java
- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/v3/V3ProxyValidateController.java
- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/v3/V3ServiceValidateController.java
- Avoid NPE when running as Spring-Boot Application due to @Controller annotations picked up to early during bootstrap of the application. 
- see #2605 
Moved ```@Controller``` to AbstractServiceValidateController, as the child classes of it are the only ones affected by the Spring-Boot wiring issue (AbstractDelegateController is also extended by the SmartOpenIdController, which is not marked ```@Controller```, so I do want to avoid side effects).
> Move @Controller annotations to superclass of ValidationControllers

- core/cas-server-core-util/src/main/java/org/apereo/cas/util/ResourceUtils.java
`ClasspathResource` must be instantiated without `classpath:` pseudo-url prefix, otherwise the resource representation will not point to an actual classpath file.
> Correctly instatiate ClasspathResource

- core/cas-server-core-monitor/src/main/java/org/apereo/cas/monitor/CacheStatus.java
Passing StringBuilder sb to each CacheStatistics objects causes the maps in the first few entries to be printed to the screen multiple times.
> Stop CacheStatus from printing Map info multiple times

- support/cas-server-support-cookie/src/main/java/org/apereo/cas/web/support/CookieRetrievingCookieGenerator.java
In CookieRetrievingCookieGenerator exists overriden method setCookieDomain, but it is never called. In constructor, super method is called.
SSO mechanism doesn't work because domain is an empty string ("")
> Incorrect cookie domain setting

- support/cas-server-support-reports/src/main/java/org/apereo/cas/web/report/DashboardController.java
DashboardController.java is passing th SSOReport endpoint flag for the SSOStatus endpoint.  This causes the SSOStatus link to show on the cas/status/dashboard, but when the link is clicked it reports 404 error.  
This pull changes the file to pass the correct endpoint flag
> Passing wrong property for SSOStatus endpoint

- api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/RegisteredServiceMultifactorPolicy.java
- core/cas-server-core-authentication/src/main/java/org/apereo/cas/services/AbstractMultifactorAuthenticationProvider.java
- core/cas-server-core-services/src/main/java/org/apereo/cas/services/DefaultRegisteredServiceMultifactorPolicy.java
... as currently the registered service mode is instantiated with default of `CLOSED`: https://github.com/apereo/cas/blob/master/core/cas-server-core-services/src/main/java/org/apereo/cas/services/AbstractRegisteredService.java#L99 no `global` failure mode branch could ever be reached.
This commit fixes that by introducing the default mode of `NOT_SET` and checking this value to make sure that the global mode could take effect.
> Proper failure mode override/default handling

- support/cas-server-support-ldap/src/main/java/org/apereo/cas/config/LdapAuthenticationConfiguration.java
I think that condition on warning days for adding handlers is not necessary. Now, in case if you want to have password policy turned on, but don't want to display warnings on password expiration, you can't do it, because [DefaultAccountStateHandler:165](https://github.com/apereo/cas/blob/master/support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/authentication/support/DefaultAccountStateHandler.java#L165)
> Removed condition for adding handler 

- core/cas-server-core-tickets/src/main/java/org/apereo/cas/ticket/registry/DefaultTicketRegistrySupport.java
As I understand the internals of CAS there is no guarantee that a ticket registry does not have expired tickets. Hence ticket expiration needs to be checked when trying to obtain a *valid* authentication.
PR adds TGT expiration check to `DefaultTicketRegistrySupport` so that call to `getAuthenticationFrom` won't return authentication of an expired ticket. This fulfils contract defined in JavaDoc:
> @return valid Authentication OR NULL if there is no valid SSO session present identified by the provided TGT id SSO token
The scenario this PR solves is following:
* Once user goes to login flow with TGC referencing expired TGT, this TGT is being picked by `InitialFlowSetupAction#configureWebflowContext`.
* Later after a succesful authentication a new TGT should be ideally issued, but that is …
> Prevent extracting expired TGT authentication.

- core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasCoreTicketsSchedulingConfiguration.java
To avoid confusion when reading the source and debugging, etc.
> More accurate since tag for this class

- core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasCoreTicketsConfiguration.java
Found this testing 5.1.0 release:
When using a distributed ticket registry cache such as Hazelcast, the de-serialization of the ServiceTicketImpl fails when reading the ticket from a different host then what created it.  
Removing @RefreshScope from the ServiceTicketExpirationPolicy bean allows it to be serialized between different hosts.
> @RefreshScope on ServiceTicketExpirationPolicy causes deserializtion err

- docs/cas-server-documentation/installation/User-Interface-Customization-CSSJS.md
The first line of this corrects an inaccurate statement now that head.js stuff moved from cas.js to bottom.html. 
The rest is a section about using webjars, mainly for CAS developers. If you think that is unnecessary or too much information, I can delete it.
> Fix documentation as result of webjars change, add how-to doc for webjar

- support/cas-server-support-hazelcast-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/HazelcastTicketRegistry.java
Found this in 5.1.x load testing.  
The Sf4j Logger will iterate collections calling toSting() on each entry in a map.  This causes severe degradation once the map reaches even a trivial size.  
Changed the debug statement to just echo the mapName and not pass instance to the LOGGER.debug().
> Slf4j prints entire Map contents

- core/cas-server-core-tickets/src/main/java/org/apereo/cas/ticket/registry/AbstractTicketRegistry.java
- core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/AbstractTicketRegistryTests.java
- core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/DefaultTicketRegistryTests.java
- support/cas-server-support-couchbase-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/CouchbaseTicketRegistry.java
- support/cas-server-support-dynamodb-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/DynamoDbTicketRegistry.java
- support/cas-server-support-dynamodb-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/DynamoDbTicketRegistryTests.java
- support/cas-server-support-ehcache-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/EhCacheTicketRegistry.java
- support/cas-server-support-ehcache-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/EhCacheTicketRegistryTests.java
- support/cas-server-support-hazelcast-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/HazelcastTicketRegistry.java
- support/cas-server-support-hazelcast-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/HazelcastTicketRegistryTests.java
- support/cas-server-support-ignite-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/IgniteTicketRegistry.java
- support/cas-server-support-ignite-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/IgniteTicketRegistryTests.java
- support/cas-server-support-infinispan-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/InfinispanTicketRegistry.java
- support/cas-server-support-infinispan-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/InfinispanTicketRegistryTests.java
- support/cas-server-support-memcached-monitor/src/test/java/org/apereo/cas/monitor/MemcachedMonitorTests.java
- support/cas-server-support-memcached-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MemCacheTicketRegistry.java
- support/cas-server-support-memcached-ticket-registry/src/test/java/org/apereo/cas/MemCacheTestUtils.java
- support/cas-server-support-memcached-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/MemCacheTicketRegistryTests.java
- support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java
- support/cas-server-support-mongo-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistryTests.java
- support/cas-server-support-redis-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/RedisTicketRegistryTests.java
Lots of `TicketRegistry` implementations were not encoding `ticketId` when deleting tickets. This lead to issues like the one described in #2660.
Commit description:
* I have added ticket ID encoding where it seem it was missing (some registries had encoding already in place or were fetching encoded tickets and using their id instead).
* I have also deleted one ambiguous method on `AbstractTicketRegistry`. This method was unused and did not state whether the provided ticket was supposed to be `EncodedTicket` or not.
Additional comments:
* It would be nice to have unit tests for encoded registry behavior, but writing such tests is too complex for me.
* `TicketRegistry` implementations don't have single naming / style convention when comes to encoded values. Possible future improvement: …
> Fix deletion of encoded tickets in ticket registries

- core/cas-server-core-services/src/main/java/org/apereo/cas/services/AbstractResourceBasedServiceRegistryDao.java
- core/cas-server-core-services/src/main/java/org/apereo/cas/services/ServiceRegistryConfigWatcher.java
Closes #2676 
Changes:
- move registeredService logic out of the watcher.
This could be a first step to make the watcher logic agnostic that could be reused for ```ConfigurationDirectoryPathWatchService```
> Move service action responsibilities into the serviceRegistry

- support/cas-server-support-throttle/src/main/java/org/apereo/cas/web/support/AbstractThrottledSubmissionHandlerInterceptorAdapter.java
Dear CAS developers,
I have noticed that the CAS throttling subsystem reports successful authentications as failed, if the 'service' parameter is specified and a redirect to the service URL follows the successful authentication. I think this should not happen and HTTP status code 302 should be handled in the same way like 200 or 201.
There is some ongoing discussion here, although not completely about this change: https://groups.google.com/a/apereo.org/forum/#!topic/cas-dev/7yhZDm0Az0k
If this change looks OK, I can also prepare a merge request for 5.1.x and master.
Thank you!
Jarda
> Throttling - HTTP Status 302 should not be reported as failure

- support/cas-server-support-throttle/src/main/java/org/apereo/cas/web/support/AbstractThrottledSubmissionHandlerInterceptorAdapter.java
This is the same pull request as
#2683
but for master.
> Throttling - HTTP Status 302 should not be reported as failure [branch master]

- support/cas-server-support-throttle/src/main/java/org/apereo/cas/web/support/AbstractThrottledSubmissionHandlerInterceptorAdapter.java
This is the same pull request as
https://github.com/apereo/cas/pull/2683
but for branch 5.1.x.
> Throttling - HTTP Status 302 should not be reported as failure [branch 5.1.x]

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/support/authentication/Pac4jAuthenticationEventExecutionPlanConfiguration.java
Closes #2647
Add additional "clientName" property to Pac4jProperties, have
Pac4jAuthenticationEventExecutionPlanConfiguration use it to
configure the underlying pac4j SAML2Client.
> Add ability for deployers to name pac4j SAML clients

- support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/authentication/support/DefaultAccountStateHandler.java
Check that warning.getExpiration() is not null, to avoid NPE.
> Fix NPE when password has expired but there are remaining logins.

- support/cas-server-support-audit-jdbc/src/main/java/org/apereo/cas/audit/config/CasSupportJdbcAuditConfiguration.java
Closes #2700 
- the JdbcAuditTrailManager needs to be created as bean so that the destroy method is called
> Fixes the grateful shutdown of cas

- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java
If password management is disabled and pwdReset is true,
a java.lang.IllegalArgumentException is thrown with message:
Cannot find state with id 'casMustChangePassView' in flow 'login'.
> Fix casMustChangePassView missing state.

- core/cas-server-core-authentication/src/main/java/org/apereo/cas/web/flow/AuthenticationExceptionHandlerAction.java
getAttributes() should be called on currentEvent() to get the
exception.class.
With this fix ppolicy views are now accessible again.
> FIX unreachable ppolicy views

- core/cas-server-core-authentication/src/main/java/org/apereo/cas/authentication/RegisteredServiceAuthenticationHandlerResolver.java
As currently the default collector returned by no-arg `Collectors#joining` just concatenates the names with no delimiters and it's hard to read in the logs.
> Join with comma separator

- api/cas-server-core-api-events/src/main/java/org/apereo/cas/support/events/dao/CasEvent.java
- core/cas-server-core-events/src/main/java/org/apereo/cas/support/events/listener/DefaultCasEventListener.java
- core/cas-server-core-events/src/test/java/org/apereo/cas/support/events/AbstractCasEventRepositoryTests.java
- support/cas-server-support-electrofence/src/test/java/org/apereo/cas/impl/mock/MockTicketGrantingTicketCreatedEventProducer.java
creationTime should be CasEvent's property (as in AbstractCasEventRepository)
or else an IllegalArgumentException is thrown
(InitialAuthenticationAttemptWebflowEventResolver).
```
2017-06-26 15:23:13,982 TRACE [org.apereo.cas.audit.spi.ThreadLocalPrincipalResolver] - <Resolving principal at audit point [execution(AuthenticationRiskScore org.apereo.cas.impl.engine.DefaultAuthe
nticationRiskEvaluator.eval(Authentication,RegisteredService,HttpServletRequest))] with thrown exception [java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property
: creationTime of: org.apereo.cas.support.events.dao.CasEvent [SELECT r from org.apereo.cas.support.events.dao.CasEvent r where r.type = :type and r.creationTime >= :creationTime and r.principalId =
:principalId]]> …
```
> Make creationTime CasEvent's property

- webapp/resources/static/js/authnEvents.js
creationTime does not exist anymore in properties ( #2721 ), as a
consequence, creationTime column displays Invalid Date. Update
authnEvents.js to get creationTime from the right place.
> Fix creationTime column - 5.1.x

- webapp/resources/static/js/authnEvents.js
creationTime does not exist anymore in properties ( #2720  ), as a
consequence, creationTime column displays Invalid Date. Update
authnEvents.js to get creationTime from the right place.
> Fix creationTime column - Master

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/ticket/accesstoken/OAuthAccessTokenExpirationPolicy.java
Closes #2737
Now the sliding window check for access token is made in the following way:
lastTimeUsed + timeToKillInSeconds = expirationTime
if currentSystemTime > expirationTime then token is expired
> Checking expiration time for access token fixed (#2737)

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/ticket/accesstoken/OAuthAccessTokenExpirationPolicy.java
Closes #2737
Now the sliding window check for access token is made in the following way:
lastTimeUsed + timeToKillInSeconds = expirationTime
if currentSystemTime > expirationTime then token is expired
> Checking expiration time for access token fixed.

- gradle.properties
- support/cas-server-support-token-authentication/src/main/java/org/apereo/cas/token/authentication/TokenAuthenticationHandler.java
- support/cas-server-support-token-core/src/main/java/org/apereo/cas/token/TokenConstants.java
See https://github.com/pac4j/pac4j/issues/946 for details
Added new service property  "jwtSecretsAreBase64Encoded" as boolean value. Default or missing value is *false*. Property set to *true* implies the secrets are Base64 encoded just like proposed by key generator tool. The modification expects newer version >=2.1.0-SNAPSHOT of pac4j-jwt 
See also https://github.com/pac4j/pac4j/pull/951 for even more details
Usage:
```json
"jwtSecretsAreBase64Encoded": {
"@class": "org.apereo.cas.services.DefaultRegisteredServiceProperty",
"values": [
"java.util.HashSet",
[
"true"
]
]
}
```
> jwt authentication should accept base64 encoded keys

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenAuthorizationCodeGrantRequestExtractor.java
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenRefreshTokenGrantRequestExtractor.java
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenRequestDataHolder.java
- support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/OAuth20AccessTokenControllerTests.java
Fix for #2731 commited in rev. cf38394 introduced a new bug. After the fix refresh token is generated for all grant types, including refresh_token grant type, which is wrong.
This fix removes refresh token generation for "refresh_token" grant type.
> Removing refresh token generation when using grant type 'refresh_token'.

- docs/cas-server-documentation/installation/DuoSecurity-Authentication.md
Build fails with `Could not find com.github.duosecurity:duo_client_java:${project.'cas.version'}` if this repository is not specified.
> Added `dupclient` repository (still required)

- support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java
- support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/TicketHolder.java
Makes tickets stored in MongoDb expire automatically by setting the expireAt field to be a date type.
Previously it was being set to the ticket's TTL so the Mongo index for auto-deletion had no effect.
This change assumes that the CAS and Mongo server dates are in sync.  If they are not, tickets may be deleted from MongoDb earlier than expected (solution would seem to be to set ticket.getProperties().getStorageTimeout() appropriately).
Closes #2748
> Makes tickets stored in MongoDb expire automatically

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/jpa/AbstractJpaProperties.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
added the ability to specify hibernate-specific properties, similar to standard spring boot jpa settings
Example: cas.serviceRegistry.jpa.properties.hibernate.globally_quoted_identifiers=true
This setting specifically allows the service management overlay to work against a mysql database.  The SamlRegisteredService_AttributeNameFormats object contains a field named 'key', which prevents MySQL from being used.  Instructing hibernate to quote all identifiers allows this to work without any modification to the code.  This could also be useful for any other hibernate-specific settings without the need to add further custom properties and property support.  This also follows existing spring boot conventions for custom hibernate properties.
> allow hibernate specific properties

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20AccessTokenEndpointController.java
- support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/OAuth20AccessTokenControllerTests.java
Closes #2644 in 5.1.x.
Returning correct expires_in value for access token.
> Returning correct expires_in value for access token (#2644)

- docs/cas-server-documentation/installation/Configuration-Properties.md
using [0] gives an error because the property is not of array-type (5.1.1)
> fixes wrong info

- support/cas-server-support-couchbase-ticket-registry/src/main/resources/META-INF/spring.factories
Reverts incorrect ticket registry configuration on `apereo:5.1.x` branch introduced in 6ae24ed.
Closes #2638
> Revert mismatch ticket registry configuration

- support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/authorization/LdapUserAttributesToRolesAuthorizationGenerator.java
When no attributes are returned for the user or
when configured role attribute can not be found,
instead of throwing IllegalStateException, log the
appropriate message and return the (unmodified) profile.
(That's, also, how generateAuthorizationForLdapEntry in
LdapUserGroupsToRolesAuthorizationGenerator handles
similar cases.)
With this change, cas-management shows correctly the
authorizationFailure view instead of throwing
> The CAS management webapp is unavailable.
> Replace IllegalStateException with log messages.

- core/cas-server-core-tickets/src/main/java/org/apereo/cas/ticket/registry/DefaultTicketRegistryCleaner.java
Just using streams in DefaultTicketRegistryCleaner
Please consider the possibility of making ticketRegistry.getTickets() returning a Stream<Ticket> so there would be only 1 stream created
> Use streams in default cleaner

- support/cas-server-support-hazelcast-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/HazelcastTicketRegistry.java
- support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java
- support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/RedisTicketRegistry.java
Following the discussion in #2779, I have migrated this 3 registries to use streams.
Iin the MongoDb one, please review the ToDo annotation and also, previously tickets were being decoded twice
> Using streams in Hazelcast, MongoDb and Redis ticket registries

- docs/cas-server-documentation/integration/Attribute-Value-Release-Policies.md
The `property` map of the Mapped Regex attribute filter requires an explicit `"@class": "java.util.HashMap"` or similar definition for the software to parse and interpret it correctly.
> Mapped Regex attribute filter docs update

- support/cas-server-support-pm-rest/src/main/java/org/apereo/cas/pm/rest/RestPasswordManagementService.java
Fix 'change' method in RestPasswordManagementService to use the correct endpoint. It was using the 'endpointUrlEmail' property instead of the 'endpointUrlChange' one.
> Fix RestPasswordManagementService to use 'urlChange' endpoint

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/support/authentication/Pac4jAuthenticationEventExecutionPlanConfiguration.java
This PR introduce a new configuration parameter for AuthnContext comparison type.
This parameter will be used set comparison attribute of the given AuthnContextClassRef. In case of missing value, "exact" comparison type is used.
> AuthnContext comparison type is mandatory for AuthnContextClassRef

- support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java
Commit 6e9ba3b1d0ef7af9990925ef71f9379596ef9ab7 broke the existing password management functionality by replacing the state and view id string literals with the constants.  The wrong constant was used.
`createEndState(flow, "casPasswordUpdateSuccess", "casPasswordUpdateSuccessView");`
was changed to
`createEndState(flow, CasWebflowConstants.VIEW_ID_PASSWORD_UPDATE_SUCCESS, CasWebflowConstants.VIEW_ID_PASSWORD_UPDATE_SUCCESS);`
it needed to be
`createEndState(flow, CasWebflowConstants.STATE_ID_PASSWORD_UPDATE_SUCCESS, CasWebflowConstants.VIEW_ID_PASSWORD_UPDATE_SUCCESS);`
> Fix Password Management webflow state (master)

- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java
Commit 6e9ba3b1d0ef7af9990925ef71f9379596ef9ab7 broke the existing password management functionality by replacing the state and view id string literals with the constants.  The wrong constant was used.
`createEndState(flow, "casPasswordUpdateSuccess", "casPasswordUpdateSuccessView");`
was changed to
`createEndState(flow, CasWebflowConstants.VIEW_ID_PASSWORD_UPDATE_SUCCESS, CasWebflowConstants.VIEW_ID_PASSWORD_UPDATE_SUCCESS);`
it needed to be
`createEndState(flow, CasWebflowConstants.STATE_ID_PASSWORD_UPDATE_SUCCESS, CasWebflowConstants.VIEW_ID_PASSWORD_UPDATE_SUCCESS);`
> Fix Password Management webflow state 5.1.x

- support/cas-server-support-yaml-service-registry/src/main/java/org/apereo/cas/services/config/YamlServiceRegistryConfiguration.java
The current bean name for this service registry impl. does not work with @Conditional bean creation, thus this impl. is not being picked up.
> Fix conditional bean creation

- docs/cas-server-documentation/installation/Configuration-Properties.md
Resolves the following error in CAS 5.1.1 (Java 8, Tomcat 8):
````
ERROR [org.springframework.boot.SpringApplication] - <Application startup failed>
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.OpenSAMLConfig' defined in class path resource [org/apereo/cas/config/CoreSamlConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apereo.cas.support.saml.OpenSamlConfigBean]: Factory method 'openSamlConfigBean' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.ParserPool' defined in class path resource …
```
> Propose new default value for cas.samlCore.securityManager setting

- support/cas-server-support-saml-mdui-core/src/main/java/org/apereo/cas/support/saml/mdui/SamlMetadataUIInfo.java
In the case when SAML SP does not provide MDUI and CAS login UI template tries to display that metadata via getter method wrappers such as `SamlMetadataUIInfo::getDisplayName` and `SamlMetadataUIInfo::getDescription` etc., NPE results. This PR corrects this defect.
> Fix NPE when UIInfo is not available

- gradle/dependencies.gradle
> Remove HikariCP-java6 dependency from quartz as HikariCP (non java6) is included elsewhere

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/web/flow/DelegatedClientAuthenticationAction.java
- support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/support/authentication/Pac4jAuthenticationEventExecutionPlanConfiguration.java
- webapp/resources/application.properties
This fixes the default Google pac4j login button appearing with a label of Google2 and a class of btn-google2 (instead of bootstrap-social's btn-google).
> Use 'Google' name for Google2 pac4j client

- core/cas-server-core-services/src/test/java/org/apereo/cas/services/RegisteredServiceTestUtils.java
- core/cas-server-core-util/src/main/java/org/apereo/cas/util/RandomUtils.java
- core/cas-server-core-util/src/main/java/org/apereo/cas/util/gen/AbstractRandomStringGenerator.java
- support/cas-server-support-consent-core/src/main/java/org/apereo/cas/consent/JsonConsentRepository.java
- support/cas-server-support-digest-authentication/src/main/java/org/apereo/cas/digest/util/DigestAuthenticationUtils.java
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
- support/cas-server-support-saml-googleapps-core/src/main/java/org/apereo/cas/support/saml/authentication/principal/GoogleAccountsServiceResponseBuilder.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/AbstractSamlProfileHandlerController.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/SamlProfileSamlAssertionBuilder.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/SamlProfileSamlAuthNStatementBuilder.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/response/SamlProfileSaml2ResponseBuilder.java
- support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/util/AbstractSaml20ObjectBuilder.java
- support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/util/SamlCompliantUniqueTicketIdGenerator.java
- support/cas-server-support-sqrl/src/main/java/org/apereo/cas/config/SqrlConfiguration.java
- support/cas-server-support-ws-idp/src/main/java/org/apereo/cas/ws/idp/web/BaseWSFederationRequestController.java
Try NativePRNGNonBlocking and failover to SHA1PRNG until Java 9
Weakens random source slightly.
- [] Reference any other pull requests that might be related.
#2812 moved SecureRandom to NativePRNG which is too slow on some platforms for the volume of data retrieved.
This corrects that by moving it to non blocking IO and falling back to the default.
> NativePRNG too slow

- core/cas-server-core-services-api/src/main/java/org/apereo/cas/authentication/principal/ShibbolethCompatiblePersistentIdGenerator.java
- core/cas-server-core-services/src/test/java/org/apereo/cas/authentication/principal/ShibbolethCompatiblePersistentIdGeneratorTests.java
- core/cas-server-core-util/src/main/java/org/apereo/cas/util/DigestUtils.java
This is a fix for the Shibboleth compatible PersistentID generator. The fix is two parts:
* A test that will test for a valid value and verify the returned value of the generated against this value
* Updates to the generator to satisfy the test
No further configuration beyond what is documented should be needed.
There should be no side effects other than the generated ID will be different now, possibly preventing the use of services previously integrated. A new generator might need to be created to replicate the broken state.
> Fix for Shibboleth compatible PersistentID generator

- support/cas-server-support-ehcache-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/EhCacheTicketRegistry.java
This change is inline with "In general, you need to ensure the cache is alive long enough to support the individual expiration policy of tickets, and let CAS clean the tickets as part of its own cleaner."
On some types of storage mass eviction causes faulty removal on another it is too expensive.
> Prevent expensive mass eviction from EhCache

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/ignite/IgniteProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- gradle/dependencies.gradle
- support/cas-server-support-ignite-ticket-registry/build.gradle
- support/cas-server-support-ignite-ticket-registry/src/main/java/org/apereo/cas/config/IgniteTicketRegistryConfiguration.java
Completes support for logging through log4j2 to the ignite support.
Adds client mode config option to run the Ignite node as a client for externalizing the server node.
- Netsplits caused the ignite grid to segregate and ignite has no good way of handling this without restarting the JVM.
No doc needed for the log4j stuff, it's just completing the support so ignite will use log4j2. The client mode change has an entry for the config option added and needs no other doc.
Fixes limitations of my prior ignite work.
> Add clientMode config option to run the Ignite node as a client for externalizing the server node

- support/cas-server-support-spnego/src/main/java/org/apereo/cas/support/spnego/authentication/handler/support/JcifsSpnegoAuthenticationHandler.java
- support/cas-server-support-spnego/src/test/java/org/apereo/cas/support/spnego/MockJcifsAuthentication.java
- support/cas-server-support-spnego/src/test/java/org/apereo/cas/support/spnego/MockUnsuccessfulJcifsAuthentication.java
- support/cas-server-support-spnego/src/test/java/org/apereo/cas/support/spnego/authentication/handler/support/JcifsSpnegoAuthenticationHandlerTests.java
**Brief description of changes applied**
An unsuccessful SPNEGO authentication may result in
jcifs.spnego.Authentication.process() to pass without exception and in
authentication.getPrincipal() == null. Fixed code to be null safe
and extended tests to encompass this scenario.
**Any documentation on how to configure, test**
The mentioned scenario occurs if cas-server-support-spnego is enabled
and a windows client tries to authenticate with a local user (= a
user that is unknown for jcifs.spnego.Authentication).
**Any possible limitations, side effects, etc**
Nothing
> Fix possible NPE in JcifsSpnegoAuthenticationHandler

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/saml/SamlCoreProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-saml/src/main/java/org/apereo/cas/config/SamlConfiguration.java
- support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/util/Saml10ObjectBuilder.java
- support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/web/view/AbstractSaml10ResponseView.java
- support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/web/view/Saml10FailureResponseView.java
- support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/web/view/Saml10SuccessResponseView.java
- support/cas-server-support-saml/src/test/java/org/apereo/cas/support/saml/web/view/Saml10FailureResponseViewTests.java
- support/cas-server-support-saml/src/test/java/org/apereo/cas/support/saml/web/view/Saml10SuccessResponseViewTests.java
Addresses #2836
This adds a `cas.samlCore.issueLength` property with a default value of 30 seconds to properly set the interval between the `NotBefore` and `NotOnOrAfter` timestamps in the SAML assertion. Currently this interval is configured using the `cas.samlCore.skewAllowance` property, which is used to adjust for clock skew.
Examining a SAML assertion using the current code and default configuration (with the `skewAllowance` set to `5`) will show the `NotBefore` timestamp set to 5 seconds in the past and `NotOnOrAfter` timestamp set to 5 seconds after `NotBefore`. This results in a validity period that will expire almost immediately after it is issued.
With these changes, the default behavior will result in the `NotBefore` timestamp set to 5 seconds in the past and `NotOnOrAfter` …
> Added cas.samlCore.issueLength property to fix assertion validity period

- docs/cas-server-documentation/planning/High-Availability-Performance-Testing.md
- etc/loadtests/jmeter/CAS_CAS.jmx
- etc/loadtests/jmeter/CAS_Oauth.jmx
- etc/loadtests/jmeter/CAS_SAML2.jmx
- etc/loadtests/jmeter/cas-users.csv
Hi,
I am adding some basic JMeter scripts that can be used for testing CAS performance.  
There are 3 scripts:
- Basic CAS Login
- CAS Oauth Login
- CAS SAML login
I have also added the appropriate documentation to the "/planning/High-Availability-Performance-Testing" page. This documentation states the requirements, description and how to run the scripts.
This is my first pull request, so if I have missed anything, please inform me and I can add as appropriate.  
Thanks you,
Axel
> Jmeter test scripts

- webapp-mgmt/cas-management-webapp-support/src/main/java/org/apereo/cas/mgmt/config/CasManagementWebAppConfiguration.java
- webapp/cas-server-webapp-config/src/main/java/org/apereo/cas/config/CasWebAppConfiguration.java
Make the LocaleResolver beans conditional on if another LocaleResolver is already loaded into the spring context.
This will allow deployers to deploy a highly customized LocaleResolver if required.
> make it possible to override the localeResolver

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/ldap/LdapAuthenticationProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-ldap/src/main/java/org/apereo/cas/authentication/LdapAuthenticationHandler.java
- support/cas-server-support-ldap/src/main/java/org/apereo/cas/config/LdapAuthenticationConfiguration.java
Set a fixed name (default value principalLdapDn) for principal's DN attribute,
instead of dynamically create one, based on principal's username.
> Set a fixed name for principal's DN attribute.

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/ldap/LdapAuthenticationProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-ldap/src/main/java/org/apereo/cas/authentication/LdapAuthenticationHandler.java
- support/cas-server-support-ldap/src/main/java/org/apereo/cas/config/LdapAuthenticationConfiguration.java
Using a fixed name for principal's DN attribute name (principalDnAttributeName) solves the following issues:
- if user's id (i.e user@example.com) contains illegal (for xml naming) characters, the following exception occurs when validating ST tickets (CAS3.0 protocol):
`org.xml.sax.SAXParseException: Element type "cas:LdapAuthenticationHandler.user" must be followed by either attribute specifications, ">" or "/>".`
- principal's DN attribute can be referenced, easier, in attribute filtering
policies.
> 5.1.x fix principal dn

- support/cas-server-support-saml-mdui-core/src/main/java/org/apereo/cas/support/saml/mdui/SamlMetadataUIInfo.java
* call this.uiInfo again to get LocalizedNames
* add null check to avoid NPE
This bug has a history already:
PR https://github.com/apereo/cas/pull/2832
PR https://github.com/apereo/cas/pull/2872 (5.1.x)
Closes #2880
> refixed UIInfo to avoid ClassCast and NullPointerException

- support/cas-server-support-consent-webflow/src/main/java/org/apereo/cas/web/flow/AbstractConsentAction.java
For SAML2 services, the RequestContext's service and registered service are both the SAML2/Callback service. 
For consent, service gets resolved to be the SAML service, but in line 59 the registered service was set to the Callback service. I believe this should also be the SAML service, to resolve consentableAttributes correctly.
> consent: fixed registered service for e.g. saml

- support/cas-server-support-rest/src/main/java/org/apereo/cas/support/rest/resources/TicketGrantingTicketResource.java
On a regular authentication failure (wrong password etc.) TicketGrantingTicketResource issues a log message with level ERROR and a stacktrace. This seems inappropriate because 
1) the stacktrace does not provide any useful insights and 
2) the ERROR log level suggest a fatal error although this is a regular result from login workflow.
More reasonable is a WARNing without stacktrace.
> Issue reasonable log message for authentication failure (cas-server-support-rest)

- core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/AbstractRegisteredService.java
- core/cas-server-core-services/src/test/java/org/apereo/cas/services/RegexRegisteredServiceTests.java
remove Jsonignore annotation from logoutType property to have another values as BACK_CHANNEL
included test is failing with annotation on place
> handle logoutType properly

- core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/resolver/impl/RankedAuthenticationProviderWebflowEventResolver.java
Lack of this transition here shows up in the logs as error condition when LPPE warnings are present in the primary authentication leg.
> Add successWithWarnings transition to the list of standard recognized transitions

- webapp/resources/templates/casPropagateLogoutView.html
This functionality seems to me unfinished - so I provide my working changes. 
- splits empty tag *i* for proper rendering
- properly encloses injected variables
- uses only id for service didplay
- provides interim question icon for pending requests
There are small known bug
- error responses from other domains are not rendered - as error callback is not called in jQuery.
For testing
- set logoutType to FRONT_CHANNEL
- log in to several CASified applications
- logout in CAS and check behaviour of logout page.
- be aware that URLs endings with localdomain are discarded by URLValidator in CAS so more valid URLs should be used
I am not sure how to automate testing of this change.
> fixes casPropagateLogoutView

- support/cas-server-support-consent-webflow/src/main/java/org/apereo/cas/web/flow/AbstractConsentAction.java
For Saml services, the previously displayed ${service.id} contained the
callback service with the whole encoded saml request. With this fix, the
actual service as resolved by consent is displayed.
> consent: change displayed service id

- README.md
I don't think Apereo projects should be including ads in their websites, not even in their READMEs on GitHub.
This changeset would back out this ad from the CAS README.
(Reverts d8afe813c8b1fc62d63af0c1bf6f202a0ab5878e "[skip tests]".)
> feat(readme): rm codesponsor ad

- support/cas-server-support-cloud-directory-authentication/src/main/java/org/apereo/cas/authentication/CloudDirectoryAuthenticationHandler.java
The current password checking/matching only works for encoding algorithms that always encode to the same value. `PasswordEncoder` types like `BCryptPasswordEncoder` and `StandardPasswordEncoder` from `spring-security` use randomly generated salts and therefore encode to a different value every time. To fix this we need to use the `PasswordEncoder`'s `matches` method instead. `AbstractUsernamePasswordAuthenticationHandler` already provides a protected method that calls this.
This issue might be present in the other authentication handlers as well. Just glancing over a couple of them, it looks like the issue also exists in the Cassandra one.
> Fix Cloud Directory authentication for PasswordEncoder types that use randomly generated salts

- support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/VerifySecurityQuestionsAction.java
- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/PasswordManagementService.java
This allows for implementations of `PasswordManagementService` to implement their own security question answer verification. 
Our answers are hashed so this change allows us to add on to instead of replacing CAS code. We can keep the entire existing password reset process by only implementing a `PasswordManagementService`. While on the face it seems unnecessary to pass _everything_ back for checking it allows the service to check the answer without doing another lookup or otherwise storing data.
I tried to keep this as simple as possible by implementing the default code in the interface. If you'd prefer it in `BasePasswordManagementService` let me know. 
While working on this I noticed that the pm flow relies on `PasswordManagementService.getSecurityQuestions()` having a stable/consistent …
> Allow PasswordManagementService to perform security question validation (take 2)

- support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java
The view CasWebflowConstants.VIEW_ID_MUST_CHANGE_PASSWORD (casMustChangePassView) isn't being registered if pm was enabled. 
If an authentication method results in an AccountPasswordMustChangeException an error is thrown instead of starting the password management flow.
The resulting error looked like this:
```
2017-09-20 14:24:14,396 DEBUG [org.apereo.cas.authentication.support.DefaultAccountStateHandler] - <Handling error [CHANGE_AFTER_RESET]>
2017-09-20 14:24:14,396 DEBUG [org.apereo.cas.authentication.PolicyBasedAuthenticationManager] - <[LdapAuthenticationHandler] exception details: [null].>
2017-09-20 14:24:14,397 ERROR [org.apereo.cas.authentication.PolicyBasedAuthenticationManager] - <Authentication has failed. Credentials may be incorrect or CAS cannot find authentication handler …
```
> Fix MUST_CHANGE_PASSWORD state breaking when pm is enabled

- support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/PasswordChangeAction.java
- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/BasePasswordManagementService.java
- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/InvalidPasswordException.java
- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/PasswordManagementService.java
Our LDAP is the authoritative source for password policy as we have systems besides CAS that do some password management (admin utils, mostly). As a result, implementing a password validator inside of CAS would make for redundant code that may or may not perfectly match the downstream system. (And that doesn't even count things that may not be possible like checking against old passwords)
This pull request allows for a `PasswordManagementService` to report when a downstream system detects a password change with an invalid password.
I looked at various approaches and none seemed great -- this is the least bad approach I could come up with. I'm open to suggestions on alternatives.
Without something like this we resort to replacing the `PasswordChangeAction` bean, and in my continuous quest …
> Allow downstream systems to invalidate password changes

- core/cas-server-core-authentication/src/main/java/org/apereo/cas/services/DefaultMultifactorAuthenticationProviderBypass.java
The class org.apereo.cas.services.DefaultMultifactorAuthenticationProviderBypass was updated to read the correct property value when checking for a principal attribute bypass.
Previously setting the bypass.principalAttributeValue would be ignored with the side effect of any principal with only the bypass.principalAttributeName being able to bypass MFA security.
> Updated DefaultMultifactorAuthenticationProviderBypass locateMatchingAttributeBasedOnPrincipalAttributes to use correct property

- api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/ServiceRegistryDao.java
- core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/AbstractServiceRegistryDao.java
- core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/ServiceRegistryInitializer.java
- core/cas-server-core-services-registry/src/test/java/org/apereo/cas/services/ServiceRegistryInitializerTests.java
The first commit contains a test that demonstrates the problem.  The second commit contains a potential fix for the problem.
> initFromJson creates duplicate records when ids are assigned by the DAO

- support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java
Looks like `CasWebflowConstants.VIEW_ID_ACCOUNT_DISABLED` was being registered twice, once above where it should be and once as part of the password management flows.
Removing the second case inside the pm flows results in everything behaving as you'd expect. I updated the folder in the issues project with a way to verify it easily.
I tested these cases:
```
protected HandlerResult authenticateUsernamePasswordInternal(final UsernamePasswordCredential credential,
final String originalPassword)
throws GeneralSecurityException, PreventedException {
GeneralSecurityException e;
if( "disabled".equals( credential.getUsername() ) ) {
e = new AccountDisabledException();
}
else if( "expired".equals( credential.getUsername() ) ) {
e = new CredentialExpiredException();
}
else if( "locked".equals( …
```
> Fix: Login flow results in Account Disabled message when must-change-password is set and new password fails validation #2945

- core/cas-server-core-audit/src/main/java/org/apereo/cas/audit/spi/config/CasCoreAuditConfiguration.java
This allows a deployer that has custom audits to extend the default resolvers instead of replacing all of them.
> Make it easier to add custom audit action and resource resolvers

- webapp/resources/messages_sk.properties
This patch 
- corrects small typos in Slovak translation
- adds logout link in login confirmation screen
- removes redundant escaping for equal sign
> correct small typos in Slovak translation

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/memcached/BaseMemcachedProperties.java
- support/cas-server-support-memcached-core/src/main/java/org/apereo/cas/memcached/kryo/CasKryoTranscoder.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/config/SamlIdpComponentSerializationConfiguration.java
Complete previous 5.1.x work of ensuring that all Expiration Policy classes are registered for memcached Kryo serializer handling.  Related to 5.1.x pull request 2921.
> Serialization Config - Register some additional Expiration Policy classes

- webapp/resources/messages.properties
- webapp/resources/messages_de.properties
- webapp/resources/templates/error.html
The error page was using the snippet for the "bad hours" page which is not
correct for the general error. This should clarify the intention of the error
page
How is the policy with adding new text snippet? Do I need to update all the other language files too?
See https://github.com/apereo/cas/issues/2958.
> Add extra text snippet for error page

- support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/VerifyPasswordResetRequestAction.java
This fixes an issue where sometimes questions would not be in the same order during display and verification resulting in the answer not matching the question.
While `BasePasswordManagementService` knows to keep the questions in a `LinkedHashMap` for consistency `VerifyPasswordResetRequestAction` was throwing the keys in a regular `HashSet` for use by the template resulting in inconsistent ordering when displaying on the form. Verification, though, continued to use a `LinkedHashMap` resulting in sometime mismatches.
This PR swaps out the `HashSet` for a `LinkedHashSet` to ensure consistent iteration.
> Fix password questions losing their order in HashSet

- support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/web/flow/SAML2ClientLogoutAction.java
Hello!
We encountered a little issue with the SAML2 Client Logout Action with PAC4J. This pull request should fix it for CAS 5.1.
The action took a random (any) SAML2 client from all PAC4J clients. This worked fine if there were
exactly 1 SAML2 client in the system and just this client was used. However, it did not work if no PAC4J client was used (standard login) or if there were more than 1 SAML2 client.
Now, the SAML2ClientLogoutAction now takes into account the currently used PAC4J client, which is resolved from the PAC4J user profile.
To test:
- Configure CAS with PAC4J and at least 2 different SAML2 clients
- Log in using SAML
- Log out
- The logout should take you to the correct IdP server (provided it supports single logout)
- Log in without SAML
- Log out
- You should end on the …
> SAML2ClientLogoutAction Fix - Use Specific SAML2 Client [branch 5.1.x]

- support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/web/flow/SAML2ClientLogoutAction.java
This is the same pull request as #2967 , just for the master branch.
--
We encountered a little issue with the SAML2 Client Logout Action with PAC4J. This pull request should fix it for CAS 5.1.
The action took a random (any) SAML2 client from all PAC4J clients. This worked fine if there were
exactly 1 SAML2 client in the system and just this client was used. However, it did not work if no PAC4J client was used (standard login) or if there were more than 1 SAML2 client.
Now, the SAML2ClientLogoutAction now takes into account the currently used PAC4J client, which is resolved from the PAC4J user profile.
To test:
- Configure CAS with PAC4J and at least 2 different SAML2 clients
- Log in using SAML
- Log out
- The logout should take you to the correct IdP server (provided it supports single …
> SAML2ClientLogoutAction Fix - Use Specific SAML2 Client [branch master]

- support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/VerifyPasswordResetRequestAction.java
- support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/VerifySecurityQuestionsAction.java
- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/BasePasswordManagementService.java
The [PR yesterday](https://github.com/apereo/cas/pull/2968) fixed question order for `PasswordManagementService`s that are backed by a consistent store, but for ones with an inconsistent store (json, rest, jdbc?) questions could be ordered differently for each request. This PR takes it a step further and sorts the questions when displayed or verified to ensure they are consistent in all cases.
> Fix question order for backing stores with inconsistent ordering

- core/cas-server-core-events/src/main/java/org/apereo/cas/support/events/listener/DefaultCasEventListener.java
- core/cas-server-core-web/src/main/java/org/apereo/cas/web/support/WebUtils.java
Solving a NPE setting the geoLocationRequest into the CasEvent when there is no HttpServletRequest.
Just adding some null checks.
> Do not get location if there is not source to get it from

- support/cas-server-support-ldap/src/main/java/org/apereo/cas/authentication/LdapAuthenticationHandler.java
In our testing we noticed an unusual case where if a user's password has expired and they've exhausted grace logins they would still see the password change view even though the ldap server had responded with `INVALID_CREDENTIALS`. (And thus can't change their password). If it weren't expired it would end up at the end throwing a `FailedLoginException`, but because it's also marked as expired, the `AccountStateHandler` throws an exception first, even though it's lower on the totem pole.
I think the ideal solution would be to move the password policy check inside the `if (response.getResult()) {` block, but I can't be sure no one who's overriding the LDAP `AccountStateHandler` isn't relying on getting in there with a bad response. (Though I can't think of a reason why you would do that) …
> Fix for invalid credentials being allowed through password policy check (LDAP)

- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/rest/RestPasswordManagementService.java
- support/cas-server-support-rest-authentication/src/main/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandler.java
Should call getEndpointUrlChange instead of getEndpointUrlEmail for password change.
> REST PM calling wrong endpoint

- support/cas-server-support-saml-idp-core/src/main/java/org/apereo/cas/support/saml/services/SamlRegisteredService.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/enc/BaseSamlObjectSigner.java
- webapp-mgmt/cas-management-webapp/src/domain/saml-service.ts
An option is create for user to choose from BasicCredential and BasicX509Credential for KeyInfo,
BasicX509Credential being the default option
**Brief description of changes applied**
- a field called signingCredentialType is created in SamlRegisteredService (with getter setter and all the others things),
- which have two possible values being BASIC and BASIC_X509.
- If developer do not specified, default is trigger.
- If developer specified but have wrong value, default is triggered with warn output to the debug log
**Any possible limitations, side effects, etc**
Please note that I have not tested this pull request
> saml2 Response KeyInfo changed from X509Data to RSAKeyValue #2937

- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/config/CasValidationConfiguration.java
Currently responses to `/cas/proxyValidate` always use the V3 protocol version. This PR restores support for the v2 protocol version unless the server is explicitly configured to use the V3 protocol.
> update v2 proxyValidate to observe v3ForwardCompatible flag

- support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/web/flow/DelegatedClientAuthenticationAction.java
Hello!
It may happen that you configure PAC4J clients to contain a mix of direct and indirect clients. Then, whenever the control flow reaches prepareForLoginPage(), an exception can occur because the current code counts with indirect clients only. This fix should filter-out direct clients before a type cast.
To hit the bug:
- Configure your PAC4J clients to have some indirect and direct clients (some are in the basic CAS configuration)
- Perform a classic login (without any client name)
(If you are OK with this change, I can also prepare the same pull request for master.)
> Fix of PAC4J client action - Prevent typecast failure [branch 5.1.x]

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/oauth/OAuthProperties.java
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/OAuth20AccessTokenController.java
Enables CAS Throttle to be configured for accessing an OAuth token.  Prevents brute force attacks on OAuth configured CAS on the /accessToken path.  Similar to the CAS Rest configuration for CAS Throttle.
Also reverts change to /accessToken from GET back to POST.  Please see https://tools.ietf.org/html/rfc6749#section-4.1.3.  Plus the CAS documentation also specifies it should be a POST and not a GET.
> Add cas throttle to o auth

- core/cas-server-core/src/main/java/org/apereo/cas/DefaultCentralAuthenticationService.java
Previously the `Assertion` returned from the `validateServiceTicket` api would contain the `Service` object that the ticket was originally issued for. This behavior appears to have changed when we bootified CAS, now `validateServiceTicket` returns a `Service` object based off of the validation request itself.
I think when validating an issued ticket, after we verify the service ticket is valid for the supplied service, we should be performing the various policy decisions against the Service object the ticket was issued for and not against the Service object generated from the validation endpoint itself. This will allow any auth policy decisions to be made based on the original permission request by the user, and not on the validation request made by a client server.
My use case: I'm …
> Use the service from when the service ticket was issued, not when we are validating it

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/oauth/OAuthProperties.java
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
- support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/web/flow/DelegatedClientAuthenticationAction.java
- support/cas-server-support-trusted-mfa/src/main/java/org/apereo/cas/trusted/authentication/api/MultifactorAuthenticationTrustRecord.java
Enables CAS Throttle to be configured for accessing an OAuth token. Prevents brute force attacks on OAuth configured CAS on the /accessToken path. Similar to the CAS Rest configuration for CAS Throttle.
> Enable use CAS throttling support with OAuth module.

- core/cas-server-core-logging/src/main/java/org/apereo/cas/logging/config/CasLoggingConfiguration.java
- core/cas-server-core-logging/src/main/java/org/apereo/cas/logging/web/ThreadContextMDCServletFilter.java
- docs/cas-server-documentation/installation/Logging.md
Closes #3032 
Add `alternateClientAddr` and `alternateServerAddr` [MDC](https://apereo.github.io/cas/development/installation/Logging.html#mapped-diagnostic-context) variables to support alternative headers defined for the `cas.audit.alternateClientAddrHeaderName` and `cas.audit.alternateServerAddrHeaderName` properties.
The above mentioned MDC variables will only return a value if `cas.audit.alternateClientAddrHeaderName` or `cas.audit.alternateServerAddrHeaderName` are defined. Otherwise, null will be returned. This is the same behavior if attempting to call a nonexistent MDC variable (ex. `%X{foo}`).
This implemented was tested by setting `cas.audit.alternateClientAddrHeaderName` to `X-FORWARDED-FOR` . After initiating a request  to CAS, the `alternateClientAddr` MDC variable contained …
> Add support for alternateClientAddr and alternateServerAddr MDC variables

- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java
**Cas Configuration:**
> CAS v5.1.5
> cas.pm.authn.enabled=true
**Use Case:**
When Authentication service raises `AccountPasswordMustChangeException`, CAS maps the error to view - `CasWebflowConstants.VIEW_ID_MUST_CHANGE_PASSWORD `. At this state, if `PasswordChangeAction` returns false or raises exception, CAS incorrectly shows Account Disabled page instead of 'CasWebflowConstants.VIEW_ID_MUST_CHANGE_PASSWORD' with error message.
**Cause:**
`PasswordManagementWebflowConfigurer` configures 3 views for Error event. Hence, whenever action returns error event, the flow shows AccountDisabled view.
**Fix:**
`VIEW_ID_ACCOUNT_DISABLED` was incorrectly configured and was registering itself as error event handler in to login flow.
> In current master, this issue seems to have implemented correctly …
> Issue #3040 - fixed Incorrect Error Transition Configuration for Login Flow

- api/cas-server-core-api-web/src/main/java/org/apereo/cas/services/web/support/AuthenticationAttributeReleasePolicy.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/core/authentication/AuthenticationAttributeReleaseProperties.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/core/authentication/AuthenticationProperties.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/core/authentication/ProtocolAttributeReleaseProperties.java
- core/cas-server-core-web/src/main/java/org/apereo/cas/config/CasCoreWebConfiguration.java
- core/cas-server-core-web/src/main/java/org/apereo/cas/services/web/support/DefaultAuthenticationAttributeReleasePolicy.java
- core/cas-server-core-web/src/main/java/org/apereo/cas/services/web/view/AbstractCasView.java
- core/cas-server-core-web/src/main/java/org/apereo/cas/services/web/view/AbstractDelegatingCasView.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-saml/src/main/java/org/apereo/cas/config/SamlConfiguration.java
- support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/web/view/AbstractSaml10ResponseView.java
- support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/web/view/Saml10FailureResponseView.java
- support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/web/view/Saml10SuccessResponseView.java
- support/cas-server-support-saml/src/test/java/org/apereo/cas/support/saml/web/view/Saml10FailureResponseViewTests.java
- support/cas-server-support-saml/src/test/java/org/apereo/cas/support/saml/web/view/Saml10SuccessResponseViewTests.java
- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/config/CasValidationConfiguration.java
- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/view/Cas10ResponseView.java
- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/view/Cas20ResponseView.java
- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/view/Cas30JsonResponseView.java
- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/view/Cas30ResponseView.java
- support/cas-server-support-validation/src/test/java/org/apereo/cas/web/view/Cas10ResponseViewTests.java
- support/cas-server-support-validation/src/test/java/org/apereo/cas/web/view/Cas20ResponseViewTests.java
- support/cas-server-support-validation/src/test/java/org/apereo/cas/web/view/Cas30ResponseViewTests.java
Currently it's an all or nothing approach when including authentication protocol attributes in the CAS validation response. This causes problems when an `AuthenticationMetaDataPopulator` puts data in the Authentication attributes that is meant for internal use only within AuthenticationPolicies. 
This PR is designed to provide more fine grained control over which authentication protocol attributes can be released.
There are 2 new configuration parameters:
`cas.authn.authenticationAttributeRelease.neverRelease`
`cas.authn.authenticationAttributeRelease.onlyRelease`
the `neverRelease` configuration property indicates authentication attributes that should never be released.
the `onlyRelease` configuration property will allow only the specified authentication attributes to be released. the …
> Provide a mechanism to limit authentication protocol attributes released

- core/cas-server-core-authentication/src/main/java/org/apereo/cas/authentication/handler/support/AbstractUsernamePasswordAuthenticationHandler.java
- core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/handler/support/SimpleTestUsernamePasswordAuthenticationHandler.java
- core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/handler/support/SimpleTestUsernamePasswordHandlerTests.java
any subclass of `UsernamePasswordCredential` was not being accepted by `AbstractUsernamePasswordAuthenticationHandler`
> Fix UserPassAuthnHandler accepting UserPassCredential subclasses

- core/cas-server-core/src/main/java/org/apereo/cas/DefaultCentralAuthenticationService.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/config/SamlIdPConfiguration.java
When processing `grantServiceTicket()` make sure various access checks are performed against the actual service authenticating, not against the CAS SAML/OAuth intermediate endpoint.
> Fix grantServiceTicket permission checks for SAML services

- support/cas-server-support-actions/src/main/java/org/apereo/cas/web/config/CasSupportActionsConfiguration.java
- support/cas-server-support-actions/src/main/java/org/apereo/cas/web/flow/GenerateServiceTicketAction.java
- support/cas-server-support-actions/src/main/java/org/apereo/cas/web/flow/InitialFlowSetupAction.java
- support/cas-server-support-actions/src/test/java/org/apereo/cas/web/flow/InitialFlowSetupActionCookieTests.java
the `registeredService` that was present in the webflow (and accessed inside Thymeleaf templates) wasn't taking `ServiceSelectionStrategies` into account.
I also found some unnecessary duplicate logic in the process. (at least as far as I can tell)
> Fix registeredService in webflow for SAML auth

- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/PasswordValidator.java
- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java
- webapp/resources/templates/casExpiredPassView.html
- webapp/resources/templates/fragments/pwdupdateform.html
This PR will fix `NullPointerExcetion` which is raised when on Password Update page (`casMustChangePassView` and `casExpiredPassView`), user submits the form with empty passwords.
Following changes were made;
- Added empty text check into `PasswordValidator`
- Disabled submit button on form load
- Added missing `pm.js` on expired password view page
> Issue - 5.1.x => NullPointerException when Empty passwords are given on Password Update Form

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/OAuth20CasCallbackUrlResolver.java
- support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/web/controllers/OidcAuthorizeEndpointController.java
Fix OIDC errors
- on statup when OIDC dependency is added 
```
Caused by: java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'oidcAuthorizeController' method
public org.springframework.web.servlet.ModelAndView org.apereo.cas.support.oauth.web.endpoints.OAuth20AuthorizeEndpointController.handleRequestPost(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception
to {[/oauth2.0/authorize],methods=[POST]}: There is already 'authorizeController' bean method
public org.springframework.web.servlet.ModelAndView org.apereo.cas.support.oauth.web.endpoints.OAuth20AuthorizeEndpointController.handleRequestPost(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception mapped.
```
Commit [Allow …
> bug fix OIDC errors

- docs/cas-server-documentation/installation/Installing-ServicesMgmt-Webapp.md
- support/cas-server-support-pm/src/main/java/org/apereo/cas/pm/config/PasswordManagementConfiguration.java
- support/cas-server-support-pm/src/test/java/org/apereo/cas/pm/impl/JsonResourcePasswordManagementServiceTests.java
- support/cas-server-support-pm/src/test/resources/pm.properties
- webapp/resources/templates/fragments/pwdupdateform.html
This PR is a followup to [#3067](https://github.com/apereo/cas/pull/3067). It will add Password Validation routine which will validate password against following rules;
- Password should not be empty
- It should match to the configured Password Policy Pattern
> PasswordValidator routine added

- support/cas-server-support-electrofence/src/main/java/org/apereo/cas/impl/calcs/DateTimeAuthenticationRequestRiskCalculator.java
Count all TGT related events that happened between "windowInHours before" and
"windowInHours after" current authentication attempt. Currently many false
positives alarms arise as the check takes into account only those events that
happened exactly at "windowInHours before" or "windowInHours after" or at the
same hour.
> 5.1.x-Fix windowInHours checking.

- api/cas-server-core-api-configuration/src/main/java/org/apereo/cas/configuration/model/core/CasServerProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-shell/src/main/java/org/apereo/cas/shell/commands/AddPropertiesToConfigurationCommand.java
When you use the shell with a non-cas property, the name is usually not the full property name but the id is correct so this uses the id instead. 
build.cmd cli -sh 
add-property -group tomcat
If you try that without this patch you will see the results aren't useful.
> Use id instead of name when adding properties to property file in cli shell

- api/cas-server-core-api-webflow/src/main/java/org/apereo/cas/web/flow/CasWebflowConstants.java
- support/cas-server-support-basic/src/main/java/org/apereo/cas/web/flow/BasicAuthenticationWebflowConfigurer.java
- support/cas-server-support-digest-authentication/src/main/java/org/apereo/cas/digest/web/flow/DigestAuthenticationWebflowConfigurer.java
- support/cas-server-support-generic-remote-webflow/src/main/java/org/apereo/cas/web/flow/RemoteAddressWebflowConfigurer.java
- support/cas-server-support-openid-webflow/src/main/java/org/apereo/cas/web/flow/OpenIdWebflowConfigurer.java
- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/Pac4jWebflowConfigurer.java
- support/cas-server-support-scim/src/main/java/org/apereo/cas/web/flow/ScimWebflowConfigurer.java
- support/cas-server-support-spnego-webflow/src/main/java/org/apereo/cas/web/flow/SpengoWebflowConfigurer.java
- support/cas-server-support-token-webflow/src/main/java/org/apereo/cas/web/flow/TokenWebflowConfigurer.java
- support/cas-server-support-trusted-webflow/src/main/java/org/apereo/cas/web/flow/TrustedAuthenticationWebflowConfigurer.java
- support/cas-server-support-wsfederation-webflow/src/main/java/org/apereo/cas/web/flow/WsFederationWebflowConfigurer.java
- support/cas-server-support-x509-webflow/src/main/java/org/apereo/cas/web/flow/X509WebflowConfigurer.java
`TRANSITION_ID_SEND_TICKET_GRANTING_TICKET` duplicated `STATE_ID_SEND_TICKET_GRANTING_TICKET`.
The pattern for naming CAS webflow constants is to use `STATE_ID_` for any state id's. So, consolidate the duplicate constants to that.
> Consolidate duplicate state id constant

- api/cas-server-core-api-configuration/src/main/resources/META-INF/spring.factories
This is duplicated in the core/cas-server-core-configuration
> Delete spring.factories from api/cas-server-core-api-configuration

- support/cas-server-support-themes/src/main/java/org/apereo/cas/services/web/ServiceThemeResolver.java
fixed dynamic theme, execute grovvy script if it exists.
by default, `ResourceUtils.getRawResourceFrom(rService.getTheme())` is return a `FileSystemResource `, But  do not want to a `FileSystemResource` that is a ordinary theme name. so execute groovy script if it is exists.
> fixed dynamic theme

- core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/services/ReturnRestfulAttributeReleasePolicy.java
https://github.com/apereo/cas/blob/3c23af44fcb69e4918fcea8da8f86738acd75702/core/cas-server-core-util/src/main/java/org/apereo/cas/util/HttpUtils.java#L81
---
`service.getId()` is long type. 
There will be case string exception, there require string type.
It is require string before append params to url.
> RestfulAttribute case string exception

- support/cas-server-support-mongo-core/src/main/java/org/apereo/cas/mongo/MongoDbConnectionFactory.java
This patch corrects the handling of MongoDB connection strings in the **MongoDbConnectionFactory**.
When configuring CAS to work with MongoDB, you have a choice of
1. Using several properties of the form **${configurationKey}.mongo._whatever_** to specify the username, password, host(s), port(s), database name, replica set name, etc.  of the MongoDB instance, or
2. Specifying all of those values in the form of a [MongoDB connection string](https://docs.mongodb.com/v3.4/reference/connection-string/) to the **${configurationKey}.mongo.clientUri** property.
The MongoDB documentation recommends using a replica set in production. To configure a Mongo client (in this case, the java driver used by CAS) to use a replica set, you give it a comma-separated list of hosts (and ports, if non-standard …
> Fix handling of MongoDB connection string (clientUri) in MongoDbConnectionFactory

- support/cas-server-support-mongo-core/src/main/java/org/apereo/cas/mongo/MongoDbConnectionFactory.java
This patch applies the same fix to MongoDbConnectionFactory that PR#3090 applied in the 5.2.x branch.
Briefly, it corrects the way MongoDbConnectionFactory processes MongoDb connection strings (essentially by removing the code that "messed with" them and instead just passing them to the Mongo java driver to deal with).
Note: I included Misagh's change to the original patch that cleans up the extra import statement that was causing checkstyle to fail.
> Apply PR#3090 from 5.2.x (fix clientUri handling in MongoDbConnectionFactory)

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/metadata/ConfigurationMetadataGenerator.java
This is your fix, I couldn't cherry pick it b/c it moved but I copied it from master branch and tested it locally. 
I figured it might as well be included if you cut another release on 5.2.x.
> backport - fix issue with inherited fields not getting config metadata

- core/cas-server-core-configuration/src/test/java/org/apereo/cas/configuration/support/CasConfigurationJasyptCipherExecutorTests.java
- support/cas-server-support-consent-ldap/src/test/java/org/apereo/cas/consent/LdapConsentRepositoryTests.java
- support/cas-server-support-ldap/src/test/java/org/apereo/cas/adaptors/ldap/AbstractLdapTests.java
- support/cas-server-support-throttle-jdbc/src/main/java/org/apereo/cas/web/support/InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapter.java
- support/cas-server-support-throttle-jdbc/src/test/java/org/apereo/cas/web/support/InspektrThrottledSubmissionByIpAddressAndUsernameHandlerInterceptorAdapterTests.java
- support/cas-server-support-throttle-jdbc/src/test/resources/casthrottle.properties
- support/cas-server-support-x509-core/src/test/java/org/apereo/cas/adaptors/x509/authentication/handler/support/AbstractX509LdapTests.java
- support/cas-server-support-x509/src/test/java/org/apereo/cas/adaptors/x509/authentication/ldap/LdaptiveResourceCRLFetcherTests.java
I looked into the ldap tests having issues when running in parallel and I made a change thinking that the tests were running in parallel in the same JVM (where static variables might be issue) but I realize now they are running in parallel in different JVMs. I think there may still be a case where if two different LDAP tests (using different servers running on different ports) both happened to run in same JVM then the initDirectoryServer() method wouldn't create a new server (with new port) if there was already another server running (DIRECTORY !=null). This change keeps DIRECTORYs in a map with the port as key so as long as different test classes use different ports for their servers then there should be no risk of them using the wrong one. If this isn't the issue then please ignore. …
> LDAP Tests - parallel issue?

- webapp-mgmt/cas-management-webapp/src/app/form/attribute-release-policies/attribute-release-policies.component.ts
- webapp-mgmt/cas-management-webapp/src/app/form/mappedattributes/mappedattributes.component.html
- webapp-mgmt/cas-management-webapp/src/app/form/mappedattributes/mappedattributes.component.ts
This pull request fixes issues with changing the attribute release policy between ReturnAllowed and ReturnMapped that was introduced during some screen refactoring in the CAS Management App.  
This issue was reported by Ludovic Senecaux on the CAS User Mailing list
> Fixes switching of Attribute Release policy for services

- webapp/cas-server-webapp-config/src/main/java/org/apereo/cas/config/CasWebAppConfiguration.java
- webapp/cas-server-webapp-config/src/test/java/org/apereo/cas/WiringConfigurationTests.java
This allows for locale change via request parameter on all the MVC endpoints,
e.g. /consentReview, /error.
Right now, the locale request parameter is only processed in the flows.
Maybe a candidate for master as well?
> [5.2.x] Add localeChangeInterceptor to root context

- core/cas-server-core-authentication-mfa/src/main/java/org/apereo/cas/authentication/RestMultifactorAuthenticationProviderBypass.java
Currently, the parameters are added as lists which generates the following error:
```java
2018-01-03 13:04:13,374 ERROR [org.apereo.cas.util.HttpUtils] - <java.util.ArrayList cannot be cast to java.lang.String>
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_77]
at org.apereo.cas.util.HttpUtils.buildHttpUri(HttpUtils.java:81) ~[cas-server-core-util-5.2.1.jar:5.2.1]
at org.apereo.cas.util.HttpUtils.execute(HttpUtils.java:69) ~[cas-server-core-util-5.2.1.jar:5.2.1]
at org.apereo.cas.authentication.RestMultifactorAuthenticationProviderBypass.shouldMultifactorAuthenticationProviderExecute(RestMultifactorAuthenticationProviderBypass.java:48) ~[cas-server-core-authentication-mfa-5.2.1.
````
This PR …
> Fix the REST mfa bypass call

- api/cas-server-core-api-util/src/main/java/org/apereo/cas/CipherExecutor.java
... or more broadly, ClassCastExceptions thrown when a property value's type doesn't match the decryptor.  In the spirit of #2474, but in a way that will work with the use of Generics that have been included since then.
> Trap ClassCastExceptions caused by non-String YAML properties

- webapp-mgmt/cas-management-webapp/src/app/form/access-strategy/access-strategy.component.html
- webapp-mgmt/cas-management-webapp/src/app/form/access-strategy/access-strategy.component.ts
- webapp-mgmt/cas-management-webapp/src/app/form/attribute-release-policies/attribute-release-policies.component.html
- webapp-mgmt/cas-management-webapp/src/app/form/attribute-release-policies/attribute-release-policies.component.ts
- webapp-mgmt/cas-management-webapp/src/app/form/form.component.html
- webapp-mgmt/cas-management-webapp/src/app/form/rejectedattributes/rejectedattributes.component.html
- webapp-mgmt/cas-management-webapp/src/app/form/rejectedattributes/rejectedattributes.component.ts
- webapp-mgmt/cas-management-webapp/src/app/services/services.component.html
This PR fixes the following issues in the CAS Management App reported by Arnold Bergner form the cas-user mailing list:
- editing or creating a service, “Access Strategy” tab, “Required Attribues” is pre-filled with name = value = attribute name for all available attributes. Before saving, I have to delete all these lines, or service access is not possible. It would be better if these lines were not there.
- duplicating a service, there is no “save” button, and the “require all attributes” flag is checked (this was a bug when creating a new service, too)
- the footer line is cutting off part of the forms. for some tabs, this makes it impossible to edit certain fields. (using firefox)
> 5.2.x Mgmt App Fixes

- support/cas-server-support-surrogate-authentication/src/main/java/org/apereo/cas/authentication/event/SurrogateAuthenticationEventListener.java
When the principal has no email attribute, the `SurrogateAuthenticationEventListener` throws a NPE:
```java
2018-01-10 08:06:23,205 WARN [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] - <null>
java.lang.NullPointerException: null
at org.apereo.cas.authentication.event.SurrogateAuthenticationEventListener.notify(SurrogateAuthenticationEventListener.java:64) ~[cas-server-support-surrogate-authentication-5.2.1.jar:5.2.1]
at org.apereo.cas.authentication.event.SurrogateAuthenticationEventListener.handleSurrogateAuthenticationFailureEvent(SurrogateAuthenticationEventListener.java:40) ~[cas-server-support-surrogate-authentication-5.2.1.jar:5.2.1]
```
> Fix NPE on surrogate mail notification

- support/cas-server-support-surrogate-authentication/src/main/java/org/apereo/cas/authentication/event/SurrogateAuthenticationEventListener.java
When the principal has no email attribute, the `SurrogateAuthenticationEventListener` throws a NPE:
```java
2018-01-10 08:06:23,205 WARN [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] - <null>
java.lang.NullPointerException: null
at org.apereo.cas.authentication.event.SurrogateAuthenticationEventListener.notify(SurrogateAuthenticationEventListener.java:64) ~[cas-server-support-surrogate-authentication-5.2.1.jar:5.2.1]
at org.apereo.cas.authentication.event.SurrogateAuthenticationEventListener.handleSurrogateAuthenticationFailureEvent(SurrogateAuthenticationEventListener.java:40) ~[cas-server-support-surrogate-authentication-5.2.1.jar:5.2.1]
```
> Fix NPE on surrogation mail notification

- support/cas-server-support-ignite-ticket-registry/src/main/java/org/apereo/cas/config/IgniteTicketRegistryTicketCatalogConfiguration.java
Change on ProxyTicketDefinition storage name from "serviceTicketsCache" to "proxyTicketsCache" to fix duplicate cache name issue which raise IgniteCheckException on startup.
Best Regards,
Alexandre de Pellegrin
> Fix IgniteCheckException on startup due to duplicate cache names

- support/cas-server-support-pm-jdbc/src/main/java/org/apereo/cas/pm/jdbc/JdbcPasswordManagementService.java
- support/cas-server-support-pm-jdbc/src/test/java/org/apereo/cas/pm/jdbc/JdbcPasswordManagementServiceTests.java
Fix to prevent an exception when an invalid username is used during the password reset flow
> Fix to prevent an exception when an invalid username is used during the password reset flow

- core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/crypto/PrivateKeyFactoryBean.java
- core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/crypto/PublicKeyFactoryBean.java
Hi, 
I want to submit a small patch for an issue I met on Google Apps integration on CAS 5.2.1. FYI, I already have the Google Apps integration working on our old CAS 3.4.5.
Best regards,
Alex
Main reason for this fix : 
--------------------------------
Server is not able to load Google Apps Public/Private keys on startup because it puts resource inputstream into a byte array which size is always 0.
Details :
-----------
org.springframework.boot.loader.data.RandomAccessDataFile$DataInputStream extends InputStream but doesn't override available() which returns 0 by default (and should be overriden according to java.io.InputStream javadoc). An alternative solution consists on using Spring Resource class contentLength() method instead.
Proof of the issue : 
-------------------------
Here is …
> Fix on PublicKeyFactoryBean and PrivateKeyFactoryBean used to load Google Apps certificates (cas-server-core-util-5.2.1) 

- support/cas-server-support-surrogate-authentication-rest/src/main/java/org/apereo/cas/authentication/surrogate/SurrogateRestAuthenticationService.java
- support/cas-server-support-surrogate-authentication-rest/src/main/java/org/apereo/cas/config/SurrogateRestAuthenticationConfiguration.java
My previous fix was not very good. I moved the classes without changing the package names inside the classes :-(
Notice that it did compile though, which lead me to think it was ok.
This time, it compiles and I tested it successfully.
Will submit the same PR for the master.
> Fix packages names (again) on REST surrogation support

- core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/CookieRetrievingCookieGenerator.java
At the moment the CAS ticket granting cookie max age is set to cas.tgc.rememberMeMaxAge whenever remember me is enabled (and also when remember me is disabled but a remember me form parameter is passed).  This change will only apply the remember me max age cookie expiry when both tgt remember me is enabled and remember me is checked.
> Fix the TGC cookie expiration when remember me is enabled

- support/cas-server-support-memcached-core/src/main/java/org/apereo/cas/memcached/kryo/CloseableKryoFactory.java
Kryo throws an IllegalArgumentException when RememberMe has been enabled, since a RememberMeUsernamePasswordCredential object is being stored instead of a UsernamePasswordCredential object.
I've imported the `RememberMeUsernamePasswordCredential` class and made the `CloseableKryoFactory` register the class along with the `UsernamePasswordCredential`
Since CAS does not register the classes with an associated int ID, I don't see any bad consequences.
The original stacktrace: 
```
2018-01-31 10:50:45,606 ERROR [org.apereo.cas.ticket.registry.MemcachedTicketRegistry] - <Failed adding [TGT-***************************************************************EDBwrsQ734-AndersMacBookPro]>
com.esotericsoftware.kryo.KryoException: com.esotericsoftware.kryo.KryoException: …
```
> Attempt to fix an IllegalArgumentException in the MemcachedTicketRegistry

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/mongo/BaseMongoDbProperties.java
http://api.mongodb.com/java/current/com/mongodb/WriteConcern.html
NORMAL is already deprecated, and fallback was UNACKNOWLEDGED, which could case fail in CAS. 
(The application could not find a ticket that was already created.)
> Mongo default writeConcern to ACKNOWLEDGED

- core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/BaseTicketSerializers.java
We've experienced performance issues with ticket serialization in `MongoDbTicketRegistry`.
Turned out the bottleneck is the continuous instantiation of `ObjectMapper`.
> Ticket serialization performance fix

- core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/actions/CasDefaultFlowUrlHandler.java
Closing no issues.
Instead of creating a StringBuilder for storing the prefix and a linkedHashMap for the sufix (flowExecutionKeyParameter) we can use the Collector.joining method.
> Use streams utilities instead of creating intermediate variables

- support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java
- support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/token/OidcIdTokenGeneratorService.java
We're using OpenId Connect (OIDC) for authentication with CAS and wanted to implement Single Logout (SLO).
That's when I realized the logout request from cas only contains the service ticket id, which is not available in out application and even not included in the id token during logging in, so we cannot match the session.
After investigating how to include the service ticket in the token, I found "jti" attribute a good place for it. OIDC docs about "jti":
"A unique identifier for the token, which can be used to prevent reuse of the token. These tokens MUST only be used once, unless conditions for reuse were negotiated between the parties; any such negotiation is beyond the scope of this specification."
IMHO service ticket is fullfilling those requirements in case of CAS OIDC.
> Use OAuth2 service ticket id as "jti" OIDC claim

- support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/RedisTicketRegistry.java
I encountered some issues with Redis and in case of an addition, the exception is swallowed. Like for update. While it's ok for retrieval and deletion.
I'm not sure if it's done on purpose, otherwise, this PR fixes it.
> Log exceptions for all Redis operations

- core/cas-server-core-authentication/src/main/java/org/apereo/cas/authentication/DefaultAuthenticationEventExecutionPlan.java
- core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/configurer/AbstractCasWebflowConfigurer.java
I change the implementation of "createEvaluateActionForExistingActionState" for fix the issue with the "remove all" action of "ActionList".
The problem was here : "action.getActionList().forEach(a -> action.getActionList().remove(a));".
This line of code remove only the first element but not throws an java.util.ConcurrentModificationException (I don't know why, an idea ?).
> fix : remove all actions present in "ActionList", before only first element is removed

- api/cas-server-core-api-configuration/src/main/java/org/apereo/cas/configuration/CasConfigurationProperties.java
This change allows projects that use cas modules as dependencies to provide their own CasConfigurationProperties implementation.  Specifically used for CAS Management to all the project to be built using maven overlay.
> Mark CasConfigurationProperties @ConditionalOnMisssingBean

- webapp/cas-server-webapp-config/src/main/java/org/apereo/cas/config/CasApplicationContextConfiguration.java
This bean is actually a duplicate of the bean already created via the
`spring.aop.auto=true` configuration. Because there were 2 AdvisorAutoProxyCreator
beans present in the application context the `@Transactional` advice was being
applied twice to beans.
I discovered the duplicate advice when I was attempting to include some additional advice that I needed to run before the `@Transactional` advice was run. My advice was only being picked up by the other proxy creator, and this proxy creator was wrapping the objects in a second proxy with both proxies applying the `@Transactional` advice.
> remove unnecessary DefaultAdvisorAutoProxyCreator

- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java
Adds support for SAML binding HTTP-POST as configured by:
```
cas.authn.pac4j.saml[0].destinationBinding=urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
```
This was not supported because [pac4j creates a redirect action of type SUCCESS](https://github.com/pac4j/pac4j/blob/400cec0c94a93ba80dc43208c9e5d179dfd70af4/pac4j-saml/src/main/java/org/pac4j/saml/redirect/SAML2RedirectActionBuilder.java) with no location but with content. 
The content contains the result of Velocity template which has an HTML with a form that does the POST action and a script that executes the form automatically. 
But the [cas-pac4j integration code](https://github.com/apereo/cas/blob/fb21bd0045590c821d5f588276409a74f062e4f4/support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/web/f …
> Allowing SAML binding HTTP-POST by supporting RedirectAction SUCCESS

- core/cas-server-core-cookie-api/src/main/java/org/apereo/cas/web/support/CookieRetrievingCookieGenerator.java
we need to sanitize the cookie domain to be null if it is not set so that the TGC will actually be tracked by a web browser. This behavior existed existed in CAS pre-5.3.0, it looks like it got dropped when implementing lombok setters
> fix TGC generation

- support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java
> Prevent overflow in MongoDbTicketRegistry.getExpireAt (5.2.x)

- support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java
A sufficiently large TTL (eg 30 days in seconds: 2592000) will overflow a 32 bit signed integer when multiplied by 1000, which causes the getExpireAt return value to occur in the past.  By leaving the TTL as a long this class of bug is prevented until a TTL of ~292471208 years is used.
> Prevent overflow in MongoDbTicketRegistry.getExpireAt

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jSamlProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/support/authentication/Pac4jAuthenticationEventExecutionPlanConfiguration.java
This PR provides missing configuration parameter to enable SAML2.0 AttributeConsumingServiceIndex
> Provides missing configuration to specify SAML2.0 AttributeConsumingServiceIndex

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/support/JpaBeans.java
- core/cas-server-core-cookie/src/main/java/org/apereo/cas/web/config/CasCookieConfiguration.java
- core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/executor/WebflowExecutorFactory.java
- support/cas-server-support-jpa-ticket-registry/src/main/java/org/apereo/cas/config/JpaTicketRegistryConfiguration.java
- support/cas-server-support-oauth-core/src/main/java/org/apereo/cas/config/OAuthProtocolTicketCatalogConfiguration.java
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
- webapp/cas-server-webapp-config/src/main/java/org/apereo/cas/config/CasMetricsConfiguration.java
Commit 0953eb3958d2ae4482b7053ad894c1fde62f2210 added duration support for a number of properties, however in some cases it converted the durations to milliseconds where seconds were expected.  This PR fixes those cases.
> Fix some instances of passing milliseconds where seconds were expected.

- webapp/cas-server-webapp-tomcat/src/main/java/org/apereo/cas/config/CasEmbeddedContainerTomcatConfiguration.java
This PR converts `CasEmbeddedContainerTomcatConfiguration` to use a `EmbeddedServletContainerCustomizer` instead of providing a `TomcatEmbeddedServletContainerFactory` so that CAS implementations can override the factory themselves (eg to enable JNDI) whilst also benefitting from the CAS tomcat configuration properties.
> Convert Tomcat config from overriding the factory bean to providing a customizer

- ci/run-couchbase-server-v5.sh
- ci/run-couchbase-server.sh
- support/cas-server-support-couchbase-service-registry/src/test/java/org/apereo/cas/services/CouchbaseServiceRegistryDaoTests.java
- support/cas-server-support-couchbase-ticket-registry/src/test/java/org/apereo/cas/ticket/registry/CouchbaseTicketRegistryTests.java
Verified ticket registry and services registry against both v4 and v5 of Couchbase by making unit tests (integration tests against dockerized Couchbase instance) pass for both versions. No code changes required except the script for docker image to use password for bucket for v4 and user password for v5 (username added must match the bucket name in use), and unit tests to reflect the bucket names and passwords by adding additional properties values right inside the @SpringBootTest annotation.
The separate `ci/run-couchbase-server-v5.sh` is introduced, but I'm not sure how to incorporate that into the travis machinery, etc.
> Couchbase v5

- support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/discovery/OidcServerDiscoverySettings.java
Adding the @Getter lombok annotation made is so Jackson tried to dump the entire cas config to JSON, it didn't get all the way through but it dumped part of the config to the browser before it got an exception and stopped.
> Avoid serializing objects that shouldn't be part of oidc well-known endpoint

- docs/cas-server-documentation/installation/Configuring-SAML2-Authentication.md
This is only a documentation change that allows users to follow a broken link to the learn how to configure SAML.
> Fix broken html links

- webapp-mgmt/cas-management-webapp/src/app/form/samlservicespane/samlservicespane.component.html
- webapp-mgmt/cas-management-webapp/src/domain/form-data.ts
This PR will fix a bug described by David Curry in the cas-user email list.  There was a naming difference between the field sending the options in FormData from the server and the name of the field that was being used in the front end client.  This change fixes the client to match the field name sent from the server.
> Fixes samlAttributeName formats options from not appearing in dropdown

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/web/tomcat/CasEmbeddedApacheTomcatClusteringProperties.java
- webapp/cas-server-webapp-tomcat/src/main/java/org/apereo/cas/config/CasEmbeddedContainerTomcatConfiguration.java
- webapp/cas-server-webapp-tomcat/src/main/java/org/apereo/cas/config/CasTomcatEmbeddedServletContainerFactory.java
This should be logically the same as it was previously but extracts the anonymous `TomcatEmbeddedServletContainerFactory` into a separate class so that CAS implementations can use it as a base for their own `EmbeddedServletContainerFactory` customisation.
> Move anonymous TomcatEmbeddedServletContainerFactory to separate class

- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/dynamodb/AbstractDynamoDbProperties.java
- core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/model/support/dynamodb/DynamoDbTicketRegistryProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-dynamodb-service-registry/src/main/java/org/apereo/cas/services/DynamoDbServiceRegistryFacilitator.java
- support/cas-server-support-dynamodb-ticket-registry/src/main/java/org/apereo/cas/config/DynamoDbTicketRegistryTicketCatalogConfiguration.java
- support/cas-server-support-dynamodb-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/DynamoDbTicketRegistryFacilitator.java
Added the ability to specify the name of the DynamoDb tables and also the ability to skip table creation on startup (This way if CAS doesn't have permissions to create tables your AWS account it won't throw an error on the 'create table if not exist' method).
Already added the info to Configuration-Properties.md the values are:
```
cas.serviceRegistry.dynamoDb.preventTableCreationOnStartup
cas.ticket.registry.dynamoDb.preventTableCreationOnStartup
cas.ticket.registry.dynamoDb.serviceTicketsTableName
cas.ticket.registry.dynamoDb.proxyTicketsTableName
cas.ticket.registry.dynamoDb.ticketGrantingTicketsTableName
cas.ticket.registry.dynamoDb.proxyGrantingTicketsTableName
```
Note: They have default values of what the behavior is expected before this change
This is my first time contributing so …
> DynamoDb naming tables and prevent table creation on startup (5.2.x)

- docker/Dockerfile
Docker command is not valid: `cas-overlay/bin/run-cas.sh` is relative to `/cas-overlay` and is being resolved to `/cas-overlay/cas-overlay/bin/run-cas.sh` file which does not exist.
This should be `bin/run-cas.sh` (which is resolved to `/cas-overlaybin/run-cas.sh`).
Steps to reproduce the issue:
`docker run -p 8080:8080 apereo/cas`
causes:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"cas-overlay/bin/run-cas.sh\": stat cas-overlay/bin/run-cas.sh: no such file or directory": unknown.
ERRO[0000] error waiting for container: context canceled
```
After this fix it works as expected.
> Fix Docker command path

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenAuthorizationCodeGrantRequestExtractor.java
Two changes:
- the `client_id` parameter is replaced by the current pac4j user profile to know the current authenticated OAuth client
- the service of the OAuth code must match the service used to call the token endpoint.
> Improve OAuth token checks

- core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/config/CasWebflowContextConfiguration.java
Without this change the `DefaultLoginWebflowConfigurer.initialize()` method is run twice, which causes the `genericSuccessViewAction` Action to be added twice and crash on the second run when a default redirect url is defined.
> Don't initialize DefaultLoginWebflowConfigurer twice

- support/cas-server-support-pac4j-core/src/main/java/org/apereo/cas/web/pac4j/DelegatedSessionCookieManager.java
- support/cas-server-support-pac4j-core/src/main/java/org/apereo/cas/web/pac4j/SessionStoreCookieSerializer.java
- support/cas-server-support-pac4j-webflow/src/test/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationActionTests.java
- support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/Pac4jDelegatedAuthenticationConfiguration.java
@mmoayyed this patch adds twitter (and oauth1 request token in general) support to the DelegatedSessionCookieManager.  It also makes the SessionStoreCookieSerialiser an overridable @Bean.
Note that the Jackson mixin is currently stored in the @Configuration class for want of a better place to put it, happy to takes suggestions of a more appropriate place for it.
> Changes to support OAuth1RequestToken deserialisation for SessionStoreCookie

- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/DelegatedClientWebflowManager.java
- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java
@mmoayyed this is a 2nd issue that I ran into with twitter delegated login - the TST ticket id was lost when twitter redirected back to CAS.  As a starting point I'm proposing storing the ticket id in the Session Cookie.
> Store TST id in session for OAuth 1.0 delegated clients

- support/cas-server-support-validation/src/main/java/org/apereo/cas/web/config/CasValidationConfiguration.java
Without this a PGT is not delivered for /cas/serviceValidate?pgtUrl=url
> the v2 serviceValidate controller should use the proxy20Handler

- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/config/DelegatedAuthenticationWebflowConfiguration.java
The Spring Boot `EmbeddedServletContainerAutoConfiguration` will attempt to construct all `ErrorViewResolver` `@Bean`s via the `ErrorPageRegistrarBeanPostProcessor` before loading the rest of the `ApplicationContext`.  Because the `DelegatedAuthenticationErrorViewResolver` was defined in a `@Configuration` with `@Autowired` dependencies, this forced the (non-lazy) `@Autowired` dependencies to be constructed before the container startup.  This has implications for CAS components using `DataSource` objects that were supposed to be obtained from JNDI because the components will be constructed before JNDI is setup by the servlet container initialisation.
This patch simply makes the `pac4jErrorViewResolver` static inside the `@Configuration` so that it can be constructed without constructing …
> Make ErrorViewResolver static to avoid instantiation of all @Autowired beans

- support/cas-server-support-themes/src/main/java/org/apereo/cas/services/web/CasThymeleafOutputTemplateHandler.java
- Change in 0f1d011 broke th:replace, [[#{some.message(arg)}]] and structureHandler.replaceWith in Thymeleaf
> Revert change from 0f1d011

- support/cas-server-support-actions/src/main/java/org/apereo/cas/web/flow/logout/TerminateSessionAction.java
Note that if pac4j is using the default `SessionStore` then the `ProfileManager.logout()` call will still force creation of a session if one didn't exist already.  This patch just prevents forcing the creation of a new session after invalidation even if the pac4j `REQUESTED_URL` was not set.
> Avoid forced session creation in TerminateSessionAction

- core/cas-server-core-configuration-api/src/main/java/org/apereo/cas/configuration/DefaultCasConfigurationPropertiesSourceLocator.java
- core/cas-server-core-configuration/src/test/java/org/apereo/cas/configuration/support/DefaultCasConfigurationPropertiesSourceLocatorTests.java
- core/cas-server-core-configuration/src/test/resources/application.yml
- core/cas-server-core-configuration/src/test/resources/directory/application.yml
- core/cas-server-core-configuration/src/test/resources/directory/cas.properties
- core/cas-server-core-configuration/src/test/resources/standalone.properties
Ensures that `cas.standalone.configurationFile` has higher priority than `cas.standalone.configurationDirectory` which in turn has higher priority than classpath `application.yml`, so that external sources can override values in the bundled file.
> Ensure external property sources have higher priority in standalone mode

- core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/DefaultAuthenticationServiceSelectionPlan.java
- core/cas-server-core-services-authentication/src/main/java/org/apereo/cas/authentication/principal/AbstractServiceFactory.java
- core/cas-server-core-services-authentication/src/main/java/org/apereo/cas/authentication/principal/WebApplicationServiceFactory.java
- core/cas-server-core-services/src/test/java/org/apereo/cas/authentication/principal/WebApplicationServiceFactoryTests.java
- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java
- support/cas-server-support-pac4j-webflow/src/test/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationActionTests.java
Follows on from #3304 and fixes a few minor issues introduced
- Fix crash when no Service is resolved
- Fix missing auth providers on login when no Service is resolved
- Fix crash when creating the OAuth Callback Service on startup because no HTTP request is available
- Fix CAS `service` parameter being ignored
> Clean up for delegated auth redirects

- core/cas-server-core-web-api/src/main/java/org/apereo/cas/web/view/ThemeFileTemplateResolver.java
- core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/resolver/impl/mfa/request/RequestSessionAttributeMultifactorAuthenticationPolicyEventResolver.java
When reading a session attribute use the version of `getSession()` that doesn't create a session if none exists.
> Don't create sessions unnecessarily

- support/cas-server-support-shell/src/main/java/org/apereo/cas/shell/commands/ValidateEndpointCommand.java
- support/cas-server-support-shell/src/main/java/org/apereo/cas/shell/commands/ValidateLdapConnectionCommand.java
This update changes the validate-endpoint command-line function to include details that can be used to troubleshoot failed https client connection. An example of the output form a failed connection:
```
validate-endpoint --url https://expired.badssl.com
Trying to connect to [https://expired.badssl.com]
Setting connection timeout to [5000]
Could not connect to the host address [https://expired.badssl.com]
The error is: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
Here are the details:
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
Caused by: …
```
> TLS Connection Detailer

- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedAuthenticationWebflowConfigurer.java
- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java
Without this change an `AuthenticationException` would just display a stack trace error page.
> Allow delegated auth transaction to transition to the handle authentication failure state

- webapp/resources/templates/casDuoLoginView.html
This implements the iFrame as documented on https://duo.com/docs/duoweb.  This fixes issue with iFrame not displaying properly on mobile devices.  This also adds a tag for IE Edge that Duo recommends.
To configure/test, set up CAS with Duo enabled.  Use a mobile phone to authenticate, and confirm the Duo iFrame doesn't look really messed up.
Don't believe there are any limitations or side effects.
Not aware of any other merge requests that are related.
> Fix Duo iFrame on mobile devices

- core/cas-server-core-web/src/main/java/org/apereo/cas/config/CasCoreHttpConfiguration.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- Using the property **cas.httpClient.hostnameVerifier**=NONE|DEFAULT doesn't work as results  of an upper case issue
- Creation of **SSLConnectionSocketFactory** doesn't take into consideration CAS **HostnameVerifier** . Adding the function call in the constructor helps the issue
Hope this help
_Guy_
> Fix http client host name verifier

- support/cas-server-support-trusted-mfa-jdbc/src/test/java/org/apereo/cas/trusted/authentication/storage/JpaMultifactorAuthenticationTrustStorageTests.java
- support/cas-server-support-trusted-mfa/src/main/java/org/apereo/cas/trusted/authentication/api/MultifactorAuthenticationTrustRecord.java
not all JPA providers support storing milliseconds for recordDate
> truncate trusted device record dates to seconds

- support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/discovery/OidcServerDiscoverySettings.java
Regression:
[Required issuer](http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) is missing from openid connect metadata on the discovery endpoint.
This is one of the blockers for using openid connect.
Let's fix it.
> return issuer to oidc discovery endpoint

- support/cas-server-support-reports/src/main/java/org/apereo/cas/web/report/RegisteredServicesReportController.java
As `configureServiceRegistry` from `SamlIdPEndpointsConfiguration.class` and `CasOAuthConfiguration.class` use the same name (RegexRegistredService), which leads to duplicate key error.
> Use `getId` as key

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenAuthorizationCodeGrantRequestExtractor.java
Up to 5.2.4, the OAuthService used to be looked up by client id, e.g. via `OAuth20Utils#getRegisteredOAuthService`: see https://github.com/apereo/cas/blob/v5.2.4/support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenAuthorizationCodeGrantRequestExtractor.java#L63
In 5.2.5, instead, `OAuth20Utils#getRegisteredOAuthServiceByRedirectUri` is used: see https://github.com/apereo/cas/blob/v5.2.5/support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/ext/AccessTokenAuthorizationCodeGrantRequestExtractor.java#L72
I found this when upgrading some code from 5.2.4 to 5.2.5
> Lookup OAuthService by clientId, as pre 5.2.5

- docs/cas-server-documentation/protocol/REST-Protocol.md
When I started to use the previous sample code, it seemed out of date or wrong relative to the current pac4j library. This replaces the sample code with a full main method that worked to log in against a local cas server (deployed with rest support).
> update REST doc sample code to work with recent pac4j

- developer/Build-Process-5X.md
I found the following param is needed when building CAS on Windows:
-DskipNpmLint=true
when building CAS on Windows:
gradlew build install --parallel -x test -x javadoc -x check
due to line ending difference in npmLint
Would like to add that in to the doc for reference, thanks
> Update Doc: Add needed parameter for building CAS

- core/cas-server-core-monitor/src/main/java/org/apereo/cas/monitor/AbstractCacheHealthIndicator.java
Currently only the last map executed in the lambda has it's info printed out to the health endpoint.  This fix ensures all maps in the cache are printed.
> Fix to print all maps in a cache for heath endpoint

- docs/cas-server-documentation/installation/Monitoring-Statistics.md
After looking at #3361  again, there is some syntax problem. My previous PR is using:
```
<div class="alert"> .....   `/status`
```
instead of
```
<div class="alert"> .....    <code>/status</code>
```
So it is not highlighting properly (see blue box in https://apereo.github.io/cas/development/installation/Monitoring-Statistics.html)
This PR will solve this. Thanks!
> Refactor on "Inform user to use `/status/health` instead of `/status`"

- support/cas-server-support-surrogate-webflow/src/main/java/org/apereo/cas/web/flow/action/SurrogateInitialAuthenticationAction.java
This is a very simple change to allow the separator in a surrogate authentication credentials be of multiple characters long.
By default, the separator character is "+", which can be overridden via _cas.authn.surrogate.separator_ in _cas.properties_.  Single character separator is rather unfortunate because almost all characters on the keyboard are legal characters for use in an email address, and email addresses are very frequently used as usernames.  This means when the surrogate authentication separator is a single character, email address as username can easily trigger unintended surrogate authentication.
Example:
**foo+bar@host.net**: surrogate authentication (surrogate = "foo", primary = "bar@host.net), or just an unusual email address "foo+bar@host.net"?
By allowing multiple …
> Allow surrogate authentication separator to be of multiple characters.

- api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/ExpirationPolicy.java
- core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/support/BaseDelegatingExpirationPolicy.java
- core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/support/RememberMeDelegatingExpirationPolicyTests.java
- support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java
The Mongo Ticket Registry applies a Mongo expire index on the expireAt field.  Currently the expireAt field is based on the expiration policy's TTL.  In the case of a Remember Me policy TTL the active TTL depends on the TicketState whereas the existing code will only ever retrieve the default TTL.  Consequently, mongo will now delete Remember Me tickets based on this default TTL expireAt index before the Remember Me time period has expired.  This change allows the Mongo Registry to query the Ticket TTL based on the ticket attributes and therefore set the correct expireAt value.
> Fix the Mongo expireAt field for RememberMe TGTs (5.3.x)

- core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/configurer/DefaultLoginWebflowConfigurer.java
After refactoring `InitialAuthenticationRequestValidationAction` out of login-webflow.xml it was no longer the start action for the login webflow.  Consequently this meant that it and `TicketGrantingTicketCheckAction` are never run and amongst other things SSO doesn't work.
This patch simply makes the `DefaultWebflowConfigurer` set the start action explicitly.
> Reinstate the initialAuthnRequestValidationCheckAction as the first webflow action (5.3.x)

- style/checkstyle-rules.xml
- style/checkstyle-suppressions.xml
- support/cas-server-support-couchdb-service-registry/src/main/java/org/apereo/cas/services/CouchDbServiceRegistry.java
Includes `val` usage in couchdb service registry for validation.
> add checkstyle suppression for lombok.val

- support/cas-server-support-mongo-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/MongoDbTicketRegistry.java
Equivalent of #3387 for 5.3.x, without a change like this modifying a ticket timeout will cause a duplicate index exception.
> Before creating mongo indexes delete any index with the same key but different options (5.3.x)

- support/cas-server-support-cosmosdb-core/src/main/java/org/apereo/cas/cosmosdb/CosmosDbDocument.java
Removed @Slf4j as it is adding LOGGER field which is not mapped to properties in BasicPersistentEntity.
Making available for 5.3.1
> CosmosDB DocumentDBConverter Fixed

- style/checkstyle-rules.xml
fixes checkstyle rule for var case where type inference will fail.  (initialized with null)
> fix val rule for null initialized variables

- support/cas-server-support-gua/src/main/java/org/apereo/cas/gua/impl/LdapUserGraphicalAuthenticationRepository.java
Use ReturnAttributes.ALL_USER instead of ReturnAttributes.NONE in order to
retrieve imageAttribute from user's object.
> Use ReturnAttributes.ALL_USER instead of ReturnAttributes.NONE.

- support/cas-server-support-spnego-webflow/src/main/java/org/apereo/cas/web/flow/SpengoWebflowConfigurer.java
Changes include the following:
- Added conditional logic when mixedModeAuthentication is false to use
startSpnegoAuthenticate flow.  Otherwise it will use
evaluateClientRequest.
- Modified createEvaluateSpnegoClientAction to be equivlent to the other
Spnego actions on failure which is
CasWebflowConstants.STATE_ID_VIEW_LOGIN_FORM
Since this change fixes the documentation listed out [here](https://apereo.github.io/cas/5.2.x/installation/SPNEGO-Authentication.html#client-selection-strategy), this change re-enables the functionality which may cause unexpected results to those using the defaults.  Some of those properties are the following:
- cas.authn.spnego.hostNameClientActionStrategy
- cas.authn.spnego.hostNamePatternString
- cas.authn.spnego.mixedModeAuthentication
- …
> Fixed SpnegoWebflowConfigurer to use the evaluateClientRequest as documented

- docs/cas-server-documentation/installation/Configuration-Properties-Common.md
For Mongo service registry, there might be a doc typo:
should be: **sslEnabled** 
instead of: **ssEnable** 
as seen on [ https://github.com/apereo/cas/blob/v5.3.1/api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/mongo/BaseMongoDbProperties.java#L106  ]
FYI, this potential typo is also seen on master branch, maybe I submit 1 more PR after this?
> Doc fix typo: (MongoDB service registry) ssEnabled => sslEnabled

- core/cas-server-core-audit-api/src/main/java/org/apereo/cas/audit/spi/ChainingAuditPrincipalIdProvider.java
- core/cas-server-core-audit/src/main/java/org/apereo/cas/audit/spi/config/CasCoreAuditConfiguration.java
This is a backport of some parts of f7ab0ca to the 5.3.x branch. This should fix a concurrency bug in `ChainingAuditPrincipalIdProvider` when `providers` field is modified concurrently in some cases. 
I did not manage to pass `checkstyle` because it complains about lombok `val`'s that should be final. `final val` seems redundant to me and not present in master:
```
> Task :core:cas-server-core-audit:checkstyleMain FAILED
[ant:checkstyle] [ERROR] /home/gagarski/repos/other/cas/core/cas-server-core-audit/src/main/java/org/apereo/cas/audit/spi/config/CasCoreAuditConfiguration.java:223:13: Variable 'resolvers' should be declared final. [FinalLocalVariable]
[ant:checkstyle] [ERROR] /home/gagarski/repos/other/cas/core/cas-server-core-audit/src/main/java/org/apereo/cas/audit/spi/config/CasCoreAud …
```
> Backporting some parts from f7ab0ca to 5.3.x

- docs/cas-server-documentation/installation/Configuration-Properties.md
- Reference any other pull requests that might be related.
Ref: #3413 
The PR will change all all ssEnabled to **ssl**Enabled for all MongoDB setting for **5.2.x  CAS doc**.
**5.1.x** and version before **do not have** this properties **sslEnabled** for MongoDB, 
so after this PR, this typo should be fixed in all version of CAS doc.
Thanks!
> doc typo fix: 5.2.x ssEnabled to sslEnabled

- support/cas-server-support-spnego-webflow/src/main/java/org/apereo/cas/web/flow/client/LdapSpnegoKnownClientSystemsFilterAction.java
- support/cas-server-support-spnego-webflow/src/main/java/org/apereo/cas/web/flow/config/SpnegoWebflowActionsConfiguration.java
- support/cas-server-support-spnego-webflow/src/test/resources/spnego-ldap-ci.properties
- support/cas-server-support-spnego-webflow/src/test/resources/spnego-ldap.properties
Fixed ldapSpnegoClientAction to set the parameter to host as documented for the property cas.authn.spnego.ldap.searchFilter (https://apereo.github.io/cas/5.2.x/installation/Configuration-Properties.html#spnego-authentication)
instead of 0
> Fixed ldapSpnegoClientAction parameter

- core/cas-server-core-tickets/src/main/java/org/apereo/cas/config/CasCoreTicketsSchedulingConfiguration.java
If the schedule method throws an exception, it will stop the schedule from ever running again.  Catching this exception here fixes this issue from ever occurring.  This case can happen if the lockingStrategy.release() within the DefaultTicketRegistryCleaner throws an exception which has happened for us a few times causing this problem.
> Fixed issue with TicketRegistryCleaner schedule

- core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/adaptive/intel/RestfulIPAddressIntelligenceServiceTests.java
- core/cas-server-core-web-api/src/test/java/org/apereo/cas/web/view/RestfulUrlTemplateResolverTests.java
- support/cas-server-support-rest-service-registry/src/test/resources/restful-svc.properties
- support/cas-server-support-surrogate-authentication-rest/src/test/java/org/apereo/cas/authentication/surrogate/SurrogateRestAuthenticationServiceTests.java
uses distinct ports for each `MockWebServer` instance to avoid transient failures due to port collisions.
> use distinct ports

- support/cas-server-support-surrogate-authentication/src/main/java/org/apereo/cas/authentication/event/SurrogateAuthenticationEventListener.java
Previously, if the user has no SMS attribute, an `NullPointerException` was thrown.
Fixed by this change, like for the email notification.
> Allow missing mobile phone in surrogation for SMS notification

- core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/AbstractRegisteredService.java
- core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/DefaultRegisteredServiceContact.java
- core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/DefaultRegisteredServiceProperty.java
Changes embedded entities in `AbstractRegisteredService` to use `@ElementCollection` and `@Embedded`. This is to support #3105 and seems to be the correct way to do it since JPA 2.0 or 2.1.
> use @ElementCollections

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jBaseClientProperties.java
- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/Pac4jOidcClientProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- gradle.properties
- support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java
- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/DelegatedClientNavigationController.java
Delegated authn to Azure is broken in two ways in 5.3.x. Pac4j's Azure impl requires a tenant value to be specified, and Azure does not return querystrings on the callback url (?client_name=AzureOidc). 
This PR adds in the azureTenantId property, adds the ability to switch from querystring based callbacks to an optional* path-based identifier, and adds an endpoint mapping to handle the callback and redirect it to the webflow.
* The Azure config forcefully sets path based callbacks.
New properties documented in the PR commit:
```
```
> Fixing support for delegated authn to azure and path based callbacks with pac4j

- docs/cas-server-documentation/installation/Configuration-Properties.md
Actual name is org.apereo.cas.configuration.CasConfigurationProperties#smsProvider
> Fix invalid property name

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/saml/idp/SamlIdPProperties.java
- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/saml/idp/SamlIdPTicketProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/config/SamlIdPTicketCatalogConfiguration.java
master is done, trying 5.3.x now
Added the ability to change the name of samlArtifactsCache and samlAttributeQueryCache. I created a new file SamlIdPTicketProperties which had the Strings for naming the above variables. I modified the file SamlIdProperties to include the new file SamlIdPTicketProperties (ticket). I changed the values in SamlIdPTicketCatalogConfiguration.java to use those variables instead of hard coded Strings. This is nice for us when we're running cas both in stage and copy that they aren't looking at the same storage place. I've been struggling getting checkstyle to work properly on my computer (Windows) but I'm pretty sure this is all correct I guess we'll see. This is for the master branch and 5.3.x
> 5.3.x: Adding the ability to change the name of samlArtifactsCache and samlAttributeQueryCache

- support/cas-server-support-trusted/src/main/java/org/apereo/cas/adaptors/trusted/web/flow/PrincipalFromRequestHeaderNonInteractiveCredentialsAction.java
We are looking to use the following trusted authentication handler config
cas.authn.trusted.remotePrincipalHeader=OOO_REMOTE_USER
When kicking up the debug logs we can see that the username or credential is not being extracted from the header properly. Trusted auth works fine after making this code change, recompiling, and redeploying. 
Here is some further detail that was posted on the mailing list.
https://groups.google.com/a/apereo.org/forum/?utm_medium=email&utm_source=footer#!msg/cas-user/eW0fO9kxgGM/nJSVjrSBAgAJ
Thanks,
Majeed
> header should be returned instead of remoteUser

- core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/OneTimeTokenAccount.java
- core/cas-server-core-authentication-api/src/test/java/org/apereo/cas/authentication/OneTimeTokenAccountTests.java
The CompareToBuilder cannot compare ArrayLists since they do not implement the Comparable interface. Executing this method causes an immediate ClassCastException in CompareToBuilder.append.
If you know a better way to fix this problem, you are welcome to abandon my proposal! ;)
> Avoid ClassCastException in OneTimeTokenAccount

- core/cas-server-core-authentication-mfa/src/main/java/org/apereo/cas/authentication/DefaultMultifactorAuthenticationProviderBypass.java
- core/cas-server-core-authentication-mfa/src/main/java/org/apereo/cas/authentication/GroovyMultifactorAuthenticationProviderBypass.java
- core/cas-server-core-authentication-mfa/src/main/java/org/apereo/cas/authentication/RestMultifactorAuthenticationProviderBypass.java
PR fixes the issue if a custom GROOVY or REST bypass provider is configured, the authentication context is never updated to remember or forget the bypass in the authentication.  The PR addresses this by evaluating the response from the custom provider and then setting the authentication context based on the result before returning.
> Update authentication when custom bypass used

- support/cas-server-support-shibboleth/build.gradle
- support/cas-server-support-shibboleth/src/main/java/org/apereo/cas/config/ExternalShibbolethIdPAuthenticationServiceSelectionStrategyConfiguration.java
- support/cas-server-support-shibboleth/src/main/java/org/apereo/cas/support/saml/ShibbolethIdPEntityIdAuthenticationServiceSelectionStrategy.java
This PR pertains to the cas-server-support-shibboleth for resolving services from an external Shibboleth IdP using the Shibcas pluglin.
- **Adds a URL decoder step when extracting the entityId parameter from the request query params.**
- **Removes cas-server-support-saml and cas-server-support-trusted as dependencies**
The SAML module was included in the build to only provide SAML_PROTOCOL_CONSTANTS_ENTITY_ID.  Use of the shibboleth module does not require that SAML be included in the build for the CAS Server.  This protocol is stable enough that defining it locally should not be a risk, and saves compiling the saml module into the build.
- **Looks for the existence of the entityId as service registry entry**
This may be more specific to our use of the registry than how others use it.  We …
> Shibcas Decode entity from request parameter

- webapp/resources/static/sass/cas.scss
Added height property to logo class so that header containing CAS logo displays properly in IE 11 (in particular it was overlapping other sections on the login page).
> Fix logo header overlap in IE 11

- core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/configurer/AbstractCasMultifactorWebflowConfigurer.java
- support/cas-server-support-actions/src/main/java/org/apereo/cas/web/flow/login/mfa/MfaInitializeAction.java
- support/cas-server-support-duo-core/src/main/java/org/apereo/cas/adaptors/duo/web/flow/action/DetermineDuoUserAccountAction.java
- support/cas-server-support-duo-core/src/main/java/org/apereo/cas/adaptors/duo/web/flow/action/PrepareDuoWebLoginFormAction.java
PR fixes the provider not find error by comparing the provider id to the flow id instead of the registered bean id in the application context.
> Fix mfa initialize

- docs/cas-server-documentation/configuration/Configuration-Management.md
- docs/cas-server-documentation/configuration/Configuration-Properties-Common.md
- docs/cas-server-documentation/configuration/Configuration-Properties.md
- docs/cas-server-documentation/configuration/Configuration-Server-Management.md
- docs/cas-server-documentation/index.md
- docs/cas-server-documentation/installation/Configuring-Proxy-Authentication.md
- docs/cas-server-documentation/installation/Configuring-SAML2-Authentication.md
- docs/cas-server-documentation/integration/Attribute-Release-Consent.md
- docs/cas-server-documentation/mfa/DuoSecurity-Authentication.md
- docs/cas-server-documentation/mfa/GoogleAuthenticator-Authentication.md
- docs/cas-server-documentation/mfa/Multifactor-TrustedDevice-Authentication.md
- docs/cas-server-documentation/mfa/Simple-Multifactor-Authentication.md
- docs/cas-server-documentation/mfa/SwivelSecure-Authentication.md
- docs/cas-server-documentation/password_management/Password-Management.md
- docs/cas-server-documentation/protocol/Protocol-Overview.md
- docs/cas-server-documentation/protocol/REST-Protocol.md
- docs/cas-server-documentation/protocol/WS-Federation-Protocol.md
- docs/cas-server-documentation/ux/User-Interface-Customization-Themes.md
Fixing broken page links found by running HTMLProofer locally
> Fixing broken page links in the documentation

- support/cas-server-support-trusted-mfa/src/main/java/org/apereo/cas/trusted/authentication/storage/MultifactorAuthenticationTrustStorageCleaner.java
- support/cas-server-support-trusted-mfa/src/main/java/org/apereo/cas/trusted/config/MultifactorAuthnTrustConfiguration.java
Because the mfaTrustStorageCleaner bean is self contained and isn't referenced elsewhere, setting it to be Lazy means it is never initialized and never actually cleans out old trust records.
> the mfaTrustStorageCleaner can't be lazy

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/authentication/ScriptedPrincipalAttributesProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- gradle.properties
- support/cas-server-support-person-directory/src/main/java/org/apereo/cas/config/CasPersonDirectoryConfiguration.java
Also allows engineName to be set to something that ScriptEnginePersonAttributeDao doesn't know how to guess based on extension.
> ScriptEnginePersonAttributeDao gets engineName based on file extension

- gradle.properties
Upgrading bouncycastle to 1.60 resolves CVE-2018-1000613
Upgrading spring boot gets slightly newer tomcat,
I have built with these locally and my local installation still works.
> update dependencies on 5.3.x

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
I have seen a bean named : `OAuth20CasClientRedirectActionBuilder defaultOAuthCasClientRedirectActionBuilder`" that is created **(seemingly) without being used anywhere** (supported by github repo search "https://github.com/search?q=defaultOAuthCasClientRedirectActionBuilder+repo%3Aapereo%2Fcas&type=Code")
A bean with the same class called: "`OAuth20CasClientRedirectActionBuilder oauthCasClientRedirectActionBuilder`" **is being used instead** of the above.
If this is indeed an unused Bean, then it would be nice that it can be removed, thanks!
> Remove Bean that might not being used

- gradle.properties
Backing off on spring-data dependency upgrades b/c they break mongodb test
MongoDbAuditTrailManagerTests broke due to code trying to convert all strings to dates
The fixes appear to be on master but they are fairly extensive and probably not worth merging to 5.3
I tried not upgrading spring data mongo but still got error so spring data commons may be where breaking change exists.
> dependency update to fix test on 5.3 branch 

- docs/cas-server-documentation/installation/Configuration-Properties.md
- support/cas-server-support-aup-webflow/src/main/java/org/apereo/cas/web/flow/AcceptableUsagePolicyWebflowConfigurer.java
- support/cas-server-support-throttle-hazelcast/src/main/java/org/apereo/cas/web/support/config/CasHazelcastThrottlingConfiguration.java
Changed Throttle documentation to show correct defaults in Duration notation that are code in ThrottleProperties.  Changed Hazelcast throttle config to use duration when setting map idle timeout.
> Use Duration in Hz Throttle Map timeout

- support/cas-server-support-mongo-core/src/main/java/org/apereo/cas/mongo/BaseConverters.java
Add @ReadingConverter annotation to StringToZonedDateTimeConverter to prevent spurious String->ZonedDateTime conversion error when saving to MongoDbServiceRegistry.
References:
https://stackoverflow.com/questions/50286790/spring-data-mongodb-failed-to-convert-from-type-after-upgrade-to-2-0-7-with-cus
https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo.converter-disambiguation
Stack trace excerpt:
```
org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.time.ZonedDateTime] for value 'http://www.testshib.org/metadata/testshib-providers.xml'; nested exception is java.time.format.DateTimeParseException: Text 'http://www.testshib.org/metadata/testshib-providers.xml' could not be parsed at index 0
at …
```
> @ReadingConverter to avoid String -> ZonedDateTime conversion error

- api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/VariegatedMultifactorAuthenticationProvider.java
- core/cas-server-core-authentication-mfa/src/main/java/org/apereo/cas/authentication/DefaultVariegatedMultifactorAuthenticationProvider.java
Marking variegated provider interface and default implementation as deprecated starting in v5.3.4
> Mark variegated provider as deprecated

- support/cas-server-support-hazelcast-monitor/src/test/java/org/apereo/cas/monitor/HazelcastHealthIndicatorTests.java
Can't recreate failure locally, this change will let it get farther and we may get more info or the test may completely pass.
> make hazelcast test less likely to fail

- core/cas-server-core-configuration-api/src/main/java/org/apereo/cas/configuration/DefaultCasConfigurationPropertiesSourceLocator.java
- core/cas-server-core-configuration/src/test/java/org/apereo/cas/configuration/support/DefaultCasConfigurationPropertiesSourceLocatorTests.java
- core/cas-server-core-configuration/src/test/resources/directory/application-dev.properties
- core/cas-server-core-configuration/src/test/resources/directory/application-standalone.yml
- core/cas-server-core-configuration/src/test/resources/directory/application.yml
- core/cas-server-core-configuration/src/test/resources/directory/cas.properties
I think the current way external cas properties are loaded is too unlike what people expect (assuming they are familiar with spring/spring boot). In the current impl profiles do not override non-profiles (e.g. cas.properties) and profiles are processed in alphabetical order. If you think this change is too much (it's not backwards compatible) then I could submit an alternate config class that could be configurable (to use it instead of the default). 
There are differences between this and spring boot but
files in the config directory are processed in the following order
with the last file to contain the property winning, similar to
spring boot (but spring boot does not look for <profile>.<ext>)
--spring.active.profiles=1stprofile,2ndprofile
application.properties
application.yml …
> make cas configuration standalone properties work more like spring boot

- core/cas-server-core-authentication-mfa/src/main/java/org/apereo/cas/authentication/DefaultMultifactorAuthenticationContextValidator.java
Bypass values coming through now wrapped in LinkedList.  This PR unwraps the attribute from the list when pulling out bypass attributes.
It is possible there are other places that have this same issue.
> Fix for Multivalue Authentication Attributes

- docs/cas-server-documentation/configuration/Configuration-Server-Management.md
Not sure if it is worth putting in a warning that this behavior is changed in 6.x (to profile order vs alphabetical order)
> update documentation for standalone config loading

- developer/Build-Process-6X.md
Removed a duplicate config row `ignoreTestFailures`
Remove  `also decide` after `must` on the statement: "You must *also decide to use* the 'default gradle wrapper' option"
- From the history, it used to be "You may also decide", but now should be "You must" instead
The last part is an optional addition. 
Mainly because I think it is good to guide newbie like me, how to execute the test for CAS. Moreover, `testCategoryType` is not mentioned anywhere, but is necessary to trigger a CAS test. 
If you think the addition is in the wrong place or is not needed, I will have no problem removing that part. Thanks!
> Build process doc improvement: Fix typo, and add guide for manual test

- support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/web/OidcConsentApprovalViewResolver.java
Without this change an OIDC service is unable to bypass the consent screen when it can also generate refresh tokens.
> Allow Oidc services to bypass consent even if they generate refresh tokens

- support/cas-server-support-oauth-core/src/main/java/org/apereo/cas/support/oauth/OAuth20Constants.java
- support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/web/controllers/OidcIntrospectionEndpointController.java
- Provide a 401 response instead of 200 in case of invalid or unauthorized client credentials
- Provide a 401 response instead of 500 in case of missing client credentials
- Check token parameter first (as per RFC) to prevent log message on access_token parameter check
> Adds OIDC Introspection error responses

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/validator/token/OAuth20RefreshTokenGrantTypeTokenRequestValidator.java
- support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/AbstractOAuth20Tests.java
- support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/OAuth20AccessTokenControllerTests.java
Same fix as #3619, applied to 5.3.x. 
I don't know if the change in this PR is still in the scope of 5.3.x, feel free to close it if it is not in the scope, thanks!
> [For 5.3.x] OAuth Refresh Token Flow: Allow client_secret to not be checked if the client secret is an empty string

- support/cas-server-support-ehcache-ticket-registry/src/main/java/org/apereo/cas/config/EhcacheTicketRegistryConfiguration.java
This allows spring boot admin to manage cache if cache actuator is exposed.
With this bean you get this in spring boot admin:
It currently only allows you to clear the caches, I was hoping for some stats (at least size of cache) but maybe they will add some more features to the cache actuator and/or to spring boot admin.
> Add Spring CacheManager to wrap EhCache CacheManager for springboot admin

- gradle/tasks.gradle
Build was failing when I ran with -DskipFindugs=true
```
* Where:
Script 'C:\Users\hdead\git\cas\gradle\tasks.gradle' line: 64
* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'spotbugsPlugins' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.
```
> fix build script when using -DskipFindbugs=true

- core/cas-server-core-util/src/main/java/org/apereo/cas/config/CasCoreUtilConfiguration.java
In some environments spring's ApplicationContext does not have a parent set, which will cause a NPE during startup
> NPE during startup due to missing parent of ApplicationContext used in CasCoreUtilConfiguration

- support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/authentication/principal/SamlServiceFactory.java
Split the debug log of Saml request to allow dumping the Request before parsing-exception are triggered
The new Saml/XML parsing tool is subject to throwing exception when the Saml request has issue, however the current debug LOG is made too late to get the usefull information in the log so this patch split back the LOGGER.debug in two line and dump the RequestBody before attempting to parse it.
Regards
> Improve debuging of SAML requests

- core/cas-server-core-webflow-api/src/main/java/org/apereo/cas/web/flow/actions/ClearWebflowCredentialAction.java
- support/cas-server-support-aup-core/src/main/java/org/apereo/cas/aup/DefaultAcceptableUsagePolicyRepository.java
I tested this with X509 and fallback to regular login but this has potential to impact any of the other webflows that use the credential clearing action in their webflow. Assuming they all clear the credential when there is an error that results in the flow going back to login, then this should be OK but I am not very familiar with the other flows and I don't know what other reasons there might be for clearing the credentials. 
I also made a change to the default aup repository so that if the credential is null it will fall back to storing the aup acceptance in the flow along with a debug message that someone could use to figure out why they were prompting users more often than they were expecting. I figure the extra prompts are better then a server error that prevents login. The fix to …
> avoid clearing credentials on success so AUP has access to credential

- core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/support/RememberMeDelegatingExpirationPolicy.java
- core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/support/RememberMeDelegatingExpirationPolicyTests.java
Would you please backport this fix, as 5.3.x is the current stable branch and "remember-me" function is not working, because of:
```
ERROR [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <java.util.LinkedList cannot be cast to java.lang.Boolean>
java.lang.ClassCastException: java.util.LinkedList cannot be cast to java.lang.Boolean
at org.apereo.cas.ticket.support.RememberMeDelegatingExpirationPolicy.getExpirationPolicyNameFor(RememberMeDelegatingExpirationPolicy.java:54) ~[cas-server-core-tickets-api-5.3.5.jar:5.3.5]
at org.apereo.cas.ticket.support.BaseDelegatingExpirationPolicy.getExpirationPolicyFor(BaseDelegatingExpirationPolicy.java:135) ~[cas-server-core-tickets-api-5.3.5.jar:5.3.5]
at org.apereo.cas.ticket.support.BaseDelegatingExpirationPolicy.isExpired(BaseDelegati …
```
> Backport Fix for ClassCastException in remember-me functionality

- core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/RandomUtils.java
Changes algorithm used by the SecureRandom generator to a native non-blocking algorithm.  The currently used algorithm has the potential to cause unacceptable latency on Unix/Linux systems depending on implementation of /dev/random.
> Changes the SecureRandom class to use an non-blocking algorithm.

- support/cas-server-support-saml/build.gradle
- support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/authentication/principal/SamlServiceFactory.java
When using SAML ECP, `createService` in `SamlServiceFactory` throws a `NullPointerException`. For SAML ECP workflow, the service is extracted later from `<samlp:Request>`.
See http://docs.oasis-open.org/security/saml/Post2.0/saml-ecp/v2.0/saml-ecp-v2.0.html for more information.
> Backport Fix for NullPointerException in SAML ECP Request

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/monitor/MonitorProperties.java
- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/ConnectionPoolingProperties.java
- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/ldap/AbstractLdapProperties.java
- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/support/Beans.java
- docs/cas-server-documentation/configuration/Configuration-Properties.md
This allows the ldap monitor module to be used and not interfere with server startup when ldap is unavailable or incorrectly configured.
> default ldap monitor to a min pool size of zero

- core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/HttpRequestUtils.java
- core/cas-server-core-web-api/src/main/java/org/apereo/cas/web/support/WebUtils.java
- support/cas-server-support-interrupt-core/src/main/java/org/apereo/cas/interrupt/RestEndpointInterruptInquirer.java
In a multi-language setup it may be valuable for the REST interrupt endpoint to have
knowledge about the browser language settings of the user. With this commit, we now
propagate that information to the REST interrupt endpoint.
> Propagate "Accept-Language" to interrupt REST endpoint

- docs/cas-server-documentation/protocol/REST-Protocol.md
- support/cas-server-support-rest/src/main/java/org/apereo/cas/config/CasRestConfiguration.java
- support/cas-server-support-rest/src/main/java/org/apereo/cas/support/rest/resources/ServiceTicketResource.java
- support/cas-server-support-rest/src/test/java/org/apereo/cas/support/rest/ServiceTicketResourceTests.java
Applications that use the CAS REST protocol may need to authenticate to security sensitive services that demand a service ticket that was issued from the presentation of the user’s primary credentials (those services only validate service tickets with the activation of the optional "renew" parameter of the /validate /serviceValidate CAS requests)
This proposed change to the REST API is to allow applications to add optional "username", "password", and "renew" parameters to the REST service ticket request, to be able to obtain STs that can be accepted by such security sensitive services.
This change has the same purpose as PR #3633 and is supposed to replace it. The approach seems better as it avoids the problem of potentially creating two resources in a single REST request.
> REST: Obtain ST with SSO bypass.

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/ldap/AbstractLdapProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties-Common.md
- support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/util/LdapUtils.java
and added an appropriate line to the documentation
Not issued yet, no side-effects on tests so far
> Added ability to set ldaptive's allowMultipleEntries via cas.properties

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/metadata/ConfigurationMetadataGenerator.java
- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/jpa/AbstractJpaProperties.java
- api/cas-server-core-api-configuration-model/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- gradle/webapp.gradle
I think this file should be picked up and processed by the spring boot property migration stuff but I haven't tested it yet.
The spring-boot PropertiesMigrationReporter picks up any properties that have a deprecation section with level=error. There is a @DeprecatedConfigurationProperty annotation for deprecating properties that you still support but that you want users to migrate away from but once the property is gone, this "additional-spring-configuration-metadata.json" file is where you put properties that no longer exist. 
The "replacement" and "reason" attributes aren't both required. Spring-boot seems to leave off reason when there is a replacement and specify reason when there is no replacement but I think the code allows for both to be there. 
[Example from spring-boot …
> point upgrader at new property names for properties that have been renamed

- api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/RegisteredServiceProperty.java
- core/cas-server-core-web-api/src/main/java/org/apereo/cas/services/web/support/RegisteredServiceResponseHeadersEnforcementFilter.java
- docs/cas-server-documentation/installation/Configuring-Service-Http-Security-Headers.md
The service property "httpHeaderEnableXFrameOptions" can control if the
x-frame-options header should be inserted in the HTTP response. However it
make sense to control the value of the x-frame-options using service files.
This commit implements that feature by introducing the property
"httpHeaderXFrameOptions".
> Add possibility of overriding value of x-frame-options using service files

- core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/resource/AbstractResourceBasedServiceRegistry.java
Errors occur when CAS is trying to load e.g. swp files generated by vim
> Avoid errors on trying to load service files starting with dots

- core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/resource/AbstractResourceBasedServiceRegistry.java
Errors occur when CAS is trying to load e.g. swp files generated by vim
> Avoid errors on trying to load service files starting with dots [FORWARD PORT]

- api/cas-server-core-api-services/src/main/java/org/apereo/cas/services/RegisteredServiceProperty.java
- core/cas-server-core-web-api/src/main/java/org/apereo/cas/services/web/support/RegisteredServiceResponseHeadersEnforcementFilter.java
- docs/cas-server-documentation/services/Configuring-Service-Http-Security-Headers.md
The service property "httpHeaderEnableXFrameOptions" can control if the
x-frame-options header should be inserted in the HTTP response. However it
make sense to control the value of the x-frame-options using service files.
This commit implements that feature by introducing the property
"httpHeaderXFrameOptions".
Forward-Port: 95dad85
> Add possibility of overriding the value of the "x-frame-options" header using service files [FORWARD PORT]

- support/cas-server-support-rest/src/main/java/org/apereo/cas/support/rest/resources/RestResourceUtils.java
- support/cas-server-support-rest/src/main/java/org/apereo/cas/support/rest/resources/ServiceTicketResource.java
- support/cas-server-support-rest/src/main/java/org/apereo/cas/support/rest/resources/TicketGrantingTicketResource.java
- support/cas-server-support-rest/src/main/java/org/apereo/cas/support/rest/resources/UserAuthenticationResource.java
This change adds localized messages to get human readable reasons of authentication failures on a REST request.
Messages are added at the end of already existent messages in the json response.
A "Accept-Language" http header in the request allows messages language selection.
> REST & Internationalization: Add localized msg in resp. on auth failure.

- gradle/dependencies.gradle
if openid needs xerces, it will get it when someone includes openid cas
module
The version of xerces referenced here has CVE associated with it and it is lower than the version cas uses.
> Gradle: exclude xerces dependency from default includes

- gradle.properties
- support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java
- support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/logout/CasServerSpecificLogoutHandler.java
- support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/logout/RequestSloException.java
- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java
It only works for front-channel calls, but the back-channel support can be added by customization.
> Handle SAML2 SLO calls

- docs/cas-server-documentation/protocol/CAS-Protocol-Specification.md
Without escaping the <LF> rendered as a html tag.
It's a minor documentation issue.
> documentation: escaping <LF> to HTML entities

- api/cas-server-core-api-configuration-model/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- api/cas-server-core-api-configuration-model/src/test/java/org/apereo/cas/configuration/AdditionalMetadataVerificationTests.java
spring boot currently gets NPE when processing the replacement for cas.admin-pages-security.ip
```
2018-12-02 21:40:32,131 ERROR [org.springframework.boot.SpringApplication] - <Application run failed>
java.lang.NullPointerException: null
at org.springframework.boot.context.properties.migrator.PropertiesMigrationReporter.detectMapValueReplacementType(PropertiesMigrationReporter.java:140) ~[spring-boot-properties-migrator-2.1.1.RELEASE.jar!/:2.1.1.RELEASE]
at org.springframework.boot.context.properties.migrator.PropertiesMigrationReporter.isRenamed(PropertiesMigrationReporter.java:115) ~[spring-boot-properties-migrator-2.1.1.RELEASE.jar!/:2.1.1.RELEASE]
at org.springframework.boot.context.properties.migrator.PropertiesMigrationReporter.lambda$mapPropertiesWithReplacement$1(PropertiesMigratio …
```
> make sure replacement property doesn't have array syntax in it

- support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java
This may fix the password reset flow issue mentioned in [this thread](https://github.com/apereo/cas/pull/2940#issuecomment-442390806). I haven't yet tested it, will update this from WIP when I have. Quoting from that thread:
> I think I found the problem. [These two variables](https://github.com/apereo/cas/blob/master/support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java#L45-L46) both have the same value. I think this clobbers the password reset flow in favor of the forgot username flow. Switching one of the values (or both, to be less generic) should fix it.
Our build process doesn't easily allow me to swap in an unpublished CAS, so I'm going to have to work toward properly testing it. Hopefully in the next few days.
> Fix password reset flow

- support/cas-server-support-u2f/src/main/java/org/apereo/cas/adaptors/u2f/U2FAuthenticationHandler.java
- webapp/resources/templates/casU2fLoginView.html
- webapp/resources/templates/casU2fRegistrationView.html
Fix broken mfa-u2f in CAS 5.3
1. Fix non existant keys of messages on registration and authentication views :
- before patch : ![image](https://user-images.githubusercontent.com/1167372/49213758-46660c80-f3c5-11e8-961a-1c0008b3957b.png)
- after patch : ![image](https://user-images.githubusercontent.com/1167372/49217677-81b90900-f3ce-11e8-8653-742bf94b1e2b.png)
2. Fix thymeleaf exception where CAS displays registration and authentication views (mfa-u2f can't be used) :
ERROR [org.thymeleaf.TemplateEngine] - <[THYMELEAF][ajp-nio-8109-exec-9] Exception processing template "error": Error resolving template "tag", template might not exist or might not be accessible by any of the configured Template Resolvers (template: "casU2fRegistrationView" - line 46, col 71)> …
> Fix mfa u2f : Templates of view and duplicated attributes

- core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/cipher/BaseBinaryCipherExecutor.java
Same fix as: 
[5.3] Fix potential non-threadsafe usage for Cipher class #3679
> [6.x] Fix potential non-threadsafe use of Cipher

- api/cas-server-core-api-configuration-model/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- api/cas-server-core-api-configuration-model/src/test/java/org/apereo/cas/configuration/AdditionalMetadataVerificationTests.java
Spring boot property migrator currently fails if replacement doesn't
exist in metadata. Change the two properties that are either not in
cas metadata or are in spring metadata which we can't validate
against easily.
The reason property still points to the new values.
> Fix replacements in additional spring metadata

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/ehcache/EhcacheProperties.java
- docs/cas-server-documentation/installation/Configuration-Properties.md
- gradle/tasks.gradle
- support/cas-server-support-ehcache-ticket-registry/src/main/java/org/apereo/cas/config/EhcacheTicketRegistryConfiguration.java
This backports pull request for master branch. In CAS 5.3 the property has to be systemProps vs systemprops, presumably due to the different spring boot versions. I think either will work in 6.0. 
There is also a minor build script change which I think is already on master branch.
>  Allows spring config to be used to customize ehcache replication config.

- core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/credential/UsernamePasswordCredential.java
- webapp/resources/templates/casAuthyLoginView.html
- webapp/resources/templates/casAzureAuthenticatorLoginView.html
- webapp/resources/templates/casDuoLoginView.html
- webapp/resources/templates/casGoogleAuthenticatorLoginView.html
- webapp/resources/templates/casRadiusLoginView.html
- webapp/resources/templates/casSwivelLoginView.html
- webapp/resources/templates/casYubiKeyLoginView.html
- webapp/resources/templates/fragments/loginform.html
The errors were showing up twice.
Either this code needs to be removed or the @​Size validation constraint needs to go.  
There is still an issue where there is no space between the messages but that seems to be a problem anywhere something like this is  used:
```
<div class="alert alert-danger" th:if="${#fields.hasErrors('*')}">
<span th:each="err : ${#fields.errors('*')}" th:utext="${err}">Example error</span>
</div>
```
Should the space just be added after ${err}?
> Remove error messages handled by the @Size annotation on the fields.

- support/cas-server-support-person-directory/src/main/java/org/apereo/cas/config/CasPersonDirectoryConfiguration.java
It's actually not a big deal and probably no one would notice it but it clearly makes no sense to trim constant string without spaces. Not sure if trim is needed here at all though.
> Minor typo fix in attributes merger configuration

- support/cas-server-support-pac4j-authentication/src/main/java/org/apereo/cas/integration/pac4j/authentication/handler/support/AbstractPac4jAuthenticationHandler.java
Currently, when `cas.authn.pac4j.principalAttributeId` or `cas.authn.pac4j.PROVIDER.principalAttributeId` is specified, `cas.authn.pac4j.typedIdUsed` is not considered, [cf. AbstractPac4jAuthenticationHandler](https://github.com/apereo/cas/blob/8461a5bbc0f76058cf0b6e9e173b45a12e170372/support/cas-server-support-pac4j-authentication/src/main/java/org/apereo/cas/integration/pac4j/authentication/handler/support/AbstractPac4jAuthenticationHandler.java#L105).
In case you need to know, which pac4j client did the authentication in the authn flow, it is useful to consistently return a typed principal ID irrespective of whether a custom principalAttributeId is set or not.
This patch implements exactly that behaviour.
> pac4j: Consider typedIdUsed when a custom principalAttributeId is specified

- api/cas-server-core-api-ticket/src/main/java/org/apereo/cas/ticket/registry/TicketRegistry.java
- core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/policy/UniquePrincipalAuthenticationPolicy.java
- core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/registry/AbstractTicketRegistry.java
- core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/registry/DefaultTicketRegistryCleaner.java
- core/cas-server-core/src/main/java/org/apereo/cas/AbstractCentralAuthenticationService.java
- core/cas-server-core/src/test/java/org/apereo/cas/DefaultCentralAuthenticationServiceMockitoTests.java
- support/cas-server-support-couchdb-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/CouchDbTicketRegistry.java
- support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/RedisTicketRegistry.java
I've noticed some bursts in memory usage when using `RedisTicketRegistry` together with `DefaultTicketRegistryCleaner`. 
After some research I've found out that `DefaultTicketRegistryCleaner` loads all the tickets from Redis to Java heap memory due to default implementation of `getTicketsStream()` in `RedisTicketRegistry` (which calls `getTickets()`).
This PR does two things:
- defines proper `getTicketsStream` in `RedisTicketRegistry`
- fetches Redis KEYS in a proper way as Redis documentation suggests (using SCAN instead of KEYS).
> Reducing Redis heap memory overhead when running ticket registry cleaner

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pm/PasswordManagementProperties.java
- docs/cas-server-documentation/configuration/Configuration-Properties.md
- docs/cas-server-documentation/password_management/Password-Management-REST.md
- support/cas-server-support-pm-rest/src/main/java/org/apereo/cas/config/pm/RestPasswordManagementConfiguration.java
With this PR, CAS will support secured PM REST-Endpoints.
>  Allow CAS to authenticate itself at the REST password management endpoints

- core/cas-server-core-services-authentication/src/main/java/org/apereo/cas/authentication/support/DefaultCasProtocolAttributeEncoder.java
It is quite common for CAS to perform attribute sanitization, therefore it should
not be logged as a warning.
> Log to info when performing attribute sanitization [FORWARD-PORT]

- core/cas-server-core-services-authentication/src/main/java/org/apereo/cas/authentication/support/DefaultCasProtocolAttributeEncoder.java
It is quite common for CAS to perform attribute sanitization therefore it should
not be logged as a warning.
> Log to info when performing attribute sanitization

- support/cas-server-support-surrogate-authentication/src/main/java/org/apereo/cas/ticket/support/SurrogateSessionExpirationPolicy.java
Add missing jackson annotations required for de-serialization of SurrogateSessionExpirationPolicy class without default constructor.
This mimics the annotations in the RememberMeDelegatingExpirationPolicy class which also extends the 
BaseDelegatingExpirationPolicy and has a constructor with an ExpirationPolicy parameter.
> Impersonation: Add missing jackson annotations to expiration policy

- webapp/resources/messages.properties
- webapp/resources/messages_de.properties
- webapp/resources/static/js/passwordMeter.js
- webapp/resources/templates/fragments/pwdupdateform.html
Added i18n support for Password Reset ([as far as currently possible with zxcvbn](https://github.com/dropbox/zxcvbn/pull/124)). This mainly involved moving the HTML elements generated inside the JavaScript code to the corresponding view fragment.
Revised passwordMeter.js and view fragment for better UX, i.e. logic of alerts and appearance.
Added German translation of new message properties.
A port forward will be provided upon (positive) feedback on these changes. What do you think?
> I18n support for Password Reset view

- support/cas-server-support-surrogate-authentication/src/main/java/org/apereo/cas/ticket/support/SurrogateSessionExpirationPolicy.java
Backport of https://github.com/apereo/cas/pull/3725
Add missing jackson annotations required for de-serialization of SurrogateSessionExpirationPolicy class without default constructor.
This mimics the annotations in the RememberMeDelegatingExpirationPolicy class which also extends the
BaseDelegatingExpirationPolicy and has a constructor with an ExpirationPolicy parameter.
> Impersonation: Add missing jackson annotations to expiration policy (port backward to 5.3.x)

- .travis.yml
- ci/html-proofer-docs.rb
- ci/html-proofer-docs.sh
- docs/cas-server-documentation/configuration/Configuration-Properties.md
- docs/cas-server-documentation/planning/Security-Guide.md
This uses a ruby container with HTMLProofer (customized fork of container with some added gems) to validate the internal links in the CAS documentation. It currently excludes the CAS-Protocol-Specification.md which has lots of bad anchor links (which could be fixed eventually).
Container:
https://github.com/hdeadman/html-proofer-docker
https://hub.docker.com/r/hdeadman/html-proofer
I have run it locally, going to see if it runs in travis.
> Use HTMLProofer to validate documentation links

- support/cas-server-support-ldap/src/main/java/org/apereo/cas/authentication/LdapPasswordSynchronizationAuthenticationPostProcessor.java
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/validator/authorization/OAuth20AuthorizationCodeResponseTypeAuthorizationRequestValidator.java
I just ran into this error on a new service I am trying to configure. Might as well log warning with some info rather than have a big NPE stack trace with no information (if service is not registered).
> avoid NPE when oauth service specified by client_id is not registered

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/pac4j/oidc/BasePac4jOidcClientProperties.java
- docs/cas-server-documentation/configuration/Configuration-Properties-Common.md
- support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DelegatedClientFactory.java
This change allows to set the response mode and response type parameters for oidc client delegation.
Priori to this change, the response mode and type could not be set and the default pac4j values where used.
The change is backward compatible and does not change the default response mode and type.
> Allow to set responseType and responseMode for OIDC clients

- core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/resource/AbstractResourceBasedServiceRegistry.java
When updated service files distributed by puppet, a temp file is created in service folder with a random extension and is loaded with a warning about name pattern not matching and duplicate id.
> Only load service registry resource files with valid extension for that registry

- support/cas-server-support-gauth/src/main/resources/webflow/mfa-gauth/mfa-gauth-webflow.xml
GoogleAuthenticatorTokenCredential class wa moved from org.apereo.cas.adaptors.gauth to org.apereo.cas.gauth.credential. Webflow configuration file `mfa-gauth-webflow.xml` adjusted to reflect this.
> Fix GoogleAuthenticatorTokenCredential package name

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
- support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/web/controllers/dynareg/OidcDynamicClientRegistrationEndpointController.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/config/SamlIdPEndpointsConfiguration.java
- support/cas-server-support-saml-sp-integrations/src/main/java/org/apereo/cas/util/SamlSPUtils.java
- support/cas-server-support-ws-idp/src/main/java/org/apereo/cas/config/CoreWsSecurityIdentityProviderConfiguration.java
Port forward of #3768
Change some built-in services from MAX_VALUE (low priority, last) to
MIN_VALUE/HIGHEST_PRIORITY b/c CAS built-in services or internal services
will not match non-CAS services (b/c they are
^protocol://domain/casprefix/.*)
Use Ordered.HIGHEST_PRIORITY instead of Integer.MIN_VALUE which are same
but HIGHEST_PRIORITY makes intent clear.
> Fix for CAS not finding built-in services due to incorrect priority

- gradle.properties
Update spring boot to latest to get transitive dependency updates (no particular reason other than avoiding possible complaints from security scanners). Update spring cloud from RC to release. Update ldaptive because release notes mention possible orphaned connections.
> update some dependencies, spring & ldaptive

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
- support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/web/controllers/dynareg/OidcDynamicClientRegistrationEndpointController.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/config/SamlIdPEndpointsConfiguration.java
- support/cas-server-support-saml-sp-integrations/src/main/java/org/apereo/cas/util/SamlSPUtils.java
- support/cas-server-support-ws-idp/src/main/java/org/apereo/cas/config/CoreWsSecurityIdentityProviderConfiguration.java
Change some built-in services from MAX_VALUE (low priority, last) to MIN_VALUE/HIGHEST_PRIORITY b/c CAS built-in services or internal services will not match non-CAS services (b/c they are ^protocol://domain/casprefix/.*). On the other hand, if your CAS server shares domain with apps, and multiple apps share default service under domain (^https://domain/.*), or if you have open service like ^https://.* then the internal services will never be matched (b/c they sort last in ordered list if they have MAX_VALUE evalutationOrder and hence other services may match first). 
In some cases I changed Integer.MIN_VALUE to Ordered.HIGHEST_PRIORITY which are the same but HIGHEST_PRIORITY makes intent clear.
I am currently trying to get an app called Linkurious to authenticate via OIDC and while this …
> Fix for CAS not finding built-in services due to incorrect priority (OIDC, SAML, WSSecurity)

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
- support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/config/SamlIdPEndpointsConfiguration.java
- support/cas-server-support-ws-idp/src/main/java/org/apereo/cas/config/CoreWsSecurityIdentityProviderConfiguration.java
So other services aren't matched before they are. 
Backport of #3768
> Make sure built-in CAS services are highest priority (SAML)

- gradle.properties
- gradle/dependencies.gradle
Newer version of dom4j (than what is defined in gradle.properties) showing up in tomcat war.
> Dependency update - exclude dom4j using new group

- gradle.properties
The bug bothering me in CAS was https://github.com/vt-middleware/ldaptive/issues/144 and now it's fixed. Can we have the properly working version in 5.3.x?
> [5.3.x] Bump ldaptive version

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/ldap/AbstractLdapProperties.java
```
java.lang.NullPointerException: Thread local SslConfig has not been set 
at 
org.ldaptive.ssl.ThreadLocalTLSSocketFactory.getDefault(ThreadLocalTLSSocketFactory.java:53) 
~[ldaptive-1.2.4.jar!/:?] 
```
Reference: https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/tC6qQO9zGRk
From @dfish3r:
> This appears to be a bug in JNDI code that manifests with an NPE in the ldaptive thread local code.
I've filed an issue, but there isn't a resolution yet.
> Work arounds include:
> * Use startTLS
> * Use the UnboundID provider
> * Use Java 8 (versions 9-12 are all affected)
This pull request switches the default provider to use the UnboundID provider component instead, per Daniel's suggestion.
The `unboundid-ldapsdk` module is auto-included for deployments that pull in the …
> CAS configuration: Switch default LDAP provider class to UnboundIDProvider

- support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/PasswordManagementWebflowConfigurer.java
It seems a small change, but it's not.
I encountered an issue with the password management feature. I struggled quite some time to find out the issue: the TGT creation happens in a specific action in 5.3 while it happened in the `realSubmit` action in 5.2. So I moved the `doCheckPassword` action after the TGT creation (and not only after the `realSubmit` action).
I tested both the password change and reset features.
> Fix password management

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java
- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/profile/ClientIdAwareProfileManager.java
This PR fixes incorrect CasProfile caching when doing two subsequent authentications into different services.
Let's consider two services:
- A that is allowed to release attributes a1, a2
- B that is allowed to release attributes a1, a2, a3
Let's consider that user is also logged into CAS (for simplicity), i. e. he has TGT.
Now let's consider this user initiating authorization code flow by going to `/oauth2.0/authorize` endpoint with service `A` credentials. User's browser goes through the following redirects:
- /oauth2.0/callbackAuthorize/
- /login/
- /oauth2.0/authorize
- supplied callback URL
So far so good. But the bad thing is that now a pac4j profile is attached to a user session and this profile contains only a1 and a2 attributes. I believe the profile is added by this interceptor. …
> Fix incorrect CasProfile caching between different OAuth 2.0 services

- support/cas-server-support-saml-idp-web/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/enc/SamlIdPObjectSigner.java
- support/cas-server-support-shell/build.gradle
Adding javaparser to avoid this exception on shell startup. 
```
No active profile set, falling back to default profiles: default
could not get type for name com.github.javaparser.ast.visitor.VoidVisitorAdapter from any class loader
org.reflections.ReflectionsException: could not get type for name com.github.javaparser.ast.visitor.VoidVisitorAdapter
at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390) [reflections-0.9.11.jar!/:?]
at org.reflections.Reflections.expandSuperTypes(Reflections.java:381) [reflections-0.9.11.jar!/:?]
at org.reflections.Reflections.<init>(Reflections.java:126) [reflections-0.9.11.jar!/:?]
at org.reflections.Reflections.<init>(Reflections.java:168) [reflections-0.9.11.jar!/:?]
at org.reflections.Reflections.<init>(Reflections.java:141) …
```
> fix missing jar from (class not found on startup but shell still worked)

- core/cas-server-core-services-registry/src/test/java/org/apereo/cas/services/resource/DeleteResourceBasedRegisteredServiceWatcherTests.java
This is a test for recent change to avoid processing deleted temp files as deleted services.
> Test for ignoring tmp files during delete from resource based registry

- docs/cas-server-documentation/installation/Configuration-Properties-Common.md
property is named "node" but in the docu it is "nodes"
> fix redis sentinal property

- gradle/dependencies.gradle
Exclude el-api under another artifact name that is currently used. Not sure why we are including el-impl:2.2 since Tomat comes with 3.0 impl of its own (and 3.0 api).
> Exclude el-api 2.2 dependency that conflicts with 3.0 from tomcat 9

- support/cas-server-support-interrupt-core/src/main/java/org/apereo/cas/config/CasInterruptConfiguration.java
This lambda inquirer causes to always interrupt the login process.
```
2019-02-11 18:52:58,269 DEBUG [org.apereo.cas.interrupt.webflow.actions.InquireInterruptAction] - <Invoking interrupt inquirer using [GroovyScriptInterruptInquirer]>
2019-02-11 18:52:58,269 DEBUG [org.apereo.cas.interrupt.BaseInterruptInquirer] - <No service was found in the request context. Proceeding as usual...>
2019-02-11 18:52:58,270 DEBUG [org.apereo.cas.interrupt.webflow.actions.InquireInterruptAction] - <Invoking interrupt inquirer using [CasInterruptConfiguration$$Lambda$863/0x0000000840dc7c40]>
2019-02-11 18:52:58,270 DEBUG [org.apereo.cas.interrupt.webflow.actions.InquireInterruptAction] - <Interrupt inquiry is required since inquirer produced a response [InterruptResponse(message=Authentication flow is …
```
> Remove creation of lambda interrupt inquirer

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/support/sms/NexmoProperties.java
- docs/cas-server-documentation/configuration/Configuration-Properties.md
- support/cas-server-support-passwordless/src/main/java/org/apereo/cas/web/flow/DisplayBeforePasswordlessAuthenticationAction.java
- support/cas-server-support-sms-nexmo/src/main/java/org/apereo/cas/support/sms/NexmoSmsSender.java
Fix Nexmo SMS support
Nexmo client needs private key if applicationId is set. DisplayBeforePasswordlessAuthenticationAction uses email configuration for sms notifications.
[x] Remove applicationId default value from NexmoProperties
[x] Add privateKeyContentsPath to NexmoProperties
[x] Use SMS configuration for sms notifications (DisplayBeforePasswordlessAuthenticationAction)
[x] Use default applicationId "CAS" if a private key path is set and applicationId not
> Fix Nexmo support 4.0.x

- support/cas-server-support-passwordless/src/main/java/org/apereo/cas/web/flow/AcceptPasswordlessAuthenticationAction.java
Passwordless authentication fails on token verification. Token is removed before all verifications.
This PR moves token deletion at the end of the doExecute method.
Tested with passwordless auth and in-memory tokens
> Delete passwordless token after authentication

- support/cas-server-support-x509/src/main/java/org/apereo/cas/adaptors/x509/config/X509AuthenticationConfiguration.java
- support/cas-server-support-x509/src/test/java/org/apereo/cas/AllTestsSuite.java
- support/cas-server-support-x509/src/test/java/org/apereo/cas/adaptors/x509/config/DefaultX509ConfigTests.java
If I take a clean overlay (6.1-RC2-SNAPSHOT) and add this dependency:
```gradle
compile "org.apereo.cas:cas-server-support-x509-webflow:${casServerVersion}"
```
then the CAS server fails to start b/c it is trying to create an ldaptiveResourceCRLFetcher that isn't configured (default crlFetcher is resource type). 
I was having trouble testing this outside of overlay but I don't see any references to these beans (only the crlFetcher bean) so I think it is safe to remove these annotations. 
This is the error that occurs. 
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apereo.cas.adaptors.x509.authentication.CRLFetcher]: Factory method 'ldaptiveResourceCRLFetcher' threw exception; nested exception is java.lang.IllegalArgumentException: LDAP url …
```
> Only create a single CRLFetcher bean (depending on property)

- support/cas-server-support-consent-webflow/src/main/java/org/apereo/cas/web/consent/CasConsentReviewController.java
Use session to avoid redirect loop when accessing /consentReview page.
Currently, user's profile is not saved when performing pac4j callback logic. This causes a redirect loop when accessing /consentReview as, after ticket validation, pac4j finds no user profile and user is redirected again to login page.
> Fix redirect loop in /consentReview

- support/cas-server-support-interrupt-webflow/src/main/java/org/apereo/cas/interrupt/webflow/InterruptWebflowConfigurer.java
I've encountered following exception:
No transition was matched on the event(s) signaled by the [1] action(s) that executed in this action state 'inquireInterruptAction' of flow 'login'; transitions must be defined to handle action result outcomes -- possible flow configuration error? Note: the eventIds signaled were: 'array<String>['interruptSkipped']', while the supported set of transitional criteria for this action state is 'array<TransitionCriteria>[interruptRequired, interruptRequired]'
I believe InquireInterruptAction has the 'interruptRequired' transition attached twice and no 'interruptSkipped' at all.
> Lacking interruptSkipped transition

- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/DelegatedClientNavigationController.java
**- [] Brief description of changes applied**
I'm using cas 6.0.3 with OIDC and Azure Active Directory as a provider.
After sucessful authentication in the provider I'm redirected back to cas, but the call in to handled because
the endpoint only accepts HTTP GET calls.
**- [] Test cases for all modified changes, where applicable**
Before the changes I received an exception
`org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported`
Which does not occur anymore after the changes
**- [] The same pull request targetted at the master branch, if applicable**
N/A
**- [] Any documentation on how to configure, test**
This is the relevant configuration for the provider:
- azure:
id: {my-id}
secret: {my-secret}
tenant: {my-tenant}
clientName: AZURE …
> Have pac4j delegatedClient endpoint accept HTTP POST requests

- api/cas-server-core-api-configuration-model/src/main/java/org/apereo/cas/configuration/model/core/authentication/PasswordEncoderProperties.java
- core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/support/password/PasswordEncoderUtils.java
- core/cas-server-core-util-api/src/main/java/org/apereo/cas/util/crypto/GlibcCryptPasswordEncoder.java
- core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/crypto/GlibcCryptPasswordEncoderTests.java
- docs/cas-server-documentation/installation/Configuration-Properties-Common.md
I've come across a use case where it is handy to be able to encrypt / hash passwords in CAS like an LDAP-Directory would do using glibc crypt.
This PR adds a corresponding password encoder based on the Apache Codec [`Crypt`](https://github.com/apache/commons-codec/blob/master/src/main/java/org/apache/commons/codec/digest/Crypt.java) class.
What do you think?
> Add glibc crypt password encoder

- core/cas-server-core-authentication-attributes/src/main/java/org/apereo/cas/authentication/principal/cache/CachingPrincipalAttributesRepository.java
When setting Principal Attribute Repository to cached, a NPE is thrown when
trying to put attributes into cache and service ticket validation fails. By
using a try - catch block, the error is logged and ticket validation succeeds.
> Fix/Swallow possible NPE exception when caching attributes.

- support/cas-server-support-jpa-ticket-registry/src/main/java/org/apereo/cas/config/JpaTicketRegistryConfiguration.java
When I add the `cas-server-support-jpa-ticket-registry` dependency, I get a bunch of errors like: `2019-04-08 15:24:14,911 ERROR [org.apereo.cas.jpa.CasHibernatePhysicalNamingStrategy] - <Could not load configuration settings to determine case insensitivity.>`.
It seems that the `ApplicationContextProvider` has not been initialized with the `ApplicationContext` when the `CasHibernatePhysicalNamingStrategy` is called.
This PR fixes this issue.
> Make properties available for JPA

- support/cas-server-support-discovery-profile/src/main/java/org/apereo/cas/discovery/CasServerDiscoveryProfileEndpoint.java
Backports existing fix from 6.1.x  to 6.0.x for the /discoverProfile endpoint
> Backport fix for discovery profile endpoint

- core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/util/DefaultUniqueTicketIdGenerator.java
- core/cas-server-core-tickets/src/test/java/org/apereo/cas/util/DefaultUniqueTicketIdGeneratorTests.java
Hyphen before suffix used to be added in the `setSuffix` method. Now that the setter is synthesized by lombok, that hyphen is gone. This breaks some clients and tools that rely upon this hyphen being there. This commit adds hyphen back.
This needs to be backported to `6.0.4`
> Fix missing hyphen before suffix in ticket id generation code

- support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/RedisTicketRegistry.java
In Redis, the TTL must be an integer value while in CAS, we may use bigger values up to `Long.MAX_VALUE`. This PR fixes the issue by limiting the TTL value to `Integer.MAX_VALUE`.
> Limit the Redis TTL to Integer.MAX_VALUE

- support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/response/accesstoken/response/OAuth20DefaultAccessTokenResponseGenerator.java
Anyway, I see the fix in the master branch. Back-porting it.
---
Reading the OAuth 2.0 spec, I understand that the `scope` parameter is a string of values separated by spaces (example: `"openid email"`) while the CAS returns a list of strings (example: `["openid", "email"]`).
See: https://tools.ietf.org/html/rfc6749#section-3.3
The Nimbus SDK also expects a string, this is how I found the error (pac4j-oidc relies on Nimbus).
> Turn the OAUTH scope parameter into a string

- support/cas-server-support-redis-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/RedisTicketRegistry.java
In current version, the plaintext of ticket_id is used as the key in Redis. It will cause all tickets to be leaked if an attacker gets Redis permission.
> encode TicketId in TicketRedisKey

- api/cas-server-core-api-webflow/src/main/java/org/apereo/cas/web/flow/CasWebflowConstants.java
- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedAuthenticationWebflowConfigurer.java
- support/cas-server-support-pac4j-webflow/src/main/java/org/apereo/cas/web/flow/DelegatedClientAuthenticationAction.java
When an SSO session is present, immediately exit DelegatedClientAuthenticationAction.doExecute() with an explicit "resumeWebflow" event that continues to the next state in the webflow.  Avoids issuance of ST without a credential challenge when the "renew" parameter is present.  Models behavior in current master branch (6.1.x).
> Skip delegation when SSO session present (5.3.x branch)

- core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/DomainServicesManager.java
When using CAS Mangement or other means to delete the last service in under a domain when using DomainServicesManager, the domain remains in the list of domains.  This PR adds a check if the last service in  domain is removed, it also removes the domain form the TreeMap.
> Removes a Service Domain if all services are removed

- core/cas-server-core-services-registry/src/main/java/org/apereo/cas/services/AbstractServicesManager.java
- webapp/resources/log4j2.xml
If the load() method is called in afterPropertiesSet() of the service manager, it may fire events that end up modifying a service and saving it with a call to servicesManager.save() (e.g. OidcProfileScopeToAttributesFilter) and that will fail b/c the servicesManager bean is in the process of being created. The services should be loaded by the serviceRegistryInitializer bean which also calls serviceManager.load().
> avoid calling load from service manager during bean creation

- core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/config/CasWebflowContextConfiguration.java
Even if I add the `cas-server-support-themes` dependency, the `changeThemeInterceptor` is not automatically added to the login webflow. Moreover, I haven't been able to find an easy workaround to define the `changeThemeInterceptor` on the login webflow.
This PR fixes that.
> Define the changeThemeInterceptor on the login webflow if it exists

- core/cas-server-core-web/src/main/resources/cas_common_messages.properties
Reverts apereo/cas#3894. 
The original path is correct. Using `dist` in the path creates a 404 as the webjar has no such path in it.
> Revert "fix: jquery dist path changed"
